### PR TITLE
fix(connlib): attempt to join topic upon `unmatched topic` error

### LINKED ISSUE #2854: "unmatched topic" when accessing `ifconfig.net` on staging
Got this one just now. Documenting for completeness. Will update this issue if I'm able to reproduce.

Screenshot 2023-12-10 at 9 19 57 AM
Screenshot 2023-12-10 at 9 19 41 AM

### PR DESCRIPTION
**Pull request by conectado**
Fixes: #2854.

Note: this is ready for review but reproducing the bug that triggered the fix takes ~1 hour or so, so I would like to wait to check that's fixed.

Can be reviewed meanwhile.

### CODE REVIEW

**Comment by conectado** [comment]
@AndrewDryga this should send the join topic message each time an `unmatched topic` message is recieved, with the same topic as the message that has the error.

File: rust/connlib/clients/shared/src/control.rs [hunk 1]
```diff
@@ -262,33 +264,48 @@ impl<CB: Callbacks + 'static> ControlPlane<CB> {
...
-                        tracing::error!(
+    pub async fn handle_error(
+        &mut self,
+        reply_error: ErrorReply,
+        reference: Option<Reference>,
+        topic: String,
+    ) {
+        match reply_error.error {
+            ErrorInfo::Offline => {
+                match reference {
```
Comment (thomaseizinger) [inline rust/connlib/clients/shared/src/control.rs]: I'd prefer collapsing pattern matching where possible:

```rust
match (reply_error.error, reference) {
	// ...
}
```

File: rust/connlib/shared/src/control.rs [hunk 2]
```diff
@@ -375,11 +378,27 @@ enum OkReply<T> {
...
+    #[serde(rename = "unmatched topic")]
+    UnmatchedTopic,
+}
+
+#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
+#[serde(untagged)]
+pub enum Reason {
+    Expected(ExpectedError),
+    UnExpected(UnexpectedError),
+}
```
Comment (thomaseizinger) [inline rust/connlib/shared/src/control.rs]: What do you think about a naming like "Known"? It is not like we "expect" an error to happen!

File: rust/connlib/clients/shared/src/control.rs [hunk 3]
```diff
@@ -262,33 +264,48 @@ impl<CB: Callbacks + 'static> ControlPlane<CB> {
...
-                        .callbacks()
-                        .on_error(&Error::ControlProtocolError);
+            }
+            ErrorInfo::Reason(Expected(ExpectedError::UnmatchedTopic)) => {
+                if let Err(e) = self.phoenix_channel.get_sender().join_topic(topic).await {
+                    tracing::debug!(err = ?e, "couldn't join topic: {e:#?}");
                 }
             }
+            e => {
+                tracing::warn!(err = ?e, "phoenix error: {e:#?}");
```
Comment (thomaseizinger) [inline rust/connlib/clients/shared/src/control.rs]: You are double logging the error.

File: rust/connlib/clients/shared/src/control.rs [hunk 4]
```diff
@@ -1,4 +1,6 @@
 use async_compression::tokio::bufread::GzipEncoder;
+use connlib_shared::control::ExpectedError;
+use connlib_shared::control::Reason::Expected;
```
Comment (thomaseizinger) [inline rust/connlib/clients/shared/src/control.rs]: I'd prefer to not globally import enum variants.

File: rust/connlib/shared/src/control.rs [hunk 5]
```diff
@@ -375,11 +378,27 @@ enum OkReply<T> {
...
+pub struct UnexpectedError(pub String);
+
+#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
+pub enum ExpectedError {
+    #[serde(rename = "unmatched topic")]
+    UnmatchedTopic,
+}
+
+#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
+#[serde(untagged)]
```
Comment (thomaseizinger) [inline rust/connlib/shared/src/control.rs:391]: Instead of making this `untagged` and adding another layer of structs, how about we use `#[serde(other)]` and just make sure we have a log of the incoming message somewhere (I believe we do) if we fail to deserialize it?

That seems like the simpler solution to me and also allows us to debug, what a message was when we receive an unknown reason.

**Review by thomaseizinger — COMMENTED** [review]
Some nits, nothing big. LGTM :)

**Review by thomaseizinger — APPROVED** [review]

File: rust/connlib/shared/src/control.rs (hunk 5 above)
Comment (conectado) [reply rust/connlib/shared/src/control.rs:391]: ah nice, didn't know about `other`

Comment (thomaseizinger) [reply rust/connlib/shared/src/control.rs:391]: For reference: https://serde.rs/variant-attrs.html#other

Comment (conectado) [reply rust/connlib/shared/src/control.rs:391]: I like this approach but it seems that `other` can't be used with externally tagged enums, which is the case with `Reason`.

**Review by jamilbk — COMMENTED** [review]
Good catch, Will defer to @thomaseizinger's approval.

**Review by thomaseizinger — APPROVED** [review]

**Comment by conectado** [comment]
Merging since this work but still needs #2879
