### PR TITLE
fix(windows): when the token expires, change the GUI to signed-out state

### LINKED ISSUE #3128: windows: GUI should change to signed-out state when the token expires and tunnel closes
**Describe the bug**
When the auth token expires, the system tray menu still shows as signed-in.

**To Reproduce**
Run the client and stay signed-in until the token expires.

**Expected behavior**
The system tray menu should change to signed-out mode

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version 375252f8fc (equivalent to 8dab84ef205 after rebasing)
 - OS: Windows 11

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ReactorScram**
Fixes #3128 

Will mark ready for review in an hour or two when it replicates on my dev laptop

### CODE REVIEW

**Comment by ReactorScram** [comment]
Oh sometimes the error is different ` Portal connection error error=PortalConnectionError(Http(Response { status: 401, version: HTTP/1.1, headers: {"cache-control": "max-age=0, private, must-revalidate",`

**Comment by ReactorScram** [comment]
Blocked on #3157

**Comment by ReactorScram** [comment]
Unblocked, but hard to test now that the tokens last longer than 1 hour. Since token expiration is handled identically to the user signing out, maybe a code review is sufficient.

File: rust/windows-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -485,9 +491,24 @@ async fn run_controller(
...
-                    },
+                        controller.refresh_system_tray_menu()?;
+                    }
+                    Req::DisconnectedTokenExpired | Req::SignOut => {
+                        tracing::debug!("Token expired or user signed out");
+                        controller.auth.sign_out()?;
+                        controller.tunnel_ready = false;
+                        if let Some(mut session) = controller.session.take() {
+                            tracing::debug!("disconnecting connlib");
+                            session.connlib.disconnect(None);
```
Comment (conectado) [inline rust/windows-client/src-tauri/src/client/gui.rs:507]: No need to disconnect connlib, when it detects an expired token it just closes itself.

**Review by conectado — APPROVED** [review]
Looks good, left a non-blocking comment

File: rust/windows-client/src-tauri/src/client/gui.rs (hunk 1 above)
Comment (ReactorScram) [reply rust/windows-client/src-tauri/src/client/gui.rs:507]: Okay. It would be hard to fix since I'm using that same match arm for user-initiated sign-outs, too. I just added a comment there in case the code moves in the future.
