### PR TITLE
fix(portal): Remove token provider and implement separate flow for service accounts

### LINKED ISSUE #2501: Can't create Service Accounts
Seem to be getting a 404 when trying to create a Service Account:

Screenshot 2023-10-24 at 5 52 31 PM

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #2501

### CODE REVIEW

File: elixir/apps/web/test/web/live/actors/show_test.exs [hunk 1]
```diff
@@ -765,67 +765,21 @@ defmodule Web.Live.Actors.ShowTest do
              }
     end
 
-    test "renders actor identities", %{
+    test "does not render renders actor identities", %{
```
Comment (bmanifold) [inline elixir/apps/web/test/web/live/actors/show_test.exs]:
```suggestion
    test "does not render actor identities", %{
```

File: elixir/apps/web/test/web/live/actors/show_test.exs [hunk 2]
```diff
@@ -765,67 +765,21 @@ defmodule Web.Live.Actors.ShowTest do
...
-      lv
-      |> element("#actors")
-      |> render()
-      |> table_to_map()
-      |> with_table_row("identity", "#{provider.name} #{identity.provider_identifier}", fn row ->
-        assert row["actions"] == "Delete"
-        assert around_now?(row["created"])
-        assert row["last signed in"] == "never"
-      end)
+      refute has_element?(lv, "#actors")
```
Comment (bmanifold) [inline elixir/apps/web/test/web/live/actors/show_test.exs]: This is a very minor nit, but I just happened to look at the page because of this test....Should the table on the page have an `id` called `identities` rather than `actors` in this case?

**Review by bmanifold — APPROVED** [review]
LGTM.  2 very minor and non-blocking comments.

File: elixir/apps/web/test/web/live/actors/show_test.exs (hunk 2 above)
Comment (AndrewDryga) [reply elixir/apps/web/test/web/live/actors/show_test.exs]: Good catch

File: elixir/apps/domain/lib/domain/auth/subject.ex [hunk 3]
```diff
@@ -7,7 +7,7 @@ defmodule Domain.Auth.Subject do
   @type permission :: Permission.t()
 
   @type t :: %__MODULE__{
-          identity: identity(),
+          identity: identity() | nil,
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/auth/subject.ex:10]: Just making sure I follow -- this means a service account is not tied to any particular user correct?

File: elixir/apps/domain/lib/domain/tokens/token.ex [hunk 4]
```diff
@@ -1,11 +1,16 @@
-# TODO: service accounts auth as clients and as API clients?
+# TODO:  xxx service accounts auth as clients and as API clients?
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/tokens/token.ex]: I suspect customers will want to keep these segregated to keep the two security contexts segregated, but we can discuss further when we start on #2027

**Review by jamilbk — APPROVED** [review]
Nice work

File: elixir/apps/domain/lib/domain/auth/subject.ex (hunk 3 above)
Comment (AndrewDryga) [reply elixir/apps/domain/lib/domain/auth/subject.ex:10]: Subject is always tied to a user (actor) but can be not tied to auth identity (for service accounts).

File: elixir/apps/domain/lib/domain/tokens/token.ex (hunk 4 above)
Comment (AndrewDryga) [reply elixir/apps/domain/lib/domain/tokens/token.ex]: That is exactly why I left this comment: I think we will just add a new actor type.
