### PR TITLE
fix(gateway): Remove `/dev/net/tun` requirement and clean up upgrade script

### LINKED ISSUE #3226: feat(gateway): Create `/dev/net/tun` if not found to remove the `--device` requirement
I was trying to launch a firezone gateway(1.0.0) in Kubernetes when I got this error.

```
2024-01-14T18:40:09.242251Z INFO init{user_agent="Alpine Linux/3.19.0 (x86_64;5.15.0-91-generic;) connlib/1.0.0" login_topic="gateway"}: phoenix_channel: Received init message from portal
2024-01-14T18:40:09.242340Z DEBUG firezone_gateway: connected to portal
Error: Failed to set interface
Caused by:
No such file or directory (os error 2)
Stack backtrace:
...
```

I've found 2 solutions to this error:
- Running the container as privileged (there is no `--device` equivalent in k8s)
- Creating the device `/dev/net/tun` on startup (This is what is done in projects like gluetun: https://github.com/qdm12/gluetun/blob/master/cmd/gluetun/main.go#L334, https://github.com/qdm12/gluetun/blob/master/internal/tun/check.go#L18, https://github.com/qdm12/gluetun/blob/master/internal/tun/create.go#L14)

The second solution seems better to me, as I don't want the gateway container to run as privileged. 
Here is a very basic patch to create the device. It works on my cluster but obv it needs to be improved (that's why it's not a PR, I'm bad at rust). With this patch the flag `--device` is no longer needed when launching the gateway with docker.

```diff
diff --git a/rust/connlib/tunnel/src/device_channel/tun_linux.rs b/rust/connlib/tunnel/src/device_channel/tun_linux.rs
index 9f5eddb5a..46d484bd4 100644
--- a/rust/connlib/tunnel/src/device_channel/tun_linux.rs
+++ b/rust/connlib/tunnel/src/device_channel/tun_linux.rs
@@ -5,16 +5,15 @@ use futures_util::future::BoxFuture;
 use futures_util::FutureExt;
 use ip_network::IpNetwork;
 use libc::{
-    close, fcntl, open, F_GETFL, F_SETFL, IFF_MULTI_QUEUE, IFF_NO_PI, IFF_TUN, O_NONBLOCK, O_RDWR,
+    close, makedev, mknod, fcntl, open, F_GETFL, F_SETFL, IFF_MULTI_QUEUE, IFF_NO_PI, IFF_TUN, O_NONBLOCK, O_RDWR, S_IFCHR,
 };
 use netlink_packet_route::RT_SCOPE_UNIVERSE;
 use parking_lot::Mutex;
 use rtnetlink::{new_connection, Error::NetlinkError, Handle};
 use std::task::{Context, Poll};
-use std::{
-    fmt, io,
-    os::fd::{AsRawFd, RawFd},
-};
+use std::{fmt, fs, io, os::fd::{AsRawFd, RawFd}};
+use std::os::unix::fs::PermissionsExt;
+use std::path::Path;
 use tokio::io::unix::AsyncFd;
 
 mod utils;
@@ -81,6 +80,27 @@ impl Tun {
     }
 
     pub fn new(config: &InterfaceConfig, _: &impl Callbacks) -> Result<Self> {
+        let s = match std::str::from_utf8(TUN_FILE) {
+            Ok(v) => v,
+            Err(e) => panic!("Invalid UTF-8 sequence: {}", e),
+        };
+        let path = Path::new(s);
+        if !path.exists() {
+            let parent_dir = path.parent().unwrap();
+            fs::create_dir_all(parent_dir)?;
+            let permissions = fs::Permissions::from_mode(0o751);
+            fs::set_permissions(parent_dir, permissions)?;
+
+            const MAJOR: u32 = 10;
+            const MINOR: u32 = 200;
+            unsafe {
+                mknod(
+                    TUN_FILE.as_ptr() as _,
+                    S_IFCHR,
+                    makedev(MAJOR, MINOR),
+                )
+            };
+        }
         let fd = match unsafe { open(TUN_FILE.as_ptr() as _, O_RDWR) } {
             -1 => return Err(get_last_error()),
             fd => fd,
@@ -163,7 +183,7 @@ impl Tun {
 
                         Ok(())
                     }
-                    .boxed(),
+                        .boxed(),
                 )
             }
         }

```

**Platform (please complete the following information):**
- Firezone Version 1.0.0-c73dd141709bc2b7c3f66bf6952065691f968286
- OS: Linux
- Distro: Ubuntu 22.04
- Kernel version: 5.15.0
- Deployment method: Kubernetes

### PR DESCRIPTION
**Pull request by jamilbk**
* Clean up gateway upgrade script
* Fixes #3226 to remove another place where things can go wrong when upgrading gateways

### CODE REVIEW

File: rust/connlib/tunnel/src/device_channel/tun_linux.rs [hunk 1]
```diff
@@ -82,6 +89,11 @@ impl Tun {
     }
 
     pub fn new(config: &InterfaceConfig, _: Vec<IpAddr>, _: &impl Callbacks) -> Result<Self> {
+        if let Err(e) = create_tun_device() {
+            tracing::error!("failed to create tun device: {err:#?}", err = e);
+            return Err(get_last_error());
+        }
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_linux.rs]:
```suggestion
        create_tun_device()?;
```

File: rust/connlib/tunnel/src/device_channel/tun_linux.rs [hunk 2]
```diff
@@ -232,6 +244,26 @@ fn set_non_blocking(fd: RawFd) -> Result<()> {
...
+        fs::create_dir_all(parent_dir)?;
+        let permissions = fs::Permissions::from_mode(0o751);
+        fs::set_permissions(parent_dir, permissions)?;
+        unsafe {
+            mknod(
+                TUN_FILE.as_ptr() as _,
+                S_IFCHR,
+                makedev(TUN_DEV_MAJOR, TUN_DEV_MINOR),
+            )
+        };
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_linux.rs]: `mknod` might fail so you need to check if this returns non-zero and bubble up the error like:

```rs
if unsafe{ mknod(..) } != 0 { return Err(get_last_error()) }
```
we can wrap it in its own funciton

File: rust/connlib/tunnel/src/device_channel/tun_linux.rs [hunk 3]
```diff
@@ -232,6 +244,26 @@ fn set_non_blocking(fd: RawFd) -> Result<()> {
     }
 }
 
+fn create_tun_device() -> Result<()> {
+    let path = Path::new(std::str::from_utf8(TUN_FILE).unwrap());
+
+    if !path.exists() {
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_linux.rs]: If we do:

```rs
if path.exist() { return Ok(()) }
```

instead, I think it would be a bit clearer.

File: rust/connlib/tunnel/src/device_channel/tun_linux.rs [hunk 4]
```diff
@@ -232,6 +244,26 @@ fn set_non_blocking(fd: RawFd) -> Result<()> {
...
+        let parent_dir = path.parent().unwrap();
+        fs::create_dir_all(parent_dir)?;
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_linux.rs]: [nit]
```suggestion
        fs::create_dir_all(path.parent().unwrap())?;
```

**Review by conectado — DISMISSED** [review]

**Review by thomaseizinger — APPROVED** [review]
LGTM modulo fixing CI
