### PR TITLE
fix(connlib): handle resources changing site

### LINKED ISSUE #9881: Handle resources changing sites
Ideally, connlib would treat `resource_created_or_updated` with a change in the `sites` as an addressability change, the same way we treat address / ip_stack changes.

What we have to do now is a hack - anytime a resource's sites change, we send `resource_deleted` followed by `resource_created_or_updated`. This requires tracking more state in the portal to determine if a resource has lost all its sites, and if so, refrain from sending the `resource_created_or_updated`.

### PR DESCRIPTION
**Pull request by thomaseizinger**
Similar to how resources can be edited to change their address, IP stack or other properties, they can also be moved between different sites. Currently, `connlib` requires the portal to explicitly remove the resource and then re-add it for this to work.

Our system gets more robust if we also detect that the sites of a resource have changed and handle it like other addressability changes.

To ensure that this works correctly, we also extend the proptests to simulate addressability changes of resources.

Resolves: #9881
Related: #10593

### CODE REVIEW

File: rust/connlib/tunnel/src/client.rs [hunk 1]
```diff
@@ -1732,9 +1745,12 @@ impl ClientState {
 
         if let Some(resource) = self.resources_by_id.get(&new_resource.id()) {
             let resource_addressability_changed = resource.has_different_address(&new_resource)
-                || resource.has_different_ip_stack(&new_resource);
+                || resource.has_different_ip_stack(&new_resource)
+                || resource.has_different_site(&new_resource);
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/client.rs:1749]: This line is the actual fix, the rest is testing infra.

**Review by jamilbk — APPROVED** [review]
LGTM thanks for adding this! I'll add a code path in the portal with a version gate that omits the `resource_deleted` call before `resource_created_or_updated`.

**Comment by jamilbk** [comment]
@thomaseizinger Does this also handle the case where the site changes name? Or was that already handled by `resource_created_or_updated`?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Does this also handle the case where the site changes name? Or was that already handled by `resource_created_or_updated`?

I am comparing site ID and name so yes, we'll be disconnecting when the site changes name. Probably should fix that and only compare the ID?

**Comment by jamilbk** [comment]
> > @thomaseizinger Does this also handle the case where the site changes name? Or was that already handled by `resource_created_or_updated`?
> 
> I am comparing site ID and name so yes, we'll be disconnecting when the site changes name. Probably should fix that and only compare the ID?

Probably not the biggest issue in the world, but as an admin I would expect name changes to be fairly benign - otherwise we probably want to add a disclaimer in the portal.

**Comment by jamilbk** [comment]
Yeah the ID would be the consistent thing to compare against.

**Comment by jamilbk** [comment]
https://github.com/firezone/firezone/issues/10613
