### PR TITLE
fix(apple): Ensure fetching resource state if already connected

### LINKED ISSUE #9837: Launching the apple client if already connected fails to initialize Resource menu properly
If VPN is already connected in system settings, launching the Apple client on macOS produced a wonky menu state.

Image

### PR DESCRIPTION
**Pull request by klochowicz**
Fixes an issue where the Resources menu would not populate when launching
the app while already connected by ensuring the initial VPN status
triggers the resource loading handler.

Fixes #9837

### CODE REVIEW

**Comment by klochowicz** [comment]
tested locally by killing the app and restarting it directly from derived data.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 1]
```diff
@@ -107,7 +107,11 @@ public final class Store: ObservableObject {
       try await self?.handleVPNStatusChange(newVPNStatus: status)
     }
     try ipcClient().subscribeToVPNStatusUpdates(handler: vpnStatusChangeHandler)
-    self.vpnStatus = try ipcClient().sessionStatus()
+
+    let initialStatus = try ipcClient().sessionStatus()
+    self.vpnStatus = initialStatus
+    // Handle initial status to ensure resources start loading if already connected
+    try await handleVPNStatusChange(newVPNStatus: initialStatus)
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:114]:
```suggestion
    self.vpnStatus = try ipcClient().sessionStatus()
    // Handle initial status to ensure resources start loading if already connected
    try await handleVPNStatusChange(newVPNStatus: self.vpnStatus)
```

Wouldn't this be cleaner?

**Review by thomaseizinger — APPROVED** [review]

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift (hunk 1 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:114]: not sure about this, because self.vpnStatus is optional and would have to be unwrapped!

This is hard to spot, as Swift is implicit about the assignment `self.vpnStatus = initialStatus` - in Rust this would have been much more clear, something like: `self.vpnStatus = Some(initialStatus)`

I'd rather keep it as is than to add a needless unwrap that could get triggered if anyone removes the update above.

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:114]: Ah yeah, fair enough. With that knowledge, I agree the temporary variable is cleaner.

**Comment by thomaseizinger** [comment]
Could you explain a bit in the PR description, why this fixes the bug?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 2]
```diff
@@ -107,7 +107,11 @@ public final class Store: ObservableObject {
       try await self?.handleVPNStatusChange(newVPNStatus: status)
     }
     try ipcClient().subscribeToVPNStatusUpdates(handler: vpnStatusChangeHandler)
-    self.vpnStatus = try ipcClient().sessionStatus()
+
+    let initialStatus = try ipcClient().sessionStatus()
+    self.vpnStatus = initialStatus
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift]: This line can probably be removed? It's the first thing that `handleVPNStatusChange` does just below.
