### PR TITLE
fix(connlib): mangle packet for upstream dns as resource

### LINKED ISSUE #3027: DNS isn't forwarded to upstream Resource
Customer has DNS timeouts under the following setup (IPs changed for anonymity)

- Upstream DNS set to a 10.0.0.0/24 address in the portal, i.e. `10.0.0.36`
- `10.0.0.0/24` Resource exists and policy is created
- Firezone-managed Relays is selected for the Site (seems to be behind symmetric NAT)
- iPhone is on WiFi, local DHCP in 10.1.1.0/24 (non-overlapping range)

Troubleshooting steps taken:

- Tested manually resolving names directly against the DNS server, works (`dig @10.0.0.36 google.com` from iPhone)
- Tested using a different upstream with similar packet routing works:
  - Changed upstream to Cloudflare's `1.1.1.2` resolver
  - Added `1.1.1.2` as a resource in the site
  - Tested again, DNS resolves and uses Cloudflare's resolver

Based on the above, it seems that connlib is having issues forwarding the requests to the upstream `10.0.0.36` resolver only.

### PR DESCRIPTION
**Pull request by conectado**
Fixes #3027 

Left a few TODO, will solve it when doing #3123 

Draft because we're still testing but it's almost ready

### CODE REVIEW

**Review by jamilbk — CHANGES_REQUESTED** [review]
Tested, and it works for the regular case! But I found a bug with an edge case if we try to query the DNS server directly and it's a resource, `dig` detects that connlib has mangled the packet and refuses to accept the answer:

```
jamil@Airbook-Mac:~ % ping 10.0.11.229   
PING 10.0.11.229 (10.0.11.229): 56 data bytes
64 bytes from 10.0.11.229: icmp_seq=0 ttl=62 time=72.606 ms
64 bytes from 10.0.11.229: icmp_seq=1 ttl=62 time=72.502 ms
64 bytes from 10.0.11.229: icmp_seq=2 ttl=62 time=72.486 ms
64 bytes from 10.0.11.229: icmp_seq=3 ttl=62 time=72.643 ms
64 bytes from 10.0.11.229: icmp_seq=4 ttl=62 time=73.275 ms

jamil@Airbook-Mac:~ % dig @10.0.11.229 reddit.com
;; reply from unexpected source: 100.100.111.1#53, expected 10.0.11.229#53
;; reply from unexpected source: 100.100.111.1#53, expected 10.0.11.229#53
;; reply from unexpected source: 100.100.111.1#53, expected 10.0.11.229#53

; <<>> DiG 9.10.6 <<>> @10.0.11.229 reddit.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

File: rust/connlib/tunnel/src/client.rs [hunk 1]
```diff
@@ -109,6 +109,30 @@ where
...
+
+        // TODO: assuming single dns
+        let Some(upstream_dns_srv) = upstream_dns.iter().next().cloned() else {
+            return;
+        };
+
+        self.role_state.lock().upstream_dns = upstream_dns;
+
+        self.role_state
+            .lock()
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/client.rs:130]: Why is `role_state` locked twice back-to-back here?

File: rust/connlib/tunnel/src/client.rs [hunk 2]
```diff
@@ -767,6 +810,11 @@ impl RoleState for ClientState {
 
             if self.refresh_dns_timer.poll_tick(cx).is_ready() {
                 let mut connections = Vec::new();
+
+                self.peers_by_ip
+                    .iter()
+                    .for_each(|p| p.1.inner.transform.expire_dns_track());
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/client.rs:816]: Just making sure I understand - This timer doesn't enforce the expiring, it just cleans up old DNS tracks, right? I was a little confused because the timer is 300 seconds but they're supposed to expire after only 60 seconds.

File: rust/connlib/tunnel/src/peer.rs [hunk 3]
```diff
@@ -274,16 +294,37 @@ impl PacketTransform for PacketTransformClient {
...
+            .as_ref()
+            .is_some_and(|upstream| **upstream == src)
+        {
+            if let Some(dgm) = pkt.as_udp() {
+                if let Ok(message) = domain::base::Message::from_slice(dgm.payload()) {
+                    if self
+                        .mangled_dns_ids
+                        .lock()
+                        .remove(&message.header().id())
+                        .is_some_and(|exp| exp.elapsed() < IDS_EXPIRE)
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/peer.rs:316]: So we check every packet, if it's UDP, then we also check if it's a valid DNS packet, if it is then we update the DNS tracking?

The `elapsed` could be removed here by storing the Instant when the track will expire instead of the instant when the track began, but since this is only called on DNS packets, it shouldn't affect performance much.

File: rust/connlib/clients/shared/src/control.rs [hunk 4]
```diff
@@ -100,15 +100,16 @@ impl<CB: Callbacks + 'static> ControlPlane<CB> {
...
-                        create_resolver(interface.upstream_dns, self.tunnel.callbacks());
                     tracing::info!("Firezone Started!");
                 }
             } else {
                 tracing::info!("Firezone reinitializated");
             }
         }
 
+        self.tunnel.set_upstream_dns(&interface.upstream_dns);
+        *self.fallback_resolver.lock() =
```
Comment (ReactorScram) [inline rust/connlib/clients/shared/src/control.rs:111]: Blocking locks are used in an async fn here because the critical section is short and there are no nested locks, so it's unlikely to block for long or deadlock, right?

**Review by ReactorScram — APPROVED** [review]
LGTM. I understood a little of it, I assume it'll make more sense as I gradually see more of the code over time.

File: rust/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:130]: I rather keep locks around for as little as possible, to reduce contention. There's no need to keep any syncing between the two times `role_state` is locked in this function.

File: rust/connlib/tunnel/src/client.rs (hunk 2 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:816]: yup! this is just to cleanup the `HashSet` containing the ids so it doesn't grow too big if a lot of dns queries never see a response.

File: rust/connlib/tunnel/src/peer.rs (hunk 3 above)
Comment (conectado) [reply rust/connlib/tunnel/src/peer.rs:316]: > So we check every packet, if it's UDP, then we also check if it's a valid DNS packet, if it is then we update the DNS tracking?

and the destination ip is for the upstream DNS.

 > The `elapsed` could be removed here by storing the Instant when the track will expire instead of the instant when the track began, but since this is only called on DNS packets, it shouldn't affect performance much.

Even if we did that, we need to retrieve the current time and that's the syscall that could, in theory, be a performance hit. And the `std` time's module API is much nicer when checking elapsed time.

File: rust/connlib/clients/shared/src/control.rs (hunk 4 above)
Comment (conectado) [reply rust/connlib/clients/shared/src/control.rs:111]: The important thing is that we don't need to hold the lock across an `await` point, given that, it's just less performant to use an async one.
[ref](https://tokio.rs/tokio/tutorial/shared-state#on-using-stdsyncmutex)

File: rust/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (ReactorScram) [reply rust/connlib/tunnel/src/client.rs:130]: They are both DNS-related but okay

File: rust/connlib/tunnel/src/peer.rs (hunk 3 above)
Comment (ReactorScram) [reply rust/connlib/tunnel/src/peer.rs:316]: Yeah. I think when I wrote this comment I thought it would be checking multiple timers but it does the hashmap lookup and only checks one, if it checks any. Sounds good.

File: rust/connlib/clients/shared/src/control.rs (hunk 4 above)
Comment (ReactorScram) [reply rust/connlib/clients/shared/src/control.rs:111]: Okay. The Tokio docs were a little confusing to me, saying both "it's not better because the async mutex is sync internally" but also "async locking doesn't block"

But I think this clears it up - "The primary use case for the async mutex is to provide shared mutable access to IO resources such as a database connection. If the value behind the mutex is just data, it’s usually appropriate to use a blocking mutex such as the one in the standard library or [parking_lot](https://docs.rs/parking_lot)."

Cause if it's just data then the worst that can happen is that the thread could be paused while holding the lock, but if the thread is paused, it wouldn't be executing any other tasks anyway. And in both cases, any other task needing the lock will block.

File: rust/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:130]: But, if `upstream_dns` is modified and another thread modifies `peers_by_ip` before this can there will be no harm since the created peer will use the new `upstream_dns`

**Review by jamilbk — APPROVED** [review]
