### PR TITLE
fix(portal): test API endpoints for verification

### LINKED ISSUE #11190: There is a small delay in Entra after granting permissions, we get a 403
After a minute or two this resolves.

We should try to hit all the entra endpoints in the verification process to ensure things work.

### PR DESCRIPTION
**Pull request by jamilbk**
Adds sanity API requests to test verification before allowing saving Google and Entra directories.

Fixes #11190

### CODE REVIEW

File: elixir/apps/web/lib/web/live/settings/directory_sync.ex [hunk 1]
```diff
@@ -1378,12 +1379,41 @@ defmodule Web.Settings.DirectorySync do
...
   end
 
+  defp endpoint_name_from_path(path) do
+    cond do
+      String.contains?(path, "/users") -> "users"
+      String.contains?(path, "/groups") -> "groups"
+      String.contains?(path, "/orgunits") -> "organization units"
+      true -> "API endpoint"
+    end
+  end
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/web/lib/web/live/settings/directory_sync.ex]: Fixed, we can just show the full path.

File: elixir/apps/web/lib/web/live/settings/directory_sync.ex [hunk 2]
```diff
@@ -285,35 +285,18 @@ defmodule Web.Settings.DirectorySync do
     if stored_token && Plug.Crypto.secure_compare(stored_token, state_token) do
       send(pid, :success)
 
-      # After admin consent, verify we can actually access the directory using client credentials
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/directory_sync.ex:288]: This was redundant - we now do the Entra verification in the verification live view so it won't send back a success message to the listening view if not successful, and will print it there.

File: elixir/apps/web/lib/web/live/settings/directory_sync.ex [hunk 3]
```diff
@@ -1380,94 +1364,12 @@ defmodule Web.Settings.DirectorySync do
     "Google service is currently unavailable (HTTP #{status}). Please try again later."
   end
 
-  defp parse_google_verification_error(error) do
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/directory_sync.ex:1383]: Handled in verification view.

File: elixir/apps/domain/lib/domain/google/api_client.ex [hunk 4]
```diff
@@ -50,6 +50,56 @@ defmodule Domain.Google.APIClient do
...
+    )
+  end
+
+  defp test_org_units(access_token) do
+    test_endpoint(
+      "/admin/directory/v1/customer/my_customer/orgunits",
+      access_token,
+      %{"type" => "all"}
+    )
+  end
```
Comment (bmanifold) [inline elixir/apps/domain/lib/domain/google/api_client.ex:90]: I noticed the other two functions had params of `"maxResults" => "1"`

Is this function going to try and grab all of the Org Units?

Comment (jamilbk) [reply elixir/apps/domain/lib/domain/google/api_client.ex:90]: maxResults is not a supported query parameter for org units unfortunately.

Comment (bmanifold) [reply elixir/apps/domain/lib/domain/google/api_client.ex:90]: Ah, ok.  That's disappointing.

**Review by bmanifold — APPROVED** [review]
