### PR TITLE
fix(apple): save networkSettings var

### LINKED ISSUE #10017: Issues applying system default resolvers on iOS
Seeing some strange logs on iOS, these logs are right after another:

```
Received system-defined DNS servers servers=[7057261D841809D82B2E50CC67494F796AD72857]
No system default DNS servers available! Can't initialize resolver. DNS resources won't work.
```

And noticed that, in fact, the DNS resource(s) were unavailable.

Any idea how Sentry is hashing these? Is it possible the iOS DNS trick is starting to fail us, and this could be the connlib sentinel?

### PR DESCRIPTION
**Pull request by jamilbk**
In 45466e3b78a8f5a80f333651b7669e8e57779190, the `networkSettings` variable was no longer saved on the `adapter` instance, causing all calls of the iOS-specific version of getting system resolvers to return the connlib sentinels after the tunnel first came up.

This PR fixes that logic bug and also cleans this area of the codebase up just a tiny bit so it's easier to follow.

Lastly, we also fix a bug where if the tunnel came up while Firezone was already running, `networkSettings` would be `nil`, and we would read the default system resolvers, which were the connlib sentinels.

Fixes https://github.com/firezone/firezone/issues/10017

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice catch. It may be useful to add a few debug log lines here. For one, I find natural language in those easier to read along as they are often a good replacement for comments. Two, looking at those logs will then make it easier to debug in case we ever want to know what is happening.

**Comment by jamilbk** [comment]
Yeah let me do one more quick pass over it to add more logging, comments, and some testing.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 1]
```diff
@@ -446,32 +403,61 @@ extension Adapter: CallbackHandlerDelegate {
...
     #endif
 
+    // Step 2: Validate and strip scope suffixes
     var parsedResolvers: [String] = []
 
-    // Normalize addresses to remove any possible scope suffixes
     for stringAddress in resolvers {
       if let ipv4Address = IPv4Address(stringAddress) {
-        parsedResolvers.append("\(ipv4Address)")
+        if ipv4Address.isWithinSentinelRange() {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:420]: Connlib filters these out for you already so you wouldn't need to do that :)

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 2]
```diff
@@ -123,43 +123,22 @@ class Adapter {
...
 
-      // Tell connlib to reset network state, but only do so if our connectivity has
-      // meaningfully changed. On darwin, this is needed to send packets
-      // out of a different interface even when 0.0.0.0 is used as the source.
-      // If our primary interface changes, we can be certain the old socket shouldn't be
-      // used anymore.
-      if lastRelevantPath?.connectivityDifferentFrom(path: path) != false {
-        lastRelevantPath = path
-
+      if lastPath?.connectivityDifferentFrom(path: path) != false {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:131]: Thinking about it now, does it make sense to update the path but not react to it? Wouldn't it better to store the last path we performed a reset on and always compare connectivity to that?

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 1 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift:420]: Are you saying I should move the warning log to connlib instead?

Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift:420]: It would be helpful to know that we are (mistakenly) trying to set the sentinels as resolvers. Note this is really only a problem on iOS AFAIK.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 2 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift:131]: It's logically the same either way. This way there's one less thing to update inside the conditional and it's a bit less cognitive overhead IMO.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 1 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift:420]: I didn't see that there is a warning log, yeah I guess that makes sense then.

We can add a debug log to connlib that we are filtering a sentinel DNS and we already have one that we don't have any DNS servers.

What we could react to instead is receiving an empty list of DNS resolvers to set from connlib? Really that should never happen.

Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift:420]: I don't want to add the warning log to connlib because we may have intermitten states where we don't have a resolver so there would be false-positives.

All of this is going to get a lot easier once we do #8263 because then there will only be one resolver IP and that is simply always set. Then, connlib definitely knows if it is in a state where it doesn't have any servers to forward the queries to.
