### PR TITLE
Fix lost client_* state on magic link resend

### LINKED ISSUE #2012: portal: When signing-in to the app using magic links, re-sign-in doesn't work
When logging in to the macOS / iOS app using magic links, after I enter my email and click on "Request sign in link", I get a form to enter the token. The straightforward flow (entering the token correctly) works fine. However, if I either (a) click on "Resend email", or (b) submit a wrong token, then I can't enter a token anymore -- correspondingly, in the email it sends, I get a sign-in link rather than a token.

Also, would be nice if the token is trimmed (i.e. leading and trailing spaces removed) before being verified (iOS adds a space after I type the token).

Cc: @jamilbk

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes https://github.com/firezone/firezone/issues/2012

### CODE REVIEW

File: elixir/apps/web/lib/web/live/auth/email.ex [hunk 1]
```diff
@@ -137,15 +142,24 @@ defmodule Web.Auth.Email do
...
         value={@client_platform}
-      /> Did not receive it?
-      <button
-        type="submit"
-        class="inline font-medium text-blue-600 dark:text-blue-500 hover:underline"
-      >
-        Resend email
-      </button>
+      />
+      <.input
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/auth/email.ex:148]: 👍

File: elixir/apps/web/test/web/live/auth/email_test.exs [hunk 2]
```diff
@@ -1,17 +1,191 @@
...
+        identity_id: identity.id,
+        secret: secret
+      })
+      |> submit_form(conn)
+
+    assert redirected_to(conn, 302) =~ "firezone://handle_client_auth_callback"
+    refute conn.assigns.flash["error"]
+  end
+
+  test "renders token form for Android users", %{
```
Comment (jamilbk) [inline elixir/apps/web/test/web/live/auth/email_test.exs:71]: 👍 

The shorter token has been much easier to test with on Android.

**Review by jamilbk — APPROVED** [review]
Awesome, LGTM!
