### PR TITLE
Make phoenix crash detection configurable.

### LINKED ISSUE #807: No straightforward way to disable Phoenix crash detection
The only way I found to disable crash detection is to edit `/opt/firezone/service/phoenix/finish`, which is clumsy. I think there should be an option to disable it or, even better, use exponential backoff instead of stopping the service forever. The rationale is that it might be crashing because of external dependencies not being ready yet, so retrying a bit later would have fixed it. There are probably more cases where retrying forever is desired (e.g. to reduce the chance of being locked out).

In my use case, the OIDC server might start later than Firezone, so by the time OIDC starts, Phoenix has already crashed five times and disabled itself, requiring manual intervention. In my opinon, crashing IS the correct behaviour for an unavailable external dependency, although right now the `finish` script sends a (kind of misleading) event to PostHog if telemetry is enabled.

### PR DESCRIPTION
**Pull request by akrousset**
Fixes #807 

### Summary
- Add `default['firezone']['phoenix']['crash_detection']['enabled']` to Firezone config.
- Add table entry for this new config option in the configuration file doc.

### CODE REVIEW

File: omnibus/cookbooks/firezone/attributes/default.rb [hunk 1]
```diff
@@ -303,6 +303,7 @@
 default['firezone']['phoenix']['log_directory'] = "#{node['firezone']['log_directory']}/phoenix"
 default['firezone']['phoenix']['log_rotation']['file_maxbytes'] = 104_857_600
 default['firezone']['phoenix']['log_rotation']['num_to_keep'] = 10
+default['firezone']['phoenix']['crash_detection']['enabled'] = true
```
Comment (jamilbk) [inline omnibus/cookbooks/firezone/attributes/default.rb:310]: Probably want a comment above this explaining what it does?

File: docs/src/css/custom.css [hunk 2]
```diff
@@ -39,3 +39,8 @@ body {
 h1,h2,h3,h4,h5,h6 {
   font-family: 'Open Sans', sans-serif;
 }
+
+table {
```
Comment (jamilbk) [inline docs/src/css/custom.css:43]: Thanks

**Review by jamilbk — APPROVED** [review]
