### PR TITLE
fix(connlib): log fragmented IP packets on debug

### LINKED ISSUE #10335: Failed to read from TUN FD: Failed to parse UDP packet: UDP Payload Error: Not enough data to decode 'UDP payload'. 9366 byte(s) would be required, but only 14 byte(s) are available based on the slice length.
Sentry Issue: [APPLE-CLIENT-8B](https://firezone-inc.sentry.io/issues/6871129600/?referrer=github_integration)

```
Failed to read from TUN FD: Failed to parse UDP packet: UDP Payload Error: Not enough data to decode 'UDP payload'. 9366 byte(s) would be required, but only 14 byte(s) are available based on the slice length.
```

### PR DESCRIPTION
**Pull request by thomaseizinger**
When an application sends UDP packets that are larger than the MTU of the underlying interface, the kernel fragments the packet at the IP level. Firezone does not support fragmented IP packets because we need to pack each IP packet into a UDP packet.

Right now, we don't check for fragmented IP packets which results in packet parsing errors because the slice we are trying to parse the packet from is not long enough.

To avoid spamming Sentry in these cases, we explicitly check for fragmented IP packets and only log those on DEBUG.

Resolves: #10335

### CODE REVIEW

**Comment by thomaseizinger** [comment]
This is an alternative to #10485. We don't have any customer reports right now that something is not working due to these fragmented IP packets and we are already dropping them. Hence, we might as well just drop them in a less noisy manner and come back to this in case it ever becomes a problem.

At least the explicit check will make it much more obvious in the logs that we are dealing with IP fragmentation here.

File: rust/connlib/tun/src/unix.rs [hunk 1]
```diff
@@ -79,8 +80,12 @@ where
                             break;
                         };
                     }
+                    Err(e) if e.root_cause().is::<ip_packet::Fragmented>() => {
+                        tracing::debug!("{e:#}"); // Log on debug to be less noisy.
```
Comment (thomaseizinger) [inline rust/connlib/tun/src/unix.rs:84]: Alternatively to this, we could also continue logging it on WARN but it might just slowly eat into our Sentry budget. What do you think @jamilbk ?

**Review by klochowicz — APPROVED** [review]
LGTM! 

is there a ticket somewhere to add support for fragmented IP packets?

**Comment by thomaseizinger** [comment]
> is there a ticket somewhere to add support for fragmented IP packets?

No because I don't think we will ever support them. In order to route packets to e.g. DNS resources, we need to NAT them on layer 4 (i.e. TCP/UDP/ICMP). A fragmented IP packet only has the L4 header in the first fragment with the following packets referencing the earlier one through an ID in the IP header. Supporting such packets would mean that Firezone would have to track state across IP packets in several places. We are already advertising an MTU of 1280 to ensure each packet fits into a single UDP packet going forward. I'd consider any application that doesn't respect that and relies on IP fragmentation to send bigger payloads to be badly behaved.
