### PR TITLE
fix(apple): retry startup on CancellationError

### LINKED ISSUE #12215: Swift.CancellationError: CancellationError() (Code: 1)
Sentry Issue: [APPLE-CLIENT-A7](https://firezone-inc.sentry.io/issues/7015805863/?referrer=github_integration)

```
Swift.CancellationError: CancellationError() (Code: 1)
```

### PR DESCRIPTION
**Pull request by klochowicz**
- Retry startup steps if OS cancels them, handling transient system extension or VPN unavailability during boot
- Use exponential backoff for up to 4 attempts, logging each retry and giving up with a warning if all fail
- Transition to a recoverable UI state after repeated failures to avoid leaving user stuck on a spinner

the fix was tested by provoking a CancellationError locally and verifying that without an error strategy we're stuck on a spinner, and that after recovering UI we can still use the client.

Fixes #12215

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice work!

**Comment by jamilbk** [comment]
@claude Take a look

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 1]
```diff
@@ -208,6 +209,7 @@ public final class Store: ObservableObject {
     }
 
     IPCClient.subscribeToVPNStatusUpdates(session: session, handler: vpnStatusChangeHandler)
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift]: This spawns a task internally, maybe we should use the handle of this task as the source of truth for whether this has been done already?

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift]: Not sure what that functionality has to do with the IPC client to be honest? Also, maybe we should refactor this to be a stream instead of callback? For example, we could create a function on `Store` that exposes a stream of notifications and spawn a task in here that takes the stream and calls `self.handleVPNStatusChange` on it. If the task handle for that is present, we have successfully initialised it already.

Should probably be a cancellable task like we do for other things.

**Review by thomaseizinger — APPROVED** [review]
LGTM

One idea how we can get rid of this boolean variable.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift (hunk 1 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift]: I love the idea, will give this a crack in a follow-up (edit: added the fix here, as I had to rebase anyway due to conflicts in the changelog)
