### PR TITLE
fix(Android): add alert dialog for errors in auth flow

### LINKED ISSUE #4723: CustomUriViewModel crashes when given an invalid token
#### Describe the bug

Fatal Exception: java.lang.IllegalStateException: Invalid state parameter 70f17506a289e53a3c47feb55c5698a59834455206cbcd30ecaf980fbd44c785! Authentication will not succeed...
       at dev.firezone.android.features.customuri.ui.CustomUriViewModel$parseCustomUri$1.invokeSuspend(CustomUriViewModel.kt:41)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

#### Platform (please complete the following information)

Android

### PR DESCRIPTION
**Pull request by jasonboukheir**
fixes #4723

### CODE REVIEW

**Comment by jasonboukheir** [comment]
@jamilbk How can I best test this? I've tested it with a fake error and the notification is showing correctly, but what is the recommended way to test the original issue with a broken app link?

File: kotlin/android/app/src/main/java/dev/firezone/android/features/customuri/ui/CustomUriHandlerActivity.kt [hunk 1]
```diff
@@ -41,4 +49,10 @@ class CustomUriHandlerActivity : AppCompatActivity(R.layout.activity_custom_uri_
             finish()
         }
     }
+
+    private fun notifyError(message: String) {
+        val notification = CustomUriNotification.update(this, CustomUriNotification.Error(message)).build()
+        val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
+        manager.notify(CustomUriNotification.ID, notification)
```
Comment (jasonboukheir) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/customuri/ui/CustomUriHandlerActivity.kt:55]: weird to get the notification manager here, but also in the `CustomUriNotification` object. This function is doing both High Level and Low Level (using CustomUriNotification to build the notification, but also not using it to "notify")

Comment (jasonboukheir) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/customuri/ui/CustomUriHandlerActivity.kt:55]: Also some repeating myself with the `TunnelStatusNotification`. Not sure of a good way to consolidate them both yet :/

**Review by jamilbk — APPROVED** [review]
