### PR TITLE
Fix OIDC error matching to catch token and verify failures

### LINKED ISSUE #1426: OIDC Authentication failure may result in 500
'String.chars not implemented for ...`

auth_controller.ex line 89

### PR DESCRIPTION
**Pull request by jamilbk**
The phoenix process crashes with 'String.chars not implemented for ...` when the `fetch_tokens` or `verify` function fails in `openid_connect`. This is due to a change in the error response tuple that wasn't reflected in the error matches in `auth_controller.exs`.

Fixes #1426

### CODE REVIEW

File: apps/fz_http/lib/fz_http_web/controllers/auth_controller.ex [hunk 1]
```diff
@@ -85,21 +85,14 @@ defmodule FzHttpWeb.AuthController do
           |> redirect(to: ~p"/")
       end
     else
-      {:error, reason} ->
-        msg = "OpenIDConnect Error: #{reason}"
-        Logger.warn(msg)
+      # Error verifying state, claims or fetching tokens
+      {:error, error} ->
```
Comment (AndrewDryga) [inline apps/fz_http/lib/fz_http_web/controllers/auth_controller.ex:89]: You might also want to add an `{:error, {:invalid_jwt, reason}}` clause for invalid tokens

**Review by AndrewDryga — APPROVED** [review]
