### PR TITLE
fix(gui-client/linux): show a specific error message in the GUI when updating

### LINKED ISSUE #5790: bug(gui-client/linux): Broken pipe error / installing a new deb while the GUI is signed in
#### Describe the bug

1. IPC service starts, Git commit 0447688
2. About 2h10m pass
3. GUI Client logs in via deep link auth
4. The Client operates normally for about 2 hours (Are UTC times of logs considered private?)
5. Last log line from IPC service, unclear if it gracefully shut down or crashed
6. About 20 seconds pass
7. New IPC instance starts, Git commit 35926eb (modified)
8. 1 second passes
9. GUI tries to send `SetDns` to IPC service and fails with Broken pipe error

#### To Reproduce

Synthetic:

1. Run the IPC service in `run-debug` mode on a dev system
2. Run the GUI and sign in
3. Ctrl+C the IPC service
4. The GUI will exit with the same "Broken pipe" error, and it will be triggered by `SetDns` since the system's DNS changes when the IPC service exits

More likely:

1. Install 0447688
2. Run the GUI and sign in
3. Install any newer version on top of it
4. Within 5 seconds, the GUI will show the SetDns error

#### Expected behavior

1. Expected the IPC service to stay up

#### Screenshots / Logs

Internal Slack: https://firezonehq.slack.com/archives/C07312PRYE4/p1720440317393909?thread_ts=1720437611.153999&cid=C07312PRYE4

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Linux GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 0447688, 1.1.2, but the synthetic repro steps work on 0ff45c34f9, the tip of `main`
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ PopOS, unknown arch
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Production deb

#### Additional context

~~The Linux GUI Client doesn't get DNS change events from the OS, it polls every 5 seconds. So the `SetDns` call likely succeeded a couple times before failing~~ (We poll every 5 seconds but it only goes up to the GUI and over to the IPC service if anything changed)

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5790 (we could do more, but this might be sufficient)

image
image

The code is cross-platform, but this is unlikely to happen on Windows because the MSI refuses to update if the GUI process is running. On Linux `apt-get` will update and restart the IPC service without touching the GUI process.

```[tasklist]
- [x] Test on Linux with `apt-get install`
- [x] Update changelog
- [x] Run a 5-minute smoke test on Linux
- [x] Run a 5-minute smoke test on Windows
- [x] Open for review
- [ ] Merge
```

### CODE REVIEW

File: rust/headless-client/src/ipc_service.rs [hunk 1]
```diff
@@ -133,24 +116,48 @@ fn run_smoke_test() -> Result<()> {
...
+/// client a hint about that before we exit.
+async fn ipc_listen(signals: &mut signals::Terminate) -> Result<()> {
     // Create the device ID and IPC service config dir if needed
     // This also gives the GUI a safe place to put the log filter config
     device_id::get_or_create().context("Failed to read / create device ID")?;
     let mut server = IpcServer::new(ServiceId::Prod).await?;
     loop {
-        Handler::new(&mut server).await?.run().await;
+        let mut handler_fut = pin!(Handler::new(&mut server));
+        let Some(handler) = poll_fn(|cx| {
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs:145]: A lot of nesting going on here. Could this be simpler if we used a `select()` instead and matched on the `Either`?

File: rust/headless-client/src/ipc_service.rs [hunk 2]
```diff
@@ -167,7 +174,19 @@ struct Handler {
...
+    CallbackChannelClosed,
     Ipc(ClientMsg),
+    IpcDisconnected,
+    IpcError(anyhow::Error),
+    Terminate,
+}
+
+// Open to better names
+#[must_use]
+enum HandlerOutcome {
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: I think something with `Result` would be more conventional, like:

```rust
enum HandlerOk {
    ClientDisconnected,
    ServiceTerminating
}
```

And then use a `Result<HandlerOk, ...>`

File: rust/headless-client/src/ipc_service.rs [hunk 3]
```diff
@@ -192,42 +211,72 @@ impl Handler {
...
-                // This borrows `self` so we must drop it before handling the `Event`.
-                let cb = pin!(self.cb_rx.recv());
-                match future::select(self.ipc_rx.next(), cb).await {
-                    future::Either::Left((Some(Ok(x)), _)) => Event::Ipc(x),
-                    future::Either::Left((Some(Err(error)), _)) => {
-                        tracing::error!(?error, "Error while deserializing IPC message");
-                        continue;
+            let event = poll_fn(|cx| {
+                if let Poll::Ready(()) = signals.poll_recv(cx) {
+                    // `recv` on signals is cancel-safe.
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: Typically, when you use `poll` fns, you don't need to worry about cancel safety unless you constructed a future and are carrying it around as a value but then it is obvious anyway that you are dropping data here.

File: rust/headless-client/src/ipc_service.rs [hunk 4]
```diff
@@ -192,42 +211,72 @@ impl Handler {
...
+                    Poll::Ready(Event::Terminate)
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: If you early return here, you can avoid the `else` and the blocks are all on the same indentation. I find that easier to reason about.

File: rust/headless-client/src/ipc_service.rs [hunk 5]
```diff
@@ -192,42 +211,72 @@ impl Handler {
...
+                } else if let Poll::Ready(result) = pin!(&mut self.ipc_rx).poll_next(cx) {
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: For complex return types from a poll like this, I typically `match` right away so there is only one layer of pattern matching.

File: rust/headless-client/src/ipc_service.rs [hunk 6]
```diff
@@ -192,42 +211,72 @@ impl Handler {
...
         loop {
-            let event = {
-                // This borrows `self` so we must drop it before handling the `Event`.
-                let cb = pin!(self.cb_rx.recv());
-                match future::select(self.ipc_rx.next(), cb).await {
-                    future::Either::Left((Some(Ok(x)), _)) => Event::Ipc(x),
-                    future::Either::Left((Some(Err(error)), _)) => {
-                        tracing::error!(?error, "Error while deserializing IPC message");
-                        continue;
+            let event = poll_fn(|cx| {
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: It might be worth extracting a dedicated poll function for this to hide the details from the flow of the loop.

**Review by thomaseizinger — APPROVED** [review]
Nice work! Left some food for thought :)

File: rust/headless-client/src/ipc_service.rs (hunk 5 above)
Comment (ReactorScram) [reply rust/headless-client/src/ipc_service.rs]: Like this? (Comparing old and new)
image
Maybe if I did `use Poll::Ready`. Otherwise the lines are a bit long.

File: rust/headless-client/src/ipc_service.rs (hunk 1 above)
Comment (ReactorScram) [reply rust/headless-client/src/ipc_service.rs:145]: It would take fewer lines, I just don't like how the `Either::Left((thing_i_want, _future_i_always_drop))` looks

File: rust/headless-client/src/ipc_service.rs (hunk 5 above)
Comment (thomaseizinger) [reply rust/headless-client/src/ipc_service.rs]: Yeah! The lines are long but the benefit is that the compiler makes an exhaustiveness check for you so you can glance over it in most cases.
