### PR TITLE
fix(apple): accumulate changes to `NetworkSettings`

### LINKED ISSUE #11185: onResourcesUpdated called with breaking addressability changes at time of resource intent
@thomaseizinger Unfortunately this is still causing an issue on Apple platforms.

We're still seeing connlib emit a onResourcesChanged event that is different from the one first emitted when the tunnel comes up. This is causing the `ERR_NETWORK_CHANGED` error in browsers on macOS when first accessing a DNS resource.

Here's the before and after that's causing the issue:

```
{
  "message": "Optional(dev_firezone_firezone_network_extension.NetworkSettings(mtu: 1280, tunnelAddressIPv4: Optional(\"100.74.176.162\"), tunnelAddressIPv6: Optional(\"fd00:2021:1111::1d:4299\"), dnsAddresses: [\"100.100.111.1\", \"fd00:2021:1111:8000:100:100:111:0\"], _routes4: [<NEIPv4Route: 0x600001c4cd00>, <NEIPv4Route: 0x600001c4cc00>, <NEIPv4Route: 0x600001c4caa0>, <NEIPv4Route: 0x600001c4cba0>, <NEIPv4Route: 0x600001c4cae0>, <NEIPv4Route: 0x600001c4cb00>, <NEIPv4Route: 0x600001c4d300>, <NEIPv4Route: 0x600001c4cbe0>, <NEIPv4Route: 0x600001c4ca80>], _routes6: [<NEIPv6Route: 0x600001c4ca20>, <NEIPv6Route: 0x600001c4ca40>, <NEIPv6Route: 0x600001c4cbc0>], dnsResourceAddresses: [], matchDomains: [\"\"], searchDomains: [\"\"]))",
  "severity": "DEBUG",
  "time": "2025-12-15T16:25:03.496Z"
}
{
  "message": "NetworkSettings(mtu: 1280, tunnelAddressIPv4: Optional(\"100.74.176.162\"), tunnelAddressIPv6: Optional(\"fd00:2021:1111::1d:4299\"), dnsAddresses: [\"100.100.111.1\", \"fd00:2021:1111:8000:100:100:111:0\"], _routes4: [<NEIPv4Route: 0x600001c4cd00>, <NEIPv4Route: 0x600001c4cc00>, <NEIPv4Route: 0x600001c4caa0>, <NEIPv4Route: 0x600001c4cba0>, <NEIPv4Route: 0x600001c4cae0>, <NEIPv4Route: 0x600001c4cb00>, <NEIPv4Route: 0x600001c4d300>, <NEIPv4Route: 0x600001c4cbe0>, <NEIPv4Route: 0x600001c4ca80>], _routes6: [<NEIPv6Route: 0x600001c4ca20>, <NEIPv6Route: 0x600001c4ca40>, <NEIPv6Route: 0x600001c4cbc0>], dnsResourceAddresses: [\"**.cloudflare.com\", \"**.googleapis.com\", \"*.cloudflare.com\", \"example.com\", \"ifconfig.me\", \"ifconfig.net\", \"metabase.c.firezone-prod.internal\"], matchDomains: [\"\"], searchDomains: [\"\"])",
  "severity": "DEBUG",
  "time": "2025-12-15T16:25:03.496Z"
}
```

The diff is:

```
- dnsResourceAddresses: []
+ dnsResourceAddresses:
+   - **.cloudflare.com
+   - **.googleapis.com
+   - *.cloudflare.com
+   - example.com
+   - ifconfig.me
+   - ifconfig.net
+   - metabase.c.firezone-prod.internal
```

It looks like connlib doesn't emit any dnsResources to the app layer until one is attempted to be accessed. Can that be fixed so that we send all resources available upon connect?

Otherwise this triggers `networkSettings.apply()` mid-HTTP-request which causes browsers to drop the TCP connection.

Related: #11120 
Related: #11129

### PR DESCRIPTION
**Pull request by thomaseizinger**
Right now, the order in which the `ResourcesUpdated` and `TunInterfaceUpdated` events are processed by the Network Extensions matters. That is because the `NetworkSettings` only get initialized on the first `TunInterfaceUpdated` event and hence the data from prior `ResourcesUpdated` events is lost until it is emitted again.

This causes user-visible issues because we re-apply the `NetworkSettings` on changes to the resource list to flush the DNS cache. When a user first accesses a resource, we connect to the corresponding site and therefore change the site status to "Online". Because prior updates of the resource list have been discarded, this is the first event that informs the `NetworkSettings` of the list of DNS resources and it gets re-applied to clear the cache, causing browsers like Chrome to reset all of their sockets.

To fix this, we rework the `NetworkSettings` class to a simple struct that just holds and accumulates data. It internally performs diffs on every update and returns an instance of `NEPacketTunnelNetworkSettings` if anything has changed.

This fixes this issue because `NEPacketTunnelNetworkSettings` can only be built if we have IP addresses for the TUN device and the list of resources gets buffered internally as the current list. Hence, subsequent updates to the resource list won't create a new `NEPacketTunnelNetworkSettings` and thus won't disrupt the user in loading the resource.

To verify this further, we implement unit-tests and run them in CI.

Fixes: #11185

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift:1]: I had to move this to `FirezoneKit` to actually add tests for it.

File: scripts/build/macos-test.sh
Comment (thomaseizinger) [inline scripts/build/macos-test.sh:1]: This isn't very pretty but I couldn't be bothered to factor out the setup of the runner into a dedicated script that I can call in CI.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 1]
```diff
@@ -62,10 +62,10 @@ class Adapter: @unchecked Sendable {
   private let accountSlug: String
 
   /// Network settings for tunnel configuration.
-  private var networkSettings: NetworkSettings?
+  private let networkSettings: LockedState<NetworkSettings>
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]: Is using `LockedState` here enough @klochowicz @jamilbk ?

This will ensure that the state is updated atomically but we might still race two applications on the packet tunnel provider I think?

Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: I think the existing workQueue is intended to fix things like this. You should be able to change the workQueue call to wrap the entire body of the handleEvent function in Adapter and that will synchronize accesses.

Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Otherwise I believe we currently have a subtle bug where tunInterfaceUpdated and onResourcesUpdated ordering can be lost because the workQueue dispatch appears to only happen inside the resourcesUpdated case.

Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: With this new code, the ordering should no longer matter because we just accumulate the changes.

Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Changed it to use the `dispatchQueue`

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift:1]: This was required for the tests.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift [hunk 2]
```diff
@@ -0,0 +1,249 @@
...
+    tunnelNetworkSettings.ipv6Settings = ipv6Settings
+
+    // Set DNS settings if we have addresses
+    if !dnsAddresses.isEmpty {
+      let dnsSettings = NEDNSSettings(servers: dnsAddresses)
+      dnsSettings.matchDomains = matchDomains
+      dnsSettings.searchDomains = searchDomain.map { [$0] } ?? []
+      dnsSettings.matchDomainsNoSearch = false
+      tunnelNetworkSettings.dnsSettings = dnsSettings
+    }
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: I believe this introduces a bug where the searchDomain and upstream resolvers won't be applied unless we read at least one system resolver, right?

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: Why? The `dnsAddresses` here are the DNS server IPs, not the resources.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift [hunk 3]
```diff
@@ -0,0 +1,328 @@
...
+
+    // Second update with different DNS
+    let result = settings.updateTunInterface(
+      ipv4: "10.0.0.1",
+      ipv6: "fd00::1",
+      dnsAddresses: ["8.8.8.8"],
+      searchDomain: nil,
+      routes4: [],
+      routes6: []
+    )
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:181]: Not sure if it matters _too_ much but I believe these would be the connlib sentinels in the current architecture, regardless of the upstream resolvers setting.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift [hunk 4]
```diff
@@ -0,0 +1,328 @@
...
+
+    // Set dummy
+    _ = settings.setDummyMatchDomain()
+
+    // Clear dummy
+    let result = settings.clearDummyMatchDomain()
+
+    #expect(result?.dnsSettings?.matchDomains == ["", "example.com"])
+    #expect(result?.dnsSettings?.searchDomains == ["example.com"])
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:286]: Is this testing what the comment says? Don't we need an `expect` before the call to assert that it's changed?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift (hunk 2 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: I've renamed the variables to make that clearer and added a unit test.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 3 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:181]: Are you saying that the test data should match what we will actually be setting? I can do that but then we should also update the IPs I guess? Not sure if it is very important.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift [hunk 5]
```diff
@@ -0,0 +1,328 @@
...
+    // Configure TUN without search domain
+    _ = settings.updateTunInterface(
+      ipv4: "10.0.0.1",
+      ipv6: "fd00::1",
+      dnsAddresses: ["1.1.1.1"],
+      searchDomain: nil,
+      routes4: [],
+      routes6: []
+    )
+
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:302]: Same here re: adding an expect to assert on the state pre-function-under-test call.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 4 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:286]: There is another test that ensures that `setDummyMatchDomain` actually does something.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 5 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:302]: Same as above: There is another test that asserts that behaviour. I prefer not asserting things mid-test to ensure a test only breaks if the invariant it is trying to capture is broken and not some other part of the system.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift [hunk 6]
```diff
@@ -0,0 +1,328 @@
...
+    // First DNS resources update (empty list)
+    _ = settings.updateDnsResources(addresses: [])
+
+    // Second DNS resources update with same empty list
+    let result = settings.updateDnsResources(addresses: [])
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift]: Perhaps another assertion here with a populated list makes sense?

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 4 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:286]: 👍

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 3 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:181]: Yeah I assume this will be changing very soon with #10979 or its successor anyway, just wanted to call this out because `1.1.1.1` and `8.8.8.8` _are_ valid DNS server IPs, so it appears at first glance we are testing with realistic data when in fact that isn't the case.

**Comment by thomaseizinger** [comment]
I am already glad I added these tests. There are a lot of subtle behaviours around the match / search domains.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift (hunk 2 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: What happens if dnsServers is empty?

Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: I suppose this won't be the case if an admin has configured upstream resolvers. If default system resolvers cannot be found or come up empty, we will hit this, but I'm not sure if this is an edge case we care about.

**Review by jamilbk — APPROVED** [review]
LGTM depending on how/if we want to handle the empty `dnsServers` case. We do have some of these errors in Sentry which might cause this condition?

https://firezone-inc.sentry.io/issues/6795931349/?project=4508175177023488&query=is%3Aunresolved%20SystemConfiguration&referrer=issue-stream

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift (hunk 2 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: I can restore prior behaviour where we just pass it on. That is probably the safer thing to do.

**Comment by thomaseizinger** [comment]
> LGTM depending on how/if we want to handle the empty `dnsServers` case. We do have some of these errors in Sentry which might cause this condition?
> 
> [firezone-inc.sentry.io/issues/6795931349?project=4508175177023488&query=is%3Aunresolved%20SystemConfiguration&referrer=issue-stream](https://firezone-inc.sentry.io/issues/6795931349/?project=4508175177023488&query=is%3Aunresolved%20SystemConfiguration&referrer=issue-stream)

I have restored our previous behaviour where we always pass the list in, even if it is empty.

**Comment by thomaseizinger** [comment]
> LGTM depending on how/if we want to handle the empty `dnsServers` case. We do have some of these errors in Sentry which might cause this condition?

I've just done some local testing and passing no DNS servers and passing an empty list results both in MacOS just using the system resolvers.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift [hunk 7]
```diff
@@ -0,0 +1,244 @@
...
+    } else {
+      self.matchDomains = [""]
+    }
+    return buildNetworkSettings()
+  }
+
+  // MARK: - NEPacketTunnelNetworkSettings Builder
+
+  /// Build NEPacketTunnelNetworkSettings from current state
+  public func buildNetworkSettings() -> NEPacketTunnelNetworkSettings? {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: This should not be public actually.

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]:
```suggestion
  private func buildNetworkSettings() -> NEPacketTunnelNetworkSettings? {
```

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift (hunk 5 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/NetworkSettingsTests.swift:302]: perhaps a `#require` would be good here? Ideally, we want to verify that the preconditions for the function under test are set up properly - it also makes it easier to understand and maintain as you're actively documenting your assumptions.

in some test frameworks, there's `assume()` (e.g. pytest) that skips the test instead of failing when they're not met, making it more clear when the tests fail. unfortunately, that's not the case with Swift...

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift [hunk 8]
```diff
@@ -0,0 +1,244 @@
...
+      || oldSearchDomain != self.searchDomain
+      || !NetworkSettings.compareRoutes4(oldRoutes4, self.routes4)
+      || !NetworkSettings.compareRoutes6(oldRoutes6, self.routes6)
+
+    if !hasChanges {
+      return nil
+    }
+
+    return buildNetworkSettings()
+  }
```
Comment (klochowicz) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: you could improve this bay comparing whole structs (would require implementing `Equatable`, but it would be cleaner altogether)

```
public mutating func updateTunInterface(...) -> NEPacketTunnelNetworkSettings? {
    var candidate = self
    candidate.tunnelAddressIPv4 = ipv4
    candidate.tunnelAddressIPv6 = ipv6
    candidate.dnsServers = dnsServers
    candidate.searchDomain = searchDomain
    candidate.matchDomains = searchDomain.map { ["", $0] } ?? [""]
    candidate.routes4 = routes4.sorted { ... }
    candidate.routes6 = routes6.sorted { ... }
    
    guard candidate != self else { return nil }
    self = candidate
    return buildSettings()
}

**Review by klochowicz — APPROVED** [review]
looks good, with some suggestion for improvement

File: swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift (hunk 8 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/NetworkSettings.swift]: I like that, will update.
