### PR TITLE
fix(gateway): Fix systemd gateways on SELinux-enabled distros and improve systemd gateway UX

### LINKED ISSUE #2944: SELinux support
Firezone gateways expect to be able to:

- Mount a Docker volume mapping `/var/lib/firezone` (Docker-based installs)
- Read/write to `/var/lib/firezone` (systemd-based installs)
- Read `/dev/net/tun` to create a new tun interface

This should be considered when creating an SELinux policy that is compatible with the Firezone gateway.

### LINKED ISSUE #3112: systemd gateway masquerading not working with more than one interface
Fresh Ubuntu / Debian instances on AWS and Vultr don't seem to have masquerading working with systemd.

### LINKED ISSUE #3124: Gateway shows Online but not used for client connections
Gateway is showing `Online`, but isn't being used for client connections. This is making it confusing to debug, since clients will fail to use it with `Portal error: offline` messages in the client logs.

Screenshot 2024-01-04 at 4 40 14 PM

### PR DESCRIPTION
**Pull request by jamilbk**
- Fix permissions and caps on each start
- Fixes incompatibility with some systemd versions that barf at the inline `ExecStartPre`
- Fixes erroneous error printed by iptables
- Fixes masquerading not working for wireless interfaces
- Single-step systemd copy-paste command
- Fixes #2944 
- Fixes #3124 
- Fixes #3112 

Tested on CentOS 7 and Ubuntu 22.04

### CODE REVIEW

**Review by AndrewDryga — APPROVED** [review]

File: elixir/apps/web/lib/web/live/sites/new_token.ex [hunk 1]
```diff
@@ -295,6 +220,81 @@ defmodule Web.Sites.NewToken do
...
+    # Enable packet forwarding
+    sysctl -w net.ipv4.ip_forward=1
+    sysctl -w net.ipv4.conf.all.src_valid_mark=1
+    sysctl -w net.ipv6.conf.all.disable_ipv6=0
+    sysctl -w net.ipv6.conf.all.forwarding=1
+    sysctl -w net.ipv6.conf.default.forwarding=1
+    EOF
+
+    # Make ExecStartPre script executable
+    chmod +x /usr/local/bin/firezone-gateway-execstartpre.sh
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/live/sites/new_token.ex]: Is this a standard location for unit file scripts?

Comment (jamilbk) [reply elixir/apps/web/lib/web/live/sites/new_token.ex]: The thinking was that this is more of an upgrade and fix-permissions script. I think `/usr/local/bin` is appropriate for those, but I think this should probably be renamed to `/usr/local/bin/firezone-gateway-init.sh` to be usable outside of the `systemd` context.

Comment (jamilbk) [reply elixir/apps/web/lib/web/live/sites/new_token.ex]: Fixed, good catch
