### PR TITLE
fix(connlib): retry with backoff on 429, 408

### LINKED ISSUE #11593: [phoenix-channel] Don't shutdown on `429`
Turns out we can't rate limit reconnects even if we wanted to:

```
2025-12-30T21:09:08.567Z  INFO tunnel::client: Resetting network state (primary network path changed)
2025-12-30T21:09:08.768Z ERROR client_shared::eventloop: Fatal tunnel error: Connection to portal failed: Failed to establish WebSocket connection: 429 Too Many Requests
2025-12-30T21:09:08.768Z  INFO tunnel::client: Initiating graceful shutdown
```

### PR DESCRIPTION
**Pull request by jamilbk**
- Returns `Event::Hiccup` for retryable 4xx errors: `429: Too many requests` and `408: Request timeout` so that we can block reconnect storms at the load balancer. Prior to this, a `429` would cause the portal connection to die permanently and gracefully shutdown.
- Parses the `Retry-After` header for `429` and `503` responses and uses that for the backoff duration if present.

Fixes #11593

### CODE REVIEW

File: rust/libs/connlib/phoenix-channel/src/lib.rs
Comment (jamilbk) [inline rust/libs/connlib/phoenix-channel/src/lib.rs:1]: Full disclosure, very much open to feedback since our LLM overlords whipped this up under my supervision.

Comment (thomaseizinger) [reply rust/libs/connlib/phoenix-channel/src/lib.rs:1]: I think we should parse the `Retry-After` header here and honor it. Those are mandatory for 429s I think?

Comment (thomaseizinger) [reply rust/libs/connlib/phoenix-channel/src/lib.rs:1]: Shouldn't be too difficult I'd think.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 1]
```diff
@@ -949,9 +951,83 @@ fn serialize_msg(
 mod tests {
     use std::net::{Ipv4Addr, SocketAddrV4};
 
+    use tokio::io::AsyncWriteExt;
     use tokio::net::TcpListener;
 
     use super::*;
+    use crate::login_url::{DeviceInfo, PublicKeyParam};
+
+    fn make_test_channel(port: u16) -> PhoenixChannel<(), (), (), PublicKeyParam> {
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Tests should go into the `tests` directory with the other integration tests.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 2]
```diff
@@ -1114,4 +1190,104 @@ mod tests {
...
+        let mut channel = make_test_channel(port);
+        channel.connect(PublicKeyParam([0u8; 32]));
+
+        let result = tokio::time::timeout(Duration::from_secs(5), async {
+            future::poll_fn(|cx| channel.poll(cx)).await
+        })
+        .await
+        .expect("should not timeout");
+
+        // 408 should trigger a Hiccup (retry) not an Error::Client
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: I have not seen this before. When are we sending 408s?

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 1 above)
Comment (thomaseizinger) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Also, utility functions below their usage please.

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Are we sending a `Retry-After` header? Instead of excluding 429s here, I think we should add a branch where we _only_ handle 429s.

In there, we should then parse any potential `Retry-After` header and respect it. You will have to write a bit of custom code but it shouldn't be too difficult to essentially do the same thing we do for retryable errors but with a custom sleep time (if present).

If not present, we can fallback to our internal backoff.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 2 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: This is apparently commonly returned by load balancers if the client opens a connection and does not send any HTTP data in time.

From https://docs.cloud.google.com/load-balancing/docs/https/https-logging-monitoring#failure-messages -

> The Google Front End (GFE) idled out the client connection due to lack of progress while it was proxying either the request or the response.

I thought it's a good idea to add a handler for this in case another bug or specific network condition triggers this response.

File: rust/libs/connlib/phoenix-channel/src/lib.rs
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs:1]: Google ALB doesn't support this header but agreed we should make this as future-proof and robust as we can.

**Comment by jamilbk** [comment]
Both `503` and `429` may include the `Retry-After` so I've updated this PR to handle the header for that error code as well.

This can either be in seconds (more common) or IMF date format, so I've included handling and tests for both paths.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 3]
```diff
@@ -228,6 +228,40 @@ impl std::error::Error for InternalError {
     }
 }
 
+/// Parses a Retry-After header value into a Duration.
+///
+/// The header can be either:
+/// - A number of seconds (e.g., "120")
+/// - An HTTP date in IMF-fixdate format (e.g., "Wed, 21 Oct 2015 07:28:00 GMT")
+fn parse_retry_after(response: &tungstenite::http::Response<Option<Vec<u8>>>) -> Option<Duration> {
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Utilities below usage please.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 4]
```diff
@@ -481,10 +515,33 @@ where
...
                     Poll::Ready(Err(InternalError::WebSocket(tungstenite::Error::Http(r))))
-                        if r.status().is_client_error() =>
+                        if r.status().is_client_error()
+                            && r.status() != StatusCode::TOO_MANY_REQUESTS
+                            && r.status() != StatusCode::REQUEST_TIMEOUT =>
                     {
                         return Poll::Ready(Err(Error::Client(r.status())));
                     }
+                    // Handle 429 and 503 with Retry-After header
+                    Poll::Ready(Err(InternalError::WebSocket(tungstenite::Error::Http(r))))
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: If you move this branch further up, you can remove the conditionals in the other branch because they are matched top to bottom so more specific ones should go further up.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 5]
```diff
@@ -481,10 +515,33 @@ where
...
+                        if (r.status() == StatusCode::TOO_MANY_REQUESTS
+                            || r.status() == StatusCode::SERVICE_UNAVAILABLE)
+                            && parse_retry_after(&r).is_some() =>
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: I'd suggest we remove this here and do it in the branch with a fallback to either 0 or another default value.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 6]
```diff
@@ -481,10 +515,33 @@ where
...
+                    {
+                        let duration = parse_retry_after(&r).expect("checked above");
+                        let status = r.status();
+
+                        self.state = State::Reconnect { backoff: duration };
+
+                        return Poll::Ready(Ok(Event::RetryAfter {
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Do we need an event here? I think we can just say `continue` and immediately reconnect.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 7]
```diff
@@ -228,6 +228,40 @@ impl std::error::Error for InternalError {
     }
 }
 
+/// Parses a Retry-After header value into a Duration.
+///
+/// The header can be either:
+/// - A number of seconds (e.g., "120")
+/// - An HTTP date in IMF-fixdate format (e.g., "Wed, 21 Oct 2015 07:28:00 GMT")
+fn parse_retry_after(response: &tungstenite::http::Response<Option<Vec<u8>>>) -> Option<Duration> {
+    let header = response.headers().get("retry-after")?;
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Please use the constant from the `http::headers` module.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 8]
```diff
@@ -228,6 +228,40 @@ impl std::error::Error for InternalError {
...
+    let value = header.to_str().ok()?;
+    parse_retry_after_value(value)
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Nit: I think this is cleaner to write as:


```suggestion
    let duration= parse_retry_after_value(value)?;
    
    Some(duration)
```

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 9]
```diff
@@ -228,6 +228,40 @@ impl std::error::Error for InternalError {
...
+        return Some(Duration::from_secs(seconds));
+    }
+
+    // Try parsing as HTTP date (IMF-fixdate format: "Wed, 21 Oct 2015 07:28:00 GMT")
+    if let Ok(date) = chrono::DateTime::parse_from_rfc2822(value) {
+        let now = chrono::Utc::now();
+        let retry_at = date.with_timezone(&chrono::Utc);
+
+        if retry_at > now {
+            let duration = retry_at - now;
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: You can use `saturating_sub` here to avoid the `if` altogether.

File: rust/gateway/src/eventloop.rs [hunk 10]
```diff
@@ -780,6 +780,23 @@ async fn phoenix_channel_event_loop(
 
                 portal.update_ips(ips);
             }
+            Either::Left((Ok(phoenix_channel::Event::RetryAfter { duration, error }), _)) => {
+                tracing::info!(?duration, "Server requested retry-after: {error:#}");
+
+                let ips = match resolver
+                    .lookup_ip(portal.host())
```
Comment (thomaseizinger) [inline rust/gateway/src/eventloop.rs:770]: If we reconnected successfully, the IPs seem to be valid, right? So no reason to re-resolve them.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 6 above)
Comment (thomaseizinger) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: I guess it does make it easier to test.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 11]
```diff
@@ -791,6 +848,11 @@ pub enum Event<TInboundMsg> {
         max_elapsed_time: Option<Duration>,
         error: anyhow::Error,
     },
+    /// The server sent a 429 or 503 with a Retry-After header specifying when to retry.
+    RetryAfter {
+        duration: Duration,
+        error: anyhow::Error,
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Is an error useful here?I think we can remove that and maybe just include the status code?

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 12]
```diff
@@ -791,6 +848,11 @@ pub enum Event<TInboundMsg> {
         max_elapsed_time: Option<Duration>,
         error: anyhow::Error,
     },
+    /// The server sent a 429 or 503 with a Retry-After header specifying when to retry.
+    RetryAfter {
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: I think we should return this any time we get backpressured and not just if there is a `Retry-After` header.

**Review by thomaseizinger — COMMENTED** [review]
Good progress, a bit more feedback!

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 1 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Fixed

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (jamilbk) [reply rust/gateway/src/eventloop.rs:770]: I can't say for sure. Two cases where this may not be true:

- DNS record update. It's possible the old IPs will be now served by some other backend we do not wish to connect to. Unless we are observing the record TTL here it would be safer to re-resolve (queries are cheap right?).
- Cloud provider migration. During the cutover, we probably want things onto the new infra as soon as possible.

Probably unlikely, but given our propensity for hitting "unlikely" events, we need this to be as robust as possible.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 3 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Should be fixed now.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 4 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Good call. Did a bit of refactoring to simplify this.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 5 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Yeah, doing a 1s default-backoff start now.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 6 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Good point. I gave this more thought and it seems that the Hiccup event works fine here already, so I've removed this custom event.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 7 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Updated to use `tokio_tungstenite::tungstenite::http::header::RETRY_AFTER` since it's already a dep.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 8 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: 👍

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (jamilbk) [reply rust/gateway/src/eventloop.rs:770]: This behavior is actually unchanged - looks like the last change here was de7d3bff89 so probably already correct.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 12 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Removed to just use the existing `Hiccup`.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 11 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Removed to just use the existing `Hiccup`.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 9 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Done

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (thomaseizinger) [reply rust/gateway/src/eventloop.rs:770]: It is irrelevant now with the move to `Hiccup` as an event but with the custom event, it made no sense to re-resolve the IPs because can only receive a 429 when we connected successfully.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 13]
```diff
@@ -480,6 +481,41 @@ where
...
+                            Some(duration) => duration,
+                            None => match self.reconnect_backoff.as_mut() {
+                                Some(reconnect_backoff) => reconnect_backoff
+                                    .next_backoff()
+                                    .ok_or_else(|| Error::MaxRetriesReached {
+                                        final_error: r.status().to_string(),
+                                    })?,
+                                None => {
+                                    self.reconnect_backoff = Some((self.make_reconnect_backoff)());
+                                    Duration::from_secs(1)
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: If we are reusing the reconnect backoff now, why not just get the first duration from there?

**Review by thomaseizinger — APPROVED** [review]
LGTM

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (jamilbk) [reply rust/gateway/src/eventloop.rs:770]: > It is irrelevant now with the move to Hiccup as an event but with the custom event, it made no sense to re-resolve the IPs because can only receive a 429 when we connected successfully.

Connect successfully to what though? What happens in the following edge case?

1. `api.firezone.dev` IP reservation is released
2. GCP assigns this IP to another customer
3. Clients/Gateways enter this reconnect loop

Comment (jamilbk) [reply rust/gateway/src/eventloop.rs:770]: We don't honor any kind of TTL returned on the `api.firezone.dev` A / AAAA records right? Someone else's load balancer could be sending us `429`s.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 13 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Updated.

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (thomaseizinger) [reply rust/gateway/src/eventloop.rs:770]: > > It is irrelevant now with the move to Hiccup as an event but with the custom event, it made no sense to re-resolve the IPs because can only receive a 429 when we connected successfully.
> 
> Connect successfully to what though? What happens in the following edge case?
> 
>     1. `api.firezone.dev` IP reservation is released
> 
>     2. GCP assigns this IP to another customer
> 
>     3. Clients/Gateways enter this reconnect loop

In this case, the TLS handshake will fail and we just exit which is the correct behaviour IMO.

Comment (thomaseizinger) [reply rust/gateway/src/eventloop.rs:770]: > > It is irrelevant now with the move to Hiccup as an event but with the custom event, it made no sense to re-resolve the IPs because can only receive a 429 when we connected successfully.
> 
> Connect successfully to what though? What happens in the following edge case?
> 
>     1. `api.firezone.dev` IP reservation is released
> 
>     2. GCP assigns this IP to another customer
> 
>     3. Clients/Gateways enter this reconnect loop

In this case, the TLS handshake will fail and we just exit which is the correct behaviour IMO.

File: rust/client-ffi/src/lib.rs [hunk 14]
```diff
@@ -495,6 +495,7 @@ fn connect(
         (),
         || {
             ExponentialBackoffBuilder::default()
+                .with_initial_interval(Duration::from_secs(1))
```
Comment (thomaseizinger) [inline rust/client-ffi/src/lib.rs]: Are we sure we want this? This will delay any reconnect by 1s. In which circumstances is that useful? For random IO errors, this is just negative UX (although maybe not very noticable) and for cases where the portal cuts all connections at the same time, this just delays the thundering herd by 1s.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 15]
```diff
@@ -480,6 +481,45 @@ where
...
+                                Some(reconnect_backoff) => reconnect_backoff
+                                    .next_backoff()
+                                    .ok_or_else(|| Error::MaxRetriesReached {
+                                        final_error: r.status().to_string(),
+                                    })?,
+                                None => {
+                                    let mut backoff = (self.make_reconnect_backoff)();
+                                    let duration = backoff
+                                        .next_backoff()
+                                        .expect("first backoff should always succeed");
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: To avoid this error condition, you can copy what we do in the other branch which is to first init the backoff and then call `next_backoff` with the `ok_or_else` combinator.

File: rust/libs/connlib/phoenix-channel/src/lib.rs [hunk 16]
```diff
@@ -766,6 +806,37 @@ where
...
+
+fn parse_retry_after_value(value: &str) -> Option<Duration> {
+    // Try parsing as seconds first (most common for 429 responses)
+    if let Ok(seconds) = value.parse::<u64>() {
+        return Some(Duration::from_secs(seconds));
+    }
+
+    // Try parsing as HTTP date (IMF-fixdate format: "Wed, 21 Oct 2015 07:28:00 GMT")
+    if let Ok(date) = chrono::DateTime::parse_from_rfc2822(value) {
+        let now = Duration::from_secs(chrono::Utc::now().timestamp() as u64);
```
Comment (thomaseizinger) [inline rust/libs/connlib/phoenix-channel/src/lib.rs]: Does `chrono` not support math on its `DateTime`s directly? Seems unnecessary to go to a `Duration` first here.

File: rust/gateway/src/eventloop.rs (hunk 10 above)
Comment (jamilbk) [reply rust/gateway/src/eventloop.rs:770]: > In this case, the TLS handshake will fail and we just exit which is the correct behaviour IMO.

That handles the "connecting to another customer's load balancer" case OK. What about transient certificate issues?

File: rust/client-ffi/src/lib.rs (hunk 14 above)
Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: This is useful if the websocket connects and then immediately fails, which would otherwise have reset the backoff immediately to `0`. See https://github.com/firezone/firezone/issues/11589.

Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: If delaying control plane reconnection by 1s makes a UX difference here, I might argue the hot path is too tightly coupled to it.

If this happens due to a transient network issue causing a timeout, there will already have been no data sent for at least 41 seconds (relay), or 317 seconds (client).

Comment (thomaseizinger) [reply rust/client-ffi/src/lib.rs]: > This is useful if the websocket connects and then immediately fails, which would otherwise have reset the backoff immediately to `0`. See #11589.

Okay makes sense. This is temporary then until we remove the added state layers of room joins from the API, right?

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 16 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: 👍

Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: These were converted to `Duration` based on feedback from [this comment](https://github.com/firezone/firezone/pull/11594#discussion_r2655987327) to use `saturating_sub`.

What would you prefer, `unwrap_or(Duration::ZERO)` and stick with chrono's / std types here, or convert to Duration and use `saturating_sub`?

File: rust/client-ffi/src/lib.rs (hunk 14 above)
Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: Hm, not exactly - the room join shouldn't ever directly cause a crash. The main reasons this might happen are:

- The database is overloaded or happens to be under maintenance (this occurs ~once a month for a couple minutes)
- The channel module consumes a change from the stream with an old / outdated data structure (such as after a breaking schema change)
- The Presence state schema has changed (such as adding or removing fields)

These crashes are typically benign but all can  occur very shortly after websocket connect leading to herd issues. When this occurs, the instance becomes unresponsive, and GCP reaps it, creating wild fluctuations in availability that do not resolve sometimes for up to an hour.

Unfortunately the load balancer rate limiting window only goes down to 10s, so it's not a good fit for very condensed reconnect spikes such as this, where all 200 or 300 entities on this particular node would reconnect 5-10x within a second before getting `502` or `429`'d.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 15 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Updated.

File: rust/client-ffi/src/lib.rs (hunk 14 above)
Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: I will add that the cluster CRDT is particularly tough to reason about for state migrations. To prevent each crash here on state changes we need to carefully think through each change that affects in-memory cluster state.

The "let it crash" philosophy is employed here instead, which is a much simpler solution, assuming we don't have reconnect storms.

Ideally, I think, we would have a blue-green deployment system that is account-aware, so that we can slowly roll over entire accounts to the green deployment while the blue one is drained. All presence / pubsub state is account-scoped, so this would prevent for example the case where a client on the old cluster cannot "see" relays or gateways in the new cluster.

Unfortunately that's not possible with today's API since we cannot introspect which account a particular connection belongs to.

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 16 above)
Comment (thomaseizinger) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: I'd suggest we use:

- https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.signed_duration_since
- https://docs.rs/chrono/latest/chrono/struct.TimeDelta.html#method.to_std
- and then `unwrap_or(Duration::ZERO)` to handle the error case

File: rust/client-ffi/src/lib.rs (hunk 14 above)
Comment (thomaseizinger) [reply rust/client-ffi/src/lib.rs]: Okay fair enough. Maybe we should replace this backoff with circuit-breaker or augment it with it. That would maybe get us the best of both worlds? Until then, a 1s default backoff is good enough I guess. It doesn't really solve any herd issues though, those just get delayed.

**Review by thomaseizinger — APPROVED** [review]

File: rust/client-ffi/src/lib.rs (hunk 14 above)
Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: Hm, let me think about this a bit more. I do think it's really up to the server to send `429s` for cases like this. We do have a cluster-wide rate limiter implemented for the REST API - I can see if it is a good fit for this.

Then, what we would do is implement both the load balancer rate limit on a coarse basis and then the application level load balancer with more nuanced limits. For example we use a token bucket algorithm to enforce limits for the REST API.

Comment (jamilbk) [reply rust/client-ffi/src/lib.rs]: This should mitigate reconnect storms: https://github.com/firezone/firezone/pull/11611

File: rust/libs/connlib/phoenix-channel/src/lib.rs (hunk 16 above)
Comment (jamilbk) [reply rust/libs/connlib/phoenix-channel/src/lib.rs]: Fixed.
