### PR TITLE
fix(ux): Improve styling of sign in / sign up pages

### LINKED ISSUE #5730: Larger, vertically stacked logo on Sign in pages

### PR DESCRIPTION
**Pull request by jamilbk**
- Use consistently-sized titles and spacing for form sections
- Use larger and centered hero logo to match Welcome screen in client apps
- If more than one action exists, use `style=info` instead of showing multiple primary CTA buttons

Fixes #5730 
Fixes a regression that was originally fixed in #3390 
refs #5032 

## Before

Screenshot 2024-07-24 at 11 38 29 PM
Screenshot 2024-07-24 at 11 38 21 PM
Screenshot 2024-07-24 at 11 38 17 PM

## After

Screenshot 2024-07-24 at 11 32 19 PM
Screenshot 2024-07-24 at 11 32 15 PM
Screenshot 2024-07-24 at 11 32 10 PM

### CODE REVIEW

**Comment by jamilbk** [comment]
Would love to get @Patticatti's thoughts on the changes!

File: elixir/apps/web/lib/web/components/core_components.ex [hunk 1]
```diff
@@ -14,6 +14,17 @@ defmodule Web.CoreComponents do
...
+    ~H"""
+    <a href={~p"/"} class="mb-6">
+      <img src={~p"/images/logo.svg"} class="pl-10 h-32" alt="Firezone Logo" />
+      <p class="mt-4 text-3xl">
+        Welcome to Firezone.
+      </p>
+    </a>
+    """
+  end
+
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/components/core_components.ex]: I like the idea of this component, which I think they call a "logo lockup" in [design terminology](https://kettlefirecreative.com/logo-terminology-wordmark-brandmark-lettermark-lockup/).  

What would you think about letting the text be something that's passed in?  Just wondering if there may be other places we could use something like this, but that wouldn't want the text "Welcome to Firezone".  Off the top of my head I wonder if there's anywhere that we could use this where it just says "Firezone"

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/core_components.ex]: Yeah I'll do that now.

I'll swap it out with the account name on the sign in page.

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/core_components.ex]: Also removed the link and fixed padding.

Screenshot 2024-07-25 at 12 24 01 PM

**Comment by jamilbk** [comment]
@bmanifold Ready for another review

**Review by bmanifold — APPROVED** [review]
LGTM
