### PR TITLE
fix(apple/macos): clean up utun on quit

### LINKED ISSUE #10580: utun pool increments can push interface order past others, resulting in broken DNS interception
Sometimes, when signing out and back in on macOS (and likely iOS), the system resets our `utun` causing it to increment. This actually causes the DNS resolver `order` number to increment by `600` for each `utun` index.

The problem with this is that if our `order` exceeds the second DNS resolver `order`, which typically is the DHCP resolver on the system and has an `order` of `200000`, we will now fail to intercept DNS and all DNS resources will fail to work.

Here are examples of working and not working scenarios:

#### Working - `utun34`

```
scutil --dns
DNS configuration

resolver #1
  search domain[0] : attlocal.net
  nameserver[0] : 100.100.111.1
  nameserver[1] : fd00:2021:1111:8000:100:100:111:0
  if_index : 60 (utun34)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 108400

resolver #2
  nameserver[0] : 2600:1173:1231:1234::1
  nameserver[1] : 192.168.1.254
  if_index : 17 (en8)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

#### Broken - `utun376`

```
❯ scutil --dns
DNS configuration

resolver #1
  search domain[0] : lan
  nameserver[0] : 100.100.111.1
  if_index : 397 (utun376)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 230400

resolver #2
  nameserver[0] : 10.10.10.1
  if_index : 14 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

---

The fix here seems to be to find a way to reset the `utun` index pool somehow, or find some way to lock the resolver `order`.

This could be an issue on iOS too, so hopefully whatever fixes this on macOS will work there too.

### PR DESCRIPTION
**Pull request by jamilbk**
On macOS, because it uses the System Extension packaging type, the lifecycle of the tunnel provider process is not tied directly to connlib's session start and end, but rather managed by the system. The process is likely running at all times, even when the GUI is not open or signed in.

The system will start the provider process upon the first IPC call to it, which allocates a `utun` interface. The tricky part is ensuring this interface gets removed when the GUI app quits. Otherwise, it's likely that upon the next launch of the GUI app, the system will allocate a _new_ utun interface, and the old one will linger until the next system reboot.

Here's where things get strange. The system will only remove the `utun` interface when stopping the tunnel under the following conditions:

- The provider is currently not in a `disconnected` state (so it needs to be in `reasserting`, `connecting`, or `connected`
- The GUI side has called `stopTunnel`, thereby invoking the provider's `stopTunnel` override function, or
- The provider side has called `cancelTunnelWithError`, or
- The `startTunnel`'s completionHandler is called with an `Error`

The problem we had is that we make various IPC calls throughout the lifecycle of the GUI app, for example, to gather logs, set tunnel configuration, and the like. If the GUI app was _not_ in a connected state when the user quit, the `utun` would linger, even though we were issuing a final `stopTunnel` upon quit in all circumstances.

To fix the issue, we update the dry run `startTunnel` code path we added previously in two ways:

1. We add a `dryRun` error type to the `startTunnel`'s completionHandler
2. We implement the GUI app `applicationShouldTerminate` handler in order to trigger one final dryRun which briefly moves the provider to a connected state so the system will clean us up when its completionHandler is invoked.

Tested under the following conditions:

- Launch app in a signed-out state -> quit
- Launch app in a signed-out state -> sign in -> quit
- Launch app in a signed-out state -> sign in -> sign out -> quit
- Launch app in a signed-in state -> quit
- Launch app in a signed-in state -> sign out -> quit

Notably, if the GUI app is killed with `SIGKILL`, our terminate hook is _not_ called, and the utun lingers. We'll have to accept this edge case for now.

Along with the above, the janky `consumeStopReason` mechanism has been removed in favor of NE's `cancelTunnelWithError` to pass the error back to the GUI we can then use to show the signed out alert.

Fixes #10580

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift [hunk 1]
```diff
@@ -802,10 +802,7 @@ import SwiftUI
     }
 
     @objc func quitButtonTapped() {
-      Task {
-        do { try store.stop() } catch { Log.error(error) }
-        NSApp.terminate(self)
-      }
+      NSApp.terminate(self)
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift:805]: Handled by the termination hook

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 2]
```diff
@@ -29,7 +29,7 @@ enum AdapterError: Error {
     case .connlibConnectError(let error):
       return "connlib failed to start: \(error)"
     case .setDnsError(let error):
-      return "failed to set new DNS serversn: \(error)"
+      return "failed to set new DNS servers: \(error)"
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:32]: typo

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 3]
```diff
@@ -297,24 +297,19 @@ class Adapter: @unchecked Sendable {
...
-        guard let encoded = try? PropertyListEncoder().encode(firezoneResources) else {
-          Log.log("Failed to encode resources as PropertyList")
-          completionHandler(nil)
-          return
-        }
-        propertyListData = encoded
-      } else {
-        propertyListData = Data()
-      }
+      guard let uniffiResources = self.resources
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]: Fixes a decoder error the first time this is called

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift [hunk 4]
```diff
@@ -55,13 +56,10 @@ class PacketTunnelProvider: NEPacketTunnelProvider {
     options: [String: NSObject]?,
     completionHandler: @escaping (Error?) -> Void
   ) {
-    super.startTunnel(options: options, completionHandler: completionHandler)
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:58]: This was basically a no-op

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift [hunk 5]
```diff
@@ -149,8 +147,7 @@ class PacketTunnelProvider: NEPacketTunnelProvider {
 
     // handles both connlib-initiated and user-initiated stops
     adapter?.stop()
-
-    super.stopTunnel(with: reason, completionHandler: completionHandler)
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:153]: This was basically a no-op

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Models/SessionNotification.swift [hunk 6]
```diff
@@ -98,10 +98,14 @@ public class SessionNotification: NSObject {
...
-    func showSignedOutAlertmacOS() async {
+    func showSignedOutAlertmacOS(_ message: String?) async {
       let alert = NSAlert()
       alert.messageText = "Your Firezone session has ended"
-      alert.informativeText = "Please sign in again to reconnect"
+      alert.informativeText = """
+          Please sign in again to reconnect.
+
+          \(message ?? "")
+        """
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Models/SessionNotification.swift]: Alert is whitespace normalized

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 7]
```diff
@@ -76,7 +76,7 @@ class IPCClient {
     // On macOS, IPC calls to the system extension won't work after it's been upgraded, until the startTunnel call.
     // Since we rely on IPC for the GUI to function, we need to send a dummy `startTunnel` that doesn't actually
     // start the tunnel, but causes the system to start the extension.
-    func startSystemExtension() throws {
+    func dryRunAndStop() throws {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Why is this called `dryRunAndStop` when it doesn't stop the tunnel?

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 3 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Do you mind moving this to a different PR?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 8]
```diff
@@ -126,11 +126,20 @@ public final class Store: ObservableObject {
...
+      // Only available on macOS 13+
+      if #available(macOS 13, *), vpnStatus == .disconnected {
         do {
-          let reason = try await ipcClient().consumeStopReason()
-          if reason == .authenticationCanceled {
-            await self.sessionNotification.showSignedOutAlertmacOS()
+          try manager().session()?.fetchLastDisconnectError { error in
+            guard let nsError = error as NSError?,
+              nsError.domain == "FirezoneKit.ConnlibError",
+              nsError.code == 0
```
[the remark this answers is not in the document]
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift]: Agree with Copilot here, this should be a const that is used on both sides.

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift (hunk 4 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:58]: But will it always be? I think we should keep that in case Apple adds something to the super-class that is required.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 7 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: It seems to me this should just be called `dryRunStart`.

**Review by thomaseizinger — APPROVED** [review]
Concept ACK

Would be nice to split the unrelated resource fix out of this PR. Plus, I think a bug might have creeped in? `dryRunAndStop` doesn't actually stop.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 7 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: So what this does is return an Error in the completionHandler, which achieves the same effect in a more idiomatic way. When macOS sees an Error returned, it tears down the utun all the same.

Otherwise, the system actually very briefly moves to a connected state and then we call cancel after, and I can't guarantee that won't cause a race.

So went with the first "atomic" approach.

Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: I can update the naming

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 3 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: 👍

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift (hunk 4 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:58]: There is no mechanism in Swift to enforce not calling super from an override, but Apple states in the docs that:

- we must override these methods
- [do not call](https://developer.apple.com/forums/thread/731233) stopTunnel from within the provider
- their [canonical example](https://github.com/apple-sample-code/SimpleTunnel/tree/main/PacketTunnel) doesn't call super from these overrides

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 9]
```diff
@@ -126,11 +126,20 @@ public final class Store: ObservableObject {
...
+            else { return }
+
+            Task {
+              await self.sessionNotification.showSignedOutAlertmacOS(
+                nsError.userInfo["reason"] as? String)
+            }
           }
         } catch {
           Log.error(error)
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:154]: To hell with macOS 12
