### PR TITLE
fix(portal): always use 'true' for checkbox value

### LINKED ISSUE #11418: Changing actor fields resets allow_email_otp_sign_in

### PR DESCRIPTION
**Pull request by jamilbk**
When the live_table component was introduced, it exposed a `value` attribute to be passed into a checkbox in order to use for a multi-select style live table filter.

But those filters never got used.

What also happened is it introduced a bug wherein if you don't explicitly pass a `value="true"`, the checkbox state would be lost on LiveView DOM updates since _another_ change we made to all `input` components just above would set `value` to `""` if it was `nil` or not provided.

This meant that all checkboxes that don't explicitly pass `value="true"` would effectively have a bug where they lose their checked state on any form change.

Since we don't have a multi-select type of live table filter (and let's be honest, we need to rip it out anyway), we can unwind this ball of yarn by deleting the relevant live_table code and reverting checkboxes to always send `value="true"`.

Fixes #11418

### CODE REVIEW

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 1]
```diff
@@ -153,6 +153,8 @@ defmodule Web.FormComponents do
         Phoenix.HTML.Form.normalize_value("checkbox", assigns[:value])
       end)
 
+    dbg(assigns[:value])
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/components/form_components.ex]: Guessing this wasn't intended?

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 2]
```diff
@@ -153,6 +153,8 @@ defmodule Web.FormComponents do
...
+
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/form_components.ex]: Good catch!

```suggestion
```

**Review by jamilbk — COMMENTED** [review]
I did manually navigate to the affected pages and test them manually, as well as test checkboxes on other pages to ensure no breakage.

**Review by bmanifold — APPROVED** [review]
