### PR TITLE
fix(apple): Fix menu display and activation

### LINKED ISSUE #4818: Attempt to order the `ASWebAuthenticationSession` window front on macOS
Users are still reporting window order weirdness with `ASWebAuthenticationSession`. We need to see if there's any way possible to bring the newly-opened window to focus rather than letting macOS handle it.

### PR DESCRIPTION
**Pull request by jamilbk**
When the menu was clicked, the system would show it without activating the app. This meant that other actions launched from the menu like `Sign in` could sometimes happen without their respective window coming to the foreground.

To fix it, we need more control over how the menu is displayed. So we add a click handler and open the menu manually. Note that to do this, we need to ensure `statusItem.menu = nil` otherwise the system will default to showing the menu for us, and not firing our handler.

fixes #4818

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift [hunk 1]
```diff
@@ -42,12 +42,28 @@ public final class MenuBar: NSObject {
 
     if let button = statusItem.button {
       button.image = signedOutIcon
+      button.target = self
+      button.action = #selector(statusItemClicked)
```
Comment (ReactorScram) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift:46]: "status item" is what macOS calls tray icons?

**Review by ReactorScram — APPROVED** [review]
Somewhat makes sense. I'm not familiar with the macOS GUI stuff.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift (hunk 1 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift:46]: Yeah

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift [hunk 2]
```diff
@@ -42,12 +42,28 @@ public final class MenuBar: NSObject {
...
     createMenu()
     setupObservers()
   }
 
+  @objc private func statusItemClicked() {
+    // Bring our app to the foreground.
+    // Prevents the "Window ordered front from a non-active application" warning, which
+    // can cause display issues with the menu.
+    NSApp.activate(ignoringOtherApps: true)
+    DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) { [weak self] in
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift:58]: @ReactorScram This delay prevents a race condition where if we try to show the menu too quickly after activating the app, it closes right away.

Activating the app resets the menu state, so we need this workaround. On macOS 13 there is supposedly a [much nicer](https://developer.apple.com/documentation/swiftui/menubarextra) API for this.

Comment (ReactorScram) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift:58]: hm, hope that time is sufficient
