### PR TITLE
fix(portal): don't encode tokens in session cookies

### LINKED ISSUE #11086: don't encode browser tokens for saving into cookie
In the session cookie, we store the encoded version of the token used for sign in.

This is useless and redundant - the session semantics already protect this value.

### PR DESCRIPTION
**Pull request by jamilbk**
This is completely unnecessary and only increases the spaghettification of our codebase.

Fixes #11086

### CODE REVIEW

File: elixir/apps/web/lib/web/session/cookie.ex [hunk 1]
```diff
@@ -80,76 +72,4 @@ defmodule Web.Session.Cookie do
   defp encryption_salt do
     Domain.Config.fetch_env!(:web, :cookie_encryption_salt)
   end
-
-  @doc """
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/session/cookie.ex:84]: This was all dead code.

**Review by jamilbk — COMMENTED** [review]
Tested all sign in controllers with these changes and all checks out.

File: elixir/apps/web/lib/web/controllers/email_otp_controller.ex [hunk 2]
```diff
@@ -259,16 +259,14 @@ defmodule Web.EmailOTPController do
       expires_at: DateTime.add(DateTime.utc_now(), session_lifetime_secs, :second)
     }
 
-    with {:ok, token} <- Auth.create_token(attrs) do
-      {:ok, Auth.encode_fragment!(token)}
-    end
+    Auth.create_token(attrs)
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/web/lib/web/controllers/email_otp_controller.ex:259]: Fixed

File: elixir/apps/web/lib/web/live_hooks/fetch_subject.ex [hunk 3]
```diff
@@ -30,10 +30,29 @@ defmodule Web.LiveHooks.FetchSubject do
...
+      from(t in Token, as: :tokens)
+      |> where([tokens: tokens], tokens.account_id == ^account_id)
+      |> where([tokens: tokens], tokens.id == ^token_id)
+      |> where([tokens: tokens], tokens.expires_at > ^DateTime.utc_now())
+      |> Safe.unscoped()
+      |> Safe.one()
+      |> case do
+        nil -> {:error, :token_not_found}
+        token -> {:ok, token}
+      end
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/web/lib/web/live_hooks/fetch_subject.ex]: fixed

File: elixir/apps/web/lib/web/live_hooks/fetch_subject.ex [hunk 4]
```diff
@@ -30,10 +30,29 @@ defmodule Web.LiveHooks.FetchSubject do
...
     end
   end
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/web/lib/web/live_hooks/fetch_subject.ex]: This will be handled by a new upcoming `browser_sessions` table.

File: elixir/apps/web/lib/web/plugs/fetch_subject.ex [hunk 5]
```diff
@@ -15,36 +17,57 @@ defmodule Web.Plugs.FetchSubject do
...
+      from(t in Token, as: :tokens)
+      |> where([tokens: tokens], tokens.account_id == ^account_id)
+      |> where([tokens: tokens], tokens.id == ^token_id)
+      |> where([tokens: tokens], tokens.expires_at > ^DateTime.utc_now())
+      |> Safe.unscoped()
+      |> Safe.one()
+      |> case do
+        nil -> {:error, :token_not_found}
+        token -> {:ok, token}
+      end
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/web/lib/web/plugs/fetch_subject.ex]: done

File: elixir/apps/web/lib/web/session/redirector.ex [hunk 6]
```diff
@@ -55,7 +56,16 @@ defmodule Web.Session.Redirector do
...
-  def client_signed_in(%Plug.Conn{} = conn, account, actor_name, identifier, fragment, state) do
+  def client_signed_in(
+        %Plug.Conn{} = conn,
+        account,
+        actor_name,
+        identifier,
+        %Token{} = token,
+        state
+      ) do
+    fragment = Domain.Auth.encode_fragment!(token)
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/session/redirector.ex:67]: Here's where we now encode the token to pass off to the client.

File: elixir/apps/web/lib/web/controllers/email_otp_controller.ex [hunk 7]
```diff
@@ -256,16 +256,14 @@ defmodule Web.EmailOTPController do
       expires_at: DateTime.add(DateTime.utc_now(), session_lifetime_secs, :second)
     }
 
-    with {:ok, token} <- Auth.create_token(attrs) do
-      {:ok, Auth.encode_fragment!(token)}
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/controllers/email_otp_controller.ex:260]: Is this not necessary any more because we're now encrypting the cookie so the whole cookie is encoded by default?

File: elixir/apps/web/lib/web/session/cookie.ex [hunk 8]
```diff
@@ -80,76 +72,4 @@ defmodule Web.Session.Cookie do
...
-  Mounts the subject for LiveView sockets
-  Reads the per-account cookie from connect_info and authenticates.
-  """
-  def mount_subject(socket, params, _session) do
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/session/cookie.ex:88]: This is more for my own edification.  Why was this needed if we already had an `on_mount` live hook setting the subject?

File: elixir/apps/web/lib/web/controllers/email_otp_controller.ex (hunk 7 above)
Comment (bmanifold) [reply elixir/apps/web/lib/web/controllers/email_otp_controller.ex:260]: Nevermind, I see where it's being encoded later in the PR.

**Review by bmanifold — APPROVED** [review]
Code looks good, just had a question for my own benefit.

File: elixir/apps/web/lib/web/session/cookie.ex (hunk 8 above)
Comment (jamilbk) [reply elixir/apps/web/lib/web/session/cookie.ex:88]: It wasn't - I believe this was moved originally from `Web.Auth` where we had live hooks mixed in with all the other functions.
