### PR TITLE
fix(android): Strip scope id off IPv6 addresses Android

### LINKED ISSUE #5781: Android App crashing on startup
#### Describe the bug

Hi my android app is crashing on startup when I'm connected to a WIFI network

#### To Reproduce

Connect to a WIFI network and try to open it (I'm already signed in and my user has access to multiple resources)

#### Expected behavior

The app should work as expected.

#### Screenshots / Logs

_If applicable, add screenshots and log traces to help debug your problem **with
any sensitive data removed**._

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Android App: Tried official 1.1.2 and builded apk on main
- _Firezone Version (e.g. 1.0.0 or N/A):_ Self Hosted ed34ca096bd48cc64f5e50678cdd63dff709e20f
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Pixel 7 Pro Android 15 Beta
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ AppStore

#### Additional context

```
crash_dump64                         A  pid: 20536, tid: 20584, name: ConnectivityThr  >>> dev.firezone.android <<<
crash_dump64                         A        #01 pc 00000000011b5e5c  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #02 pc 00000000011b4308  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #03 pc 00000000011b3fdc  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #04 pc 00000000011b3d6c  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #05 pc 00000000011b2ebc  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #06 pc 00000000011b3ae0  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #07 pc 00000000011c6fac  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #08 pc 00000000011c73e8  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000)
crash_dump64                         A        #09 pc 0000000000710ea4  /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk!libconnlib.so (offset 0x2f0000) (Java_dev_firezone_android_tunnel_ConnlibSession_setDns+708)
crash_dump64                         A        #15 pc 0000000000028aa0  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~k3H6YYv1fl0xMjaxlmj3Jg==/dev.firezone.android-72z-cFOTcpWZCSbD5bIWNA==/base.apk] (NetworkMonitor.onLinkPropertiesChanged+0)
````

I tried to debug this, and I think the problem are the DNS returned by Android that are not parsable by your rust code.

I printed `Gson().toJson(linkProperties.dnsServers)` and here are the results:

5G (working): `["<ipv6_redacted>"]`

My wifi network (crashing): `["fe80::12e9:92ff:fe7b:9120%wlan0","<ipv6_redacted>","192.168.0.1"]`

Connected to another phone through wifi (crashing): `["fe80::468:65ff:fe69:e64%wlan0"]`

Notice the weird format for link-local addresses

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #5781

### CODE REVIEW

File: kotlin/android/app/src/main/java/dev/firezone/android/tunnel/NetworkMonitor.kt [hunk 1]
```diff
@@ -25,7 +25,10 @@ class NetworkMonitor(private val tunnelService: TunnelService) : ConnectivityMan
 
             if (lastDns != linkProperties.dnsServers) {
                 lastDns = linkProperties.dnsServers
-                ConnlibSession.setDns(tunnelService.connlibSessionPtr!!, Gson().toJson(linkProperties.dnsServers))
+
+                // Stripe the scope id from IPv6 addresses. See https://github.com/firezone/firezone/issues/5781
```
Comment (jamilbk) [inline kotlin/android/app/src/main/java/dev/firezone/android/tunnel/NetworkMonitor.kt]:
```suggestion
                // Strip the scope id from IPv6 addresses. See https://github.com/firezone/firezone/issues/5781
```
