### PR TITLE
fix(portal): do not allow ports for upstream DNS servers

### LINKED ISSUE #8330: Consider disallowing non-standard DNS ports for upstream resolver
At the moment, we allow the configuration of a non-standard DNS port in the portal's DNS configuration:

Image

I think we should disallow this. Being able to configure this port creates complexity that is unnecessary. There is a standard port for DNS for a reason and admins should configure their upstream DNS servers to use that.

Instead, this input field should only accept an IP and port 53 will be implied.

### PR DESCRIPTION
**Pull request by thomaseizinger**
DNS servers are standarised to be contacted on port 53. This is also hard-coded within `connlib` when we contact an upstream server. As such, we should disallow users inputting any custom port for upstream DNS servers. Luckily - or perhaps because it doesn't presently work - no users in production have actually put in a port.

Resolves: #8330

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I'd like to fix this in preparation for #4668. To ship that, we'll need to already change the `init` message to also return DoH servers and as part of that, I want to remove the port from the IP that we send down.

**Comment by thomaseizinger** [comment]
I don't really understand the CI test failures. From what I understand, the test here is actually wrong: https://github.com/firezone/firezone/blob/0a4d5b95a98da66f7c8d97b59fd1808cedbabf3d/elixir/apps/web/test/web/live/settings/dns_test.exs#L290-L296

`addr2` hasn't been added so why do we expect that it errors with `all addresses must be unique`?

File: elixir/apps/domain/test/support/fixtures/accounts.ex [hunk 1]
```diff
@@ -14,7 +14,7 @@ defmodule Domain.Fixtures.Accounts do
         clients_upstream_dns: [
           %{protocol: "ip_port", address: "1.1.1.1"},
           %{protocol: "ip_port", address: "2606:4700:4700::1111"},
-          %{protocol: "ip_port", address: "8.8.8.8:853"}
+          %{protocol: "ip_port", address: "8.8.8.8"}
```
Comment (jamilbk) [inline elixir/apps/domain/test/support/fixtures/accounts.ex]: This is likely what's causing the test failure(s) since this address is tested in the dns_test.exs. You could try making this something else like `9.9.9.9`.

File: elixir/apps/web/test/web/live/settings/dns_test.exs [hunk 2]
```diff
@@ -259,7 +259,7 @@ defmodule Web.Live.Settings.DNSTest do
     conn: conn
   } do
     addr1 = %{address: "8.8.8.8"}
-    addr1_dup = %{address: "8.8.8.8:53"}
+    addr1_dup = %{address: "8.8.8.8"}
```
Comment (jamilbk) [inline elixir/apps/web/test/web/live/settings/dns_test.exs:262]: This IP conflicts with the one being set in the Fixture.

**Review by jamilbk — CHANGES_REQUESTED** [review]
Thanks for taking the initiative here.

Does connlib expect the string `ip_port`? If not, we have some tech debt to clean up here - `procotol` should be `ip` (requires a migration) and I believe we can actually rip out the entire `IPPort` Ecto Type since this is/was the only thing using it.

Happy to save that for a later iteration though but probably a good idea to add a TODO somewhere in this patch and a link to an issue, since IPPort is essentially dead code now.

**Comment by bmanifold** [comment]
> I don't really understand the CI test failures. From what I understand, the test here is actually wrong:
> addr2 hasn't been added so why do we expect that it errors with all addresses must be unique?

To add to @jamilbk's comments, there are a couple of other things to clarify in regards to your comments.

The first thing is that the section of code you referenced is using a `refute` and not an `assert`, so it is expecting to _not_ see the phrase `all addresses must be unique`.

Along with that, you mentioned that `addr2` hasn't been added, but with the code you linked `addr2` is being added to the form by calling `form()` and passing in a nested map with `addr2` in that map.

Other than those things, everything that was mentioned in @jamilbk's review is correct.  The fixture is creating an account that already has (what was previously) 3 unique DNS servers in it's config.

**Comment by thomaseizinger** [comment]
> Does connlib expect the string `ip_port`? If not, we have some tech debt to clean up here - `procotol` should be `ip` (requires a migration) and I believe we can actually rip out the entire `IPPort` Ecto Type since this is/was the only thing using it.

Yep, that is part of the API contract here unfortunately. I have a design locally for what I'd like the API to be for introducing DoH. This will have to stay around for a while though to not break old clients.

File: elixir/apps/web/test/web/live/settings/dns_test.exs (hunk 2 above)
Comment (thomaseizinger) [reply elixir/apps/web/test/web/live/settings/dns_test.exs:262]: Ah I see, not a duplicate of `addr1` but the first duplicate address? God that is a confusing variable name.

**Comment by thomaseizinger** [comment]
> Happy to save that for a later iteration though but probably a good idea to add a TODO somewhere in this patch and a link to an issue, since IPPort is essentially dead code now.

I'll record a follow-up issue.

**Comment by thomaseizinger** [comment]
> > Happy to save that for a later iteration though but probably a good idea to add a TODO somewhere in this patch and a link to an issue, since IPPort is essentially dead code now.
> 
> I'll record a follow-up issue.

Done: https://github.com/firezone/firezone/issues/10786

**Review by jamilbk — APPROVED** [review]
