### PR TITLE
fix(connlib): Increase max partition time to handle client network partitions more gracefully

### LINKED ISSUE #3302: Gracefully handle network switching
In the Apple and Windows clients, we use the platform-provided network change detectors to call `Session.disconnect` when "internet connectivity drops" and then `Session.connect` when it's back online.

We can use [`ConnectivityManager`](https://developer.android.com/reference/android/net/ConnectivityManager) to do the same on Android.

See here for more reference:

- Apple has a [`PathDidUpdate`](https://developer.apple.com/documentation/network/nwpathmonitor/2998735-pathupdatehandler) callback [that we subscribe to](https://github.com/firezone/firezone/blob/main/swift/apple/FirezoneNetworkExtension/Adapter.swift#L316) to receive network change events and react accordingly
- Windows provides a mechanism for this as well. See [this Slack thread](https://firezonehq.slack.com/archives/C067DSY7TFX/p1705451053915679) for an in-depth discussion.

### LINKED ISSUE #3334: Increase `MAX_PARTITION_TIME` substantially to prevent signing out clients without internet connectivity
For explanation see [this comment](https://github.com/firezone/firezone/issues/3302#issuecomment-1902169815). Otherwise a client that loses internet connectivity for a few minutes will be signed out. This will cause problems with clients operating headlessly.

Instead, we should _only_ call `on_disconnect(errorString)` if there's been a fatal error that absolutely requires signing out and clearing the token.

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #3334 
Fixes #3302

### CODE REVIEW

File: rust/windows-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -21,6 +21,12 @@ use ControllerRequest as Req;
 
 mod system_tray_menu;
 
+/// The Windows client doesn't use platform APIs to detect network connectivity changes,
```
Comment (jamilbk) [inline rust/windows-client/src-tauri/src/client/gui.rs:24]: @ReactorScram I'm not sure if this statement is accurate anymore (I know you had been working on the OS-provided way of managing connection state), but for example on the Android client this actually works quite well coupled with the `MAX_INTERVAL` of 5s set above.

Doing it with connlib like this here has the downside that the client could lose connectivity for a few seconds without communicating anything to the user, but the upside that it's simpler and has the same behavior across platforms.

Doing it via the platform APIs has the upside that we can communicate to the user and reconnect slightly more quickly but we need a state machine with an in-between state of "signed in but disconnected" state in the UI.

File: rust/connlib/clients/shared/src/lib.rs [hunk 2]
```diff
@@ -221,7 +226,7 @@ where
                         }
                     }
                     if let Some(t) = exponential_backoff.next_backoff() {
-                        tracing::error!("Connection to portal failed. Retrying connection to portal in {} seconds", t.as_secs());
+                        tracing::error!("Connection to portal failed. Retrying connection to portal in {} milliseconds", t.as_millis());
```
Comment (jamilbk) [inline rust/connlib/clients/shared/src/lib.rs]: This was printing `0` to the logs in many cases

File: rust/windows-client/src-tauri/src/client/gui.rs (hunk 1 above)
Comment (jamilbk) [reply rust/windows-client/src-tauri/src/client/gui.rs:24]: We could keep using platform APIs on platforms that support them if you've already built this in the Windows client, but then fallback to this implementation within connlib if not.

Comment (ReactorScram) [reply rust/windows-client/src-tauri/src/client/gui.rs:24]: @jamilbk It's still pretty accurate. #3262 will log the network changes but it won't use them to reconnect connlib, because of #2975.

And yeah the Windows API seems pretty reliable, it can tell us within about 3 seconds when we gain or lose Internet connectivity. I don't have any middle states for LAN-only or IPv4-only but those could be added.

So if connlib can take those as a hint like "Hey the Internet is probably back" it would be cool. Otherwise I can block it out or just spin it off as a utility crate and delete it from the code if we don't need it.

File: rust/connlib/clients/android/src/lib.rs [hunk 3]
```diff
@@ -22,6 +22,11 @@ use thiserror::Error;
 use tracing_subscriber::prelude::*;
 use tracing_subscriber::EnvFilter;
 
+/// The Android client doesn't use platform APIs to detect network connectivity changes,
+/// so we rely on connlib to do so. We have valid use cases for headless Android clients
+/// (IoT devices, point-of-sale devices, etc), so try to reconnect for 7 days.
+const MAX_PARTITION_TIME_SECS: Duration = Duration::from_secs(60 * 60 * 24 * 7);
```
Comment (ReactorScram) [inline rust/connlib/clients/android/src/lib.rs]: These could all just be `MAX_PARTITION_TIME` since they're a Duration, not an integer number of seconds, right?

File: rust/connlib/clients/shared/src/lib.rs [hunk 4]
```diff
@@ -25,6 +25,11 @@ mod messages;
 
 struct StopRuntime;
 
+/// Max interval to retry connections to the portal if it's down or the client has network
+/// connectivity changes. Set this to something short so that the end-user experiences
+/// minimal disruption to their Firezone resources when switching networks.
+const MAX_RECONNECT_INTERVAL_SECS: Duration = Duration::from_secs(5);
```
Comment (ReactorScram) [inline rust/connlib/clients/shared/src/lib.rs]: Same for this, `MAX_RECONNECT_INTERVAL`

File: rust/connlib/clients/shared/src/lib.rs (hunk 2 above)
Comment (ReactorScram) [reply rust/connlib/clients/shared/src/lib.rs]: Nit: If it's not machine-readable either way, just doing the debug print `{:?}` will automatically put a reasonable unit like `s`, `ms`, or `us` (with the mu Unicode character)

**Review by ReactorScram — DISMISSED** [review]
Looks good, just think the `_SECS` on the time constants should be removed since they're all Durations. Unless that's for the sake of `git grep` or something?

File: rust/connlib/clients/shared/src/lib.rs (hunk 2 above)
Comment (conectado) [reply rust/connlib/clients/shared/src/lib.rs]: Since we are already changing this line, I propose we change it to a `debug` level.

**Review by conectado — APPROVED** [review]
Looks good to be merged, after the comments @ReactorScram left are fixed

File: rust/connlib/clients/android/src/lib.rs (hunk 3 above)
Comment (jamilbk) [reply rust/connlib/clients/android/src/lib.rs]: Good catch!

File: rust/connlib/clients/shared/src/lib.rs (hunk 2 above)
Comment (jamilbk) [reply rust/connlib/clients/shared/src/lib.rs]: 👍

File: rust/windows-client/src-tauri/src/client/gui.rs (hunk 1 above)
Comment (jamilbk) [reply rust/windows-client/src-tauri/src/client/gui.rs:24]: Sounds good. After discussion today it seems like we probably need both implementations anyway.
