### PR TITLE
fix(apple): prevent utun increments from IPC calls

### LINKED ISSUE #10580: utun pool increments can push interface order past others, resulting in broken DNS interception
Sometimes, when signing out and back in on macOS (and likely iOS), the system resets our `utun` causing it to increment. This actually causes the DNS resolver `order` number to increment by `600` for each `utun` index.

The problem with this is that if our `order` exceeds the second DNS resolver `order`, which typically is the DHCP resolver on the system and has an `order` of `200000`, we will now fail to intercept DNS and all DNS resources will fail to work.

Here are examples of working and not working scenarios:

#### Working - `utun34`

```
scutil --dns
DNS configuration

resolver #1
  search domain[0] : attlocal.net
  nameserver[0] : 100.100.111.1
  nameserver[1] : fd00:2021:1111:8000:100:100:111:0
  if_index : 60 (utun34)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 108400

resolver #2
  nameserver[0] : 2600:1173:1231:1234::1
  nameserver[1] : 192.168.1.254
  if_index : 17 (en8)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

#### Broken - `utun376`

```
❯ scutil --dns
DNS configuration

resolver #1
  search domain[0] : lan
  nameserver[0] : 100.100.111.1
  if_index : 397 (utun376)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 230400

resolver #2
  nameserver[0] : 10.10.10.1
  if_index : 14 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

---

The fix here seems to be to find a way to reset the `utun` index pool somehow, or find some way to lock the resolver `order`.

This could be an issue on iOS too, so hopefully whatever fixes this on macOS will work there too.

### PR DESCRIPTION
**Pull request by klochowicz**
On macOS, IPC calls to the network extension can wake it whilst not
connected, causing the system to create a utun device.
If startTunnel() is not subsequently called, these devices
persist and accumulate over time.

The existing dryStartStopCycle() mechanism was introduced to wake the
extension after upgrades, but other IPC operations (log management
functions) could also wake the extension without proper cleanup.

Solution
--------

Add wrapper functions in IPCClient that automatically handle wake-up
and cleanup lifecycle for IPC calls made whilst disconnected:

- Check VPN connection status
- If connected: execute IPC operation directly (utun already exists)
- If disconnected: wake extension → wait 500ms → execute IPC → cleanup

Implementation
--------------

For async IPC operations (clearLogs, getLogFolderSize):
  Created free functions in IPCClient that wrap low-level IPC calls
  with wrapIPCCallIfNeeded():
  - clearLogsWithCleanup(store:session:)
  - getLogFolderSizeWithCleanup(store:session:)

For callback-based exportLogs:
  We cannot use wrapper because exportLogs returns immediately and uses
  callbacks for streaming chunks. Wrapper would call stop() before
  export finishes, killing the extension mid-stream.

  Solution: Manual wake-up/cleanup in LogExporter where we already have
  continuation that waits for chunk.done signal:
  1. Check if extension needs waking (vpnStatus != .connected)
  2. If yes: wake extension, wait 500ms
  3. Start export with callbacks
  4. When chunk.done=true: cleanup utun device, then resume continuation
  5. On error: cleanup utun device, then resume with error
  
  
  Fixes #10580

### CODE REVIEW

**Comment by klochowicz** [comment]
open question:

shall we allow `setConfiguration()` to wake up the extension or keep the previous fix?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 1]
```diff
@@ -97,6 +97,69 @@ enum IPCClient {
...
+  ///
+  /// On macOS, IPC calls can wake the network extension, which creates a utun device.
+  /// If not properly cleaned up (via stop), these devices accumulate.
+  @MainActor
+  private static func wrapIPCCallIfNeeded<T>(
+    store: Store,
+    session: NETunnelProviderSession,
+    operation: @MainActor () async throws -> T
+  ) async throws -> T {
+    #if os(macOS)
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Given that nothing of this body is shared, should we conditionally define the functions instead?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 2]
```diff
@@ -97,6 +97,69 @@ enum IPCClient {
...
+      if store.vpnStatus == .connected {
+        // Extension already running, utun already created, just execute
+        return try await operation()
+      } else {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: You already have an early return above so you can get rid of this `else` and save on rightwards-drift for the remaining logic.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 3]
```diff
@@ -97,6 +97,69 @@ enum IPCClient {
...
+        // Extension needs waking, must cleanup afterwards
+        try dryStartStopCycle(session: session, configuration: store.configuration)
+
+        // Wait for extension to wake up and be ready for IPC (500ms)
+        try await Task.sleep(nanoseconds: 500_000_000)
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: What happens if we don't do this?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 4]
```diff
@@ -97,6 +97,69 @@ enum IPCClient {
...
+
+        do {
+          let result = try await operation()
+          try stop(session: session)
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Should we solve this with `defer` instead?

**Review by thomaseizinger — APPROVED** [review]
Nice work! Some minor, mostly stylistic feedback.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 3 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: I had the error `Unable to count logs: noIPCData. Is the XPC service running?`

Adding this arbitrary hack has proven to be effective in getting rid of it.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 4 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: yeah, good point!

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 2 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: I do prefer visually to know the both alternatives being indented, and myself find the right drift helpful...
Happy to change it if you find it unbearable though.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 5]
```diff
@@ -97,6 +97,71 @@ enum IPCClient {
...
+
+  #if os(macOS)
+    /// Wraps an IPC call with wake-up and cleanup logic when VPN is not connected.
+    ///
+    /// On macOS, IPC calls can wake the network extension, which creates a utun device.
+    /// If not properly cleaned up (via stop), these devices accumulate.
+    @MainActor
+    private static func wrapIPCCallIfNeeded<T>(
+      store: Store,
+      session: NETunnelProviderSession,
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: `NETunnelProviderSession` is the source of truth regarding the VPN status. `Store` simply binds to its updates.

You can remove the `store` from this function call (passing `configuration` instead) and use `session.status` instead.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 6]
```diff
@@ -97,6 +97,71 @@ enum IPCClient {
...
+  @MainActor
+  static func getLogFolderSizeWithCleanup(store: Store, session: NETunnelProviderSession)
+    async throws -> Int64
+  {
+    return try await wrapIPCCallIfNeeded(store: store, session: session) {
+      try await getLogFolderSize(session: session)
+    }
+  }
+
+  // MARK: - Low-level IPC operations
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Rather than adding special cases of these functions and make the caller need to know when to use them, why not standardize a single way of making IPC calls which checks `session.status == .connected` before _all_ `sendProviderMessage` calls? Then, the all of the call sites in this module do not need to conditionally use the `Cleanup` version or not and we won't need two versions of each IPC call for macOS and iOS going forward.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift [hunk 7]
```diff
@@ -54,7 +55,28 @@ import System
       let fileHandle = try FileHandle(forWritingTo: tunnelLogURL)
 
       // 3. Await tunnel log export from tunnel process
-      try await withCheckedThrowingContinuation { continuation in
+      // Wake extension if needed, export logs, cleanup when done
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift]: Why are we explicitly waking the extension here? Isn't this the job of IPCClient to worry about whether or not to dry start stop when an IPC call is made?

**Review by jamilbk — DISMISSED** [review]
In the right direction! I think we need to clean up a couple things.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 3 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Let's hope we don't need to tune this a lot!

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 2 above)
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: What irks me about it is the inconsistency between this function (where understanding `else` is trivial) and how I'd write a say 200+ lines long function with more boolean conditions.

In my opinion, `if-else` doesn't scale which is the reason why I generally avoid it altogether to ensure consistency.

It is not a blocker for me, I just hoped to be able to convince you that early returns are better :)

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift (hunk 7 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift]: I've refactored the code to be able to more easily call the wrapper.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 2 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: For me, when we have lots of nested things, we should rather use iterators (in Rust), or perhaps split the function.

I really appreciate the explanation though. Will keep it in mind; I've addressed it here, will try to get used to it. :)

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: > For me, when we have lots of nested things, we should rather use iterators (in Rust), or perhaps split the function.

You'd have to show me what you mean by that. I can't imagine right now how iterators can easily express combinations of boolean logic.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift [hunk 8]
```diff
@@ -29,6 +29,7 @@ import System
 
     static func export(
       to archiveURL: URL,
+      store: Store,
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift]: Should this also just take `Configuration`?

**Review by thomaseizinger — APPROVED** [review]
One more non-blocking comment, otherwise LGTM

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 9]
```diff
@@ -97,39 +97,130 @@ enum IPCClient {
...
+      configuration: Configuration,
+      operation: @MainActor () async throws -> T
+    ) async throws -> T {
+      if session.status == .connected {
+        // Extension already running, utun already created, just execute
+        return try await operation()
+      }
+
+      // Extension needs waking, must cleanup afterwards
+      try dryStartStopCycle(session: session, configuration: configuration)
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Doesn't this already start *and* stop the tunnel? I.e. I don't think the stop below is needed?

The completionHandler in the startTunnel on the PacketTunnelProvider side returns a dummy error which is the same as calling stop I believe.

Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: On this note, if that's the case, we start-stop twice:

dryStartStopCycle and then again implicitly via the IPC call, and then a final stop.

@klochowicz Do you mind if I push a commit to this branch? I think that'll be faster than providing the feedback here.

Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: I don't mind, go ahead! I started using `--force-with-lease` so I won't accidentally erase your changes.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 10]
```diff
@@ -28,148 +28,116 @@ enum IPCClient {
   }
 
   // Encoder used to send messages to the tunnel
-  static let encoder = PropertyListEncoder()
-  static let decoder = PropertyListDecoder()
+  private static let encoder = PropertyListEncoder()
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift:31]: These were unused outside of this module.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 11]
```diff
@@ -28,148 +28,116 @@ enum IPCClient {
...
+  private static let decoder = PropertyListDecoder()
 
   // Auto-connect
   @MainActor
-  static func start(session: NETunnelProviderSession, configuration: Configuration) throws {
-    let tunnelConfiguration = configuration.toTunnelConfiguration()
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift:37]: I've reverted this in favor of the `setConfiguration` method, and added `Equatable` to `TunnelConfiguration` so we can avoid needless tunnel configuration saves.

The approach introduced in #10757 suffers from the following class of bugs:

- App is signed out
- User saves configuration, i.e. log filter
- User then switches on the VPN from system settings (common on iOS)
- tunnel now is started with stale configuration

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 12]
```diff
@@ -28,148 +28,116 @@ enum IPCClient {
...
-    async throws
-  {
-    let tunnelConfiguration = await configuration.toTunnelConfiguration()
-    let message = ProviderMessage.setConfiguration(tunnelConfiguration)
+    // Get data from the provider - if hash matches, provider returns nil
+    return try await sendProviderMessage(session: session, message: message)
+  }
 
-    if session.status != .connected {
-      Log.trace("Not setting configuration whilst not connected")
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift:94]: Our private version of sendProviderMessage handles this case for us now.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift [hunk 13]
```diff
@@ -52,33 +52,10 @@ import System
         .appendingPathComponent("tunnel.zip")
       fileManager.createFile(atPath: tunnelLogURL.path, contents: nil)
       let fileHandle = try FileHandle(forWritingTo: tunnelLogURL)
+      defer { try? fileHandle.close() }
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/LogExporter.swift:55]: Ensures we close the file handle regardless of outcome.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Configuration.swift [hunk 14]
```diff
@@ -203,3 +203,11 @@ public struct TunnelConfiguration: Codable, Sendable {
     self.internetResourceEnabled = internetResourceEnabled
   }
 }
+
+extension TunnelConfiguration: Equatable {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Configuration.swift:207]: Avoids needless IPC calls

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 15]
```diff
@@ -126,7 +138,7 @@ public final class Store: ObservableObject {
 
     IPCClient.subscribeToVPNStatusUpdates(session: session, handler: vpnStatusChangeHandler)
 
-    let initialStatus = IPCClient.sessionStatus(session: session)
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:129]: This `sessionStatus` seemed like a useless abstraction now with IPCClient as a enum class.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 16]
```diff
@@ -238,17 +250,7 @@ public final class Store: ObservableObject {
       throw VPNConfigurationManagerError.managerNotInitialized
     }
 
-    #if os(macOS)
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:241]: This is unneeded with the approach now implemented in this PR.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 17]
```diff
@@ -362,26 +364,9 @@ public final class Store: ObservableObject {
...
-        try session.sendProviderMessage(
-          IPCClient.encoder.encode(ProviderMessage.getResourceList(currentHash))
-        ) { data in
-          continuation.resume(returning: data)
-        }
-      } catch {
-        continuation.resume(throwing: error)
-      }
-    }
-
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:382]: This business logic was moved back into IPCClient, where we can leverage the new `sendProviderMessage` private func to have consistent IPC call semantics.

Not sure how it escaped, but it would probably be a tad cleaner to keep IPC calls in that module instead of calling them directly from other areas of the codebase.

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift [hunk 18]
```diff
@@ -56,10 +55,10 @@ class PacketTunnelProvider: NEPacketTunnelProvider {
...
     completionHandler: @escaping @Sendable (Error?) -> Void
   ) {
-    // Dummy start to get the extension running on macOS after upgrade
-    if options?["dryRun"] as? Bool == true {
-      Log.info("Dry run startup requested - extension awakened but not starting tunnel")
-      return completionHandler(PacketTunnelProviderError.dryStartStopCycle)
+    // Dummy start to attach a utun for cleanup later
+    if options?["dryStart"] as? Bool == true {
+      Log.info("Dry start requested - extension awakened and temporarily starting tunnel")
+      return completionHandler(nil)
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:61]: This ensures the tunnel _is actually started_ so that we are in a "started" state when the next IPC call hits.

**Review by jamilbk — COMMENTED** [review]
@klochowicz I pushed several cleanup changes and a few bug fixes. Please review the most recent commits and let me know if you have any questions.

@thomaseizinger Another review would be much appreciated.


#### Tested

- [x] Log count / clear / export works on iOS and macOS
- [x] `utun` does not increment in either connected or disconnected states on macOS and iOS
- [x] Configuration is persisted and latest is used on macOS / iOS
- [x] Configuration observer does not send IPC calls unless `TunnelConfiguration` instance has meaningfully changed.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift [hunk 19]
```diff
@@ -195,33 +163,50 @@ enum IPCClient {
...
       } catch {
         continuation.resume(throwing: error)
       }
     }
   }
+
+  /// On macOS, the tunnel needs to be in a connected, connecting, or reasserting state for the utun to be removed
+  /// upon stopTunnel. We do this by ensuring the tunnel is "started" prior to any IPC call. If so, we return true
+  /// so that the caller may stop the tunnel afterwards.
+  private static func maybeDryStart(_ session: NETunnelProviderSession) async throws -> Bool {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: Depending on how fancy we want to get and whether Swift supports this, we could return a RAII guard object here that internally maintains a reference to the session can calls `stopTunnel` as soon as it goes out of scope. That way, you don't have to remember to act on this boolean but it happens automatically.

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: To make this even more type-safe, you could then force all IPC messages through this "guard" object and thus enforce at compile-time that we call `maybeDryStart` in order to send any IPC message whilst also cleaning things up afterwards (if we were not connected).

**Review by thomaseizinger — APPROVED** [review]
LGTM

I left a suggestion for a more type-safe interface although I am not sure if this can be expressed in Swift.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 11 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift:37]: thanks, this is definitely a better approach - limiting this call to only fire when needed is the right thing to do.

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift (hunk 18 above)
Comment (klochowicz) [reply swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:61]: nit: perhaps a new name would be appropriate instead of "dryRun"? like "cycle" or something similar?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 19 above)
Comment (klochowicz) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: I guess this could be possible if we created a class, set a boolean and cleaned up resources in *deinit* section....

**Review by klochowicz — COMMENTED** [review]
LGTM!

thank you @jamilbk for cleaning it up.

can't approve on github, as I created the PR

File: swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift (hunk 18 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/PacketTunnelProvider.swift:61]: 👍 renamed

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift (hunk 19 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/IPCClient.swift]: @klochowicz has the right idea I think. If this grows more in complexity perhaps that will be warranted, but for now since the weird semantics are confined to just this IPCClient module perhaps we can save it for a later date.

**Review by jamilbk — APPROVED** [review]

**Comment by jamilbk** [comment]
Merging to get into next release
