### PR TITLE
fix(apple): don't send connlib DNS server IPs that aren't IPs

### LINKED ISSUE #9055: dev_firezone_firezone_network_extension.AdapterError: setDnsError("Failed to deserialize DNS servers from JSON: invalid IP address syntax at line 1 column 30") (Code: 2)
Sentry Issue: [APPLE-CLIENT-3B](https://firezone-inc.sentry.io/issues/6358638684/?referrer=github_integration)

```
dev_firezone_firezone_network_extension.AdapterError: setDnsError("Failed to deserialize DNS servers from JSON: invalid IP address syntax at line 1 column 30") (Code: 2)
```

### PR DESCRIPTION
**Pull request by jamilbk**
When pulling IPs from system resolvers, it's possible the IPv6 addresses may contain scopes which will cause connlib to barf when parsing.

To fix these, we first convert to the Swift-native type `IPv4Address` or `IPv6Address` and then use the string representation of those types, which normalizes them to plain addresses.

Fixes #9055

### CODE REVIEW

**Comment by jamilbk** [comment]
Tested on iOS and macOS with IPv4 and IPv6 resolvers with manual scopes applied.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 1]
```diff
@@ -448,7 +448,22 @@ extension Adapter: CallbackHandlerDelegate {
     let resolvers = resetToSystemDNSGettingBindResolvers()
 #endif
 
-    return resolvers
+    var parsedResolvers: [String] = []
+
+    // Normalize addresses to remove any possible scope suffixes
+    resolvers.forEach { stringAddress in
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:454]: Is there no iterator-like way of doing this? Like `filter_map` and then `collect`? Would avoid the mutability.

**Review by thomaseizinger — APPROVED** [review]
