### PR TITLE
chore(gui-client/linux): fix deep links on Ubuntu 22.04

### LINKED ISSUE #4880: bug(gui-client/linux): deep links acting strange in Ubuntu test VMs
https://firezonehq.slack.com/archives/C067DSY7TFX/p1714663372360139

Observed on 047bf78e1

- 20.04, it seems to open a 2nd instance of the GUI sometimes
- 22.04, it consistently shows an error dialog instead, even though our code to register ran properly:

image

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #4880

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/deep_link/linux.rs [hunk 1]
```diff
@@ -25,17 +26,6 @@ impl Server {
...
-        if let Ok(username) = std::env::var("SUDO_USER") {
-            // chown so that when the non-privileged browser launches us,
-            // we can send a message to our privileged main process
-            std::process::Command::new("chown")
-                .arg(username)
-                .arg(&path)
-                .status()
-                .context("couldn't chown Unix domain socket")?;
-        }
-
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/deep_link/linux.rs:38]: This is all gone because we aren't using sudo on the GUI after the process separation change.

**Review by jamilbk — APPROVED** [review]
LGTM
