### PR TITLE
refactor(windows): fix cancellation-safety when listening for network events

### LINKED ISSUE #4226: bug(gui-client): incorrect cancel-safety with `tokio::sync::Notify`
Gabi pointed this out here https://github.com/firezone/firezone/pull/4198#discussion_r1531300295

I thought `Notify::notified` was safe the way I used it for network changes, but it can lose events.

### PR DESCRIPTION
**Pull request by ReactorScram**
Not sure if this is a fix or a refactor.

Closes #4226

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/network_changes/windows.rs [hunk 1]
```diff
@@ -238,8 +242,8 @@ impl Worker {
         Ok(())
     }
 
-    pub(crate) async fn notified(&self) {
-        self.notify.notified().await;
+    pub(crate) async fn notified(&mut self) {
```
Comment (conectado) [inline rust/gui-client/src-tauri/src/client/network_changes/windows.rs:245]: I think using `recv` here as a name will be less surprising for someone going through this function

**Review by conectado — APPROVED** [review]
