### PR TITLE
fix(portal): Fix bug with preset values in policies dropdowns

### LINKED ISSUE #4688: Can't create Policy when group is pre-filled
From the Groups page -> Add Policy

Screenshot 2024-04-18 at 11 28 56 AM

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #4688

### CODE REVIEW

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 1]
```diff
@@ -137,6 +137,12 @@ defmodule Web.FormComponents do
     ~H"""
     <div phx-feedback-for={@name}>
       <.label for={@id}><%= @label %></.label>
+      <input
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/components/form_components.ex:140]: `<select>` does not send the data if it's disabled, so we add a hidden input that will do the job for it.

**Review by jamilbk — APPROVED** [review]

**Review by bmanifold — APPROVED** [review]
LGTM
