### PR TITLE
Fix/lost connection request

### LINKED ISSUE #2880: Lost NewConnection message/NewConnection response is not handled
since before that message we modify `gateway_awaiting_connection`. That gateway keeps awaiting connection forever and always return pending message.

This is probably the partial cause of #2848

But there are other problems with that since:
* weird dns response are unexplained by this
* it might or might not be that the connection to 1.1.1.1 was already established(if the tunnel connected/disconnected or the peer expired then it wasn't established but it still deserves more testing)

### PR DESCRIPTION
**Pull request by conectado**
Should fix #2880

The way I do it is after ~10 seconds dropping the `gateway_awaiting_connection` and let the client try the connection again, depending on upper layer, I think this is fine since the cases where this happens is unlikely.

It's hard to test thoroughly but I'll test with bad-condition simulators, [pumba](https://github.com/alexei-led/pumba) seems promising. In the meantime I'm still creating the PR so that I can have it reviewed.

Edit: Using Pumba with different % of packet loss things seems to go well, and connections are actually established even if the packets are loss. (Making a note that we should integrate pumba with our CI)

### CODE REVIEW

File: rust/connlib/tunnel/src/client.rs [hunk 1]
```diff
@@ -281,6 +291,22 @@ impl ClientState {
                 channel: p.channel.clone(),
             })
         }) else {
+            match self
+                .gateway_awaiting_connection_timers
+                // Note: we don't need to set a timer here because
+                // the FutureMap already expires things, it seems redundant
+                // to also have timer that expires.
+                .try_push(gateway, std::future::pending())
```
Comment (conectado) [inline rust/connlib/tunnel/src/client.rs:299]: @thomaseizinger this feels like I'm abusing the `FutureMap` interface, I'm open to other suggestions if this is not ideal

Comment (thomaseizinger) [reply rust/connlib/tunnel/src/client.rs:299]: Ha, neat workaround :D

Maybe a basic `SelectAll` with a `BoxFuture` that first sleeps and then emits the ID is a better design here?

Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:299]: `JoinSet` seems to have done the trick :) though we lose the bounded part which was nice but it's a good tradeoff

Comment (thomaseizinger) [reply rust/connlib/tunnel/src/client.rs:299]: Note that the semantics are slightly different. A `JoinSet` seems to run things in the background by spawning them onto the runtime.

File: rust/connlib/tunnel/src/client.rs [hunk 2]
```diff
@@ -167,10 +169,19 @@ pub struct ClientState {
...
+    // This timer exist for an unlikely case, on unreliable connections where the RequestConnection message
+    // or the response is lost:
+    // This would remove the "PendingConnection" message and be able to try the connection again.
+    // There are some edge cases that come with this:
+    // * a gateway in a VERY unlikely case could recieve the connection request twice. This will stop any connection attempt and make the whole thing start again.
+    // if this would happen often the UX would be awful but this is only in cases where messages are delayed for more than 10 seconds, it's enough that it doesn't break correctness.
+    // * even more unlikely a tunnel could be established in a sort of race condition when this timer goes off. Again a similar behavior to the one above will happen, the webrtc connection will be forcefully terminated from the gateway.
+    // then the old peer will expire, this might take ~180 seconds. This is an even worse experience but the likelihood of this happen is infinitesimaly small, again correctness is the only important part.
+    gateway_awaiting_connection_timers: JoinSet<GatewayId>,
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/client.rs]: I am making a note in https://github.com/firezone/firezone/issues/2966 to also deal with this problem in `firezone-connection`.

File: rust/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:299]: ah, yeah, that makes sense, I think it works fine for this case and the types are a bit simpler to write

Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:299]: I thought a bit more about this and I think I will go with the `FutureMap`, there's a *very* unlikely edge case that this prevents:
* This timer could have been initiated and this would delete the `gateway_id` from `gateway_awaiting_connection`
* We can lose connection and restart a connection intent to the same gateway
* The timer triggers while we are establishing a connection

with `FutureMap` we can remove the timer before it ever goes off if a connection is established, without an additional reference to the futures.

**Review by ReactorScram — APPROVED** [review]
I don't understand most of it but it looks okay at a glance
