### PR TITLE
fix(connlib): never delete allowed ips for a peer given dns

### LINKED ISSUE #3094: Connlib performance degradation due to the clients "forgetting" allowed ips
This happens after a dns resource ips are refreshed, connlib tries to reuse as many internal ips as possible to prevent ip exhaustion but this causes it to "forget" the old external ip for that reused internal ip and due to some sockets being still around using the old ip(or programs that doesn't re-resolve the ip) this will cause those connections to hang.

The fix is just trying not to leave any gaps but for any new external ip we assign a new internal ip.

### PR DESCRIPTION
**Pull request by conectado**
Fixes #3094 

This will make the "packet unallowed" messages you might see in connlib and make connections smoother.

### CODE REVIEW

File: rust/connlib/tunnel/src/client.rs [hunk 1]
```diff
@@ -644,6 +641,21 @@ impl IpProvider {
...
     }
+
+    pub fn get_ip_for(&mut self, ip: &IpAddr) -> Option<IpAddr> {
+        let ip = match ip {
+            IpAddr::V4(_) => self.ipv4.next().map(Into::into),
+            IpAddr::V6(_) => self.ipv6.next().map(Into::into),
+        };
+
+        if ip.is_none() {
+            // TODO: we might want to make the iterator cyclic or another strategy to prevent ip exhaustion
```
Comment (jamilbk) [inline rust/connlib/tunnel/src/client.rs:652]: When would this happen? If there are more than ~2 million unique IPs seen from matched domains?

File: rust/connlib/tunnel/src/client.rs [hunk 2]
```diff
@@ -644,6 +641,21 @@ impl IpProvider {
...
+            // this might happen in ipv4 if tokens are too long lived.
+            tracing::error!("IP exhaustion: Please reset your client");
+        }
+
+        ip
+    }
```
Comment (jamilbk) [inline rust/connlib/tunnel/src/client.rs:658]: Would it be a little more clear to name these differently?

```suggestion
    pub fn get_proxy_ip_for(&mut self, resolved_ip: &IpAddr) -> Option<IpAddr> {
        let proxy_ip = match resolved_ip {
            IpAddr::V4(_) => self.ipv4.next().map(Into::into),
            IpAddr::V6(_) => self.ipv6.next().map(Into::into),
        };

        if proxy_ip.is_none() {
            // TODO: we might want to make the iterator cyclic or another strategy to prevent ip exhaustion
            // this might happen in ipv4 if tokens are too long lived, increasing the odds we've seen over 2 million unique IPs
            tracing::error!("Proxy IP exhaustion: Reset your client to release unused IPs");
        }

        proxy_ip
    }
```

File: rust/connlib/tunnel/src/peer.rs [hunk 3]
```diff
@@ -192,22 +193,24 @@ impl Default for PacketTransformGateway {
...
+        ip_provider: &mut IpProvider,
     ) -> Option<IpAddr> {
         let mut translations = self.translations.write();
         if let Some(internal_ip) = translations.get_by_right(external_ip) {
             return Some(*internal_ip);
         }
-        translations.insert(*internal_ip, *external_ip);
-        Some(*internal_ip)
+
+        let internal_ip = ip_provider.get_ip_for(external_ip)?;
```
Comment (jamilbk) [inline rust/connlib/tunnel/src/peer.rs:210]: (nit): `proxy_ip` and `resolved_ip` might be better names for these to avoid confusion with internal IPs referring to a customer's VPC subnet. That's what I'll use when writing docs explaining how this works.

```suggestion
        let internal_ip = ip_provider.get_proxy_ip_for(external_ip)?;
```

**Review by jamilbk — COMMENTED** [review]
Just some nit about naming, otherwise LGTM!

Will defer to @ReactorScram for approval on the Rusty things.

File: rust/connlib/tunnel/src/client.rs [hunk 4]
```diff
@@ -644,6 +641,21 @@ impl IpProvider {
...
+    pub fn get_ip_for(&mut self, ip: &IpAddr) -> Option<IpAddr> {
+        let ip = match ip {
+            IpAddr::V4(_) => self.ipv4.next().map(Into::into),
+            IpAddr::V6(_) => self.ipv6.next().map(Into::into),
+        };
+
+        if ip.is_none() {
+            // TODO: we might want to make the iterator cyclic or another strategy to prevent ip exhaustion
+            // this might happen in ipv4 if tokens are too long lived.
+            tracing::error!("IP exhaustion: Please reset your client");
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/client.rs:654]: Are `tracing::error` calls supposed to bubble up to the GUI?

**Review by ReactorScram — APPROVED** [review]
I don't understand it but it looks simple enough that it shouldn't break anything

File: rust/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:652]: Exactly

File: rust/connlib/tunnel/src/client.rs (hunk 4 above)
Comment (conectado) [reply rust/connlib/tunnel/src/client.rs:654]: no but we are planning to completely get rid of `on_error` with #2867 this is just for users that look at the logs.

**Comment by thomaseizinger** [comment]
I am not sure if this applies here but @conectado can you please add tasks (or issues) to https://github.com/firezone/firezone/issues/2966 for everything that we are changing in current `firezone-tunnel`? Ideally, we would have a checklist of features that we implemented which we can cross-reference once we start integrating `firezone-connection` to ensure we have feature parity.

**Comment by conectado** [comment]
> I am not sure if this applies here but @conectado can you please add tasks (or issues) to #2966 for everything that we are changing in current `firezone-tunnel`? Ideally, we would have a checklist of features that we implemented which we can cross-reference once we start integrating `firezone-connection` to ensure we have feature parity.

@thomaseizinger this should be only connection-related things if I understand correctly, such as webrtc timeouts or anything wireguard related?

This PR in particular is about how we keep track of allowed ips(and ip translations) in the client, this will probably happen outside of `firezone-tunnel`.

I'm asking just to keep in mind what to track exactly.

**Comment by thomaseizinger** [comment]
My expectation is that even though it will be a smaller change, I expect the integration of `firezone-connection` to be almost a rewrite of `firezone-tunnel` due to the change from `async` to non;`async`, the introduction of a `UdpSocket` and the removal of `Arc` and `Mutex` as a result of going non-`async`.

Thus, I think we should have a thorough list of requirements / features that we want this to support because we don't have (integration) tests for everything.

Do you agree?
