### PR TITLE
fix(connlib): honor changes to "IP stack" after initial query

### LINKED ISSUE #11814: Honour IP stack setting of resource for cached DNS queries
When the IP stack setting of a resource gets changed after it has first been queried, we continue to return the old IPs because they are sitting in the cache. This caused an issue for a customer that used VSCode which internalls uses nodeJS's network stack. The happy eyeballs implementation of nodeJS is known to be broken which resulted in the HTTP requests sent from within VSCode to Firezone resources not work.

### PR DESCRIPTION
**Pull request by thomaseizinger**
When Firezone first resolves a DNS query for a resource, it assigns the IPs based on the "IP stack" setting at the time. If this is set to "Dual", then both IPv4 and IPv6 addresses are assigned. These IPs are then cached in a process-wide cache to ensure we have sticky DNS resource IPs even across sessions.

Changing the IP stack setting after an initial DNS query was therefore not supported. The IPs were already assigned and thus got returned, essentially bypassing the setting. Signing out of Firezone and signing back in does not fix this due to the process-wide cache.

The solution here is not to invalidate the cache but to instead always assign IPv4 and IPv6 addresses but check the _current_ IP stack setting every time we answer a query. This ensures that even when changing the setting later, it is immediately honored.

Resolves: #11814

### CODE REVIEW

File: rust/libs/connlib/tunnel/src/client/dns_cache.rs [hunk 1]
```diff
@@ -203,4 +206,27 @@ mod tests {
 
         assert_eq!(ttls, vec![1700, 3500]);
     }
+
+    #[test]
```
Comment (jamilbk) [inline rust/libs/connlib/tunnel/src/client/dns_cache.rs:210]: 👍

**Review by jamilbk — APPROVED** [review]
LGTM
