### PR TITLE
connlib: decouple data and control plane and fix backoff reset

### LINKED ISSUE #2503: Gateway should restart backoff timer after it succesfully connects
Right now, each time it connects the timer increases and it should only do that when a connection fails and reset after it's successful.

### PR DESCRIPTION
**Pull request by conectado**
This fixes #2503 
Also:
* decouples data-plane and control-plane on the gateway
* fixes a thing were a client would stop retrying connecting to a resource if it failed too many times
* add all routes on start instead of on a per-route basis

### CODE REVIEW

File: rust/gateway/src/main.rs [hunk 1]
```diff
@@ -31,17 +33,10 @@ async fn main() -> Result<()> {
...
-        ExponentialBackoffBuilder::default()
-            .with_max_elapsed_time(None)
-            .build(),
-        move || run(tunnel.clone(), connect_url.clone()).map_err(to_backoff),
-        |error, t| {
-            tracing::warn!(retry_in = ?t, "Error connecting to portal: {error:#}");
-        },
-    ));
+    let task =
+        tokio::spawn(async move { run_loop(connect_url, private_key).await }).map_err(Into::into);
```
Comment (thomaseizinger) [inline rust/gateway/src/main.rs]: There shouldn't be a need for `async move` if you don't capture any references in the parameters.

File: rust/gateway/src/main.rs [hunk 2]
```diff
@@ -51,9 +46,35 @@ async fn main() -> Result<()> {
...
+            &mut exponential_backoff,
+        )
+        .await
+        // Just satisfying the type system
+        .and(Ok(()))
+        .or_else(client_errors)?;
+
+        let Some(backoff) = exponential_backoff.next_backoff() else {
+            panic!("Gateway should backoff forever");
+        };
```
Comment (thomaseizinger) [inline rust/gateway/src/main.rs]: I think an `expect` is more idiomatic here.

File: rust/gateway/src/main.rs [hunk 3]
```diff
@@ -75,13 +98,13 @@ async fn run(
 }
 
 /// Maps our [`anyhow::Error`] to either a permanent or transient [`backoff`] error.
-fn to_backoff(e: anyhow::Error) -> backoff::Error<anyhow::Error> {
+fn client_errors(e: anyhow::Error) -> Result<()> {
```
Comment (thomaseizinger) [inline rust/gateway/src/main.rs:165]: Can we name this function something more descriptive?

Comment (thomaseizinger) [reply rust/gateway/src/main.rs:165]: Plus the docs are now wrong :)

File: rust/connlib/tunnel/src/control_protocol/gateway.rs [hunk 4]
```diff
@@ -214,13 +214,6 @@ where
         resource_addresses: Vec<IpNetwork>,
     ) -> Result<()> {
         tracing::trace!(?peer_config.ips, "new_data_channel_open");
-        let device = self.device.load().clone().ok_or(Error::NoIface)?;
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/control_protocol/gateway.rs:217]: This looks unrelated, can you send this as a separate PR?

File: rust/connlib/tunnel/src/client.rs [hunk 5]
```diff
@@ -687,7 +687,9 @@ impl RoleState for ClientState {
                 }
 
                 Poll::Ready((id, Some(Err(e)))) => {
-                    tracing::warn!(resource_id = %id, "Connection establishment timeout: {e}")
+                    tracing::warn!(resource_id = %id, "Connection establishment timeout: {e}");
+                    self.awaiting_connection.remove(&id);
+                    self.awaiting_connection_timers.remove(id);
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/client.rs:692]: What is this related to? Is this just an isolated fix? Can we have it in a separate PR? :)

File: rust/gateway/src/main.rs
Comment (thomaseizinger) [inline rust/gateway/src/main.rs:1]: Can you explain what we are trying to achieve here? Spawning tasks with cloned senders within a `poll` function is not really how this design was intended.

**Review by thomaseizinger — COMMENTED** [review]
There is a lot going on in here. It would be nice if we could split this into multiple PRs so we can land the smaller fixes separately while discussing the design for changing the eventloop of the gateway.

File: rust/gateway/src/main.rs
Comment (conectado) [reply rust/gateway/src/main.rs:1]: I know this is not the intended design and I should have left a big TODO 😓 but the problem here is that we should never exit the main `Eventloop`. Or at least we shouldn't without re-entering immediately.

Therefore when `Eventloop` is running we can't count on the `portal` being connected, so we need to include a re-connection mechanism inside the eventloop if we don't separate it to a different task.

The ideal way to do this would be inside the eventloop we have a timer that's activated after the portal disconnects and it does the whole exponential backoff I think this would require `PhoenixChannel`'s `init` to have a `poll`-like (although I wonder if we can get away by just polling the future).

I think this is good as a temporary solution, since w/o this changes the gateway is broken, because we need to maintain the data-plane even if we disconnect from the portal.

**Comment by jamilbk** [comment]
@thomaseizinger Chatted with Gabi, and we need to merge to fix the gateways currently deployed. Opened an issue to track getting your feedback resolved: https://github.com/firezone/firezone/issues/2929

**Review by jamilbk — APPROVED** [review]
