### PR TITLE
fix(ux): Remove some padding around vertical_table

### LINKED ISSUE #5228: Spacing: Less padding in details panes for each view (0.5rem)

### PR DESCRIPTION
**Pull request by jamilbk**
# Before

Screenshot 2024-06-05 at 2 08 20 PM

# After
Screenshot 2024-06-05 at 2 11 58 PM

Fixes #5228

### CODE REVIEW

**Review by bmanifold — APPROVED** [review]
We're in to personal preference here, so I'll leave the final call to you, but anyway we could split the difference on the X axis?

File: elixir/apps/web/lib/web/components/table_components.ex [hunk 1]
```diff
@@ -324,14 +324,14 @@ defmodule Web.TableComponents do
       <th
         scope="row"
         class={[
-          "text-right px-6 py-4 font-medium text-neutral-900 whitespace-nowrap",
+          "text-right px-2 py-3 font-medium text-neutral-900 whitespace-nowrap",
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/table_components.ex]:
```suggestion
          "text-right px-4 py-3 font-medium text-neutral-900 whitespace-nowrap",
```

File: elixir/apps/web/lib/web/components/table_components.ex [hunk 2]
```diff
@@ -324,14 +324,14 @@ defmodule Web.TableComponents do
...
           "bg-neutral-50 w-1/5",
           @label_class
         ]}
       >
         <%= render_slot(@label) %>
       </th>
-      <td class={["px-6 py-4", @value_class]}>
+      <td class={["px-2 py-3", @value_class]}>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/table_components.ex]:
```suggestion
      <td class={["px-4 py-3", @value_class]}>
```
