### PR TITLE
Handle EXTERNAL_URL missing scheme

### LINKED ISSUE #1314: Update to 0.7.2 failed in docker image
I am running the docker image. The update last night to 0.7.2 failed and it seems like broke the database. Trying to downgrade to 0.7.1, 0.7.0 and 0.6.16 did not work. See the log below:

```
postgres_1  |                                                                                                                                                                                                                                 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization                                                                                                                                            
postgres_1  |                                                                                                                                                                                                                                 
postgres_1  | 2023-01-14 15:26:31.962 UTC [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit                                                      
postgres_1  | 2023-01-14 15:26:31.962 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432                                                                                                                                            
postgres_1  | 2023-01-14 15:26:31.962 UTC [1] LOG:  listening on IPv6 address "::", port 5432                                                                                                                                                 
postgres_1  | 2023-01-14 15:26:31.972 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                                                                                                              
postgres_1  | 2023-01-14 15:26:31.990 UTC [29] LOG:  database system was shut down at 2023-01-14 15:26:30 UTC                                                                                                                                 
postgres_1  | 2023-01-14 15:26:32.001 UTC [1] LOG:  database system is ready to accept connections                                                                                                                                            
firezone    | 15:26:33.191 [info] == Running 20221224210654 FzHttp.Repo.Migrations.FixSitesNullableFields.change/0 forward                                                                                                                    
firezone    | ** (ArgumentError) construction of binary failed: segment 1 of type 'binary': expected a binary but got: nil
firezone    |     /app/lib/fz_http-0.7.2/priv/repo/migrations/20221224210654_fix_sites_nullable_fields.exs:14: FzHttp.Repo.Migrations.FixSitesNullableFields.change/0
firezone    |     (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:288: Ecto.Migration.Runner.perform_operation/3                                                                                                                                
firezone    |     (stdlib 4.1.1) timer.erl:235: :timer.tc/1                                                                                                                                                                                   
firezone    |     (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8                                                                                                                                               
firezone    |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:337: Ecto.Migrator.attempt/8                                                                                                                                                          
firezone    |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:258: anonymous fn/5 in Ecto.Migrator.do_up/5                                                                                                                                          
firezone    |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:308: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7                                                                                                             
firezone    |     nofile:1: (file)                                                                                                                                                                                                            
firezone    | sh: true: unknown operand                                                                                                                                                                                                       
firezone    | 15:26:33.869 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)                                                                                                                                        
firezone    | 15:26:33.871 [info] Access FzHttpWeb.Endpoint at https://firezone.hammerhaus.dedyn.io                                                                                                                                           
postgres_1  | 2023-01-14 15:26:33.895 UTC [38] ERROR:  column c0.default_client_persistent_keepalive does not exist at character 163                                                                                                          
postgres_1  | 2023-01-14 15:26:33.895 UTC [38] STATEMENT:  SELECT c0."id", c0."allow_unprivileged_device_management", c0."allow_unprivileged_device_configuration", c0."local_auth_enabled", c0."disable_vpn_on_oidc_error", c0."default_clien
t_persistent_keepalive", c0."default_client_mtu", c0."default_client_endpoint", c0."default_client_dns", c0."default_client_allowed_ips", c0."vpn_session_duration", c0."logo", c0."openid_connect_providers", c0."saml_identity_providers", c
0."inserted_at", c0."updated_at" FROM "configurations" AS c0                                                                                                                                                                                  
firezone    | 15:26:33.900 [notice] Application fz_http exited: FzHttp.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzHttp.OIDC.StartProxy                                                              
firezone    |     ** (EXIT) an exception was raised:                                                                                                                                                                                          
firezone    |         ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.default_client_persistent_keepalive does not exist                                                                                                         
firezone    |                                                                                                                                                                                                                                 
firezone    |     query: SELECT c0."id", c0."allow_unprivileged_device_management", c0."allow_unprivileged_device_configuration", c0."local_auth_enabled", c0."disable_vpn_on_oidc_error", c0."default_client_persistent_keepalive", c0."defau
lt_client_mtu", c0."default_client_endpoint", c0."default_client_dns", c0."default_client_allowed_ips", c0."vpn_session_duration", c0."logo", c0."openid_connect_providers", c0."saml_identity_providers", c0."inserted_at", c0."updated_at" F
ROM "configurations" AS c0                                                                                                                                                                                                                    
firezone    |             (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1                                                                                                                             
firezone    |             (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6                                                                                                                                          
firezone    |             (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4                                                                                                                                          
firezone    |             (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3                         
firezone    |             (ecto 3.9.4) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3                                                                                                                                             
firezone    |             (fz_http 0.7.2) lib/fz_http/configurations.ex:11: FzHttp.Configurations.get!/1                                                                                                                                      
firezone    |             (fz_http 0.7.2) lib/fz_http/oidc/start_proxy.ex:17: FzHttp.OIDC.StartProxy.start_link/1       
firezone    |             (stdlib 4.1.1) supervisor.erl:414: :supervisor.do_start_child_i/3                             
firezone    | {"Kernel pid terminated",application_controller,"{application_start_failure,fz_http,{{shutdown,{failed_to_start_child,'Elixir.FzHttp.OIDC.StartProxy',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error'
,connection_id => 38,message => nil,postgres => #{code => undefined_column,file => <<\"parse_relation.c\">>,line => <<\"3651\">>,message => <<\"column c0.default_client_persistent_keepalive does not exist\">>,pg_code => <<\"42703\">>,posi
tion => <<\"163\">>,routine => <<\"errorMissingColumn\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"SELECT c0.\\"id\\", c0.\\"allow_unprivileged_device_management\\", c0.\\"allow_unprivileged_device_configuration\\"
, c0.\\"local_auth_enabled\\", c0.\\"disable_vpn_on_oidc_error\\", c0.\\"default_client_persistent_keepalive\\", c0.\\"default_client_mtu\\", c0.\\"default_client_endpoint\\", c0.\\"default_client_dns\\", c0.\\"default_client_allowed_ips\
\", c0.\\"vpn_session_duration\\", c0.\\"logo\\", c0.\\"openid_connect_providers\\", c0.\\"saml_identity_providers\\", c0.\\"inserted_at\\", c0.\\"updated_at\\" FROM \\"configurations\\" AS c0\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_c
all_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,\"lib/ecto/adapters/sql.ex\"},{line,828}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{f
ile,\"lib/ecto/repo/queryable.ex\"},{line,229}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,19}]},{'Elixir.Ecto.Repo.Queryable','one!',3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,159}]},{'Elixir.Fz
Http.Configurations','get!',1,[{file,\"lib/fz_http/configurations.ex\"},{line,11}]},{'Elixir.FzHttp.OIDC.StartProxy',start_link,1,[{file,\"lib/fz_http/oidc/start_proxy.ex\"},{line,17}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.e
rl\"},{line,414}]}]}}}},{'Elixir.FzHttp.Application',start,[normal,[]]}}}"}
firezone    | Kernel pid terminated (application_controller) ({application_start_failure,fz_http,{{shutdown,{failed_to_start_child,'Elixir.FzHttp.OIDC.StartProxy',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',
connection_id => 38,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"3651">>,message => <<"column c0.default_client_persistent_keepalive does not exist">>,pg_code => <<"42703">>,position => <
<"163">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"SELECT c0.\"id\", c0.\"allow_unprivileged_device_management\", c0.\"allow_unprivileged_device_configuration\", c0.\"local_auth_enable
d\", c0.\"disable_vpn_on_oidc_error\", c0.\"default_client_persistent_keepalive\", c0.\"default_client_mtu\", c0.\"default_client_endpoint\", c0.\"default_client_dns\", c0.\"default_client_allowed_ips\", c0.\"vpn_session_duration\", c0.\"
logo\", c0.\"openid_connect_providers\", c0.\"saml_identity_providers\", c0.\"inserte                                  
firezone    |                                              
firezone    | Crash dump is being written to: erl_crash.dump...done 
```

 I do not have a backup yet, since I just started with firezone, so I cannot test if that would restore an old version. LEt e know if you need anything else.

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #1314

### CODE REVIEW

File: .formatter.exs [hunk 1]
```diff
@@ -1,4 +1,5 @@
 [
+  plugins: [Phoenix.LiveView.HTMLFormatter],
```
Comment (jamilbk) [inline .formatter.exs:2]: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-setup

Comment (AndrewDryga) [reply .formatter.exs:2]: It's already enabled here: https://github.com/firezone/firezone/blame/master/apps/fz_http/.formatter.exs#L16

**Review by AndrewDryga — DISMISSED** [review]
