### PR TITLE
fix(android): init Sentry layer as part of logging

### LINKED ISSUE #8050: android: check that Sentry integration works
Haven't received a single alert which seems sus.

### PR DESCRIPTION
**Pull request by thomaseizinger**
Resolves: #8050.

### CODE REVIEW

File: rust/connlib/clients/apple/src/lib.rs [hunk 1]
```diff
@@ -264,6 +264,8 @@ impl WrappedSession {
             .build()?;
         let _guard = runtime.enter(); // Constructing `PhoenixChannel` requires a runtime context.
 
+        tracing::warn!("This is a test");
+
```
Comment (jamilbk) [inline rust/connlib/clients/apple/src/lib.rs]: Meant to remove this?

```suggestion
```

Comment (thomaseizinger) [reply rust/connlib/clients/apple/src/lib.rs]: Still testing.

**Review by jamilbk — APPROVED** [review]
