### PR TITLE
fix(website): Wrap app in MixpanelProvider

### LINKED ISSUE #5744: Fix Mixpanel website integration
We are getting 0 events from Mixpanel.

### PR DESCRIPTION
**Pull request by jamilbk**
We need to wrap the `children` by `MixpanelProvider` and not simply include the Provider on the page.

Fixes #5744

### CODE REVIEW

File: website/src/components/Providers/index.jsx [hunk 1]
```diff
@@ -1,21 +1,23 @@
 "use client";
 import { MixpanelProvider } from "react-mixpanel-browser";
 import { HubspotProvider } from "next-hubspot";
-import { GoogleAnalytics } from "@next/third-parties/google";
```
Comment (jamilbk) [inline website/src/components/Providers/index.jsx:4]: This wasn't even working.

Comment (thomaseizinger) [reply website/src/components/Providers/index.jsx:4]: So we don't want to use google analytics?

**Review by thomaseizinger — APPROVED** [review]
Makes sense, context in React only applies to children. Can we verify this using the preview deploy somehow?

File: website/src/components/Providers/index.jsx (hunk 1 above)
Comment (jamilbk) [reply website/src/components/Providers/index.jsx:4]: We don't have a project for it, and we're already using Mixpanel for analytics. We already have GoogleAds and LinkedInInsidghts configured.

Comment (jamilbk) [reply website/src/components/Providers/index.jsx:4]: As well as Hubspot analytics 🙃

**Comment by jamilbk** [comment]
> Makes sense, context in React only applies to children. Can we verify this using the preview deploy somehow?

Yep! Working now:

```
{
  "event": "$mp_web_page_view",
  "properties": {
    "time": 1720152157.475,
    "distinct_id": "$device:190810eecc9b5-09d87999df4a13-19525637-4da900-190810eecc9b6",
    "$browser": "Chrome",
    "$browser_version": 126,
    "$city": "Mountain View",
    "$current_url": "https://firezone-git-fix-mixpanel-loading-firezone.vercel.app/",
    "$device_id": "190810eecc9b5-09d87999df4a13-19525637-4da900-190810eecc9b6",
    "$initial_referrer": "https://vercel.live/",
    "$initial_referring_domain": "vercel.live",
    "$insert_id": "ypub6abmujtnm117",
    "$lib_version": "2.53.0",
    "$mp_api_endpoint": "api.mixpanel.com",
    "$mp_api_timestamp_ms": 1720152162474,
    "$os": "Mac OS X",
    "$referrer": "https://vercel.live/",
    "$referring_domain": "vercel.live",
    "$region": "California",
    "$screen_height": 1692,
    "$screen_width": 3008,
    "mp_country_code": "US",
    "mp_lib": "web",
    "mp_processing_time_ms": 1720152162533,
    "mp_sent_by_lib_version": "2.53.0"
  }
}
```
