### PR TITLE
fix(apple/macOS): Fetch providerStopReason over IPC on macOS

### LINKED ISSUE #7468: Fix passing of `providerStopReason` in macOS so that "You have been signed out" continues to function
With the move the system extension, the gui process no longer knows why the tunnel became disconnected. This was stored in a plaintext file when the tunnel disconnected and then read by the gui process. If it was a 401, the user was shown an alert dialog to sign in again (session expired).

We need to use some other mechanism (Keychain will work) for communicating the last stopped reason back to the gui process.

### PR DESCRIPTION
**Pull request by jamilbk**
Since we no longer have access to the tunnel's group container from the app process, we need to move reading the last VPN stop reason to an IPC call. This call is used to show an alert to the user when their connlib session has been disconnected due to 401: Unauthorized.

Fixes #7468

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/TunnelManager.swift [hunk 1]
```diff
@@ -378,6 +384,37 @@ public class TunnelManager {
     loop()
   }
 
+  func consumeStopReason() async throws -> String {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/TunnelManager.swift:387]: This looks a bit repeated with other callbacks, assuming we can abstract over decoding the response.

**Review by thomaseizinger — APPROVED** [review]
LGTM

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/TunnelManager.swift (hunk 1 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/TunnelManager.swift:387]: Agree, I think it would make sense to move the IPC stuff into a dedicated module to keep TunnelManager focused on the actual vpn profile.

Will refactor in #7549
