### PR TITLE
chore(connlib): fix flaky IO test

### LINKED ISSUE #11904: Flaky cargo test?
https://github.com/firezone/firezone/actions/runs/21416093905/job/61664906539

### PR DESCRIPTION
**Pull request by thomaseizinger**
It appears that sometimes, something is listening on port 40000 on GitHub Actions runners. By switching to port 0, we pretty much guarantee that binding to the first address will work.

Resolves: #11904

### CODE REVIEW

File: rust/libs/connlib/tunnel/src/io.rs [hunk 1]
```diff
@@ -729,7 +729,7 @@ mod tests {
         let mut io = Io::for_test();
 
         let result = io.rebind_dns(vec![
-            SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), 40000), // This one will almost definitely work.
```
Comment (klochowicz) [inline rust/libs/connlib/tunnel/src/io.rs:732]: turns out the comment did not age well :D

**Review by klochowicz — APPROVED** [review]
