### PR TITLE
Don't override SAML config booleans

### LINKED ISSUE #1321: 0.7.2 - SAML Google not working
I have proper configuration in accordance with the documentation. All users gets error 403 with response:
`access_denied {:envelope, {:error, :no_signature}}`

Few days ago, I tested version 6.1.16 and the authentication worked.

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #1321 

Also updates a couple tests to read from `EXTERNAL_URL` instead of `http://localhost:4002` (these were failing in my env because I have a different value set)

### CODE REVIEW

File: apps/fz_http/test/fz_http_web/acceptance/admin_test.exs [hunk 1]
```diff
@@ -494,6 +494,21 @@ defmodule FzHttpWeb.Acceptance.AdminTest do
                  auto_create_users: true
                }
 
+      assert FzHttp.Config.fetch_env!(:samly, Samly.Provider) == [
```
Comment (jamilbk) [inline apps/fz_http/test/fz_http_web/acceptance/admin_test.exs:497]: This was the failing test I wrote to prevent this in the future.

**Comment by jamilbk** [comment]
Sigh, unfortunately the static analysis check is failing because it doesn't recognize the `key_function/2` function being called in the `test` env. Perhaps there's a way to ignore warnings for that file with `mix compile`.

File: apps/fz_http/lib/fz_http/config.ex [hunk 2]
```diff
@@ -67,4 +75,7 @@ defmodule FzHttp.Config do
       end
     end
   end
+
+  # String.to_atom/1 is only used in test env
+  defp key_function(app, key), do: String.to_atom("#{app}-#{key}")
```
Comment (AndrewDryga) [inline apps/fz_http/lib/fz_http/config.ex]: @jamilbk just move `defp key_function` inside `else` block above and static analysis won't complain about it. Plus you can then remove a comment too :).

File: apps/fz_http/lib/fz_http/config.ex [hunk 3]
```diff
@@ -25,9 +25,17 @@ defmodule FzHttp.Config do
...
+           :error <-
+             fetch_process_value(
+               get_last_pid_from_pdict_list(:"$ancestors"),
+               key_function(app, key)
+             ),
+           :error <-
+             fetch_process_value(
+               get_last_pid_from_pdict_list(:"$callers"),
+               key_function(app, key)
+             ) do
```
Comment (AndrewDryga) [inline apps/fz_http/lib/fz_http/config.ex]:
```suggestion
      pdict_key = key_function(app, key)
      
      with :error <- fetch_process_value(pdict_key),
           :error <- fetch_process_value(get_last_pid_from_pdict_list(:"$ancestors"), pdict_key),
           :error <- fetch_process_value(get_last_pid_from_pdict_list(:"$callers"), pdict_key) do
```

Comment (AndrewDryga) [reply apps/fz_http/lib/fz_http/config.ex]: ^ this will prevent function calling over and over again and make formatted code nicer

File: apps/fz_http/lib/fz_http/config.ex (hunk 2 above)
Comment (jamilbk) [reply apps/fz_http/lib/fz_http/config.ex]: D'oh, that's where I meant to define it. Thanks for the second pair of eyes.

**Review by AndrewDryga — APPROVED** [review]
