### PR TITLE
fix(ci): ensure version markers are replaced across all files

### LINKED ISSUE #10748: Apple releases don't bundle the correct version
Customer reports macOS client is reporting an outdated release - 1.5.8 instead of 1.5.9. This is causing clients to show as outdated on their clients page.

Image
Image

Regression introduced in cb50800d52

scripts/bump-versions.sh needs to be updated to hit the new paths.

### PR DESCRIPTION
**Pull request by jamilbk**
Upon moving the version string from PKG_VERSION and Cargo.toml, we lost the bump version automation. To avoid more bugs here in the future, we now check for the version marker across all Git-tracked files, regardless of their extension.

Fixes #10748

### CODE REVIEW

File: website/src/components/Changelog/Android.tsx [hunk 1]
```diff
@@ -21,6 +21,9 @@ export default function Android() {
     <Entries downloadLinks={downloadLinks} title="Android">
       {/* When you cut a release, remove any solved issues from the "known issues" lists over in `client-apps`. This must not be done when the issue's PR merges. */}
       <Unreleased>
+        <ChangeItem pull="10752">
```
Comment (thomaseizinger) [inline website/src/components/Changelog/Android.tsx:24]: Hold off on this, we need to merge #10745 first.

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Concept ACK. #10745 needs to merge first though, hence not approving.

Can we just remove these file extensions and just update the version string wherever we find them? I think this has happened several times now.

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@jamilbk I've pushed some follow-up commits, let me know what you think.

File: swift/apple/Firezone/xcconfig/config.xcconfig [hunk 2]
```diff
@@ -9,3 +9,6 @@ CODE_SIGN_STYLE = Automatic
 
 // Include the dynamic build number created during the build phase
 #include? "dynamic_build_number.xcconfig"
+
+// mark:next-apple-version
+MARKETING_VERSION=1.5.10
```
Comment (jamilbk) [inline swift/apple/Firezone/xcconfig/config.xcconfig:14]: I could have sworn I tried this a while ago, but Xcode didn't like it. Seems to be working ok now.

**Comment by jamilbk** [comment]
> @jamilbk I've pushed some follow-up commits, let me know what you think.

LGTM
