### PR TITLE
fix(phoenix-channel): replace all non-ASCII chars in user agent

### LINKED ISSUE #9706: Android client does not show Resources and isn't listed as Client
#### Describe the bug

The android client doesn't show any resources after signing in. In the admin UI it isn't visible as client. The VPN connection isn't active.

#### To Reproduce

Create a Site,Resource,Policy. Install android client and sign in.

#### Expected behavior

See the available resources (on iOS it works) and connect to the network.

#### Screenshots / Logs

No logs available, maybe the daemon doesn't start?
[logs.zip](https://github.com/user-attachments/files/20967067/logs.zip)

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Android Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.5.2
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Android 15, Redmi Note 11T
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ App Store

### PR DESCRIPTION
**Pull request by thomaseizinger**
HTTP headers only reliably support ASCII characters. We include information like the user's kernel build name in there and therefore need to strip non-ASCII characters from that to avoid encoding errors.

Fixes: #9706

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@lehmanju Could you test the following build? https://github.com/firezone/firezone/actions/runs/15973109999/artifacts/3431929785

File: rust/connlib/phoenix-channel/src/lib.rs [hunk 1]
```diff
@@ -824,6 +824,8 @@ fn make_request(url: Url, host: String, user_agent: String) -> Request {
     OsRng.fill_bytes(&mut r);
     let key = base64::engine::general_purpose::STANDARD.encode(r);
 
+    let user_agent = user_agent.replace(|c: char| !c.is_ascii(), "");
```
Comment (jamilbk) [inline rust/connlib/phoenix-channel/src/lib.rs:827]: Thinking more about this, wdyt of URL-encoding this instead of stripping? Then we can decode in the portal-side, and be able to retain this information.

We don't use the field now, but will in the future for more policy conditions.

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > We don't use the field now, but will in the future for more policy conditions.

What do you mean we don't use it? It is displayed in the portal right?

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > Thinking more about this, wdyt of URL-encoding this instead of stripping? Then we can decode in the portal-side, and be able to retain this information.

We can do that but it is a breaking change to what we currently do so we need to add some logic to the portal first to check if the string is URL-encoded and if it is, decode and otherwise use as is.

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: I'd suggest we strip for now to fix the issue and then coordinate around how we can send this over. There are multiple strategies on how we can deal with this breaking change.

Comment (jamilbk) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: It's not a breaking change from the portal's perspective - the user agent field will just be upserted with the encoded data.

Decoding all previous user agents will be essentially a no-op since they are not encoded today.

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > It's not a breaking change from the portal's perspective - the user agent field will just be upserted with the encoded data.

And displayed in an encoded form to the user. Surely that is semantically a breaking change?

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: All I am saying is: Without any changes to the portal, we can't just URL-encode the header and I'd like to not couple this fix to a coordinated release with the portal if it is not absolutely necessary.

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > > It's not a breaking change from the portal's perspective - the user agent field will just be upserted with the encoded data.
> 
> And displayed in an encoded form to the user. Surely that is semantically a breaking change?

Also, don't we extract the version from the user-agent and use that for controlling which clients and gateways are allowed to connect to each other?

Comment (jamilbk) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: https://github.com/firezone/firezone/pull/9727

Comment (jamilbk) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > Also, don't we extract the version from the user-agent and use that for controlling which clients and gateways are allowed to connect to each other?

Yeah but that won't be affected because the `/` and `.` fields we use in that logic are not affected by URI encoding.

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: Can we just merge this as a fix and delay the encoding? There is absolutely no harm in removing non-ASCII chars for now and we can always ship something more sophisticated later.

Iterative progress for the win.

Comment (jamilbk) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: See https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/version.ex

Comment (thomaseizinger) [reply rust/connlib/phoenix-channel/src/lib.rs:827]: > > Also, don't we extract the version from the user-agent and use that for controlling which clients and gateways are allowed to connect to each other?
> 
> Yeah but that won't be affected because the `/` and `.` fields we use in that logic are not affected by URI encoding.

Of course it is. A URI-encoded `/` is `%2F` or what am I missing?

**Comment by lehmanju** [comment]
> @lehmanju Could you test the following build? https://github.com/firezone/firezone/actions/runs/15973109999/artifacts/3431929785

Yes! The resources show correctly. However, I am not able to access them or resolve DNS queries. Logs will follow.

**Review by jamilbk — APPROVED** [review]
SGTM. I'll just link https://github.com/firezone/firezone/issues/8368 so that we can revisit this issue when we might need to use this data.
