### PR TITLE
fix(portal): only show `never synced` correctly

### LINKED ISSUE #7715: `Never synced` for failing IdP connectors
When an IdP sync is failing we show "Never synced" on the IdP list page.

### PR DESCRIPTION
**Pull request by jamilbk**
It's confusing that we clear this field upon sync failure. Instead, we let it track the time of the last sync.

Will be cleaned up in #6294 so just applying a minimal fix now.

Fixes #7715

### CODE REVIEW

File: elixir/apps/domain/lib/domain/auth/provider/changeset.ex [hunk 1]
```diff
@@ -63,7 +63,6 @@ defmodule Domain.Auth.Provider.Changeset do
 
     provider
     |> change()
-    |> put_change(:last_synced_at, nil)
```
Comment (bmanifold) [inline elixir/apps/domain/lib/domain/auth/provider/changeset.ex]: I agree with your assessment that this is slightly confusing.  Just wanted to make sure you've checked that we don't use this as a logical decision anywhere else in the code?

Comment (jamilbk) [reply elixir/apps/domain/lib/domain/auth/provider/changeset.ex]: Sigh - yeah, I started poking around here and this is quite a ball of yarn. It's probably safer to just change how we determine when to show the "Never synced" message.

Will need to clean this all up when directory sync is overhauled.

**Review by bmanifold — APPROVED** [review]
