### PR TITLE
fix(gui-client/windows): show a tooltip when the mouse hovers over the tray icon

### LINKED ISSUE #5547: Title is blank when hovering over tray icon in Windows
Should say `Firezone`.

Screenshot 2024-06-25 095015

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5547
**Only works on Windows** due to a limitation in or below Tauri.

image

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -102,7 +104,9 @@ pub(crate) fn run(
         inject_faults: cli.inject_faults,
     };
 
-    let tray = SystemTray::new().with_menu(system_tray_menu::signed_out());
+    let tray = SystemTray::new()
+        .with_menu(system_tray_menu::signed_out())
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/gui.rs:108]: Can't use `build_system_tray_menu` here because the controller isn't built yet

**Review by jamilbk — APPROVED** [review]
Thanks for the quick fix! LGTM
