### PR TITLE
fix(portal): Prevent wildcard abuse in DNS resources

### LINKED ISSUE #6357: Prohibit TLD wildcards
- [ ] Prevent TLD match-alls that can result in massive DNS resources matching
- [ ] Think about cases where users use things like `*.lan` might be used for home networks or subnets

### LINKED ISSUE #6415: Prevent complete DNS wildcard match
Customer reports he is able to enter `*.*.*.*` as a valid DNS Resource. I'm not sure this should be allowed, as it will likely not have the desired effect.

- [ ] don't allow wildcard characters for the TLD
- [ ] consider requiring the host part to not have wildcards either (e.g. firezone.dev)

### PR DESCRIPTION
**Pull request by AndrewDryga**
Now most common TLDs can't have `*` or `?` on the 2nd level, and TLD can't have matching in itself either.

Closes #6357
Closes #6415

### CODE REVIEW

File: elixir/apps/domain/lib/domain/resources/resource/changeset.ex [hunk 1]
```diff
@@ -56,10 +78,32 @@ defmodule Domain.Resources.Resource.Changeset do
...
+          [tld | _rest] -> {String.downcase(tld), ""}
+          [] -> {"", ""}
+        end
+
+      cond do
+        String.contains?(tld, ["*", "?"]) ->
+          [{field, {"TLD cannot be contain wildcards", []}}]
+
+        tld in @prohibited_tlds ->
+          [{field, {"#{tld} cannot be used, please add a DNS alias to /etc/hosts instead", []}}]
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/resources/resource/changeset.ex]:
```suggestion
          [{field, {"#{tld} cannot be used as a TLD. Try adding a DNS alias to /etc/hosts on the Gateway(s) instead", []}}]
```

File: elixir/apps/domain/test/domain/resources_test.exs [hunk 2]
```diff
@@ -969,6 +967,26 @@ defmodule Domain.ResourcesTest do
 
         assert {:ok, _resource} = create_resource(attrs, subject)
       end
+
+      attrs = Fixtures.Resources.resource_attrs(address: "localhost")
+      assert {:error, changeset} = create_resource(attrs, subject)
+      error = "localhost cannot be used, please add a DNS alias to /etc/hosts instead"
```
Comment (jamilbk) [inline elixir/apps/domain/test/domain/resources_test.exs]:
```suggestion
      error = "localhost cannot be used as a TLD. Try adding a DNS alias to /etc/hosts on the Gateway(s) instead"
```

File: elixir/apps/domain/test/domain/resources_test.exs [hunk 3]
```diff
@@ -969,6 +967,26 @@ defmodule Domain.ResourcesTest do
...
+      assert error in errors_on(changeset).address
+
+      attrs = Fixtures.Resources.resource_attrs(address: "a.localhost")
+      assert {:error, changeset} = create_resource(attrs, subject)
+      error = "localhost cannot be used, please add a DNS alias to /etc/hosts instead"
```
Comment (jamilbk) [inline elixir/apps/domain/test/domain/resources_test.exs]:
```suggestion
      error = "localhost cannot be used as a TLD. Try adding a DNS alias to /etc/hosts on the Gateway(s) instead"
```

File: elixir/apps/domain/lib/domain/resources/resource/changeset.ex [hunk 4]
```diff
@@ -56,10 +78,32 @@ defmodule Domain.Resources.Resource.Changeset do
...
+        |> Enum.reverse()
+        |> case do
+          [tld, domain | _rest] -> {String.downcase(tld), String.downcase(domain)}
+          [tld | _rest] -> {String.downcase(tld), ""}
+          [] -> {"", ""}
+        end
+
+      cond do
+        String.contains?(tld, ["*", "?"]) ->
+          [{field, {"TLD cannot be contain wildcards", []}}]
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/resources/resource/changeset.ex]:
```suggestion
          [{field, {"TLD cannot contain wildcards", []}}]
```

File: elixir/apps/domain/test/domain/resources_test.exs [hunk 5]
```diff
@@ -969,6 +967,26 @@ defmodule Domain.ResourcesTest do
...
+      assert error in errors_on(changeset).address
+
+      attrs = Fixtures.Resources.resource_attrs(address: "*.com")
+      assert {:error, changeset} = create_resource(attrs, subject)
+      error = "second level domain for IANA TLDs cannot contain wildcards"
+      assert error in errors_on(changeset).address
+
+      attrs = Fixtures.Resources.resource_attrs(address: "foo.*")
+      assert {:error, changeset} = create_resource(attrs, subject)
+      error = "TLD cannot be contain wildcards"
```
Comment (jamilbk) [inline elixir/apps/domain/test/domain/resources_test.exs]:
```suggestion
      error = "TLD cannot contain wildcards"
```

**Review by jamilbk — APPROVED** [review]
Just some minor text fixes otherwise LGTM
