### PR TITLE
fix(client/windows): put NRPT rules in a special spot if Group Policy is active

### LINKED ISSUE #6469: Domain-joined Windows hosts break Split DNS
When a Windows machine joins a domain, the Group Policy sets an empty NRPT policy. Unfortunately this overrides the one we set in the local policy section.

Normal behavior:

1. Open Firezone
2. `Get-DnsClientNrptRule` will show a rule with `DisplayName` = `Firezone SplitDNS`
3. `Get-DnsClientNrptPolicy` will show the same rule with our sentinel DNS servers

To replicate:

1. Close Firezone
4. Clear any NRPT rules in `HKLM/SOFTWARE/Policies/Microsoft/Windows NT/DNSClient/` and `HKLM/SYSTEM/CurrentControlSet/Services/Dnscache/Parameters/DnsPolicyConfig`
5. Under `HKLM/SOFTWARE/Policies/Microsoft/Windows NT/DNSClient/`, create an empty key `DNSPolicyConfig`
6. Run `gpupdate /Force` (May not be necessary)
7. Open Firezone
8. `Get-DnsClientNrptRule` will show a rule with `DisplayName` = `Firezone SplitDNS`
9. `Get-DnsClientNrptPolicy` will show nothing.

Proposed fix:

- When activating NRPT DNS control, If the `DNSPolicyConfig` key exists, then we should also add our NRPT rule to the Group Policy section of the registry, and we call `RefreshPolicyEx`
- When deactivating NRPT DNS control, we should try to delete our rule from the Group Policy section of the registry

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #6469

DNS deactivation now also uses the registry instead of PowerShell, but this may not be faster, since the latency would already be hidden from users most of the time.

### CODE REVIEW

File: rust/headless-client/src/dns_control/windows.rs [hunk 1]
```diff
@@ -104,31 +110,64 @@ fn activate(dns_config: &[IpAddr]) -> Result<()> {
...
-        .join("Dnscache")
-        .join("Parameters")
-        .join("DnsPolicyConfig")
-        .join(NRPT_REG_KEY);
+    // It's safe to always set the local rule.
+    let (key, _) = hklm.create_subkey(local_nrpt_path().join(NRPT_REG_KEY))?;
+    set_nrpt_rule(&key, &dns_config_string)?;
+
+    if group_policy_key_exists {
+        let (key, _) = hklm.create_subkey(group_nrpt_path().join(NRPT_REG_KEY))?;
```
Comment (ReactorScram) [inline rust/headless-client/src/dns_control/windows.rs]: Probably a TOCTOU gap here, if someone is taking the computer off of Group Policy right as we're activating DNS. Worth fixing before merging maybe, but not before testing

Comment (jamilbk) [reply rust/headless-client/src/dns_control/windows.rs]: Probably such a low chance it might not be worth the added complexity. I think always having the local key set should mean that it will fall back to that if GPO is disabled?

**Review by jamilbk — APPROVED** [review]

File: rust/headless-client/src/dns_control/windows.rs (hunk 1 above)
Comment (ReactorScram) [reply rust/headless-client/src/dns_control/windows.rs]: Yeah I'll leave it alone for now then and just leave a TODO
