### PR TITLE
fix(rust/client): set sentry release version and environment correctly

### LINKED ISSUE #6854: bug(rust/gui-client): release number on Sentry is wrong
#### Describe the bug

It's probably picking up the `0.1.0` from `firezone-telemetry` or something.

#### To Reproduce

`firezone-client-gui --panic`

Sentry.io will show the release as `0.1.0`

#### Expected behavior

Expected 1.3.7

#### Screenshots / Logs

image

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #6854 

- Sets release version from the GUI Client / Headless Client version instead of the `firezone-telemetry` version
- Set environment to "production" and "staging" for well-known API URLs, and "self-hosted" for others, since environments in Sentry can't have slashes in them
- Sets API URL as a tag
- Sets release to `unit test` for unit testing `firezone-telemetry` itself, since it has no good version number

image

### CODE REVIEW

File: rust/telemetry/src/lib.rs [hunk 1]
```diff
@@ -51,13 +51,16 @@ impl Telemetry {
         tracing::info!("Starting telemetry");
         let inner = sentry::init((
             dsn.0,
+            // Can't use URLs as `environment` here, because Sentry doesn't allow slashes in environments.
```
Comment (thomaseizinger) [inline rust/telemetry/src/lib.rs]: Should we match on our well-known environments and fallback to something else if the customer is self-hosted?

- `api.firezone.dev` => `production`
- `api.firez.one` => `staging`
- other => `self-hosted`

**Review by thomaseizinger — APPROVED** [review]
