### PR TITLE
windows: fix deep links

### LINKED ISSUE #2808: windows: Panic in tauri-plugin-deep-link if 2 Windows users try to run the client at the same time
**Describe the bug**
The 2nd instance will panic here https://github.com/FabianLars/tauri-plugin-deep-link/blob/0c28b75ac663b4ba0fb1f0d1ea4220f82a583764/src/windows.rs#L59

I'm guessing this is what happens to the 2nd instance:
- `prepare` tries to connect to the local socket and fails, because it's owned by the instance in another desktop session, so it believes we are the only instance
- `register` tries to listen on its own local socket and fails because the sockets share the same namespace

**To Reproduce**
1. Log in to unprivileged Windows account
2. Start Firezone
3. Switch users to another Windows account, leaving the unprivileged account signed in but locked
4. Start Firezone in debug mode in a terminal

**Expected behavior**
Expected the 2nd instance to either send a message to the first instance on the other account, or the 2nd instance to consider itself the first instance for this user and not panic.

**Screenshots / Logs**
```
thread '<unnamed>' panicked at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-deep-link-0.1.2\src\windows.rs:59:18:
Can't create listener: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

**Platform (please complete the following information):**
 - Firezone Version 3518937ad1fad2
 - OS: Windows 11

**Additional context**
Probably need to report this upstream to Tauri. Since we aren't going to allow multiple Windows users for 1.0 we can probably call this a known issue on our side.

### LINKED ISSUE #2878: windows: can't auth when running as admin in release mode
The GUI never changed to a signed-in state. Need to set up some logs that work even without a CLI. Should also gracefully try to sign in and show logs even if we don't have admin powers and can't start wintun.

### PR DESCRIPTION
**Pull request by ReactorScram**
Stacked on PR #2888

This will fix #2878 by setting some Windows security permissions to let non-admin clients connect to a named pipe server owned by an admin process.

It should also give us a path to fix 2808 (If I link it, Github assumes this PR closes that issue?), since it'll be our own code instead of tauri-plugin-deep-link, and we can just choose not to panic. I'm using Tokio's `named_pipe` module where that panic happens, and Tokio is good about just returning Results instead of panicking.

### CODE REVIEW

**Comment by ReactorScram** [comment]
Should be ready in the next hour.
Did this test: (and noted thoroughly, because the permissions have been an issue)

1. Signed out and closed Firezone
2. Deleted the deep link key from the registry with RegEdit
3. Confirmed that Firefox doesn't know what to do with our deep link (it searches in DDG for it)
4. Double-clicked on a release exe from Windows Explorer
5. Clicked through the UAC dialog
6. Observed in RegEdit that the registry key was re-created
7. Clicked "Sign-in"
8. Pretended to be Apple and cut-pasted the redirect into a "firezone-fd0020211111://lorem_ipsum" URL
9. Open that URL in Firefox
10. Click through another UAC dialog (since our exe _always_ asks to escalate, whoops)
11. Confirm Firezone is signed in

I should open an issue to try to get rid of the 2nd UAC dialog, right?

**Comment by ReactorScram** [comment]
Works okay on 004365dee

For that 2nd UAC dialog, it seems like you can't elevate* a process at runtime https://superuser.com/questions/693793/how-do-i-grant-elevated-privileges-for-a-program-during-runtime#693820

And I'm not sure whether there's a reliable way to detect if we have the right privileges ahead of time.

So, if the startup delay is acceptable, I might do this:
- Change the manifest back to non-admin (removes the 2nd UAC dialog when opening deep links)
- When the client starts, if it's a full instance and not just opening a deep link, try creating and destroying the adapter with wintun. If this fails, immediately re-launch ourselves with elevated privilege (this would let us run some debug commands without elevating, if we need)

So then it'll only show UAC at launch, and we'll know that we have enough privileges for wintun because we already tested it.

*I'd been saying "Escalate"

File: rust/windows-client/src-tauri/src/client/deep_link.rs [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+        // But this doesn't require us to listen on TCP.
+
+        let mut server_options = named_pipe::ServerOptions::new();
+        server_options.first_pipe_instance(true);
+
+        // This will allow non-admin clients to connect to us even if we're running as admin
+        let mut sd = WinSec::SECURITY_DESCRIPTOR::default();
+        let psd = WinSec::PSECURITY_DESCRIPTOR(&mut sd as *mut _ as *mut c_void);
+        unsafe {
+            // ChatGPT pointed me to these functions, it's better than the official MS docs
```
Comment (jamilbk) [inline rust/windows-client/src-tauri/src/client/deep_link.rs:63]: 🤣

Comment (ReactorScram) [reply rust/windows-client/src-tauri/src/client/deep_link.rs:63]: No wonder MS has 50% stake in them lol

File: rust/windows-client/src-tauri/src/client/debug_commands.rs [hunk 2]
```diff
@@ -45,6 +61,44 @@ mod details {
     use super::*;
     use std::sync::Arc;
 
+    pub fn open_deep_link(path: &url::Url) -> Result<()> {
+        let subscriber = tracing_subscriber::FmtSubscriber::builder()
```
Comment (jamilbk) [inline rust/windows-client/src-tauri/src/client/debug_commands.rs:65]: Is this called essentially at the entrypoint of the GUI process? Is this related to the main file logger for the app?

Comment (jamilbk) [reply rust/windows-client/src-tauri/src/client/debug_commands.rs:65]: In case it's helpful:

https://github.com/firezone/firezone/blob/main/rust/linux-client/src/main.rs#L12

**Review by jamilbk — APPROVED** [review]
Can't comment on much of the Rust stuff specifically, but otherwise LGTM.

May want to clean up or address the logging initialization

File: rust/windows-client/src-tauri/src/client/debug_commands.rs (hunk 2 above)
Comment (ReactorScram) [reply rust/windows-client/src-tauri/src/client/debug_commands.rs:65]: When a web browser navigates to our firezone:// URL, it tells Windows to open it, then Windows will launch our exe with the `open-deep-link` subcommand, as we registered it. So that 2nd instance of our app says "Oh I'm not the real app, I just need to forward this link to the main instance and then I'll exit"

I'm not sure what will happen if 2 instances of the app share the same log files but I assume it could be bad, so I didn't want to create another file_logger here. I can add that as a comment in the code.
