### PR TITLE
(fixed) Don't listen on port 80 if ACME is disabled

### LINKED ISSUE #924: Let's Encrypt / ACME Broken - 0.5.5 Release
The latest release version's changes have broken ACME issuance and renewal of certifications; rather than only exposing firezone on Port 80 when ACME isn't in use, firezone isn't responding to requests on Port 80 at all, breaking ACME as it looks for the .well-known directory over HTTP and fails to find it.

This issue is not present in 0.5.4, and given that 0.5.5 was only a bugfix release that was meant to implement a toggle on port 80 if ACME isn't enabled, this could probably just be fixed with a regression.

### PR DESCRIPTION
**Pull request by jamilbk**
Resolves an issue from the first attempt where nginx wasn't restarted when the redirect conf changes.

Fixes #924

### CODE REVIEW

File: omnibus/cookbooks/firezone/recipes/nginx.rb [hunk 1]
```diff
@@ -73,6 +74,7 @@
     package 'firezone'
     action :enable
     subscribes :restart, 'template[nginx.conf]'
+    subscribes :restart, 'template[redirect.conf]'
```
Comment (jamilbk) [inline omnibus/cookbooks/firezone/recipes/nginx.rb:77]: This was missing, causing #924

Comment (jamilbk) [reply omnibus/cookbooks/firezone/recipes/nginx.rb:77]: cc @gongjason

**Review by conectado — APPROVED** [review]
