### PR TITLE
fix(gui-client): keep the IPC service running even if the GUI quits during sign-in

### LINKED ISSUE #5450: bug(gui-client): Quitting the GUI while it's signing in crashes the IPC service
#### Describe the bug

Quitting the GUI while it's signing in crashes the IPC service.

This is because at some points in `ipc_listen` we treat a pipe disconnect as a fatal error instead of just ending that connection, deactivating DNS control, and looping over.

#### To Reproduce

1. Press Ctrl+Shift+Esc to open Task Manager
2. Click `Services`
3. Find `FirezoneClientIpcService`, its Status should be `Running`
4. Run the GUI. While it's signing in, quit the GUI.
5. The IPC service's Status should change to `Stopped`.

Replicates on the resource-constrained VM.

#### Expected behavior

1. Expected Windows to restart the IPC service if it crashes, like systemd does
2. Expected catchable errors with pipe communication to result in a loop-over, not a bail-out

#### Screenshots / Logs

IPC log

```jsonl
{"time":"2024-06-19T18:15:52.838189Z","target":"firezone_headless_client::dns_control::windows","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\dns_control\\windows.rs","line":"96"},"severity":"INFO","message":"Activating DNS control"}
{"time":"2024-06-19T18:15:54.4920576Z","target":"firezone_headless_client::dns_control::windows","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\dns_control\\windows.rs","line":"123"},"severity":"INFO","message":"Deactivated DNS control"}
{"time":"2024-06-19T18:15:54.4923193Z","target":"firezone_headless_client::windows","logging.googleapis.com/sourceLocation":{"file":"headless-client\\src\\windows.rs","line":"184"},"severity":"ERROR","error":"`ipc_listen` threw an error\n\nCaused by:\n    0: Error while handling IPC client\n    1: The pipe is being closed. (os error 232)","message":"`ipc_listen` failed"}
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.0.9
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows Server 2022 (should replicate on any Linux or Windows)
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI built by Github

#### Additional context

None

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5450

Now the entire `Handler::run` function is allowed to fail, similar to a web request handler failing in a web server.
Previously we only allowed the Handler to fail if it was idle, waiting on incoming IPC requests. Now it can fail even if it's working with connlib and about to send over IPC.

I replicated this on my Windows 11 VM in Parallels and the fix works fine there. Should be the same bug and same fix in Linux.

### CODE REVIEW

File: rust/headless-client/src/lib.rs [hunk 1]
```diff
@@ -451,10 +451,13 @@ async fn ipc_listen() -> Result<std::convert::Infallible> {
             .next_client()
             .await
             .context("Failed to wait for incoming IPC connection from a GUI")?;
-        Handler::new(stream)?
+        if let Err(error) = Handler::new(stream)?
```
Comment (conectado) [inline rust/headless-client/src/lib.rs]: can we make `run` infallible and log within it? That way we also only loop here when we want the handler to explicitly terminate

Comment (ReactorScram) [reply rust/headless-client/src/lib.rs]: Yeah I like that.

**Review by conectado — APPROVED** [review]
LGTM!
