### PR TITLE
fix(apple): reliably read system resolvers

### LINKED ISSUE #10811: System resolvers intermittently lost on iOS

### LINKED ISSUE #11192: connlib: do not emit proxy IPs for system and custom upstream DNS resolvers
Right now, connlib always maps DNS servers to sentinel IPs, regardless of which DNS servers we end up using. In case we are meant to use the system or custom upstream resolvers, there is actually no need to map them to custom IPs. We can just leave them as-is and instead add routes to capture the traffic to these servers.

We only really need the sentinel IPs when DoH is active.

### PR DESCRIPTION
**Pull request by jamilbk**
In all Firezone clients we have a split DNS feature that forwards matched queries through Firezone while leaving unmatched queries to go to either:

1. The system's default DNS resolvers, typically set by DHCP on the system's local network
2. An admin-configured upstream resolver override

On macOS, we can read these via the [`SystemConfiguration`](https://developer.apple.com/documentation/systemconfiguration) framework, which exposes an interface for making a call to the `configd` process over XPC in order to read the resolvers scoped to the system's primary interface.

On iOS, the `SystemConfiguration` framework is unavailable, however, we can achieve the same result by finding the symbol for the `dns_configuration_copy` function and calling it manually.

Both of these approaches are combined into a single `SystemConfigurationResolvers` interface consistent between the two platforms.

Resolves #11192 
Fixes #10811

### CODE REVIEW

**Comment by jamilbk** [comment]
Tested on iOS 26 and works reliably with networking roaming between cellular and WiFi.

**Comment by jamilbk** [comment]
I can add the comments back. Just wanted some initial thoughts on the approach.

**Review by thomaseizinger — APPROVED** [review]
Concept ACK

Should add some of the unrelated comments back and remove unnecessary reformatting.

I don't think we should implement this in Rust. We can of course but I don't really see the point if we are going to only call it from iOS. Unless of course we are more confident to write this kind of code in Rust rather than Swift.

Does this work on macOS too? Then we could at least write tests for it that run in CI.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift:1]: In tests, our bundle ID is different / unpredictable, so I've updated the Logger to be more flexible here while still warning us if the bundleID is amiss in release builds.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/SystemConfigurationResolvers.swift [hunk 1]
```diff
@@ -0,0 +1,309 @@
...
+
+  private static let dnsConfigurationCopy: DnsConfigurationCopyFn? = {
+    dlsym(dlopen(nil, RTLD_LAZY), "dns_configuration_copy")
+      .map { unsafeBitCast($0, to: DnsConfigurationCopyFn.self) }
+  }()
+
+  private static let dnsConfigurationFree: DnsConfigurationFreeFn? = {
+    dlsym(dlopen(nil, RTLD_LAZY), "dns_configuration_free")
+      .map { unsafeBitCast($0, to: DnsConfigurationFreeFn.self) }
+  }()
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/SystemConfigurationResolvers.swift:176]: Left a note as to why this is intentional.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/SystemConfigurationResolvers.swift [hunk 2]
```diff
@@ -0,0 +1,324 @@
...
+#endif
+
+/// Provides access to the system's DNS resolver configuration.
+///
+/// On macOS, this uses the public SystemConfiguration framework to read DNS servers
+/// from SCDynamicStore.
+///
+/// On iOS, the SystemConfiguration framework is not available in Network Extensions.
+/// Instead, we use dlsym to access the `dns_configuration_copy` function, which returns
+/// scoped resolvers that aren't shadowed by our tunnel's DNS settings.
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/SystemConfigurationResolvers.swift:20]: Is this differentiation worth it? If the private API also works on macOS, why not use the same code on both?

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+@Suite("SystemConfigurationResolvers Tests")
+struct SystemConfigurationResolversTests {
+
+  // MARK: - Basic Tests
+
+  @Test("Can instantiate SystemConfigurationResolvers")
+  func canInstantiate() async throws {
+    // Just verify instantiation doesn't crash
+    _ = SystemConfigurationResolvers()
+  }
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift:21]: What is this testing? The ctor isn't doing anything, is it?

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+  @Test("Scoped resolvers different instances return same results")
+  func scopedResolversDifferentInstancesSameResults() async throws {
+    let resolvers1 = SystemConfigurationResolvers()
+    let resolvers2 = SystemConfigurationResolvers()
+
+    let result1 = resolvers1.getDefaultDNSServersViaScopedResolvers(interfaceName: "en0")
+    let result2 = resolvers2.getDefaultDNSServersViaScopedResolvers(interfaceName: "en0")
+
+    #expect(result1 == result2)
+  }
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift:95]: Should the functions be static then if we are not using the features of the class? Should we remove the class entirely? The function names are already pretty long.

File: swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+
+    @Test("Both implementations return results for active interface")
+    func bothImplementationsReturnResults() async throws {
+      let resolvers = SystemConfigurationResolvers()
+
+      // Both should return arrays (possibly empty if en0 has no DNS configured)
+      // but importantly, neither should crash
+      let scopedResult = resolvers.getDefaultDNSServersViaScopedResolvers(interfaceName: "en0")
+      let sysConfigResult = resolvers.getDefaultDNSServersViaSystemConfiguration(
+        interfaceName: "en0")
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift:148]: Should we assert that both return the same thing?

Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Tests/FirezoneKitTests/SystemConfigurationResolversTests.swift:148]: If we decide to only implement the scoped resolver one, we can still write a test that it returns the same thing as the system configuration approach.

**Review by thomaseizinger — APPROVED** [review]
Great stuff! Happy to merge as is but I raised some questions in the comments that we should discuss.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift
Comment (thomaseizinger) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift:1]: If you can be bothered, would be nice to split this out into a separate PR.

**Comment by thomaseizinger** [comment]
I'll push up a commit to show what I mean.

**Comment by thomaseizinger** [comment]
@jamilbk I implemented my suggestion and updated the description. Let me know what you think!

**Comment by jamilbk** [comment]
> @jamilbk I implemented my suggestion and updated the description. Let me know what you think!

It is much riskier to combine these.

I don't think it's a good idea to throw away the implementation using the public API for the hack that uses the private API.

As mentioned in the Slack thread this approach carries some review risk. On iOS there is no alternative but on macOS there is a supported public API for exactly this.

There is also some runtime risk. If the struct memory layout suddenly changes, this technique could break. The public API, being documented explicitly, carries little to no risk here.

Given the above I don't believe the code savings is worth it at this point in time, considering that in most cases the macOS app breaking is far more critical a problem today than the iOS app breaking.

**Comment by thomaseizinger** [comment]
> Given the above I don't believe the code savings is worth it at this point in time, considering that in most cases the macOS app breaking is far more critical a problem today than the iOS app breaking.

My motivation was not so much the code-saving but reducing the risk of bugs from having different code paths. Testing this in CI should give us assurance that this will work and also alert us if it would break.

You are raising a good point though that having it break at all is a problem, even if we learn about it early because we'd have to push out an update.

I am happy to revert this but I think we should still simplify the implementation a bit here. There is no need for a class if we don't have any instance state and I think the tests should assert that both approaches return the same thing.

**Comment by thomaseizinger** [comment]
I've reverted my changes for now because I realised that we do actually use the class (for the cached dynamic store) but it wasn't obvious because the field was hidden further down. Why don't we initialize this in the ctor? It seems like that would be a better place than upon first access. That way, the test making a new instance would actually check something.

**Comment by thomaseizinger** [comment]
Let me know what you think of the two commits @jamilbk .

**Comment by jamilbk** [comment]
> I've reverted my changes for now because I realised that we do actually use the class (for the cached dynamic store) but it wasn't obvious because the field was hidden further down. Why don't we initialize this in the ctor? It seems like that would be a better place than upon first access. That way, the test making a new instance would actually check something.

IIRC the reason we memoized the call was because making successive or rapid initializations back to back could fail since it in effect creates an XPC connection to configd.

**Comment by thomaseizinger** [comment]
> > I've reverted my changes for now because I realised that we do actually use the class (for the cached dynamic store) but it wasn't obvious because the field was hidden further down. Why don't we initialize this in the ctor? It seems like that would be a better place than upon first access. That way, the test making a new instance would actually check something.
> 
> IIRC the reason we memoized the call was because making successive or rapid initializations back to back could fail since it in effect creates an XPC connection to configd.

It is still being memoized in the class, the difference is that we now eagerly initialize it in the ctor instead of doing it on the first access. That way, creating the `Adapter` will already fail. I think otherwise, we will just fail to update connlib with DNS servers and to the user, it will appear as if Firezone is signed-in but not working.

**Comment by jamilbk** [comment]
Possibly related: https://firezone-inc.sentry.io/issues/6795931349/?project=4508175177023488&query=is%3Aunresolved%20system&referrer=issue-stream

**Comment by thomaseizinger** [comment]
> Possibly related: [firezone-inc.sentry.io/issues/6795931349?project=4508175177023488&query=is%3Aunresolved%20system&referrer=issue-stream](https://firezone-inc.sentry.io/issues/6795931349/?project=4508175177023488&query=is%3Aunresolved%20system&referrer=issue-stream)

Seems to be certainly coming from this code but that should change with this PR (unless we do decide to combine the approaches or add a fallback?)

**Comment by jamilbk** [comment]
> > Possibly related: [firezone-inc.sentry.io/issues/6795931349?project=4508175177023488&query=is%3Aunresolved%20system&referrer=issue-stream](https://firezone-inc.sentry.io/issues/6795931349/?project=4508175177023488&query=is%3Aunresolved%20system&referrer=issue-stream)
> 
> Seems to be certainly coming from this code but that should change with this PR (unless we do decide to combine the approaches or add a fallback?)

Ok that's fine I think just wanted to get your thoughts. I'm 99% sure that error happens when the network is unstable during roaming, and likely isn't a major concern.

I'll go ahead and merge this. Should we send new clients for review or wait until #10801 is in?

**Comment by thomaseizinger** [comment]
> I'll go ahead and merge this. Should we send new clients for review or wait until #10801 is in?

Let's wait. I am basically done with it.
