### PR TITLE
fix(apple): Ensure system extension loads after upgrade

### LINKED ISSUE #8476: Need to sign in twice if macOS client is upgraded while open
The system extension is likely not being upgraded when it's in use, so we need to explicitly handle this edge case.

### LINKED ISSUE #9156: macOS: Main window keeps opening due to unexpected systemExtensionStatus
We open the main window in case the vpn configuration or system extension status is not initialized.

However, we seem to be encountering an expected state where the extension status is not `.installed`, even though it is, so perhaps it is flapping.

Possibly related: #8476

### PR DESCRIPTION
**Pull request by jamilbk**
On macOS, after upgrading the client, the new system extension fails to respond to IPC commands until it receives a `startTunnel` call. After that, subsequent IPC calls will succeed across relaunches of the app.

To fix this, we introduce a dummy `startTunnel` call on macOS that attempts to bring life into the System extension whenever we receive `nil` configuration.

We also tidy up a few other things to make this easier to follow.

Fixes #9156 
Fixes #8476

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 1]
```diff
@@ -298,11 +312,21 @@ public final class Store: ObservableObject {
     self.configurationTimer = timer
   }
 
-  private func endConfigurationPolling() {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:301]: We now unconditionally try to fetch configuration from the tunnel, silencing the error where we're not initialized. This is much simpler to reason about and will auto recover our configuration if the system extension or VPN configuration ever gets into a weird state and then resolves itself.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/SystemExtensionManager.swift [hunk 2]
```diff
@@ -7,7 +7,7 @@
 #if os(macOS)
 import SystemExtensions
 
-public enum SystemExtensionError: Error {
+enum SystemExtensionError: Error {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Managers/SystemExtensionManager.swift:10]: These are fixed as well. Not sure why they were public.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift [hunk 3]
```diff
@@ -323,6 +324,12 @@ public final class Store: ObservableObject {
             if !Task.isCancelled {
               do {
                 self.resourceList = try await self.ipcClient().fetchResources()
+              } catch let error as NSError {
+                if error.domain == "NEVPNErrorDomain" && error.code == 1 {
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:331]: Is `1` a documented constant?

**Review by thomaseizinger — APPROVED** [review]
Nice solution!

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift (hunk 3 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/Store.swift:331]: Updated with a link to https://developer.apple.com/documentation/networkextension/nevpnerror-swift.struct/code
