### PR TITLE
fix(apple): Trigger connlib reset() when IPv4, IPv6, or available network gateways has changed

### LINKED ISSUE #6515: `Session.reset()` isn't called when IPv4/6 connectivity changes but interfaces remain the same
Seems to be IPv6 connectivity issues for all Relays. Here's a snippet from a session with only IPv6 connectivity:

```
2024-08-30T20:43:44.756874Z DEBUG handle_timeout{active_socket=Some([2600:1900:4120:f732:0:140::]:3478)}: snownet::allocation: Request timed out after 1s, re-sending id=TransactionId(0x1A3589466B25177757C6F760) method=binding dst=34.94.194.198:3478
2024-08-30T20:43:44.756953Z DEBUG handle_timeout{active_socket=Some([2600:1900:4000:102d:0:be::]:3478)}: snownet::allocation: Request timed out after 1s, re-sending id=TransactionId(0x74FDB008034F1410356314F8) method=binding dst=34.41.125.154:3478
2024-08-30T20:43:46.256827Z DEBUG handle_timeout{active_socket=Some([2600:1900:4120:f732:0:140::]:3478)}: snownet::allocation: Request timed out after 1.5s, re-sending id=TransactionId(0x1A3589466B25177757C6F760) method=binding dst=34.94.194.198:3478
2024-08-30T20:43:46.256924Z DEBUG handle_timeout{active_socket=Some([2600:1900:4000:102d:0:be::]:3478)}: snownet::allocation: Request timed out after 1.5s, re-sending id=TransactionId(0x74FDB008034F1410356314F8) method=binding dst=34.41.125.154:3478
2024-08-30T20:43:48.507036Z DEBUG handle_timeout{active_socket=Some([2600:1900:4120:f732:0:140::]:3478)}: snownet::allocation: Request timed out after 2.25s, re-sending id=TransactionId(0x1A3589466B25177757C6F760) method=binding dst=34.94.194.198:3478
2024-08-30T20:43:48.507117Z DEBUG handle_timeout{active_socket=Some([2600:1900:4000:102d:0:be::]:3478)}: snownet::allocation: Request timed out after 2.25s, re-sending id=TransactionId(0x74FDB008034F1410356314F8) method=binding dst=34.41.125.154:3478
2024-08-30T20:43:51.746035Z DEBUG on_not_connected_resource{resource=656bf11c-d090-436e-b8c8-9a53aac1c024}: firezone_tunnel::client: Sending connection intent
2024-08-30T20:43:51.881094Z DEBUG handle_timeout{active_socket=Some([2600:1900:4120:f732:0:140::]:3478)}: snownet::allocation: Request timed out after 3.375s, re-sending id=TransactionId(0x1A3589466B25177757C6F760) method=binding dst=34.94.194.198:3478
2024-08-30T20:43:51.881175Z DEBUG handle_timeout{active_socket=Some([2600:1900:4000:102d:0:be::]:3478)}: snownet::allocation: Request timed out after 3.375s, re-sending id=TransactionId(0x74FDB008034F1410356314F8) method=binding dst=34.41.125.154:3478
2024-08-30T20:43:54.051536Z DEBUG handle_timeout{cid=ea28cf20-35f6-46ad-bd6f-6bc3c3fff32e}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
2024-08-30T20:43:56.942790Z DEBUG handle_timeout{active_socket=Some([2600:1900:4120:f732:0:140::]:3478)}: snownet::allocation: Request timed out after 5.0625s, re-sending id=TransactionId(0x1A3589466B25177757C6F760) method=binding dst=34.94.194.198:3478
2024-08-30T20:43:56.942874Z DEBUG handle_timeout{active_socket=Some([2600:1900:4000:102d:0:be::]:3478)}: snownet::allocation: Request timed out after 5.0625s, re-sending id=TransactionId(0x74FDB008034F1410356314F8) method=binding dst=34.41.125.154:3478
2024-08-30T20:44:04.241835Z DEBUG handle_timeout{cid=ea28cf20-35f6-46ad-bd6f-6bc3c3fff32e}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
```

[Archive.zip](https://github.com/user-attachments/files/16821933/Archive.zip)

### PR DESCRIPTION
**Pull request by jamilbk**
On Apple, we try to be smart about triggering connlib's `reset()` in order to keep from triggering endless update loops. This can happen because connlib itself triggers path monitoring updates through onUpdateRoutes and such.

Before, we only kept track of whether our primary interface changed in order to consider the path updated. Now, we also track IPv4/IPv6 connectivity and the network's available gateways (read: routers) to trigger changes. This fixes the case where our interface loses or gains IPv4 / IPv6 connectivity, or the router address changes.

Fixes #6515

### CODE REVIEW

File: elixir/apps/domain/lib/domain/auth.ex
Comment (thomaseizinger) [inline elixir/apps/domain/lib/domain/auth.ex:1]: I guess this shouldn't be part of the PR?

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 1]
```diff
@@ -291,14 +291,14 @@ extension Adapter {
     } else {
       Log.tunnel.log("\(#function): Detected network change: Online.")
 
-      // Hint to connlib we're back online, but only do so if our primary interface changes,
-      // and therefore we need to bump sockets. On darwin, this is needed to send packets
+      // Hint to connlib we're back online, but only do so if our connectivity has
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]: The "hint" wording here is kind of outdated as "reset" is not conditional on anything, we just clear all network state.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 2]
```diff
@@ -492,3 +492,15 @@ extension Adapter: CallbackHandlerDelegate {
...
 #endif
+
+extension Network.NWPath {
+
+  // We define a path as different from another if the following properties change
+  func connectivityDifferentFrom(path: Network.NWPath?) -> Bool {
+    guard let path = path else { return true }
+    return path.supportsIPv4 != self.supportsIPv4 ||
+      path.supportsIPv6 != self.supportsIPv6 ||
+      path.gateways != self.gateways ||
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]: Are these always sorted?

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 3]
```diff
@@ -52,8 +52,8 @@ class Adapter {
   /// Track our last fetched DNS resolvers to know whether to tell connlib they've updated
   private var lastFetchedResolvers: [String] = []
 
-  /// Used to avoid needlessly sending resets to connlib
-  private var primaryInterfaceName: String?
+  /// Used to avoid needlessly sending resets to connlib while still triggering reset
+  private var lastUpdatedPath: Network.NWPath?
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]:
```suggestion
  private var lastRelevantPath: Network.NWPath?
```

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 4]
```diff
@@ -52,8 +52,8 @@ class Adapter {
   /// Track our last fetched DNS resolvers to know whether to tell connlib they've updated
   private var lastFetchedResolvers: [String] = []
 
-  /// Used to avoid needlessly sending resets to connlib
-  private var primaryInterfaceName: String?
+  /// Used to avoid needlessly sending resets to connlib while still triggering reset
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]:
```suggestion
  /// Remembers the last _relevant_ path update.
  /// A path update is considered relevant if certain properties change that require us to reset connlib's network state. 
```

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 5]
```diff
@@ -492,3 +492,15 @@ extension Adapter: CallbackHandlerDelegate {
     }
   }
 #endif
+
+extension Network.NWPath {
+
+  // We define a path as different from another if the following properties change
+  func connectivityDifferentFrom(path: Network.NWPath?) -> Bool {
+    guard let path = path else { return true }
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift]: So if the new path is null, we consider that different and do a reset? What is the point of that?

**Review by thomaseizinger — APPROVED** [review]
ACK modulo the unrelated(?) Elixir changes.

**Comment by thomaseizinger** [comment]
Your test failure is most likely fixed by https://github.com/firezone/firezone/pull/6497.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 2 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Fixed using `Set` since NWEndpoint implements Equatable.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift (hunk 5 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Yeah, we need to initialize it somehow. There is a (highly unlikely) chance we can receive this callback, `lastRelevantPath` is nil, and we need to bump sockets so better to err on the side of one reset.

Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: You could initialise it (and call reset) without calling this function. That may be easier to understand how we handle that edge-case?

Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/Adapter.swift]: Updated!
