### PR TITLE
fix(portal): Use modal for confirmation dialogs

### LINKED ISSUE #5766: Refactor confirmation dialogs to be browser-based styled with our theme
Instead of using the browser's default alerts, it would be slicker if we had our own modal popup for confirming or canceling destructive actions.

See https://dev.to/neophen/beter-data-confirm-modals-in-phoenix-liveview-5al5

### LINKED ISSUE #5794: Update wording for Activities
Rename these to "Tunnel sessions" to better reflect what they represent in the backend

### LINKED ISSUE #5887: ux(portal): Typo in alert message, "Are you sure want to enable this policy?" should be "Are you sure _you_ want to enable this policy?"
#### Describe the bug

The string's missing a word

#### To Reproduce

1. Open any policy page
2. Disable if needed
3. Enable

#### Expected behavior

_A clear and concise description of what you expected to happen._

#### Screenshots / Logs

image

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Admin portal
- _Firezone Version (e.g. 1.0.0 or N/A):_ Whatever is on https://app.firez.one
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ N/A
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Whatever is on https://app.firez.one

#### Additional context

N/A

### PR DESCRIPTION
**Pull request by AndrewDryga**
Still need to replace a few more `data-confirm` actions (have an issue with HTML <dialog> positioning when it's defined inside Tailwind tables.)

Closes https://github.com/firezone/firezone/issues/5794
Closes #5766
Closes #5887

### CODE REVIEW

**Comment by AndrewDryga** [comment]
Screenshot 2024-07-10 at 5 32 17 PM

File: elixir/apps/web/assets/js/hooks.js [hunk 1]
```diff
@@ -94,4 +94,22 @@ Hooks.Copy = {
   },
 };
 
+Hooks.ConfirmDialog = {
```
Comment (jamilbk) [inline elixir/apps/web/assets/js/hooks.js:133]:
```suggestion
Hooks.CloseConfirmDialog = {
```

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 2]
```diff
@@ -358,6 +358,85 @@ defmodule Web.FormComponents do
...
+  slot :dialog_confirm_button, doc: "The content of the confirm button of the dialog"
+  slot :dialog_cancel_button, doc: "The content of the cancel button of the dialog"
+  slot :inner_block, required: true, doc: "The label for the button"
+
+  def button_with_confirmation(assigns) do
+    ~H"""
+    <dialog
+      id={"#{@id}_dialog"}
+      class={[
+        "backdrop:bg-slate-800/75 bg-transparent",
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/form_components.ex]:
```suggestion
        "backdrop:bg-gray-800/75 bg-transparent",
```

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 3]
```diff
@@ -358,6 +358,85 @@ defmodule Web.FormComponents do
...
+              value="confirm"
+              class="py-2.5 px-5 ms-3"
+            >
+              <%= render_slot(@dialog_confirm_button) %>
+            </.button>
+          </div>
+        </div>
+      </form>
+    </dialog>
+    <.button id={@id} style={@style} size={@size} icon={@icon} class={@class} phx-hook="ConfirmDialog">
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/form_components.ex:457]:
```suggestion
    <.button id={@id} style={@style} size={@size} icon={@icon} class={@class} phx-hook="CloseConfirmDialog">
```

File: elixir/apps/web/lib/web/components/form_components.ex [hunk 4]
```diff
@@ -358,6 +358,85 @@ defmodule Web.FormComponents do
...
+      id={"#{@id}_dialog"}
+      class={[
+        "backdrop:bg-slate-800/75 bg-transparent",
+        "p-4 w-full max-w-2xl md:inset-0 max-h-full",
+        "overflow-y-auto overflow-x-hidden",
+        "justify-center items-center"
+      ]}
+    >
+      <form method="dialog">
+        <div class="relative bg-white rounded-lg shadow">
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/form_components.ex]: Closes on click outside 

```suggestion
        <div
          phx-click-away={JS.dispatch("click", to: "[data-dialog-action='cancel']")}
          class="relative bg-white rounded-lg shadow"
        >

```

File: elixir/apps/web/lib/web/live/actors/show.ex [hunk 5]
```diff
@@ -405,9 +405,9 @@ defmodule Web.Actors.Show do
     </.section>
 
     <.section>
-      <:title>Authorized Activity</:title>
+      <:title>Tunnel Sessions</:title>
       <:help>
-        Authorized attempts by actors to access the resource governed by this policy.
+        Authorized attempts by the actor to access a resource.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/actors/show.ex]:
```suggestion
        Authorized sessions opened by this Actor to access a Resource.
```

File: elixir/apps/web/lib/web/live/actors/show.ex [hunk 6]
```diff
@@ -405,9 +405,9 @@ defmodule Web.Actors.Show do
     </.section>
 
     <.section>
-      <:title>Authorized Activity</:title>
+      <:title>Tunnel Sessions</:title>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/actors/show.ex]:
```suggestion
      <:title>Authorized Sessions</:title>
```

File: elixir/apps/web/lib/web/live/clients/show.ex [hunk 7]
```diff
@@ -156,9 +156,9 @@ defmodule Web.Clients.Show do
     </.section>
 
     <.section>
-      <:title>Authorized Activity</:title>
+      <:title>Tunnel Sessions</:title>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/clients/show.ex]:
```suggestion
      <:title>Authorized Sessions</:title>
```

File: elixir/apps/web/lib/web/live/clients/show.ex [hunk 8]
```diff
@@ -156,9 +156,9 @@ defmodule Web.Clients.Show do
...
       <:help>
-        Authorized attempts by actors to access the resource governed by this policy.
+        Authorized attempts by the client to access a resource.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/clients/show.ex]:
```suggestion
        Authorized sessions opened by this Client to access a Resource.
```

File: elixir/apps/web/lib/web/live/gateways/show.ex [hunk 9]
```diff
@@ -108,12 +108,37 @@ defmodule Web.Gateways.Show do
...
+        <.button_with_confirmation
+          id="delete_gateway"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Gateway</:dialog_title>
+          <:dialog_content>
+            <p>
+              Are you sure you want to delete this gateway?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/gateways/show.ex]:
```suggestion
              Are you sure you want to delete this Gateway?
```

File: elixir/apps/web/lib/web/live/gateways/show.ex [hunk 10]
```diff
@@ -108,12 +108,37 @@ defmodule Web.Gateways.Show do
...
+            <p class="mt-4 text-sm">
+              Deleting the gateway does not remove it's access token so it can be re-created again,
+              revoke the token on the
+              <.link
+                navigate={~p"/#{@account}/sites/#{@gateway.group}"}
+                class={["font-medium", link_style()]}
+              >
+                site
+              </.link>
+              page if you want to prevent the gateway from connecting to the portal.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/gateways/show.ex:131]:
```suggestion
              <strong>Note:</strong>
              Deleting a Gateway does not remove its access token.
              <.link
                navigate={~p"/#{@account}/sites/#{@gateway.group}"}
                class={["font-medium", link_style()]}
              >
                Revoke
              </.link>
              the Gateway token instead to prevent it from being re-created
              automatically the next time it starts.
```

File: elixir/apps/web/lib/web/live/groups/show.ex [hunk 11]
```diff
@@ -240,12 +240,24 @@ defmodule Web.Groups.Show do
...
-          data-confirm="Are you sure want to delete this group and all related policies?"
+        <.button_with_confirmation
+          id="delete_group"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Group</:dialog_title>
+          <:dialog_content>
+            Are you sure you want to delete this group and all related policies?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/groups/show.ex]:
```suggestion
            Are you sure you want to delete this Group and all related Policies?
```

File: elixir/apps/web/lib/web/live/policies/show.ex [hunk 12]
```diff
@@ -158,9 +158,9 @@ defmodule Web.Policies.Show do
     </.section>
 
     <.section>
-      <:title>Authorized Activity</:title>
+      <:title>Tunnel Sessions</:title>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/policies/show.ex]:
```suggestion
      <:title>Authorized Sessions</:title>
```

File: elixir/apps/web/lib/web/live/policies/show.ex [hunk 13]
```diff
@@ -158,9 +158,9 @@ defmodule Web.Policies.Show do
...
       <:help>
-        Authorized attempts by actors to access the resource governed by this policy.
+        Authorized attempts by an actors to access the resource governed by this policy.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/policies/show.ex]:
```suggestion
        Authorized sessions opened by Actors to access the Resources governed by this Policy.
```

File: elixir/apps/web/lib/web/live/policies/show.ex [hunk 14]
```diff
@@ -209,13 +209,25 @@ defmodule Web.Policies.Show do
...
+        <.button_with_confirmation
+          id="delete_policy"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
+          on_confirm_id={@policy.id}
         >
+          <:dialog_title>Delete Policy</:dialog_title>
+          <:dialog_content>
+            Are you sure you want to delete this Policy? All tunnel sessions authorized by it will be expired.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/policies/show.ex]:
```suggestion
            Are you sure you want to delete this Policy? All sessions authorized by it will be expired.
```

File: elixir/apps/web/lib/web/live/resources/show.ex [hunk 15]
```diff
@@ -248,9 +248,9 @@ defmodule Web.Resources.Show do
     </.section>
 
     <.section>
-      <:title>Authorized Activity</:title>
+      <:title>Tunnel Sessions</:title>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/resources/show.ex]:
```suggestion
      <:title>Authorized Sessions</:title>
```

File: elixir/apps/web/lib/web/live/resources/show.ex [hunk 16]
```diff
@@ -248,9 +248,9 @@ defmodule Web.Resources.Show do
...
       <:help>
-        Authorized attempts by actors to access the resource governed by this policy.
+        Authorized attempts by actors to access the resource.
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/resources/show.ex]:
```suggestion
        Authorized sessions opened by Actors to access this Resource.
```

File: elixir/apps/web/lib/web/live/resources/show.ex [hunk 17]
```diff
@@ -304,13 +304,25 @@ defmodule Web.Resources.Show do
...
+        <.button_with_confirmation
+          id="delete_resource"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
+          on_confirm_id={@resource.id}
         >
+          <:dialog_title>Delete Resource</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this resource along with all associated policies and tunnel sessions?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/resources/show.ex]:
```suggestion
            Are you sure want to delete this Resource along with all associated Policies?
            This will immediately end all active sessions opened for this Resource.
```

File: elixir/apps/web/lib/web/live/settings/identity_providers/google_workspace/show.ex [hunk 18]
```diff
@@ -155,12 +155,24 @@ defmodule Web.Settings.IdentityProviders.GoogleWorkspace.Show do
...
-          phx-click="delete"
+        <.button_with_confirmation
+          id="delete_identity_provider"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Identity Provider</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this provider along with all related data?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/identity_providers/google_workspace/show.ex]:
```suggestion
            Are you sure want to delete this provider? This will remove
            <strong>all</strong> Actors and Groups associated with this provider.
```

File: elixir/apps/web/lib/web/live/settings/identity_providers/jumpcloud/show.ex [hunk 19]
```diff
@@ -167,12 +167,24 @@ defmodule Web.Settings.IdentityProviders.JumpCloud.Show do
...
-          phx-click="delete"
+        <.button_with_confirmation
+          id="delete_identity_provider"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Identity Provider</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this provider along with all related data?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/identity_providers/jumpcloud/show.ex]:
```suggestion
            Are you sure want to delete this provider? This will remove
            <strong>all</strong> Actors and Groups associated with this provider.
```

File: elixir/apps/web/lib/web/live/settings/identity_providers/microsoft_entra/show.ex [hunk 20]
```diff
@@ -155,12 +155,24 @@ defmodule Web.Settings.IdentityProviders.MicrosoftEntra.Show do
...
-          phx-click="delete"
+        <.button_with_confirmation
+          id="delete_identity_provider"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Identity Provider</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this provider along with all related data?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/identity_providers/microsoft_entra/show.ex]:
```suggestion
            Are you sure want to delete this provider? This will remove
            <strong>all</strong> Actors and Groups associated with this provider.
```

File: elixir/apps/web/lib/web/live/settings/identity_providers/okta/show.ex [hunk 21]
```diff
@@ -173,12 +173,24 @@ defmodule Web.Settings.IdentityProviders.Okta.Show do
...
-          phx-click="delete"
+        <.button_with_confirmation
+          id="delete_identity_provider"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Identity Provider</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this provider along with all related data?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/identity_providers/okta/show.ex]:
```suggestion
            Are you sure want to delete this provider? This will remove
            <strong>all</strong> Actors and Groups associated with this provider.
```

File: elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/show.ex [hunk 22]
```diff
@@ -134,12 +134,24 @@ defmodule Web.Settings.IdentityProviders.OpenIDConnect.Show do
...
-          phx-click="delete"
+        <.button_with_confirmation
+          id="delete_identity_provider"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Identity Provider</:dialog_title>
+          <:dialog_content>
+            Are you sure want to delete this provider along with all related data?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/show.ex]:
```suggestion
            Are you sure want to delete this provider? This will remove
            <strong>all</strong> Actors and Groups associated with this provider.
```

File: elixir/apps/web/lib/web/live/sites/show.ex [hunk 23]
```diff
@@ -260,12 +260,24 @@ defmodule Web.Sites.Show do
...
-          data-confirm="Are you sure you want to delete this Site and disconnect all its Gateways?"
+        <.button_with_confirmation
+          id="delete_site"
+          style="danger"
+          icon="hero-trash-solid"
+          on_confirm="delete"
         >
+          <:dialog_title>Delete Site</:dialog_title>
+          <:dialog_content>
+            Are you sure you want to delete this Site and disconnect all its Gateways?
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/sites/show.ex]:
```suggestion
            Are you sure you want to delete this Site? This will
            <strong>immediately</strong> disconnect all associated Gateways.
```

**Review by jamilbk — CHANGES_REQUESTED** [review]
Looks great, thanks for taking this on!

I made a few UX and spelling/grammar suggestions. One of them is to settle on the `Authorized sessions` terminology instead of `Tunnel sessions`.

I did some thinking about it this morning and we can build off that terminology to describe how the Policy Engine works. We can also leverage the "session" terminology within the context of Policies when we add re-authentication periods.

**Comment by jamilbk** [comment]
Would it be possible to fix the description so it closes relevant PRs?

**Comment by jamilbk** [comment]
@AndrewDryga I spent a lot of time working through an issue with Flowbite `data-` triggers and Phoenix on Probe recently. Essentially, I found that if an element is `updated()` in the DOM by Phoenix, Flowbite doesn't reinitialize its listeners. See [this hook](https://github.com/firezone/probe/blob/main/assets/js/hooks.js#L53) I added as a workaround.

I'm not sure if it's an issue here, but something to take note of. We may need to use the Phoenix-native `JS` helpers to manipulate the DOM in the future.

**Comment by AndrewDryga** [comment]
@jamilbk we don't use Flowbite `data-` helpers, I know they do not work with LiveView (thats why we have our own tabs Hook to fix them).

File: elixir/apps/web/assets/js/hooks.js (hunk 1 above)
Comment (AndrewDryga) [reply elixir/apps/web/assets/js/hooks.js:133]: This hook doesn't close the dialog but opens it.

**Review by jamilbk — APPROVED** [review]

**Comment by jamilbk** [comment]
Much improved UX here! Just looks like a few CI checks that need to be cleaned up and LGTM

**Review by jamilbk — APPROVED** [review]
LGTM
