### PR TITLE
fix(portal): Make sure modals start with Confirm..

### LINKED ISSUE #6713: For all save modals the title should read "Confirm <thing-you're-trying-to-do>"
Title of confirmation dialog should be prefixed with `Confirm ...`

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #6713

### CODE REVIEW

File: elixir/apps/web/lib/web/live/actors/show.ex [hunk 1]
```diff
@@ -344,10 +346,11 @@ defmodule Web.Actors.Show do
         <.button_with_confirmation
           id="revoke_all_tokens"
           style="danger"
+          confirm_style="primary"
           icon="hero-trash-solid"
           on_confirm="revoke_all_tokens"
         >
-          <:dialog_title>Revoke All Tokens</:dialog_title>
+          <:dialog_title>Confirm token revocation of all actor tokens</:dialog_title>
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/actors/show.ex]:
```suggestion
          <:dialog_title>Confirm revocation of all actor tokens</:dialog_title>
```

**Review by jamilbk — APPROVED** [review]
LGTM just found a typo
