### PR TITLE
fix(portal): add includeDerivedMembership for Google APIClient

### LINKED ISSUE #11628: Regression with google directory sync
#### Describe the bug

Following the recent auth improvements, I identified a regression with google on how group memberships are computed with nested groups.

With a legacy version of firezone (12f3f53d458d7cea4c0a901521d9af7c8917b222 / before auth update) nested group memberships work

#### To Reproduce

- Create a group A
- Create a group B and add a user to it
- Add group B to group A
- Sync
- the user should be a member of both groups but it is not

#### Screenshots / Logs

Here is the fix I'm using
```
diff --git a/elixir/lib/portal/google/api_client.ex b/elixir/lib/portal/google/api_client.ex
index bd14f4480..adc8d5a4c 100644
--- a/elixir/lib/portal/google/api_client.ex
+++ b/elixir/lib/portal/google/api_client.ex
@@ -139,7 +139,8 @@ defmodule Portal.Google.APIClient do
   def stream_group_members(access_token, group_key) do
     query =
       URI.encode_query(%{
-        "maxResults" => "200"
+        "maxResults" => "200",
+        "includeDerivedMembership" => "true"
       })

     path = "/admin/directory/v1/groups/#{group_key}/members"
```

#### Platform (please complete the following information)

- _Firezone Version (e.g. 1.0.0 or N/A):_ 1fdfe7f3726206d43e142e16b6208310e98d7181

#### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by jamilbk**
- Adds `includeDerivedMembership` param to pull in nested members of groups
- Adds comprehensive tests to cover the `Portal.Google.APIClient` module
- Removes old / obsolete mocks/tests.

Fixes #11628

### CODE REVIEW

File: elixir/lib/portal/google/api_client.ex
Comment (jamilbk) [inline elixir/lib/portal/google/api_client.ex:137]:
```suggestion
  Returns a stream that yields pages of members.
  Uses includeDerivedMembership to fetch transitive memberships.
```

**Review by bmanifold — APPROVED** [review]
