### PR TITLE
fix(tauri clients): apply auth base URL and API URL settings without app restart

### LINKED ISSUE #3862: Settings changes don't seem to be taking effect until app is restarted
Steps to reproduce:

- Open the `release` client
- Sign into prod
- Change the URLs to use staging in Settings
- Sign in again, notice that prod is still being used

(Tasklist moved to #3868)

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #3862

I refactored the settings code, removing `_settings_` from some function names where it was redundant.

The log level is more difficult to change live, so I added a `tracing::info!` noting that it will apply on next app start.

```[tasklist]
### Before merging
- [x] Document whether pressing Enter on a field to apply settings is intended behavior
- [x] Document that log levels don't apply until next app start
- [x] Document that auth and API URL apply on next sign-in
```

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -309,7 +309,7 @@ async fn smoke_test(ctlr_tx: CtlrTx) -> Result<()> {
     let quit_time = tokio::time::Instant::now() + Duration::from_secs(delay);
 
     // Write the settings so we can check the path for those
-    settings::apply_advanced_settings_inner(&settings::AdvancedSettings::default()).await?;
+    settings::save(&settings::AdvancedSettings::default()).await?;
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/gui.rs:312]: `smoke_test` doesn't literally apply the settings here, so `save` is appropriate.

**Review by jamilbk — APPROVED** [review]
