### PR TITLE
fix(connlib): don't trigger intents for packets to self

### LINKED ISSUE #12425: Possible packet loop
Seeing many of these on my macOS client, `main` build. Thought I'd note it here because it seems odd.

```
connlib	dev.firezone.firezone.network-extension	20:14:58.885745-0800	snownet::node: ICE is still in progress; dropping packet because controlled agent should not initiate WireGuard sessions packet=Packet { src: 100.82.80.16, dst: 100.82.80.16, protocol: "UDP", src_port: 137, dst_port: 137, len: 68 }
```

### PR DESCRIPTION
**Pull request by jamilbk**
Packets to other devices in our reserved CGNAT ranges should exclude our own TUN IP to prevent loop scenarios.

---

Fixes #12425

### CODE REVIEW

File: rust/libs/connlib/tunnel/src/client.rs [hunk 1]
```diff
@@ -622,6 +622,15 @@ impl ClientState {
     ) -> Option<(ClientOrGatewayId, IpPacket)> {
         let dst = packet.destination();
 
+        if self
```
Comment (thomaseizinger) [inline rust/libs/connlib/tunnel/src/client.rs]: I think we should do this earlier. Like next to the check where we check the other unroutable things.

**Review by thomaseizinger — APPROVED** [review]
Concept ACK

File: rust/libs/connlib/tunnel/src/client.rs (hunk 1 above)
Comment (jamilbk) [reply rust/libs/connlib/tunnel/src/client.rs]: Updated.
