### PR TITLE
fix(portal): use reproducible relay creds

### LINKED ISSUE #9856: Generate consistent TURN credentials
When generating TURN credentials for clients and gateways to use, we currently tie these to the specific control plane connection for those entities. If it flaps, they're lost, causing `Invalidating allocation` messages, and lost packets for Relayed connections.

Instead, it would be more stable to base these off of persisted information such that they survive a WebSocket reconnection.

### PR DESCRIPTION
**Pull request by jamilbk**
When giving TURN credentials to clients and gateways, it's important that they remain consistent across hiccups in the portal connection so that relayed connections are not interrupted during a deploy, or if the user's internet is flaky, or the GCP load balancer decides to disconnect the client/gateway.

Prior to this PR, that was not the case because we essentially tied TURN credentials, required for data plane packet flows, to the WebSocket connection, a control plane element. This happened because we generated random `expires_at` and `salt` elements on _each_ connection to the portal.

Instead, what we do now is make these reproducible and tied to the auth token by hashing then base64-encoding it. The expiry is tied to the auth-token's expiry.

Fixes #9856

### CODE REVIEW

File: elixir/apps/api/lib/api/client/views/relay.ex [hunk 1]
```diff
@@ -1,26 +1,24 @@
...
+      maybe_render(relay, salt, expires_at, relay.ipv6, stun_or_turn)
     ]
     |> List.flatten()
   end
 
-  defp maybe_render(%Relays.Relay{}, _expires_at, nil, _stun_or_turn), do: []
+  defp maybe_render(%Relays.Relay{}, _salt, _expires_at, nil, _stun_or_turn), do: []
 
   # STUN returns the reflective candidates to the peer and is used for hole-punching;
   # TURN is used to real actual traffic if hole-punching fails. It requires authentication.
```
Comment (thomaseizinger) [inline elixir/apps/api/lib/api/client/views/relay.ex]: Typo here.

File: elixir/apps/api/lib/api/client/views/relay.ex [hunk 2]
```diff
@@ -1,26 +1,24 @@
...
+      maybe_render(relay, salt, expires_at, relay.ipv4, stun_or_turn),
+      maybe_render(relay, salt, expires_at, relay.ipv6, stun_or_turn)
     ]
     |> List.flatten()
   end
 
-  defp maybe_render(%Relays.Relay{}, _expires_at, nil, _stun_or_turn), do: []
+  defp maybe_render(%Relays.Relay{}, _salt, _expires_at, nil, _stun_or_turn), do: []
 
   # STUN returns the reflective candidates to the peer and is used for hole-punching;
```
Comment (thomaseizinger) [inline elixir/apps/api/lib/api/client/views/relay.ex]:
```suggestion
  # STUN returns the reflexive candidates to the peer and is used for hole-punching;
```

File: elixir/apps/api/lib/api/gateway/channel.ex [hunk 3]
```diff
@@ -207,7 +213,7 @@ defmodule API.Gateway.Channel do
         {:ok, relays} = select_relays(socket)
 
         if length(relays) > 0 do
-          relay_credentials_expire_at = DateTime.utc_now() |> DateTime.add(14, :day)
+          relay_credentials_expire_at = DateTime.utc_now() |> DateTime.add(90, :day)
```
Comment (thomaseizinger) [inline elixir/apps/api/lib/api/gateway/channel.ex:216]: What do we need this for? Because GW tokens don't expire?

Comment (jamilbk) [reply elixir/apps/api/lib/api/gateway/channel.ex:216]: Yeah

File: elixir/apps/api/lib/api/client/views/relay.ex (hunk 2 above)
Comment (jamilbk) [reply elixir/apps/api/lib/api/client/views/relay.ex]: I'll just fix this to remove the outdated code. All credentials are TURN

**Review by thomaseizinger — APPROVED** [review]
LGTM

The design described in the PR description is outdated and something seems to be up with CI.

**Comment by jamilbk** [comment]
@thomaseizinger Fixed & updated.

File: elixir/apps/api/lib/api/gateway/socket.ex [hunk 4]
```diff
@@ -27,8 +27,14 @@ defmodule API.Gateway.Socket do
           version: gateway.last_seen_version
         })
 
+        # For Relay credentials
+        turn_salt =
```
Comment (jamilbk) [inline elixir/apps/api/lib/api/gateway/socket.ex:31]: cc @bmanifold

File: elixir/apps/domain/lib/domain/relays.ex [hunk 5]
```diff
@@ -270,10 +270,9 @@ defmodule Domain.Relays do
     {:ok, relays}
   end
 
-  def generate_username_and_password(%Relay{stamp_secret: stamp_secret}, %DateTime{} = expires_at)
+  def generate_username_and_password(%Relay{stamp_secret: stamp_secret}, salt, expires_at)
       when is_binary(stamp_secret) do
     expires_at = DateTime.to_unix(expires_at, :second)
-    salt = Domain.Crypto.random_token()
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/relays.ex:276]: cc @bmanifold - `salt` here is now the `url_base64(sha256(token_string))` so that portal connection flaps do not disrupt relayed connections.

File: elixir/apps/domain/test/domain/relays_test.exs [hunk 6]
```diff
@@ -786,18 +786,19 @@ defmodule Domain.RelaysTest do
     end
   end
 
-  describe "generate_username_and_password/1" do
+  describe "generate_username_and_password/3" do
     test "returns username and password", %{account: account} do
```
Comment (thomaseizinger) [inline elixir/apps/domain/test/domain/relays_test.exs:790]: I think this test (or another) would be better if it would assert the actual output against static strings. That way, we would assert that it is pure and does not contain any randomness. You have to pass a fixed `expires_at` of course.

**Review by thomaseizinger — APPROVED** [review]

File: elixir/apps/domain/test/domain/relays_test.exs [hunk 7]
```diff
@@ -786,18 +786,19 @@ defmodule Domain.RelaysTest do
...
       relay = Fixtures.Relays.create_relay(account: account)
       stamp_secret = Ecto.UUID.generate()
       relay = %{relay | stamp_secret: stamp_secret}
       expires_at = DateTime.utc_now() |> DateTime.add(3, :second)
 
       assert %{username: username, password: password, expires_at: expires_at_unix} =
-               generate_username_and_password(relay, expires_at)
+               generate_username_and_password(relay, "test", expires_at)
 
       assert [username_expires_at_unix, username_salt] = String.split(username, ":", parts: 2)
```
Comment (thomaseizinger) [inline elixir/apps/domain/test/domain/relays_test.exs:800]: This `username_salt` is further down used to compute the expected hash which is why this test did not uncover previously that the output isn't deterministic, we should remove that.

**Comment by thomaseizinger** [comment]
Nice work! This will make relayed connections a lot more stable.

File: elixir/apps/domain/test/domain/relays_test.exs (hunk 6 above)
Comment (jamilbk) [reply elixir/apps/domain/test/domain/relays_test.exs:790]: Good call

File: elixir/apps/domain/test/domain/relays_test.exs (hunk 7 above)
Comment (jamilbk) [reply elixir/apps/domain/test/domain/relays_test.exs:800]: Fixed

**Comment by jamilbk** [comment]
Chatted with @bmanifold about this one. I think we have some work to do to allow for shorter credential lifetimes that don't automatically imply cuts to the data plane connections.

But that can be saved for a future time, because this is causing issues now and the token lifetime for clients is still "short-term".

I added a comment to revisit this with #8222 is tackled since we will need to overhaul how connlib tracks relays there.
