### PR TITLE
fix(ui): make internet resource off by default

### LINKED ISSUE #6509: Internet Resource client UX iteration
- When the resource is enabled, change its name to `{status} <-> Internet Resource` to show it's enabled. The {status} should be the same indicator as the Site offline/online indicator
- Update logic so that if the `enable/disable` hasn't been set by the user, the Internet Resource is disabled by default
- Internet resource can be in three states: `unset`, `disabledbyuser`, `enabledbyuser`

### PR DESCRIPTION
**Pull request by conectado**
With this PR we made internet resource disabled by default.

Since no other resource is disalable and internet resource behavior is particular we remove all client code to make non internet resource disalable.

Also, since the portal never makes the internet resource that can't be disabled we remove the whole code path to handle that.

Additionally, some other smaller refactors across the UI wrt internet resource

Fix #6509

### CODE REVIEW

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt [hunk 1]
```diff
@@ -1,37 +1,60 @@
...
+import dev.firezone.android.core.data.OnSymbol
+import dev.firezone.android.core.data.ResourceState
+import dev.firezone.android.core.data.stateSymbol
 import dev.firezone.android.tunnel.model.Resource
 import dev.firezone.android.tunnel.model.ResourceType
 import dev.firezone.android.tunnel.model.Site
 import dev.firezone.android.tunnel.model.StatusEnum
+import dev.firezone.android.tunnel.model.isInternetResource
 
 data class ViewResource(
```
Comment (thomaseizinger) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt]: I think this should be called a `ResourceViewModel`.

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt [hunk 2]
```diff
@@ -1,37 +1,60 @@
...
+
+fun displayName(resource: Resource, state: ResourceState): String {
+    if (resource.isInternetResource()) {
+        return internetResourceDisplayName(resource, state)
+    } else {
+        return resource.name
+    }
+}
+
+fun Resource.toViewResource(resourceState: ResourceState): ViewResource {
```
Comment (thomaseizinger) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt]: I think a ctor on `ViewResource` would be more natural.

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt [hunk 3]
```diff
@@ -1,37 +1,60 @@
...
+    }
+}
+
+fun displayName(resource: Resource, state: ResourceState): String {
+    if (resource.isInternetResource()) {
+        return internetResourceDisplayName(resource, state)
+    } else {
+        return resource.name
+    }
+}
```
Comment (thomaseizinger) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt]: I'd expect utilities to be below the function that uses them.

File: rust/gui-client/src-tauri/src/client/gui.rs [hunk 4]
```diff
@@ -787,15 +798,18 @@ impl Controller {
     async fn update_disabled_resources(&mut self) -> Result<()> {
         settings::save(&self.advanced_settings).await?;
 
-        let Status::TunnelReady { resources } = &self.status else {
-            bail!("Tunnel is not ready");
-        };
+        let internet_resource = self
+            .status
+            .internet_resource()
+            .ok_or(anyhow!("Tunnel not ready"))?;
```
Comment (thomaseizinger) [inline rust/gui-client/src-tauri/src/client/gui.rs]:
```suggestion
            .context("Tunnel not ready")?;
```

File: rust/gui-client/src-tauri/src/client/gui/system_tray.rs [hunk 5]
```diff
@@ -259,11 +262,26 @@ impl<'a> AppState<'a> {
...
+    if enabled {
+        result.push_str(ENABLED_SYMBOL);
+    } else {
+        result.push_str(DISABLED_SYMBOL);
+    }
+
+    result.push_str(" ");
+    result.push_str(name);
+
+    result
```
Comment (thomaseizinger) [inline rust/gui-client/src-tauri/src/client/gui/system_tray.rs]:
```suggestion
    let symbol = if enabled {
        ENABLED_SYMBOL
    } else {
        DISABLED_SYMBOL
    };

    format!("{symbol} {name}")
```

File: rust/gui-client/src-tauri/src/client/gui/system_tray/builder.rs [hunk 6]
```diff
@@ -68,9 +68,9 @@ pub(crate) enum Event {
     /// Quits the app, without signing the user out
     Quit,
     /// A resource was enabled in the UI
```
Comment (thomaseizinger) [inline rust/gui-client/src-tauri/src/client/gui/system_tray/builder.rs]:
```suggestion
    /// The Internet resource was enabled.
```

File: rust/gui-client/src-tauri/src/client/gui/system_tray/builder.rs [hunk 7]
```diff
@@ -68,9 +68,9 @@ pub(crate) enum Event {
...
-    EnableResource(ResourceId),
+    EnableInternetResource,
     /// A resource was disabled in the UI
```
Comment (thomaseizinger) [inline rust/gui-client/src-tauri/src/client/gui/system_tray/builder.rs]:
```suggestion
    /// The Internet resource was disabled.
```

File: rust/gui-client/src-tauri/src/client/settings.rs [hunk 8]
```diff
@@ -18,7 +18,7 @@ pub(crate) struct AdvancedSettings {
     #[serde(default)]
     pub favorite_resources: HashSet<ResourceId>,
     #[serde(default)]
-    pub disabled_resources: HashSet<ResourceId>,
+    pub internet_resource_enabled: Option<bool>,
```
Comment (thomaseizinger) [inline rust/gui-client/src-tauri/src/client/settings.rs:21]: What is the difference between `None` and `Some(false)`?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift [hunk 9]
```diff
@@ -431,13 +434,22 @@ public final class MenuBar: NSObject, ObservableObject {
     populateFavoriteResourcesMenu(newFavorites)
     populateOtherResourcesMenu(newOthers)
   }
+  
+  private func displayNameChanged(_ resource: Resource) -> Bool {
+    if resource.isInternetResource() {
+      return wasInternetResourceEnabled != model.store.internetResourceEnabled()
+    } else {
+      return false
+    }
```
Comment (thomaseizinger) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Views/MenuBar.swift]:
```suggestion
    if !resource.isInternetResource() {
      return false
    }
    
    return wasInternetResourceEnabled != model.store.internetResourceEnabled()
```

**Review by thomaseizinger — APPROVED** [review]
Overall LGTM

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt (hunk 2 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt]: I like to do the conversion as `resource.toResourceViewModel` instead of `ResourceViewModel.from(...)` and pass the resource in.

Comment (thomaseizinger) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ViewResource.kt]: Sure. My reasoning would be that if you think in terms of dependencies, then the view-stuff is okay to know about the actual entities but the entities shouldn't know about the view. Like, if you were to extract the view into a separate module / crate then you can only do that if the conversion function lives on the view-model type (or completely independent of both).

File: kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt [hunk 10]
```diff
@@ -14,6 +15,40 @@ import kotlinx.coroutines.flow.flowOn
...
+        OFF_SYMBOL
+    }
+}
+
+fun ResourceState.toggle(): ResourceState {
+    return if (this.isEnabled()) {
+        ResourceState.DISABLED
+    } else {
+        ResourceState.ENABLED
+    }
```
Comment (jamilbk) [inline kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt:49]: Are these reversed? Seems a tad confusing.

File: kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt [hunk 11]
```diff
@@ -14,6 +15,40 @@ import kotlinx.coroutines.flow.flowOn
 import java.security.MessageDigest
 import javax.inject.Inject
 
+public const val ON_SYMBOL: String = "<->"
+public const val OFF_SYMBOL: String = " — "
```
Comment (jamilbk) [inline kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt]: Should these be defined on the companion object at the bottom?

Also I think `public` might be redundant?

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+)
+
+fun internetResourceDisplayName(
+    resource: Resource,
+    state: ResourceState,
+): String {
+    return "${state.stateSymbol()} ${resource.name}"
+}
+
+fun Resource.toResourceViewModel(resourceState: ResourceState): ResourceViewModel {
```
Comment (jamilbk) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt]: Shouldn't this function be defined on the Resource class?

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/SessionActivity.kt [hunk 13]
```diff
@@ -72,9 +74,15 @@ class SessionActivity : AppCompatActivity() {
...
-        Log.d(TAG, "Resource toggled $resourceToggled")
-        tunnelService?.resourceToggled(resourceToggled)
+    fun internetState(): ResourceState {
+        return tunnelService?.internetState() ?: ResourceState.UNSET
+    }
+
+    private fun onInternetResourceToggled(): ResourceState {
+        tunnelService?.internetResourceToggled(internetState().toggle())
+        refreshList()
+        Log.d(TAG, "Internet resource toggled ${internetState()}")
```
Comment (jamilbk) [inline kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/SessionActivity.kt]: Next two lines only make sense to execute if the tunnelService is valid, no?

```suggestion
        tunnelService?.let {
          it.internetResourceToggled(internetState().toggle())
          refreshList()
          Log.d(TAG, "Internet resource toggled ${internetState()}")
        }
```

File: kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt (hunk 10 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt:49]: this function "toggles" it so it swap the state out

File: kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt (hunk 11 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/core/data/Repository.kt]: > Should these be defined on the companion object at the bottom?

Is there any benefit to that? Also, shouldn't in that case be a companion to `ResourceState`?

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt (hunk 12 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt]: It's defined in the `Resource` class but not on the `Resource` module.

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/SessionActivity.kt (hunk 13 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/SessionActivity.kt]: is there any point at which this can actually happen to be nil? Maybe I just use `!!`?

File: kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt (hunk 12 above)
Comment (conectado) [reply kotlin/android/app/src/main/java/dev/firezone/android/features/session/ui/ResourceViewModel.kt]: I converted this to a constructor on `ResourceViewModel`
