### PR TITLE
fix(portal): Allow users to manually provision OIDC users

### LINKED ISSUE #3308: Allow pre-creating identities to authenticate new actors to an existing identity provider
For OIDC auth, actors should be able to log in with an identity provider for the first time.

Make sure to generate APK and AAB bundles and possibly zip them

### PR DESCRIPTION
**Pull request by AndrewDryga**
Before, any user logging into via the OIDC connector would need to have an identity created beforehand with their known `sub` id. This presented a chicken-and-egg scenario where this was only populated in the `Identity Providers` settings flow by an admin, preventing regular users from signing in.

With this change, Admins can now create identities for actors and specify an `email` address or `sub` claim value to match against for incoming authentications to the connector.

This will allow end-users to authenticate with the configured OIDC connector.

Fixes #3308

### CODE REVIEW

File: elixir/apps/web/lib/web/live/actors/components.ex [hunk 1]
```diff
@@ -125,6 +125,27 @@ defmodule Web.Actors.Components do
...
 
+  def provider_form(%{provider: %{adapter: :openid_connect}} = assigns) do
+    ~H"""
+    <div>
+      <.input
+        label="Email or Sub claim"
+        placeholder="Email or Sub claim"
+        field={@form[:provider_identifier]}
+        autocomplete="off"
+      />
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/live/actors/components.ex:136]:
```suggestion
      />
      <p class="mt-2 text-xs text-neutral-500">
        The user's email or <code>sub</code> claim value. This will be used to match the user to this identity when signing in.
      </p>
```

**Review by jamilbk — CHANGES_REQUESTED** [review]
LGTM! Just a minor suggestion to add a helptext for the input field.
