### PR TITLE
Filter out nil IPs before adding to the nftables ruleset

### LINKED ISSUE #1331: Properly handle nil device IPs
sorry to post again.. 

So I migrated to Docker.. 

```
[+] Running 3/0
 ⠿ Container firezone-caddy-1     Running                                                                                                                                                                                   0.0s
 ⠿ Container firezone-postgres-1  Running                                                                                                                                                                                   0.0s
 ⠿ Container firezone-firezone-1  Created                                                                                                                                                                                   0.0s
Attaching to firezone-caddy-1, firezone-firezone-1, firezone-postgres-1
firezone-firezone-1  | 19:45:58.261 [info] Migrations already up
firezone-firezone-1  | sh: true: unknown operand
firezone-firezone-1  | 19:45:59.752 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
firezone-firezone-1  | 19:45:59.753 [info] Access FzHttpWeb.Endpoint at https://firezone.domain.org
firezone-firezone-1  | 19:46:00.655 [notice] Application fz_wall exited: FzWall.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzWall.Server
firezone-firezone-1  |     ** (EXIT) an exception was raised:
firezone-firezone-1  |         ** (FunctionClauseError) no function clause matching in FzCommon.FzNet.standardized_inet/1
firezone-firezone-1  |             (fz_common 0.7.2) lib/fz_net.ex:39: FzCommon.FzNet.standardized_inet(nil)
firezone-firezone-1  |             (fz_wall 0.7.2) lib/fz_wall/cli/helpers/nft.ex:270: FzWall.CLI.Helpers.Nft.get_elem/1
firezone-firezone-1  |             (fz_wall 0.7.2) lib/fz_wall/cli/helpers/nft.ex:49: FzWall.CLI.Helpers.Nft.add_ip_elem/2
firezone-firezone-1  |             (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
firezone-firezone-1  |             (elixir 1.14.2) lib/enum.ex:980: anonymous fn/3 in Enum.each/2
firezone-firezone-1  |             (elixir 1.14.2) lib/enum.ex:4307: anonymous fn/3 in Enum.each/2
firezone-firezone-1  |             (elixir 1.14.2) lib/enum.ex:4751: Enumerable.List.reduce/3
firezone-firezone-1  |             (elixir 1.14.2) lib/enum.ex:4307: Enum.each/2
firezone-firezone-1  | {"Kernel pid terminated",application_controller,"{application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{function_clause,[{'Elixir.FzCommon.FzNet',standardized_inet,[nil],[{file,\"lib/fz_net.ex\"},{line,39}]},{'Elixir.FzWall.CLI.Helpers.Nft',get_elem,1,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,270}]},{'Elixir.FzWall.CLI.Helpers.Nft',add_ip_elem,2,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,49}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,\"lib/enum.ex\"},{line,975}]},{'Elixir.Enum','-each/2-fun-0-',3,[{file,\"lib/enum.ex\"},{line,980}]},{'Elixir.Enum','-each/2-anonymous-3-',3,[{file,\"lib/enum.ex\"},{line,4307}]},{'Elixir.Enumerable.List',reduce,3,[{file,\"lib/enum.ex\"},{line,4751}]},{'Elixir.Enum',each,2,[{file,\"lib/enum.ex\"},{line,4307}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}}"}
firezone-firezone-1  | Kernel pid terminated (application_controller) ({application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{function_clause,[{'Elixir.FzCommon.FzNet',standardized_inet,[nil],[{file,"lib/fz_net.ex"},{line,39}]},{'Elixir.FzWall.CLI.Helpers.Nft',get_elem,1,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,270}]},{'Elixir.FzWall.CLI.Helpers.Nft',add_ip_elem,2,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,49}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,"lib/enum.ex"},{line,975}]},{'Elixir.Enum','-each/2-fun-0-',3,[{file,"lib/enum.ex"},{line,980}]},{'Elixir.Enum','-each/2-anonymous-3-',3,[{file,"lib/enum.ex"},{line,4307}]},{'Elixir.Enumerable.List',reduce,3,[{file,"lib/enum.ex"},{line,4751}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,4307}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}})
firezone-firezone-1  |
^CGracefully stopping... (press Ctrl+C again to force)
```

and .env

```
EXTERNAL_URL="https://firezone.domain.org"
ADMIN_EMAIL="firezone@localhost"
GUARDIAN_SECRET_KEY="8< ENCRYPTED >8"
DATABASE_ENCRYPTION_KEY="8< ENCRYPTED >8"
SECRET_KEY_BASE="8< ENCRYPTED >8"
LIVE_VIEW_SIGNING_SALT="8< ENCRYPTED >8"
COOKIE_SIGNING_SALT="8< ENCRYPTED >8"
COOKIE_ENCRYPTION_SALT="8< ENCRYPTED >8"
DATABASE_NAME="firezone"
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_POOL="12"
DATABASE_SSL="false"
DATABASE_SSL_OPTS="{}"
DATABASE_PARAMETERS="{}"
EXTERNAL_TRUSTED_PROXIES="[]"
PRIVATE_CLIENTS="[]"
WIREGUARD_PORT="51820"
WIREGUARD_DNS="1.1.1.1, 1.0.0.1"
WIREGUARD_ALLOWED_IPS="0.0.0.0/0, ::/0"
WIREGUARD_PERSISTENT_KEEPALIVE="63"
WIREGUARD_MTU="1280"
WIREGUARD_ENDPOINT="1.2.3.4"
WIREGUARD_IPV4_ENABLED="true"
WIREGUARD_IPV4_MASQUERADE="true"
WIREGUARD_IPV4_NETWORK="10.3.2.0/24"
WIREGUARD_IPV4_ADDRESS="10.3.2.1"
WIREGUARD_IPV6_ENABLED="false"
WIREGUARD_IPV6_MASQUERADE="false"
WIREGUARD_IPV6_NETWORK="fd00::3:2:0/120"
WIREGUARD_IPV6_ADDRESS="fd00::3:2:1"
DISABLE_VPN_ON_OIDC_ERROR="false"
SECURE_COOKIES="true"
ALLOW_UNPRIVILEGED_DEVICE_MANAGEMENT="true"
ALLOW_UNPRIVILEGED_DEVICE_CONFIGURATION="true"
OUTBOUND_EMAIL_CONFIGS="{\"smtp\":{\"relay\":\"smtp.example.com\",\"port\":587,\"username\":\"\",\"password\":\"\",\"ssl\":true,\"tls\":\"always\",\"auth\":\"always\",\"no_mx_lookup\":false,\"retries\":2},\"mailgun\":{\"apikey\":null,\"domain\":null},\"mandrill\":{\"api_key\":null},\"sendgrid\":{\"api_key\":null},\"post_mark\":{\"api_key\":null},\"sendmail\":{\"cmd_path\":\"/usr/bin/sendmail\",\"cmd_args\":\"-N delay,failure,success\"}}"
AUTH_OIDC_JSON="{}"
LOCAL_AUTH_ENABLED="true"
MAX_DEVICES_PER_USER="40"
CONNECTIVITY_CHECKS_ENABLED="true"
CONNECTIVITY_CHECKS_INTERVAL="3600"
TLS_OPTS="tls {
                on_demand
              }"
DATABASE_PASSWORD="8< ENCRYPTED >8"
DEFAULT_ADMIN_PASSWORD="8< ENCRYPTED >8"
```

The  firezone-firezone-1 container does not ever start..

_Originally posted by @bcookatpcsd in https://github.com/firezone/firezone/issues/1327#issuecomment-1386030686_

### PR DESCRIPTION
**Pull request by jamilbk**
This edgecase happens when `WIREGUARD_IPV4_ENABLED` or `WIREGUARD_IPV6_ENABLED` are set to `false`; when a new device is generated, we don't allocate an IP for it. This causes a failed function match, and should be handled instead by simply skipping the `nil` IP from being added to the user's `nftables` group.

**Note**: This functionality will be removed with the release of the gateway's eBPF packet filter in 0.8.

Fixes #1331

### CODE REVIEW

File: apps/fz_wall/lib/fz_wall/cli/live.ex [hunk 1]
```diff
@@ -67,11 +67,17 @@ defmodule FzWall.CLI.Live do
...
 
   @doc """
-  Adds device ip to the user's sets.
+  Adds device ip(s) to the user's sets, omitting missing IPs.
   """
   def add_device(device) do
     list_dev_sets(device.user_id)
-    |> Enum.each(fn set_spec -> add_elem(set_spec.name, device[set_spec.ip_type]) end)
+    |> Enum.filter(fn set_spec ->
+      # Only call add_elem/2 for IPs that are present
```
Comment (AndrewDryga) [inline apps/fz_wall/lib/fz_wall/cli/live.ex:75]: We must have a test for this one

Comment (jamilbk) [reply apps/fz_wall/lib/fz_wall/cli/live.ex:75]: This logic will be moved to the gateway in `0.8` and will be tested there.

**Review by AndrewDryga — APPROVED** [review]
