### PR TITLE
Adopt new http transport opts in OIDC lib

### LINKED ISSUE #1368: HTTP_CLIENT_SSL_OPTS not work after 0.7.3
Hi,

I have try to set HTTP_CLIENT_SSL_OPTS
```
HTTP_CLIENT_SSL_OPTS='{"verify": "verify_peer", "cacertfile": "/etc/ssl/ca.crt"}'
```

Breaking change between 0.7.2 and higher 0.7.3

Thank you

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #1368

### CODE REVIEW

File: config/runtime.exs [hunk 1]
```diff
@@ -236,7 +236,7 @@ if config_env() == :prod do
 
   # Configure OpenID Connect
   config :openid_connect,
-    http_client_options: [ssl: FzCommon.map_ssl_opts(http_client_ssl_opts)]
+    finch_transport_opts: FzCommon.map_ssl_opts(http_client_ssl_opts)
```
Comment (jamilbk) [inline config/runtime.exs:239]: Would it make sense to set Finch as the http client [here](https://github.com/firezone/firezone/blob/master/config/config.exs#L40)? This is used [here](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/connectivity_check_service.ex#L67) by the connectivity checks service.

Sadly, the [posthog](https://github.com/nkezhaya/posthog/blob/master/lib/posthog/client.ex) library we use seems hard-coded to `hackney` :-(. Probably need to fork that at some point and customize it.

Comment (AndrewDryga) [reply config/runtime.exs:239]: @jamilbk yes - I plan to do that once I get to reworking connectivity checks, but it should be done in a different PR and is not critical right now.

And you can't just set a new `http_client`, they are not compatible. That option should be removed to avoid confusion.

Comment (jamilbk) [reply config/runtime.exs:239]: Refs https://github.com/firezone/firezone/issues/1373

**Review by jamilbk — APPROVED** [review]
