### PR TITLE
fix(portal): Prevent races during relay selection by only using the ones connected for more than 5 seconds ago

### LINKED ISSUE #6099: `relays_presence` contains same relay in `disconnected` and `connected`
We just observed the following message being broadcast to gateways during a deploy:

```
Jul 31 05:58:10 perf sudo[506882]: 2024-07-31T05:58:10.299838Z TRACE wire::api::recv: {"event":"relays_presence","ref":null,"topic":"gateway","payload":{"connected":[{"id":"66954123-7f64-4059-b9e2-def1b2633bf6","type":"turn","addr":"34.74.204.173:3478","username":"1723615090:q6GytmZfJLtg7O5o8M_r5g","password":"jb9W70XEzu/enJIFPe4mMU/5iI5vsJYmVlCoDiLkl80","expires_at":1723615090},{"id":"66954123-7f64-4059-b9e2-def1b2633bf6","type":"turn","addr":"[2600:1900:4020:eb:0:57::]:3478","username":"1723615090:Hn7uwLCuByPmCUcobaK0kA","password":"L+a8WPH+SFqFY0AnPhj7asCQByl4eoqdPZmxZby8yjw","expires_at":1723615090},{"id":"d0d6d43d-c437-48a0-bbde-fc397e22a8d3","type":"turn","addr":"199.223.232.179:3478","username":"1723615090:o7sjIerX7TQOaScvaM-87g","password":"TQFIko3kaZqOfpwO0LpM4J0vsEeeDD9BpsovFXBWOdE","expires_at":1723615090},{"id":"d0d6d43d-c437-48a0-bbde-fc397e22a8d3","type":"turn","addr":"[2600:1900:4000:102d:0:b::]:3478","username":"1723615090:lewcj_jxpf4iHBv0uvzwSQ","password":"dtQytSQkhnsc+1Lo0C8SVfh7Reu9mD3NYQkcM2jrK8o","expires_at":1723615090}],"disconnected_ids":["66954123-7f64-4059-b9e2-def1b2633bf6"]}}
Jul 31 05:58:10 perf sudo[506882]: 2024-07-31T05:58:10.300368Z  INFO snownet::node: Removed TURN server rid=66954123-7f64-4059-b9e2-def1b2633bf6 address=Dual { v4: 34.74.204.173:3478, v6: [2600:1900:4020:eb:0:57::]:3478 }
Jul 31 05:58:10 perf sudo[506882]: 2024-07-31T05:58:10.300536Z  INFO snownet::node: Added new TURN server rid=66954123-7f64-4059-b9e2-def1b2633bf6 address=Dual { v4: 34.74.204.173:3478, v6: [2600:1900:4020:eb:0:57::]:3478 }
```

We are being given the same relay to disconnect and connect at the same time.

Just a second after, the relay still works but about a minute later, we try to use it for a connection and then the requests start timing out.

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #6099
Should push #6109 to not being needed short term.

### CODE REVIEW

**Comment by AndrewDryga** [comment]
@jamilbk we need to wait for 5 seconds in integration tests now.

**Review by jamilbk — APPROVED** [review]
LGTM, just want to note that this and the consistency fix are included in this one PR right?

One thought that came to mind here was if we roll over Relays too quickly, but I guess the region deployment strategy should prevent that, i.e. one instance in each region is rolled.

**Comment by thomaseizinger** [comment]
Is 5s enough? If you look at the logs in https://github.com/firezone/firezone/issues/6099#issuecomment-2259784744 in detail, you can see that the same relay that is returned in disconnected is still given out later as a connected one. And the logs are minutes apart there.

My Elixir isn't very good 😅
Is this definitely fixing the race condition where a disconnected relay is never returned as connected?

**Comment by AndrewDryga** [comment]
@thomaseizinger @jamilbk race condition is fixed separately in this PR, when we select for new relays we exclude the ones from `disconnected_ids` from the query.

File: elixir/apps/api/lib/api/client/channel.ex [hunk 1]
```diff
@@ -327,7 +327,9 @@ defmodule API.Client.Channel do
         attributes: %{
           relay_id: relay_id
         } do
-        {:ok, relays} = select_relays(socket)
+        :ok = Relays.unsubscribe_from_relay_presence(relay_id)
+
+        {:ok, relays} = select_relays(socket, [relay_id])
```
Comment (AndrewDryga) [inline elixir/apps/api/lib/api/client/channel.ex:333]: Here is the additional fix for relay being present in both lists.

**Comment by AndrewDryga** [comment]
@jamilbk 

> One thought that came to mind here was if we roll over Relays too quickly, but I guess the region deployment strategy should prevent that, i.e. one instance in each region is rolled.

We only shut down instance when new one is healthy, there is a shutdown timeout plus there is a timeout that we give before we start firing a liveness probe which should be more than enough to cover the 5 seconds difference. As we scale and have 3+ relays per region this won't be an issue at all because we'll migrate them one by one.

File: elixir/apps/api/test/api/client/channel_test.exs [hunk 2]
```diff
@@ -333,18 +350,18 @@ defmodule API.Client.ChannelTest do
...
         connected: [relay_view1, relay_view2]
       }
 
-      assert relay_view1.id == relay.id
-      assert relay_view2.id == relay.id
-      assert relay_id == relay.id
+      assert relay_view1.id == relay2.id
+      assert relay_view2.id == relay2.id
+      assert relay1_id == relay1.id
     end
```
Comment (thomaseizinger) [inline elixir/apps/api/test/api/client/channel_test.exs:365]: The property that we are interested in, and which currently doesn't hold is:

```suggestion
        assert relay_view1.id != relay1_id
        assert relay_view2.id != relay1_id
    end
```

It might be worth adding 1 more test that represents staging / prod more closely where we have ~10 relays, disconnect them all one by one, connect new ones, capture all relays presence messages and assert that none of the disconnected ones ever get returned as connected.

That test doesn't need to capture which specific ones of the newly connected ones do get returned so you don't need to simulate the selection logic. We use property-based testing connlib extensively and it helped us find a lot of these subtle bugs :)

**Review by thomaseizinger — APPROVED** [review]
Thanks for the quick turnaround! Approving to unblock. I can't fully confirm that is fixes the bug because I can't read elixir well enough. A property-based test could help though!

**Comment by thomaseizinger** [comment]
> @thomaseizinger @jamilbk race condition is fixed separately in this PR, when we select for new relays we exclude the ones from `disconnected_ids` from the query.

And that helps across multiple `relays_presence` events? I've also seen disconnected relays returned as connected in _later_ events.

**Comment by thomaseizinger** [comment]
> > @thomaseizinger @jamilbk race condition is fixed separately in this PR, when we select for new relays we exclude the ones from `disconnected_ids` from the query.
> 
> And that helps across multiple `relays_presence` events? I've also seen disconnected relays returned as connected in _later_ events.

Look at relay `542b5b7b-ba09-4573-af81-43614a94d6c0` in the linked logs. It is being returned minutes after as connected in presence events for different relays, despite already being disconnected.

File: elixir/apps/api/test/api/client/channel_test.exs (hunk 2 above)
Comment (AndrewDryga) [reply elixir/apps/api/test/api/client/channel_test.exs:365]: Isn't
```
assert relay_view1.id == relay2.id
```
is the same as
```
assert relay_view1.id != relay1_id
```
because we know that `relay2.id != relay1_id`?

> It might be worth adding 1 more test that represents staging / prod more closely where we have ~10 relays, disconnect them all one by one, connect new ones, capture all relays presence messages and assert that none of the disconnected ones ever get returned as connected.

The suggested test is the same as restarting this one multiple times, before we were testing on just one relay, I've added 2nd to capture that (doesn't matter if it's 10 of them or 2). So if there is a bug our tests will find that sooner than later anyways.

I will add a test that makes sure that relay won't be ever returned even if it was single one online though.

**Comment by AndrewDryga** [comment]
> And that helps across multiple relays_presence events? I've also seen disconnected relays returned as connected in later events.

From the logs it looks like `542b5b7b-ba09-4573-af81-43614a94d6c0` was connected, then it disconnected and connected back (and stayed like that). The only issue with logs is that we had it once in connected and disconnected list once (due to nature of using CRDT for distributing presence that Phoenix aggregates over a time window, ~1.5s for inter-cluster events).

I think the reason for this was that the relay that was connected to an API instance re-established a websocket connection to a new API instance because everything is rolled out at the same time. With current changes if it jumps between instances disconnect message will come really quickly but it will be visible in `connected` only after 5 seconds (that are only sent when relay client/gateway uses is disconnected so not pushed proactively). This also will help if we have a relay that crash loops - it won't be able to spam websocket processes and hurt the connectivity.

File: elixir/apps/api/test/api/client/channel_test.exs (hunk 2 above)
Comment (thomaseizinger) [reply elixir/apps/api/test/api/client/channel_test.exs:365]: > Isn't
> 
> ```
> assert relay_view1.id == relay2.id
> ```
> 
> is the same as
> 
> ```
> assert relay_view1.id != relay1_id
> ```
> 
> because we know that `relay2.id != relay1_id`?

In this test setup, yes. If you'd use more inputs, modelling which ones is actually returned gets more difficult and obscures the test. In connlib, we don't care which one we get but the property of not receiving a disconnected one is really important. What I am suggesting is IMO simply a more intentional assertion of what we want. It is your codebase, so up to you :)

**Comment by thomaseizinger** [comment]
> > And that helps across multiple relays_presence events? I've also seen disconnected relays returned as connected in later events.
> 
> From the logs it looks like `542b5b7b-ba09-4573-af81-43614a94d6c0` was connected, then it disconnected and connected back (and stayed like that). The only issue with logs is that we had it once in connected and disconnected list once (due to nature of using CRDT for distributing presence that Phoenix aggregates over a time window, ~1.5s for inter-cluster events).

Will the relay ID change when its stamp secret changes? These IDs need to be unique to the relay's state (available allocations, stamp secret etc). So when it reboots, it needs to be treated as a different relay, otherwise I have no way of knowing in connlib, whether or not I need to throw away the state I have or can keep using it.

**Comment by AndrewDryga** [comment]
@thomaseizinger relay id will change if IP address will change (so new VM has new ID), relay should keep `stamp_secret` between WS reconnects so we should be fine?

**Comment by thomaseizinger** [comment]
> @thomaseizinger relay id will change if IP address will change (so new VM has new ID), relay should keep `stamp_secret` between WS reconnects so we should be fine?

It keeps the secret when it reconnects but not if the container restarts. So that could be an issue.

**Comment by thomaseizinger** [comment]
> @thomaseizinger relay id will change if IP address will change (so new VM has new ID), relay should keep `stamp_secret` between WS reconnects so we should be fine?

Can you make it based on stamp secret instead? I can move the secret to the URL if that helps.

**Comment by AndrewDryga** [comment]
> So when it reboots, it needs to be treated as a different relay, otherwise I have no way of knowing in connlib, whether or not I need to throw away the state I have or can keep using it.

Just realized, why do you need to worry about it? You are guaranteed to get presence event when that happens, when you get one you should always discard all state related to it, doesn't matter if it will reboot as the same one or not. Or I am missing something?

**Comment by thomaseizinger** [comment]
> > So when it reboots, it needs to be treated as a different relay, otherwise I have no way of knowing in connlib, whether or not I need to throw away the state I have or can keep using it.
> 
> Just realized, why do you need to worry about it? You are guaranteed to get presence event when that happens, when you get one you should always discard all state related to it, doesn't matter if it will reboot as the same one or not. Or I am missing something?

If it is a relay that I already know, I must not throw away the state because the relay identifies me by my 3-tuple so it won't give me another allocation if I previously already made one.

I identify the relay by its ID and keep the local state if I already know it.

**Comment by AndrewDryga** [comment]
> If it is a relay that I already know, I must not throw away the state because the relay identifies me by my 3-tuple so it won't give me another allocation if I previously already made one.

Would it currently return an error if you try to get another allocation? Would it be better to either return existing allocation or remove old one and create a new one if the same peer (3-tuple) is requesting a new one vs keeping the state even after it's ID being in `disconnected_ids`?

**Comment by thomaseizinger** [comment]
> > If it is a relay that I already know, I must not throw away the state because the relay identifies me by my 3-tuple so it won't give me another allocation if I previously already made one.
> 
> Would it currently return an error if you try to get another allocation? Would it be better to either return existing allocation or remove old one and create a new one if the same peer (3-tuple) is requesting a new one vs keeping the state even after it's ID being in `disconnected_ids`?

Yes, creating an allocation when you already have one is an error. It would be a deviation from how TURN Is meant to work. I am not against doing that in principle but to me, that is a bigger chunk of work because we need to think through attack scenarios etc. There is probably a reason why the TURN protocol is specified the way it is and I would like to stick to it for the time being unless we have good reason to change this.

In this particular case, it seems reasonable to me that a relay ID is unique per stamp secret. When the stamp secret changes, the credentials change too, meaning semantically, it is a new relay. Other than the same IP, it has nothing in common with the previous instance. All the state management gets a lot easier if we just treat it as a new relay.

If you read through https://github.com/firezone/firezone/pull/6101, you'll learn that exactly this upsert behaviour is the underlying cause for the busy loop that we have been experiencing.

**Comment by AndrewDryga** [comment]
@thomaseizinger do we also want relay to be created when the same relay reconnected with the same stamp secret?

The reason why I'm asking all this is that if we start to create new relays on every stamp secret change there will be much more of them, so it will be really easy to spam our `relays` table with entities. Fortunately we don't enable self-hosted relays feature for anyone so it can only happen by an accident, but who knows how this will change in a year or two.

**Comment by thomaseizinger** [comment]
> @thomaseizinger do we also want relay to be created when the same relay reconnected with the same stamp secret?
> 
> The reason why I'm asking all this is that if we start to create new relays on every stamp secret change there will be much more of them, so it will be really easy to spam our `relays` table with entities. Fortunately we don't enable self-hosted relays feature for anyone so it can only happen by an accident, but who knows how this will change in a year or two.

Good question. A reconnect with the same stamp secret means all the state on the relay is intact and we just had a network partition of the WebSocket.

Thinking about though, if there is a network partition, we would have also broadcast a `relays_presence`, signalling that relay as disconnected and thus cleared all local state. Even if it reconnects with the same secret, we would have lost our local state already.

So I think what I need to do locally is react to the `AllocationMismatch` error, send a `REFRESH` with lifetime 0 (that deletes the current allocation) and start again. That way, it shouldn't matter that the same ID is used.

**Comment by thomaseizinger** [comment]
I have a solution ready that fixes this on the connlib side: https://github.com/firezone/firezone/pull/6117. With that, we don't care how you generate the relay ID and what it is correlated to.

For now, I am also assuming that the credentials don't change. If I already know the relay with a certain ID, I don't do anything to it.

This is based on the assumption that we will always receive a `relays_presence` event when a relay disconnects, regardless whether it reboots, meaning we would have already thrown away the state anyway prior to that so there is no need for upserting and we just need to sync up the state with the relay by deleting the allocation and making a new one in case it only got partitioned and not restarted.

**Review by thomaseizinger — APPROVED** [review]

File: elixir/apps/domain/lib/domain/relays.ex [hunk 3]
```diff
@@ -244,12 +246,13 @@ defmodule Domain.Relays do
...
 
     connected_relays = Map.merge(connected_global_relays, connected_account_relays)
-    connected_relay_ids = Map.keys(connected_relays)
+    connected_relay_ids = Map.keys(connected_relays) -- except_ids
 
     relays =
       Relay.Query.not_deleted()
       |> Relay.Query.by_ids(connected_relay_ids)
       |> Relay.Query.global_or_by_account_id(account_id)
+      |> Relay.Query.by_last_seen_at_greater_than(5, "second", :ago)
```
Comment (thomaseizinger) [inline elixir/apps/domain/lib/domain/relays.ex]: Do we really need this if we filter the currently disconnecting one? Can you explain where the race condition actually happens?

Comment (AndrewDryga) [reply elixir/apps/domain/lib/domain/relays.ex]: @thomaseizinger I added this as a preventive measure from too quickly changing the online state, it's not required to fix the race. Will think for a bit if we should go with it or not.
