### PR TITLE
fix(gui-client): un-initialize wintun correctly

### LINKED ISSUE #4765: bug(gui-client/windows): wintun failing to create adapter
#### Describe the bug

The Client gets stuck signing in forever because wintun throws an error and connlib doesn't bubble it anywhere

#### To Reproduce

Not sure yet. I've seen it happen while restarting the app, as though the tunnel interface was not torn down fully

#### Expected behavior

- Expected wintun to work
- Expected errors to result in an error dialog or something that can reset the GUI to a usable state

#### Screenshots / Logs

```jsonl
{"time":"2024-04-24T14:18:06.7012667Z","target":"log","severity":"ERROR","logFile":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\wintun-0.4.0\\src\\log.rs","logLine":30,"logModulePath":"wintun::log","logTarget":"wintun::log","message":"WinTun: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)"}
{"time":"2024-04-24T14:18:06.7019883Z","target":"log","severity":"ERROR","logFile":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\wintun-0.4.0\\src\\log.rs","logLine":30,"logModulePath":"wintun::log","logTarget":"wintun::log","message":"WinTun: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)"}
{"time":"2024-04-24T14:18:06.745354Z","target":"firezone_tunnel::device_channel::tun_windows","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\device_channel\\tun_windows.rs","line":"70"},"severity":"ERROR","message":"wintun::Adapter::create failed, probably need admin powers: Failed to create adapter"}
{"time":"2024-04-24T14:18:06.7454742Z","target":"connlib_client_shared::eventloop","logging.googleapis.com/sourceLocation":{"file":"connlib\\clients\\shared\\src\\eventloop.rs","line":"199"},"severity":"WARNING","message":"Failed to set interface on tunnel: Failed to create adapter"}
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (d656cd5)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI from draft release

#### Additional context

Refs #4763

```[tasklist]
### Tasks
- [x] Ask wintun if the adapter already exists and log the result
- [x] Fault injection flag in the debug IPC service to replicate this
- [x] Can we retry with backoff?
- [ ] Can we get an `on_disconnect` or something to bubble this to the GUI?
```

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #4765 

It turns out that if I don't join the worker thread explicitly it messes up wintun a lot. I wonder if I should report that as a bug or what. It's kind of our fault for keeping a handle to the `Session` alive in the thread.

```[tasklist]
- [x] Move the debug command from `gui-client` to `headless-client`
- [x] Move the initialization out of `firezone-tunnel`, revert the `pub` changes, use `anyhow::Context`
```

### CODE REVIEW

File: rust/connlib/tunnel/src/device_channel.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ use std::collections::HashSet;
 use std::io;
 use std::net::IpAddr;
 use std::task::{Context, Poll, Waker};
-use tun::Tun;
+pub use tun::Tun;
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel.rs]: Made this public so the debug command can replicate the issue.

File: rust/connlib/tunnel/src/device_channel/tun_darwin.rs [hunk 2]
```diff
@@ -19,7 +19,7 @@ use tokio::io::unix::AsyncFd;
 const CTL_NAME: &[u8] = b"com.apple.net.utun_control";
 
 #[derive(Debug)]
-pub(crate) struct Tun {
+pub struct Tun {
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_darwin.rs]: This is pointless but it keeps us from having to write `target_os` directives in `device_channel.rs` to make it `pub` on Windows specifically.

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 3]
```diff
@@ -24,14 +24,18 @@ use windows::Win32::{
     },
     Networking::WinSock::{AF_INET, AF_INET6},
 };
+use wintun::Adapter;
+
+// Not sure how this and `TUNNEL_NAME` differ
+const ADAPTER_NAME: &str = "Firezone";
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs:30]: I had originally extracted this so I could use it when deleting the adapter, but deleting is not necessary if I just join the worker thread.

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 4]
```diff
@@ -24,14 +24,18 @@ use windows::Win32::{
...
 
 // TODO: Double-check that all these get dropped gracefully on disconnect
 pub struct Tun {
     /// The index of our network adapter, we can use this when asking Windows to add / remove routes / DNS rules
     /// It's stable across app restarts and I'm assuming across system reboots too.
     iface_idx: u32,
     packet_rx: mpsc::Receiver<wintun::Packet>,
-    _recv_thread: std::thread::JoinHandle<()>,
+    recv_thread: Option<std::thread::JoinHandle<()>>,
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs:37]: Not idiomatic, but I am not aware of any better way to join a thread inside `Drop`

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 5]
```diff
@@ -41,31 +45,31 @@ impl Drop for Tun {
         if let Err(e) = self.session.shutdown() {
             tracing::error!("wintun::Session::shutdown: {e:#?}");
         }
+        if let Some(recv_thread) = self.recv_thread.take() {
+            if let Err(error) = recv_thread.join() {
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs:49]: This appears to completely fix the issue.

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 6]
```diff
@@ -41,31 +45,31 @@ impl Drop for Tun {
...
+                tracing::error!(?error, "Couldn't join `recv_thread`");
+            }
+        } else {
+            tracing::error!("No `recv_thread` in `Tun`");
+        }
     }
 }
 
 impl Tun {
+    #[tracing::instrument]
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs]: `Tun::new` takes about 500 ms

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 7]
```diff
@@ -41,31 +45,31 @@ impl Drop for Tun {
...
         let path = connlib_shared::windows::wintun_dll_path()?;
         let wintun = unsafe { wintun::load_from_path(path) }?;
-        let uuid =
-            uuid::Uuid::from_str(TUNNEL_UUID).expect("static UUID should always parse correctly");
-        let adapter =
-            match wintun::Adapter::create(&wintun, "Firezone", TUNNEL_NAME, Some(uuid.as_u128())) {
-                Ok(x) => x,
-                Err(e) => {
-                    tracing::error!(
-                        "wintun::Adapter::create failed, probably need admin powers: {}",
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs:62]: Since #3712 merged, we always have admin powers in the IPC service. For the headless Client it's not a big deal, it isn't used on Windows yet.

File: rust/gui-client/src-tauri/src/client/debug_commands.rs [hunk 8]
```diff
@@ -9,20 +9,16 @@ pub enum Cmd {
...
-    Hostname,
     NetworkChanges,
 }
 
 pub fn run(cmd: Cmd) -> Result<()> {
     match cmd {
-        Cmd::CheckForUpdates => check_for_updates()?,
-        Cmd::Crash => crash()?,
-        Cmd::DnsChanges => client::network_changes::run_dns_debug()?,
-        Cmd::Hostname => hostname(),
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/debug_commands.rs]: I haven't used the `debug hostname` subcommand in months, so I got rid of it.

File: rust/headless-client/src/windows.rs [hunk 9]
```diff
@@ -71,6 +71,19 @@ pub(crate) fn run_ipc_service(_cli: CliCommon) -> Result<()> {
     windows_service::service_dispatcher::start(SERVICE_NAME, ffi_service_run).context("windows_service::service_dispatcher failed. This isn't running in an interactive terminal, right?")
 }
 
+/// Wintun stress test to shake out issue #4765
+pub(crate) fn run_wintun() -> Result<()> {
+    crate::debug_command_setup()?;
+
+    let iters = 1000;
```
Comment (ReactorScram) [inline rust/headless-client/src/windows.rs]: Before this change, this stress test failed before 100 loops, now it can do 1,000 loops, so I think we got it.

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: Can this just be a `cfg(all(test, target_os = "windows"))`? Why does it have to be a run by a command?

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: Could this even live inside `Tun` itself so we don't need to make it public?

File: rust/gui-client/src-tauri/src/client/debug_commands.rs (hunk 8 above)
Comment (thomaseizinger) [reply rust/gui-client/src-tauri/src/client/debug_commands.rs]: SGTM. I'd prefer these refactorings to go in separate PRs in case we need to revert something.

File: rust/headless-client/src/windows.rs (hunk 9 above)
Comment (ReactorScram) [reply rust/headless-client/src/windows.rs]: It needs admin privilege to run. ChatGPT says `runas` can do it, but it asks for a password, so I don't think it'll work in CI. Also you have to quote the whole command line, so `sudo --preserve-env some_command some_arg` would become `runas /env /user:USER "some_command some_arg"`

I didn't feel like messing with it, but it would be nice, we do have a thing for using `sudo` in CI on Linux

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: Hmm, I wouldn't want to run them on all platforms, so we'd only need admin on Windows, right? Perhaps make it an ignored test for now and include ignored tests in CI?

It is not super clean but may be good enough until we think of some other classification of tests. Could also hide it behind a dedicated "sudo-tests" `cfg` (not a feature!)

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: Apparently UAC is disabled in CI by default so it might just work as is?

https://github.com/actions/runner-images/discussions/6557#discussioncomment-4123946

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: I pushed some commits as a PoC, seems to be working well! I haven't verified that they actually fail if we remove the thread-joining though.

Comment (ReactorScram) [reply rust/headless-client/src/windows.rs]: Oh okay, I thought it would need some special command.
I'll replace `sudotests` with whatever the Linux tests are already using, though

Comment (thomaseizinger) [reply rust/headless-client/src/windows.rs]: > I'll replace sudotests with whatever the Linux tests are already using, though

Sure! I didn't know that we already have tests that use elevated privileges? Running `cargo test` locally doesn't require sudo for me.

Note that `sudotests` is nothing special, just a cfg. Could be named anything!

Comment (ReactorScram) [reply rust/headless-client/src/windows.rs]: Yeah here it is. They're just ignored tests, and in CI we tell Cargo to run ignored tests https://github.com/firezone/firezone/blob/cf9f7504ce9e2c1d54dabc37ebcdef08b3c66fbe/rust/connlib/clients/shared/src/lib.rs#L185

File: rust/gui-client/src-tauri/src/client/debug_commands.rs (hunk 8 above)
Comment (ReactorScram) [reply rust/gui-client/src-tauri/src/client/debug_commands.rs]: It's in #5363 now

File: rust/connlib/tunnel/src/device_channel/tun_linux.rs [hunk 10]
```diff
@@ -31,7 +31,7 @@ const TUN_DEV_MINOR: u32 = 200;
 const TUN_FILE: &CStr = unsafe { CStr::from_bytes_with_nul_unchecked(b"/dev/net/tun\0") };
 
 #[derive(Debug)]
-pub struct Tun {
+pub(crate) struct Tun {
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_linux.rs:34]: Not related but I didn't want to make a whole PR just to remove one word

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 11]
```diff
@@ -24,48 +24,52 @@ use windows::Win32::{
...
+        if let Err(error) = self.session.shutdown() {
+            tracing::error!(?error, "wintun::Session::shutdown");
+        }
+        if let Some(recv_thread) = self.recv_thread.take() {
+            // We must join the worker thread here to prevent issue #4765
+            if let Err(error) = recv_thread.join() {
+                tracing::error!(?error, "Couldn't join `recv_thread`");
+            }
+        } else {
+            tracing::error!("No `recv_thread` in `Tun`");
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs]: we can just `self.recv_thread.take().unwrap().join();`  This should never fail and if it fails there's nothing we can do

**Review by conectado — APPROVED** [review]

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs (hunk 11 above)
Comment (ReactorScram) [reply rust/connlib/tunnel/src/device_channel/tun_windows.rs]: I want to at least log errors. I didn't read the docs close enough the first time, if `join` returns `Err` it's not that it didn't join, but that the worker thread panicked, and it returns the panic message. So I'll fix that and simplify the `if-let`
