### PR TITLE
chore(gui-client): fix papercuts

### LINKED ISSUE #5789: Tauri Client papercuts
1. Log architecture at startup, next to Git version (In case customers hit any arch-specific issues)
2. When printing the "User not in group" fatal error to stdout, also print the command that's shown in the dialog, so it's easy to copy-paste on dev / test systems
3. Add graceful shutdown message to IPC service at `INFO` level (So we can see if the IPC service crashes on any customer systems, e.g. #5790)
4. ~~If we have a problem calling `SetDns`, log the old and new DNS servers before crashing~~ (Can't do that on `INFO`, customer DNS resolvers might be private)

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5789 

The SIGTERM catching would have helped debug #5790 

```[tasklist]
### Tasks
- [x] catch SIGTERM and log when systemd shuts us down gracefully
- [x] Log architecture at startup
```

### CODE REVIEW

File: rust/headless-client/src/ipc_service/linux.rs [hunk 1]
```diff
@@ -10,10 +11,11 @@ pub(crate) fn run_ipc_service(cli: CliCommon) -> Result<()> {
...
     }
     let rt = tokio::runtime::Runtime::new()?;
-    if let Err(error) = rt.block_on(super::ipc_listen()) {
-        tracing::error!(?error, "`ipc_listen` failed");
-    }
-    Ok(())
+    let _guard = rt.enter();
+    let mut signals = Signals::new()?;
+
+    // Couldn't get the loop to work here yet, so SIGHUP is not implemented
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service/linux.rs]: Stale?

File: rust/headless-client/src/ipc_service.rs [hunk 2]
```diff
@@ -91,26 +91,41 @@ pub fn run_only_ipc_service() -> Result<()> {
...
+/// Run the IPC service, and exit if we catch any signals
+///
+/// Shared between the Linux systemd service and the debug subcommand
+/// TODO: Better name
+async fn ipc_listen_with_signals(signals: &mut Signals) -> Result<()> {
+    let ipc_service = pin!(ipc_listen());
+
+    match future::select(pin!(signals.recv()), ipc_service).await {
+        future::Either::Left((SignalKind::Hangup, _)) => {
+            bail!("Exiting, SIGHUP not implemented for the IPC service");
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs:115]: This is an artefact of reusing the `Signals` abstraction here. Even if it is a bit more code, I'd advocate against sharing code that doesn't properly fit all call-sites.

File: rust/headless-client/src/ipc_service.rs [hunk 3]
```diff
@@ -91,26 +91,41 @@ pub fn run_only_ipc_service() -> Result<()> {
...
+    tracing::info!(
+        arch = std::env::consts::ARCH,
+        git_version = crate::GIT_VERSION,
+        system_uptime_seconds = crate::uptime::get().map(|dur| dur.as_secs()),
+    );
     let rt = tokio::runtime::Runtime::new()?;
     let _guard = rt.enter();
     let mut signals = Signals::new()?;
 
     // Couldn't get the loop to work here yet, so SIGHUP is not implemented
```
Comment (thomaseizinger) [inline rust/headless-client/src/ipc_service.rs]: Stale?

File: rust/headless-client/src/ipc_service.rs (hunk 2 above)
Comment (thomaseizinger) [reply rust/headless-client/src/ipc_service.rs:115]: Or is this just a TODO to implement later?

**Review by thomaseizinger — APPROVED** [review]
Left some commets to think about but oberall LGTM :)
