### PR TITLE
fix(client): flush the OS' DNS cache whenever resources change

### LINKED ISSUE #5052: bug(client): adding service actor to group / enabling policy only takes effect after restarting the Client
#### Describe the bug

_A clear and concise description of what the bug is._

#### To Reproduce

By adding a service actor to a group:

1. Set up the Headless Client but don't put the service actor in any groups that have access to Resources
2. Run the Headless Client
3. Check IP with `ifconfig.net`, expect the computer's real IP address
4. Add the service actor to a group that has a Policy with access to `ifconfig.net`
5. Check IP a few more times, it still shows the computer's real IP address
6. Restart the Headless Client
7. Check IP again, it's instantly changed to the Gateway's IP

By enabling a policy:

1. Disable `ifconfig.net` policies for your actor
2. Start the Client
3. Run `curl -4 https://ifconfig.net/ip`, expect your real IP
4. Enable the policy
5. Run curl again, expect the gateway IP, it should fail

#### Expected behavior

Expected that the Gateway's IP should appear immediately after Step 4, and not need the Client to restart to take effect

#### Screenshots / Logs

None

#### Platform (please complete the following information)

Reproduces on:
- Linux GUI Client
- Linux Headless Client
- Windows Headless Client

May reproduce on:
- Windows GUI Client

Doesn't reproduce on:
- macOS Client

#### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5052

On my dev VMs:
- systemd-resolved = 15 ms to flush
- Windows = 600 ms to flush

I tested with the headless Clients on Linux and Windows and it fixes the issue. On Windows I didn't replicate the issue with the GUI Client, on Linux this patch also fixes it for the GUI Client.

### CODE REVIEW

File: rust/connlib/shared/src/tun_device_manager/linux.rs [hunk 1]
```diff
@@ -232,7 +232,7 @@ async fn add_route(route: &IpNetwork, idx: u32, handle: &Handle) -> Result<()> {
     Ok(())
 }
 
-async fn delete_route(route: &IpNetwork, idx: u32, handle: &Handle) -> Result<()> {
+async fn remove_route(route: &IpNetwork, idx: u32, handle: &Handle) -> Result<()> {
```
Comment (ReactorScram) [inline rust/connlib/shared/src/tun_device_manager/linux.rs:235]: Changed this name to be more consistent

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 2]
```diff
@@ -134,8 +134,6 @@ impl Tun {
             self.remove_route(*old_route)?;
         }
 
-        // TODO: Might be calling this more often than it needs
-        flush_dns().expect("Should be able to flush Windows' DNS cache");
```
Comment (ReactorScram) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs:138]: Moved this to `on_update_resources`. I'm assuming we always get a resource update at startup, so this would be redundant anyway, and moving it brings Linux and Windows closer into alignment.

File: rust/headless-client/src/standalone.rs [hunk 3]
```diff
@@ -192,7 +192,10 @@ pub fn run_only_headless_client() -> Result<()> {
                     }) => return Err(anyhow!(error_msg).context("Firezone disconnected")),
                     InternalServerMsg::Ipc(IpcServerMsg::Ok)
                     | InternalServerMsg::Ipc(IpcServerMsg::OnTunnelReady)
-                    | InternalServerMsg::Ipc(IpcServerMsg::OnUpdateResources(_)) => {}
+                    | InternalServerMsg::Ipc(IpcServerMsg::OnUpdateResources(_)) => {
+                        // On every resources update, flush DNS to mitigate <https://github.com/firezone/firezone/issues/5052>
+                        dns_controller.flush()?;
+                    }
```
Comment (ReactorScram) [inline rust/headless-client/src/standalone.rs:198]: The callback handler code here is duplicated between the IPC service and the headless Client. Since they do almost the same thing, we can probably refactor it someday so that they share the same main loop, and the only difference is that one listens for IPC events and one listens for in-process commands

**Comment by jamilbk** [comment]
I think this may also be the cause of #4834. Linking it here so we have a thread to investigate when we can tackle that issue. Unfortunately from preliminary Googling I don't know if we have a button to push there for Android.

Will need to test if this is also an issue on macOS / iOS but I don't think it is. I believe the OS either doesn't use a cache or flushes it for us.

**Comment by ReactorScram** [comment]
Yeah on macOS I did not get it to replicate. But that's strange because ChatGPT says macOS has a cache, and the fix in this PR is to flush when our resources change, which the OS shouldn't be aware of. So why _doesn't_ it happen on other OSes?

**Review by conectado — APPROVED** [review]
Nice work!

**Comment by jamilbk** [comment]
> Yeah on macOS I did not get it to replicate. But that's strange because ChatGPT says macOS has a cache, and the fix in this PR is to flush when our resources change, which the OS shouldn't be aware of. So why _doesn't_ it happen on other OSes?

It's possible macOS does not have a cache _before_ the DNS servers for VPN interfaces, to prevent this sort of issue. I assume Windows and Linux _do_ cache before queries reach the tunnel interface, and possibly Android too.
