### PR TITLE
chore(Portal): Remove simple forms, change navbar links, fix form styles

### LINKED ISSUE #2015: Allow users to switch between recently logged in accounts
Use Case: I'm a contractor and I need to be able to sign into different Firezone tenants throughout my workday

Solution: 
1. We need to display a drop-down showing recent logged-in accounts in the UI;
2. Session cookies should be scoped per path so that a user can be signed into multiple accounts at the same time reducing the size of cookies we store (so that we don't hit the max size limit).

Related PR that implements recent account IDs cookie: https://github.com/firezone/firezone/pull/1990

### LINKED ISSUE #4237: Remove use of `simple_form` component
There is no point in having two ways to build forms while we use `<.form` almost everywhere anyway.

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes #4237
Closes #2015

There are new links in the navbar and the floating status badge is replaced with a link in the burger menu too:

https://github.com/firezone/firezone/assets/1877644/2d72f6d7-a14a-4e56-808d-2e703eca158a

### CODE REVIEW

File: elixir/apps/web/lib/web/components/navigation_components.ex [hunk 1]
```diff
@@ -22,10 +22,7 @@ defmodule Web.NavigationComponents do
             <.icon name="hero-bars-3-center-left" class="w-6 h-6" />
             <span class="sr-only">Toggle sidebar</span>
           </button>
-          <a
-            href="https://www.firezone.dev/?utm_source=product"
-            class="flex items-center justify-between mr-4"
-          >
+          <a href={~p"/"} class="flex items-center justify-between mr-4">
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/components/navigation_components.ex:25]: @jamilbk I think there is no point in going to the website for a user who is already using the portal because the website is mostly about marketing/sales. The common practice for logo is to go to `/` on click and we get an additional benefit: it provides a poor man's account switch. If you have multiple accounts you can click on the logo and quickly jump between them.

File: elixir/apps/web/lib/web/live/sign_in.ex [hunk 2]
```diff
@@ -109,9 +109,13 @@ defmodule Web.SignIn do
         <div :if={Web.Auth.fetch_auth_context_type!(@params) == :browser} class="mx-auto p-6 sm:p-8">
           <p class="py-2">
             Meant to sign in from a client instead?
-            <.website_link href="/kb/user-guides">
-              Read the docs.
-            </.website_link>
+            <.website_link href="/kb/user-guides">Read the docs.</.website_link>
+          </p>
+          <p class="py-2">
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/live/sign_in.ex:114]: This is also added for navigation consistency, it's only shown on admin sessions and never on clients.

File: elixir/apps/web/lib/web/components/navigation_components.ex (hunk 1 above)
Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex:25]: Do we have any other way for them to get to Docs, Support, or the Contact forms website that's easily accessible? This might be the only place.

I think we maybe want to leave this link as-is since those use cases are probably more common than switching accounts (I don't think anyone belongs to more than one account?).

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex:25]: That'll require some more styling work. I think this is OK for now.

File: elixir/apps/web/lib/web/components/navigation_components.ex [hunk 3]
```diff
@@ -22,17 +22,28 @@ defmodule Web.NavigationComponents do
...
             <span class="self-center text-2xl font-medium whitespace-nowrap">
               Firezone
             </span>
           </a>
         </div>
         <div class="flex items-center lg:order-2">
+          <a
+            href="https://www.firezone.dev/kb?utm_source=product"
+            class="mr-6 mt-1 text-neutral-700 hover:text-neutral-900 md:ml-2 hidden md:block"
+          >
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/components/navigation_components.ex]: What do you think about adding a `target="_blank"` in this `a` tag?

**Review by jamilbk — COMMENTED** [review]
Agree with @bmanifold about the `target = "_blank"` otherwise LGTM!

File: elixir/apps/web/lib/web/components/navigation_components.ex (hunk 3 above)
Comment (AndrewDryga) [reply elixir/apps/web/lib/web/components/navigation_components.ex]: @bmanifold thanks for catching this! I totally forgot to add those.
