### PR TITLE
fix(rust/client/windows): set our DNS resolvers on our interface

### LINKED ISSUE #6777: Issues connecting to resources from within WSL
Customer reports issues connecting to resources from within the WSL environment on Windows.

- [x] Investigate connecting to IP/CIDR resources from within WSL
- [x] Investigate connecting to DNS resources from within WSL

```[tasklist]
- [ ] Figure out how WSL generates resolv.conf and fix it
- [ ] Add our resolver to our tunnel interface
```

Hypotheses:

- DNS tunneling might be off in WSL? - No, Windows docs indicate it's on by default https://learn.microsoft.com/en-us/windows/wsl/troubleshooting
- Our DNS resolvers are not set to our interface? - Yes

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #6777

### CODE REVIEW

File: rust/headless-client/src/lib.rs
Comment (ReactorScram) [inline rust/headless-client/src/lib.rs:1]: Removed unit tests here that only covered `clap`'s behavior and not our code

**Comment by ReactorScram** [comment]
I couldn't get the IPv6 part to work on my dev system, maybe because I don't have IPv6 on this network.

It works in CI and it should be harmless even if IPv6 doesn't work. I can test IPv6 when I'm back home Monday.

File: rust/headless-client/src/dns_control/windows.rs [hunk 1]
```diff
@@ -140,6 +135,45 @@ fn activate(dns_config: &[IpAddr]) -> Result<()> {
...
+/// Sets our DNS servers in the registry so `ipconfig` and WSL will notice them
+/// Fixes #6777
+fn set_nameservers_on_interface(dns_config: &[IpAddr]) -> Result<()> {
+    let hklm = winreg::RegKey::predef(winreg::enums::HKEY_LOCAL_MACHINE);
+
+    let services_path = Path::new(r"SYSTEM\CurrentControlSet\Services");
+    let interface_path = Path::new(r"Parameters\Interfaces").join(format!("{{{TUNNEL_UUID}}}"));
+
+    let key = hklm.open_subkey_with_flags(
+        services_path
```
Comment (thomaseizinger) [inline rust/headless-client/src/dns_control/windows.rs]: I'd suggest to make both of the entire IPv4 and IPv6 paths string templates, even if that duplicates parts of them. It can be helpful if these things are "greppable" and dynamically building them prevents that.

Comment (thomaseizinger) [reply rust/headless-client/src/dns_control/windows.rs]: I think in this case, it should also result in a lot less code because we only need to define two paths and can straight open them?

File: rust/headless-client/src/dns_control/windows.rs [hunk 2]
```diff
@@ -140,6 +135,45 @@ fn activate(dns_config: &[IpAddr]) -> Result<()> {
...
+
+    Ok(())
+}
+
+// e.g. [100.100.111.1, 100.100.111.2] -> "100.100.111.1;100.100.111.2"
+fn concat_ips<'a, I: IntoIterator<Item = &'a IpAddr>>(iter: I) -> String {
+    iter.into_iter()
+        .map(|ip| ip.to_string())
+        .collect::<Vec<_>>()
+        .join(";")
```
Comment (thomaseizinger) [inline rust/headless-client/src/dns_control/windows.rs]: I think `Itertools` has a `join` that directly works on anything that is `fmt::Display`able.

File: rust/headless-client/src/dns_control/windows.rs [hunk 3]
```diff
@@ -171,3 +205,66 @@ fn set_nrpt_rule(key: &winreg::RegKey, dns_config_string: &str) -> Result<()> {
...
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use std::collections::BTreeSet;
+
+    // Passes in CI but not locally. Maybe ReactorScram's dev system has IPv6 misconfigured. There it fails to pick up the IPv6 DNS servers.
+    #[ignore = "Needs admin, changes system state"]
+    #[test]
+    fn dns_control() {
```
Comment (thomaseizinger) [inline rust/headless-client/src/dns_control/windows.rs:209]: Nice one!

File: rust/headless-client/src/dns_control/windows.rs [hunk 4]
```diff
@@ -171,3 +205,66 @@ fn set_nrpt_rule(key: &winreg::RegKey, dns_config_string: &str) -> Result<()> {
...
+                .await
+        })
+        .unwrap();
+
+        let mut dns_controller = DnsController {
+            dns_control_method: DnsControlMethod::Nrpt,
+        };
+
+        let fz_dns_servers = vec![
+            [100, 100, 111, 1].into(),
```
Comment (thomaseizinger) [inline rust/headless-client/src/dns_control/windows.rs]: Nit: I think this would be a tad more readable if it used `IpAddr::from`.

**Review by thomaseizinger — APPROVED** [review]
Nice work!
