### PR TITLE
fix(windows): add routes faster

### LINKED ISSUE #3114: fix(windows): add_route is slow
Shelling out to ~~netsh~~ Powershell's New-NetRoute is slow.

### PR DESCRIPTION
**Pull request by ReactorScram**
This will fix #3114 and save about 13 seconds at startup, compared to shelling out to Powershell.

~~I'm not 100% sure it works for IPv6 routes - I'm setting port, flowinfo, and scope to 0 and just assuming that it's fine.~~

(I went back and tested IPv6 and it's fine. See comments below)

For some reason Windows wants a socket address in this API even though I don't think the port is used for anything.

### CODE REVIEW

File: rust/connlib/tunnel/src/device_channel/tun_windows.rs [hunk 1]
```diff
@@ -127,16 +130,28 @@ impl Tun {
...
+        let prefix = &mut row.DestinationPrefix;
+        match route {
+            IpNetwork::V4(x) => {
+                prefix.PrefixLength = x.netmask();
+                prefix.Prefix.Ipv4 = SocketAddrV4::new(x.network_address(), 0).into();
+            }
+            IpNetwork::V6(x) => {
+                prefix.PrefixLength = x.netmask();
+                prefix.Prefix.Ipv6 = SocketAddrV6::new(x.network_address(), 0, 0, 0).into();
+                tracing::warn!("ipv6 not implemented right here yet");
```
Comment (conectado) [inline rust/connlib/tunnel/src/device_channel/tun_windows.rs]: Does this means that this PR will break ipv6 routes right now?

I'd wait for the fix before merging

Comment (ReactorScram) [reply rust/connlib/tunnel/src/device_channel/tun_windows.rs]: actually I haven't been testing IPv6, it doesn't even work on main right now - #3119 

So it's not a regression per se but I'll ~~see if it's easy to fix in this PR at the same time.~~ fix it in another PR and block this one on that

Comment (ReactorScram) [reply rust/connlib/tunnel/src/device_channel/tun_windows.rs]: #3120 has a proposed fix for IPv6 on Windows
~~They don't have any conflict so this could go ahead with broken IPv6, or it could wait on the fix.~~

This should wait for #3120 since I can't prove the new add_route for IPv6 works if IPv6 doesn't work at all

Comment (ReactorScram) [reply rust/connlib/tunnel/src/device_channel/tun_windows.rs]: I tested with `curl --ipv6 -v https://ifconfig.net/ip` and it works. The IP address curl connects to, and the IP address ifconfig.net shows for me, both differ when the tunnel is up. So I removed this warning

**Comment by ReactorScram** [comment]
Changed it just now to also ignore errors caused by duplicate routes. I'm getting `172.16.0.0/24` twice and Windows throws an error the 2nd time.

**Review by jamilbk — APPROVED** [review]
lgtm
