### PR TITLE
fix(android): prevent null pointer segfault on 32-bit platforms

### LINKED ISSUE #3637: Segfault on Android when reading interface name
Getting a SEGV_MAPERR (signal 11) on 32-bit Android when reading the interface name that we set with ioctl.

### PR DESCRIPTION
**Pull request by jamilbk**
Without this alignment, accessing the `name` field reliably produces a segfault:

```
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1d in tid 13835 (Thread-7), pid 13757 (irezone.android)
```

Interestingly, this only happens in release builds on 32-bit platforms. Logging the returned name fixes it too which hints at some kind of optimisation issue. Adding a padding is the most reliable fix.

Fixes: #3637.

### CODE REVIEW

File: rust/connlib/tunnel/src/device_channel/tun_android.rs [hunk 1]
```diff
@@ -100,16 +100,15 @@ impl ioctl::Request<GetInterfaceNamePayload> {
...
-
-        cstr.to_string_lossy()
+        String.from_utf8_lossy(&self.name)
     }
 }
 
 #[derive(Default)]
 #[repr(C)]
-struct GetInterfaceNamePayload;
+struct GetInterfaceNamePayload {
```
Comment (jamilbk) [inline rust/connlib/tunnel/src/device_channel/tun_android.rs:112]: I could very well be wrong, but I think what may have been happening here is that the `name` field was being optimized out due to a potential compiler bug for the 32-bit android targets.

For a `Request<GetInterfaceNamePayload>`, the ioctl writes the ifname back into the `name` field of the request, unlike the `GetInterfaceMTUPayload` in `device_channel.rs` where it's written into the `payload` field. `Request` has `repr(C)` on it and the appropriate fields defined, but perhaps the struct layout of the `GetInterfaceNamePayload` type was taking precedence.

So the `ioctl` writes the ifname into a squashed struct and `self.name` points to an invalid memory address, causing the `SEGV_MAPERR`.

Another way to test this fix is to remove the `GetInterfaceNamePayload>` type and use a plain `Request`.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs [hunk 2]
```diff
@@ -100,16 +100,15 @@ impl ioctl::Request<GetInterfaceNamePayload> {
...
-        cstr.to_string_lossy()
+        String::from_utf8_lossy(&self.name)
     }
 }
 
 #[derive(Default)]
 #[repr(C)]
-struct GetInterfaceNamePayload;
+struct GetInterfaceNamePayload {
+    name: [u8; libc::IF_NAMESIZE],
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/tun_android.rs]: I think it is very unlikely that this fixes the bug because you are not using this field. You'd have to access it via `self.payload.name`.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs [hunk 3]
```diff
@@ -100,16 +100,15 @@ impl ioctl::Request<GetInterfaceNamePayload> {
     }
 
     fn name(&self) -> std::borrow::Cow<'_, str> {
-        // Safety: The memory of `self.name` is always initialized.
-        let cstr = unsafe { std::ffi::CStr::from_ptr(self.name.as_ptr() as _) };
-
-        cstr.to_string_lossy()
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/tun_android.rs]: Very likely, there is something wrong with our unsafe code here. Given that there is a non-unsafe version, we should probably just do that.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs (hunk 1 above)
Comment (thomaseizinger) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs:112]: > So the `ioctl` writes the ifname into a squashed struct and `self.name` points to an invalid memory address, causing the `SEGV_MAPERR`.

The idea of using `repr(C)` is that the structs are indeed "squashed". In other words, it is important that `name` is defined first and then the fields of `payload` in the order they are defined as. `GetInterfaceMtuPayload` adds an additional `mtu` field to it  for example.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs (hunk 3 above)
Comment (thomaseizinger) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: I guess what might be wrong is that the buffer is not always 0-terminated? In that case, we will read beyond array length and read invalid memory. See https://doc.rust-lang.org/std/ffi/struct.CStr.html#safety.

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
I think just removing the `unsafe` code should also fix this.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs (hunk 3 above)
Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: That's what @conectado suspected too, but we tried all variants of the CStr functions with no luck, including the non-unsafe alternatives.

Strangely, the struct change here was the most reliable "fix" I found. I sent it for testing with a user so we can see what he reports.

There have been a few cases of compiler bugs for android in the past, so maybe it's that?

Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: See thread https://github.com/firezone/firezone/pull/3583#discussion_r1484198263

Comment (thomaseizinger) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: > That's what @conectado suspected too, but we tried all variants of the CStr functions with no luck, including the non-unsafe alternatives.

In this patch, you are not using the `CStr` functions though but `String::from_utf8_lossy(&self.name)`. Are you saying that using `String::from_utf8_lossy(&self.name)` by itself does **not** fix the issue?

File: rust/connlib/tunnel/src/device_channel/tun_android.rs (hunk 2 above)
Comment (thomaseizinger) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: If this actually fixes it, can you log how long the interface name is once it is retrieved?

Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: It's only 4 characters, flops between `tun0` and `tun1` as we rebuild the VpnService.

It's true that when this happens, the interface name is not null terminated -- but it's not anywhere in the name field. Reading that field causes the segfault.

IIRC The TUNGETIFF ioctl writes the interface name into the request parameter, not the payload (which is blank), unlike the mtu ioctl.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs (hunk 3 above)
Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: Indeed, it does not. The problem is I believe that the memory that self.name references isn't valid anymore by the time the function returns, or gets "cleaned up" from the heap.

- does not happen in `debug`
- does not happen if we trace logs near the call
- does not happen on other targets just 32-bit android

Feels like a compiler bug being too eager to optimize heap utilization

Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: Let's pair today after standup on this if you're available

Comment (jamilbk) [reply rust/connlib/tunnel/src/device_channel/tun_android.rs]: User reported the crash is fixed with this build. It's a gnarly one for sure.

File: rust/connlib/tunnel/src/device_channel/tun_android.rs [hunk 4]
```diff
@@ -109,7 +109,12 @@ impl ioctl::Request<GetInterfaceNamePayload> {
 
 #[derive(Default)]
 #[repr(C)]
-struct GetInterfaceNamePayload;
+struct GetInterfaceNamePayload {
+    // Fixes a nasty alignment bug on 32-bit architectures on Android.
+    // Essentially, the compiler will optimize out the `name` field in the Request struct
+    // if the ioctl payload is not aligned to 32 bytes.
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/tun_android.rs]:
```suggestion
    // The `name` field in `ioctl::Request` is only 16 bytes long and accessing it causes a NPE without this alignment.
    // Why? Not sure. It seems to only happen in release mode which hints at an optimisation issue.
```

**Review by thomaseizinger — APPROVED** [review]
Just a minor suggestion to the wording.
