### PR TITLE
fix(portal): Fix Resource show error on API created Resource

### LINKED ISSUE #6267: Viewing a resource after creating connection via API causes View crash
From the logs:
```
"** (FunctionClauseError) no function clause matching in Web.CoreComponents."created_by (overridable 1)"/1
    (web 0.1.0+deadbeef) lib/web/components/core_components.ex:901:in `Web.CoreComponents."created_by (overridable 1)"(%{schema: ...
    (phoenix_live_view 1.0.0-rc.5) lib/phoenix_live_view/tag_engine.ex:92:in `Phoenix.LiveView.TagEngine.component/3'
    (web 0.1.0+deadbeef) lib/web/live/resources/show.ex:172:in `anonymous fn/2 in Web.Resources.Show.render/1'
    (phoenix_live_view 1.0.0-rc.5) lib/phoenix_live_view/diff.ex:391:in `Phoenix.LiveView.Diff.traverse/7'
    (phoenix_live_view 1.0.0-rc.5) lib/phoenix_live_view/diff.ex:532:in `anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7'
    (elixir 1.17.1) lib/enum.ex
```

### PR DESCRIPTION
**Pull request by bmanifold**
Viewing a Resource created by an API client was crashing the view due to the function creating the link to the actor not accounting for the API client case.

Closes #6267

### CODE REVIEW

**Review by AndrewDryga — APPROVED** [review]

File: elixir/apps/web/lib/web/components/core_components.ex [hunk 1]
```diff
@@ -928,6 +935,28 @@ defmodule Web.CoreComponents do
     """
   end
 
+  attr :account, :any, required: true
+  attr :actor, :any, required: true
+
+  def actor_link(%{actor: %Domain.Actors.Actor{type: :api_client}} = assigns) do
+    ~H"""
+    <.link
+      class="text-accent-500 hover:underline"
```
Comment (jamilbk) [inline elixir/apps/web/lib/web/components/core_components.ex]: curious why `link_style()` isn't used here?

**Review by jamilbk — APPROVED** [review]
Left a non-blocking comment re: link_style

File: elixir/apps/web/lib/web/components/core_components.ex (hunk 1 above)
Comment (bmanifold) [reply elixir/apps/web/lib/web/components/core_components.ex]: It should be.  I wasn't paying attention to the class, just copy/pasted what was previously being used.  I'll update it.

Comment (bmanifold) [reply elixir/apps/web/lib/web/components/core_components.ex]: Updated
