### PR TITLE
connlib+android: enable fd replacement

### LINKED ISSUE #2227: Android segfault when reading from `fd` in deep call stack
Opening an issue to track work.

From @conectado's findings:

> So a bit of a summary on the segfault I'm finding, so, this function:
```
    #[tracing::instrument(level = "trace", skip(self, iface_config, device_io))]
    async fn iface_handler(
        self: &Arc<Self>,
        iface_config: Arc<IfaceConfig>,
        device_io: DeviceIo,
    ) -> std::io::Result<()> {
        let mut src = [0u8; MAX_UDP_SIZE];
        let mut dst = [0u8; MAX_UDP_SIZE];
        device_io.read(&mut src[..iface_config.mtu()]).await;
        tracing::trace!(?dst);
        Ok(())
    }
```
> segfaults with SEGV_ACCERR  (Note that this is simplified to have some minimal repro of the bug, this doesn't work)
> This is called from:
```
    #[tracing::instrument(level = "trace", skip(self))]
    pub(crate) async fn start_iface_handler(self: &Arc<Self>) {
        let Some(device_io) = self.device_io.read().clone() else {
            let err = Error::NoIface;
            tracing::error!(?err);
            let _ = self.callbacks().on_disconnect(Some(&err));
            return;
        };
        let Some(iface_config) = self.iface_config.read().clone() else {
            let err = Error::NoIface;
            tracing::error!(?err);
            let _ = self.callbacks().on_disconnect(Some(&err));
            return;
        };
        let device_writer = device_io.clone();
        self.iface_handler(iface_config, device_io).await;
    }
```
> And device_io.read works as:
```
    pub async fn read(&self, out: &mut [u8]) -> std::io::Result<usize> {
        self.0
            .async_io(Interest::READABLE, |inner| inner.read(out))
            .await
    }
```
> With inner.read being:
```
    pub fn read(&self, dst: &mut [u8]) -> std::io::Result<usize> {
        match unsafe { read(self.fd, dst.as_mut_ptr() as _, dst.len()) } {
            -1 => Err(io::Error::last_os_error()),
            n => Ok(n as usize),
        }
    }
```
> Buuut... if I reduce the size of the buffer of src and dst to 1500 , it doesn't crash
> If I inline, manually, iface_handler into start_iface_handler it doesn't crash, (but if I use #[inline(always)] it does)
> if I redefine iface_handler to:
```
    #[tracing::instrument(level = "trace", skip(self, iface_config, device_io))]
    async fn iface_handler(
        self: &Arc<Self>,
        iface_config: Arc<IfaceConfig>,
        device_io: DeviceIo,
    ) -> std::io::Result<()> {
        let mut src = [0u8; MAX_UDP_SIZE];
        device_io.read(&mut src[..iface_config.mtu()]).await;
        let mut dst = [0u8; MAX_UDP_SIZE];
        tracing::trace!(?dst);
        Ok(())
    }
```
> It doesn't crash
> and right now, I think the last one is the biggest clue. I'll start using objdump/gdb to figure out what's happening

### PR DESCRIPTION
**Pull request by conectado**
Should be easier to review commit by commit.

The gist of this commit is:
* `onAddRoute` on Android now takes an address+prefix as to minimize parsing
* `onAddRoute` recreates the vpn service each time(TODO: is this too bad for performance?)
* `on_add_route` and `onAddRoute` returns the new fd
* on android after `on_add_route` we recreate `IfaceConfig` and `DeviceIo` and we store the new values
*  `peer_handler` now runs on a loop, where each time we fail a write with an error code 9(bad descriptor) we try to take the new `DeviceIo`
* we keep an [`AbortHandle`](https://docs.rs/tokio/latest/tokio/task/struct.AbortHandle.html) from the `iface_handler` task, since closing the fd doesn't awake the `read` task for `AsyncFd`(I tried it, right now `close` is only called after dropping the fd) so we explicitly abort the task and start a new one with the new `device_io`.
* in android `DeviceIo` has an atomic which tells if it's closed or open and we change it to closed after `on_add_route`, we use this as to never double-close the fd, instead we wait until it's dropped. This *might* affect performance on android since we use non-`Ordering::Relaxed` atomic operation each read/write but it won't affect perfromance in other platforms, furthermore I believe the performance gains if we remove this will be minimal.

Fixes #2227

### CODE REVIEW

File: rust/connlib/libs/tunnel/src/iface_handler.rs [hunk 1]
```diff
@@ -164,35 +164,51 @@ where
...
+            };
+            if let Err(err) = self.iface_handler(iface_config, device_io).await {
+                if err.raw_os_error() != Some(9) {
+                    tracing::error!(?err);
+                    let _ = self.callbacks().on_error(&err.into());
+                    break;
+                } else {
+                    tracing::warn!("bad_file_descriptor");
+                }
+            }
```
Comment (thomaseizinger) [inline rust/connlib/libs/tunnel/src/iface_handler.rs]: We seem to have this pattern a lot where we have some control flow but we can't use `?` or other idiomatic Rust things like `ok_or` combinators because we want to log the error if it fails.

Have you considered introducing a helper function that takes a reference to `callbacks` and a `Future` that returns `Result` and spawns it, logging the error on failure?

That could allow you to write this loop in a much more idiomatic way and move the cross-cutting concern of logging away.

File: rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs [hunk 2]
```diff
@@ -67,9 +71,13 @@ impl Drop for IfaceStream {
...
-        match unsafe { write(self.fd, buf.as_ptr() as _, buf.len() as _) } {
-            -1 => Err(io::Error::last_os_error()),
-            n => Ok(n as usize),
+        if !self.closed.load(Ordering::Acquire) {
+            match unsafe { write(self.fd, buf.as_ptr() as _, buf.len() as _) } {
+                -1 => Err(io::Error::last_os_error()),
+                n => Ok(n as usize),
+            }
+        } else {
+            Err(std::io::Error::from_raw_os_error(9))
```
Comment (thomaseizinger) [inline rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs]: Nit: Prefer early-return of the error case:

```rust
        if self.closed.load(Ordering::Acquire) {
            return Err(std::io::Error::from_raw_os_error(9));
        }

        match unsafe { write(self.fd, buf.as_ptr() as _, buf.len() as _) } {
            -1 => Err(io::Error::last_os_error()),
            n => Ok(n as usize),
        }
            
```

File: rust/connlib/libs/tunnel/src/iface_handler.rs [hunk 3]
```diff
@@ -139,7 +139,7 @@ where
         if let Some(r) = self.check_for_dns(src) {
             match r {
                 dns::SendPacket::Ipv4(r) => device_writer.write4(&r[..])?,
-                dns::SendPacket::Ipv6(r) => device_writer.write4(&r[..])?,
```
Comment (thomaseizinger) [inline rust/connlib/libs/tunnel/src/iface_handler.rs]: Nice catch :D

File: rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs [hunk 4]
```diff
@@ -90,6 +90,8 @@ impl IfaceStream {
     }
 
     pub fn read(&self, dst: &mut [u8]) -> std::io::Result<usize> {
+        // We don't read(or write) again from the fd because the given fd number might be reclaimed
+        // so this could make an spurious read/write to another fd and we DEFINETLY don't want that
```
Comment (thomaseizinger) [inline rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs]: I think it would make sense to build an abstraction here that only gives you access to the `fd` in a closure after checking that it is no closed. That would reduce this repeated checking down to a single function.

File: rust/connlib/libs/tunnel/src/iface_handler.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/libs/tunnel/src/iface_handler.rs]: I like this idea, this loop in particular was discarded in a later commit but `iface_handler` and `peer_handler` have this problem along with other timer related loops.

I'll make this on a separate PR to keep this one focused: #2241

**Review by jamilbk — CHANGES_REQUESTED** [review]
To fix the kotlin lint issues run

`./gradlew spotlessApply` from kotlin/android

Looks like there's a windows-2022 build issue also 🙃

**Review by jamilbk — APPROVED** [review]

**Review by jamilbk — COMMENTED** [review]
Approved the onAddRoute functionality -- building a new VpnService should be fairly quick until we have orgs that are bulk changing resources (e..g REST API). But ok for now.

Will defer to @thomaseizinger for final approval on the refactoring stuff

**Review by pratikvelani — APPROVED** [review]

**Comment by jamilbk** [comment]
Updating base to latest main to run newer CI

File: rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs (hunk 4 above)
Comment (conectado) [reply rust/connlib/libs/tunnel/src/device_channel/tun/tun_android.rs]: See what you think of [this](https://github.com/firezone/firezone/pull/2235/commits/dde50bcad3907be055cd266f6c25eec2be8c90ba) I like how it works but I'm unsure since the abstraction is leaky since I still need `AsRawFd` to work.

File: rust/connlib/clients/android/src/lib.rs [hunk 5]
```diff
@@ -195,27 +195,30 @@ impl Callbacks for CallbackHandler {
...
                 &self.callback_handler,
-                "onAddRoute",
-                "(Ljava/lang/String;)V",
-                &[JValue::from(&route)],
+                name,
+                "(Ljava/lang/String;I)I",
+                &[JValue::from(&ip), JValue::Int(route.netmask().into())],
             )
+            .and_then(|val| val.i())
+            .map_err(|source| CallbackError::CallMethodFailed { name, source })
```
Comment (thomaseizinger) [inline rust/connlib/clients/android/src/lib.rs]: If you do `map_err` first, you can use `?` and avoid the use of the `and_then` combinator in favor of just linear function execution.

File: rust/connlib/clients/android/src/lib.rs [hunk 6]
```diff
@@ -301,7 +304,7 @@ impl Callbacks for CallbackHandler {
 fn throw(env: &mut JNIEnv, class: &str, msg: impl Into<JNIString>) {
     if let Err(err) = env.throw_new(class, msg) {
         // We can't panic, since unwinding across the FFI boundary is UB...
-        tracing::error!("failed to throw Java exception: {err}");
+        tracing::error!(?err, "failed to throw Java exception");
```
Comment (thomaseizinger) [inline rust/connlib/clients/android/src/lib.rs:309]: Doesn't need to be solved in this PR but debug-logging errors doesn't actually give us a whole lot because it only shows the error representation and not the actual messages. I'd say we either display format them or, if it is an anyhow error do it via `:#` which gives you a nice run-down of all causes: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations

Unfortunately, `tracing` doesn't support the `#` modifier yet (see https://github.com/tokio-rs/tracing/issues/1311) so it would have to look something like:

```suggestion
        tracing::error!("failed to throw Java exception: {:#}", anyhow::Error::new(err));
```

or


```suggestion
        tracing::error!("failed to throw Java exception: {err:#}");
```

if it is already an `anyhow::Error`.

File: rust/connlib/clients/apple/src/lib.rs [hunk 7]
```diff
@@ -104,9 +104,9 @@ impl Callbacks for CallbackHandler {
         Ok(())
     }
 
-    fn on_add_route(&self, route: IpNetwork) -> Result<(), Self::Error> {
+    fn on_add_route(&self, route: IpNetwork) -> Result<RawFd, Self::Error> {
         self.inner.on_add_route(route.to_string());
-        Ok(())
+        Ok(-1)
```
Comment (thomaseizinger) [inline rust/connlib/clients/apple/src/lib.rs]: If this is on purpose, we should leave a comment here explaining why we return `-1` here.

File: rust/connlib/clients/shared/src/lib.rs [hunk 8]
```diff
@@ -79,6 +79,7 @@ where
             callbacks,
         };
         let runtime = tokio::runtime::Builder::new_multi_thread()
+            .thread_stack_size(3 * 1024 * 1024)
```
Comment (thomaseizinger) [inline rust/connlib/clients/shared/src/lib.rs:85]: Comment explaining this would be great.

File: rust/connlib/tunnel/src/control_protocol/gateway.rs [hunk 9]
```diff
@@ -96,7 +96,8 @@ where
                     tracing::trace!("new_data_channel_open");
                     Box::pin(async move {
                         {
-                            let Some(iface_config) = tunnel.iface_config.read().clone() else {
+                            let Some(iface_config) = tunnel.iface_config.read().await.clone()
+                            else {
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/control_protocol/gateway.rs]: What is this weird formatting? Does `rustfmt` do this?

File: rust/connlib/tunnel/src/device_channel/device_channel_unix.rs [hunk 10]
```diff
@@ -53,8 +53,18 @@ impl IfaceConfig {
...
+            let device_io = DeviceIo(stream);
+            let mtu = iface.mtu().await?;
+            let iface_config = IfaceConfig {
+                iface,
+                mtu: AtomicUsize::new(mtu),
+            };
+            Ok(Some((iface_config, device_io)))
+        } else {
+            Ok(None)
+        }
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/device_channel_unix.rs]: Perhaps use `let else` here to reduce indentation of the happy path.

File: rust/connlib/tunnel/src/device_channel/tun/closeable.rs [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+    value: T,
+}
+
+impl<T: AsRawFd> AsRawFd for Closeable<T> {
+    fn as_raw_fd(&self) -> RawFd {
+        self.value.as_raw_fd()
+    }
+}
+
+impl<T: Copy> Closeable<T> {
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/tun/closeable.rs]: Why enforce `Copy` here? I'd suggest you pass a reference to `f` instead and if the caller constructed `Closeable` with a type that is copy, they can always move out of it themselves. Or make the type not generic in the first place if we only ever use it with a single one (haven't checked).

File: rust/connlib/tunnel/src/device_channel/tun/tun_android.rs [hunk 12]
```diff
@@ -50,24 +52,27 @@ pub(crate) struct IfaceDevice(Arc<AsyncFd<IfaceStream>>);
...
+        unsafe { close(self.fd.as_raw_fd()) };
     }
 }
 
 impl IfaceStream {
     fn write(&self, buf: &[u8]) -> std::io::Result<usize> {
-        match unsafe { write(self.fd, buf.as_ptr() as _, buf.len() as _) } {
+        match self
+            .fd
+            .with(|fd| unsafe { write(fd, buf.as_ptr() as _, buf.len() as _) })?
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/device_channel/tun/tun_android.rs:74]: It would be great to have `SAFETY` comments on here.

File: rust/connlib/tunnel/src/iface_handler.rs [hunk 13]
```diff
@@ -168,31 +168,23 @@ where
...
-                        continue;
-                    }
-                }
-            };
+            let res = device_io.read(&mut src[..iface_config.mtu()]).await?;
+            if res == 0 {
+                return Ok(());
+            }
 
             tracing::trace!(target: "wire", action = "read", bytes = res, from = "iface");
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/iface_handler.rs]: Perhaps this should be _before_ the early exit on `0` to also capture that in the logs?

File: rust/connlib/tunnel/src/iface_handler.rs [hunk 14]
```diff
@@ -168,31 +168,23 @@ where
...
-            // TODO
-            let _ = self
+            if let Err(Error::Io(e)) = self
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/iface_handler.rs]: So any non `io::Error` is just slightly discarded? Seems a bit odd.

File: rust/connlib/tunnel/src/lib.rs [hunk 15]
```diff
@@ -337,16 +361,18 @@ where
...
         let (iface_config, device_io) = create_iface(config, self.callbacks()).await?;
-        iface_config
-            .add_route(DNS_SENTINEL.into(), self.callbacks())
-            .await?;
         let iface_config = Arc::new(iface_config);
 
-        *self.device_io.write() = Some(device_io.clone());
-        *self.iface_config.write() = Some(Arc::clone(&iface_config));
-        self.start_timers()?;
+        *self.device_io.write().await = Some(device_io.clone());
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/lib.rs]: Damn, took me a while understand what is happening here.

File: rust/connlib/tunnel/src/lib.rs [hunk 16]
```diff
@@ -295,23 +296,46 @@ where
...
             ice_candidate_queue,
             callbacks: CallbackErrorFacade(callbacks),
+            iface_handler_abort,
         })
     }
 
+    #[tracing::instrument(level = "trace", skip(self))]
+    pub async fn add_route(self: &Arc<Self>, route: IpNetwork) -> Result<()> {
+        let mut device_io = self.device_io.write().await;
+        let mut iface_config = self.iface_config.write().await;
```
Comment (thomaseizinger) [inline rust/connlib/tunnel/src/lib.rs]: If we do these two in the wrong order anywhere, we might run into a deadlock. Can't we combine them into one structure?

**Review by thomaseizinger — APPROVED** [review]
Left a few more comments, nothing blocking :)

File: rust/connlib/clients/android/src/lib.rs (hunk 6 above)
Comment (conectado) [reply rust/connlib/clients/android/src/lib.rs:309]: Then I'd also like to keep the `err` part, since that would be easier to filter by error type, so what do you think of something like:

```rs
tracing::error!(?err, "failed to throw Java exception: {err:#}");
```
?

File: rust/connlib/clients/android/src/lib.rs (hunk 5 above)
Comment (conectado) [reply rust/connlib/clients/android/src/lib.rs]: After calling `i()` we still want to map that error to `CallMethodFailed` since we don't implement `From` `jni`'s `Error` (it needs more context information so we can't trivially implement it), so it'd be quite more verbose if we don't use `and_then` having to call `map_err` twice.

File: rust/connlib/tunnel/src/control_protocol/gateway.rs (hunk 9 above)
Comment (conectado) [reply rust/connlib/tunnel/src/control_protocol/gateway.rs]: ~~*sigh* rustfmt doesn't get along with `let..else` yet and I'm used to depend on that for my indentation.~~ my bad, rustfmt indeed does this.

File: rust/connlib/tunnel/src/device_channel/tun/tun_android.rs (hunk 12 above)
Comment (conectado) [reply rust/connlib/tunnel/src/device_channel/tun/tun_android.rs:74]: I'll create an issue to add the missing `SAFETY` to all `unsafe`.

File: rust/connlib/tunnel/src/iface_handler.rs (hunk 14 above)
Comment (conectado) [reply rust/connlib/tunnel/src/iface_handler.rs]: My bad, left over of a previous approach

File: rust/connlib/clients/apple/src/lib.rs (hunk 7 above)
Comment (conectado) [reply rust/connlib/clients/apple/src/lib.rs]: Changed to use `Option` and added comment on the trait.

File: rust/connlib/tunnel/src/device_channel/tun/tun_android.rs (hunk 12 above)
Comment (conectado) [reply rust/connlib/tunnel/src/device_channel/tun/tun_android.rs:74]: #2277

File: rust/connlib/clients/android/src/lib.rs (hunk 5 above)
Comment (thomaseizinger) [reply rust/connlib/clients/android/src/lib.rs]: Ah damn.

File: rust/connlib/clients/android/src/lib.rs (hunk 6 above)
Comment (thomaseizinger) [reply rust/connlib/clients/android/src/lib.rs:309]: We could create our own error wrapper:

```rust
struct ErrorWithSources {
	inner: anyhow::Error
}

impl fmt::Display for ErrorWithSources {
	// always forward using alternate modifier
}

fn err_with_sources(err: impl std::error::Error) -> ErrorWithSources { }
```

And then use that as:

```rust
tracing::error!(err = %err_with_sources(err), "failed to throw Java exception");
```
