### PR TITLE
Sync users with OIDC provider

### LINKED ISSUE #585: Disable user VPN sessions when removed from OIDC provider
Add a periodic check to disconnect or disable a user's VPN if refreshing their token from the OIDC provider fails.

https://discourse.firez.one/t/google-sso-with-auto-disconnect/66

### PR DESCRIPTION
**Pull request by princemaple**
close #585 

This functionality is done in 2 parts:

1. Store OIDC connection (mainly the refresh token) when user login via an OIDC provider. **This can only be done when they sign in via the chose provider the first time. Existing users will have to revoke their access on the provider and re-login.**
2. Check users' OIDC connection status using the refresh token, periodically. If the user no longer has a valid status, disable their VPN session by timestamping their `disabled_at` so the rest of the system can pick it up and disable their wireguard interface.
3. Additionally, add the ability for admins to disable/re-enable specific users' permission to connect VPN.
image

image

----

image

----

image

### CODE REVIEW

**Comment by princemaple** [comment]
Given that we go the refresh token route. Some notes.

Refresh Token:
- Google gives it to you by default
  - although it says you need to specify `access_type: offline`, it actually doesn't care
- Okta takes a `offline_access` scope
- I imagine most others will be like this 2. If the user uses one that requires a scope, we need to state clearly that they need to find out what the scope required is.

Implementation:
- config `refresh_interval`
- Store `refresh_token_provider`, `refresh_token`, `refreshed_at` on user, assuming there is always only 1 identity provider is being used, on a separate table if otherwise
- use GenServer to periodically send refresh request, if `refreshed_at` + `refresh_interval` is in the past for the user
- use the `refresh_token` type instead of `authorization_token` when requesting for `access_token`

Q:
- What needs to be done to achieve "Disable user VPN sessions", remove all devices of the user?

cc @jamilbk @mdp

**Comment by jamilbk** [comment]
@princemaple

Yeah, seems like requesting a `refresh_token` + `access_token` and then periodically requesting a new `access_token` in the background seems like the best way to accomplish this, assuming the OIDC provider fails the request if the user is removed / disabled in their system.

+1 on using a GenServer with a periodic timer for this (I use this pattern in a couple places). Maybe spawn a GenServer for each user or each OIDC provider since they may have different rate limits / error responses?

Maybe we should track `refresh_token_response` as well? It would be helpful to save the refresh response body and status code in case an administrator wants to debug.

Hmm, I'll have to think about what multiple OIDC providers means for refresh tokens, but it's kinda feeling like this should be in its own table anyway. Having a dedicated schema module for this would make it easier to test, easier to reason about, more secure, etc.

To disable VPN sessions, see here: https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/devices.ex#L91

I update the list of public keys active on the server's WireGuard interface each minute, and if a user's VPN session has expired, their devices' keys are simply omitted from that list.

**Comment by princemaple** [comment]
A couple updates:

1. Google does need the `access_type: "offline"` after all, despite the internet (SO) and the google oauth playground both say otherwise, at least when signing in from the web prompt
2. Refresh token is only granted the very first time you sign in (at least for google). We will need to let the users know that they have to reconfigure their oauth, or revoke all current users and let them sign in again. @jasonboukheir 

Progress:

1. oidc/oauth is pretty well designed I guess. I can simply reuse the `fetch_tokens` from `:openid_connect` with some overriding params, like so:
```elixir
OpenIDConnect.fetch_tokens(
  :google,
  %{grant_type: "refresh_token", refresh_token: "REFRESH_TOKEN"}
)
```
This returns `{:ok, refreshed_claims}`

2. I revoked my test app's access to my account, hopefully simulating the same situation when a user is removed from their org. I managed to get a 400.

This returns `{:error, :fetch_tokens, %HTTPoison.Response{status_code: 400}}`

**Comment by princemaple** [comment]
Ready for a first pass. Functionality is there.

Obviously tests haven't been added. I manually tested against a dummy google project.

File: apps/fz_http/lib/fz_http/oidc/refresher.ex [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+      refreshed_at: DateTime.utc_now(),
+      refresh_response: refresh_response
+    })
+
+    with %{error: _} <- refresh_response do
+      Logger.info("Disabling user\##{user_id}...")
+
+      user_id
+      |> Users.get_user!()
+      |> User.changeset(%{last_signed_in_at: ~U[1970-01-01 00:00:00Z]})
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http/oidc/refresher.ex]: Hm, wonder if we should prevent disabling an `admin` user? Maybe if it's the last admin in the system?

Comment (jamilbk) [inline apps/fz_http/lib/fz_http/oidc/refresher.ex]: Instead of changing `last_signed_in_at` here, I think we'll probably have to add a `disabled_reason` string on `users` to track disabled Users and check for this in `Devices.to_peer_list/0` since we allow never-signed-in Users to connect to VPN if the adminstrator has not turned on the `Require users to authenticate for VPN` setting.

`disabled_reason` could be set to `oidc_refresh_error` for now. Later down the road we could add more, e.g. `too_many_password_attempts` or `disabled_by_admin` (later down the road).

File: apps/fz_http/lib/fz_http/oidc/refresh_manager.ex [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+  defp schedule do
+    Process.send_after(self(), :spawn_refresher, @spawn_interval)
+  end
+
+  defp spawn_refresher do
+    schedule()
+
+    User
+    |> Repo.all()
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http/oidc/refresh_manager.ex:39]: Maybe this could be optimized to only fetch users that have an associated `oidc_connection`?

File: apps/fz_http/lib/fz_http_web/controllers/auth_controller.ex [hunk 3]
```diff
@@ -67,6 +67,16 @@ defmodule FzHttpWeb.AuthController do
          {:ok, claims} <- openid_connect.verify(provider, tokens["id_token"]) do
       case UserFromAuth.find_or_create(provider, claims) do
         {:ok, user} ->
+          # only first-time connect will include refresh token
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/controllers/auth_controller.ex:70]: Hmm thinking through this, if Firezone is offline for an extended time, will that disable all OIDC users permanently? Or will it just force them to re-authenticate at the next sign-in?

**Review by jamilbk — COMMENTED** [review]
Nice approach! The only gotcha I think we need to be careful of is disabling users if Firezone is offline or has no connectivity for an extended period.

Ah also, we should have some mechanism for an administrator to re-enable an accidentally-disabled user... maybe a UI form?

File: apps/fz_http/lib/fz_http/oidc/refresh_manager.ex (hunk 2 above)
Comment (princemaple) [reply apps/fz_http/lib/fz_http/oidc/refresh_manager.ex:39]: Yep, I omitted a lot of optimization, intentionally. As I wasn't sure, what we will do eventually, like having a manager per site, or per user, or per site per user, or per site per provider, etc.

File: apps/fz_http/lib/fz_http/oidc/refresher.ex (hunk 1 above)
Comment (princemaple) [reply apps/fz_http/lib/fz_http/oidc/refresher.ex]: Admins don't get disconnected either way, but if the point was to not change their last logged in time, the point is valid.

**Comment by princemaple** [comment]
@jamilbk 

Being offline is not a problem. Even though it's called `refresh_token`. it doesn't necessarily refresh. It either gets you a new `access_token`, or returns your old access_token but reactivated, depending on the implementation of the provider. I didn't need to send an old `access_token` alongside to get a new one, from google. **EDIT: The refresh token does not expire.**

`disable_reason` sounds good. However, seeing `disabled_by_admin`, I think the semantics here is a little vague. Can a disabled user log into the system? Or are they simply not allowed to connect their VPN? The current `last_signed_in_at` approach only disables the VPN usage. Users can sign in as usual.

File: apps/fz_http/lib/fz_http/oidc/refresher.ex (hunk 1 above)
Comment (princemaple) [reply apps/fz_http/lib/fz_http/oidc/refresher.ex]: > Ah also, we should have some mechanism for an administrator to re-enable an accidentally-disabled user... maybe a UI form?

They could add the user back to their OIDC provider? If you meant not using an OIDC login, I guess they can remove the user's OIDC connection - then they will not be checked, hence won't be disabled.

**Comment by jamilbk** [comment]
> The current last_signed_in_at approach only disables the VPN usage.

I think only disabling VPN makes sense. My point was that with the "Require Authentication for VPN Sessions" set to `Never` or `Once`, I'm not sure changing the `last_signed_in_at` will actually disable their VPN session?

Screen Shot 2022-05-19 at 6 18 40 PM

File: apps/fz_http/lib/fz_http/oidc/refresh_manager.ex (hunk 2 above)
Comment (jamilbk) [reply apps/fz_http/lib/fz_http/oidc/refresh_manager.ex:39]: Sounds good.

**Comment by princemaple** [comment]
> My point was that with the "Require Authentication for VPN Sessions" set to `Never` or `Once`, I'm not sure changing the `last_signed_in_at` will actually disable their VPN session?

Ah right. Didn't think about this. OK so we need a way to disable a user's session without relying on the `last_signed_in_at` field. This is actually better and more reliable.

So, the last thing is working out what we do with the disable reason. `too_many_password_attempts` would lock out the user from signing in. Do you think we need `disable_vpn_reason` and `disable_login_reason`?

**Comment by jamilbk** [comment]
Hmmm could probably just use `oidc_refresh_failed`? I guess it'd be easy to change later with a migration so not too picky.

**Comment by princemaple** [comment]
Sure. Get it going first. 👍

**Comment by princemaple** [comment]
Can use a second pass.

Now uses `allowed_to_connect` field.
Admins can toggle this field on User#Index and User#Show.

TODO

- [x] Add OIDC connections section to User#Show
- [x] Only refresh users that are currently allowed to connect - prevent some excessive disabling...
- [x] Remove `site_id` for now

UPDATE: Now uses `disabled_at`

**Comment by princemaple** [comment]
removed outdated screenshot

File: apps/fz_http/lib/fz_http/oidc/refresher.ex [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+          %{error: "unknown error"}
+      end
+
+    OIDC.update_connection(conn, %{
+      refreshed_at: DateTime.utc_now(),
+      refresh_response: refresh_response
+    })
+
+    with %{error: _} <- refresh_response do
+      Logger.info("Disabling user\##{user_id}...")
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http/oidc/refresher.ex]: May want to state why here and log the email instead of user_id? , e.g.

```elixir
Logger.info("Disabling user #{user.email} due to OIDC token refresh failure...")
```

File: apps/fz_http/lib/fz_http/oidc/refresher.ex [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http/oidc/refresher.ex:60]: Could you add a new [telemetry function](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/telemetry.ex) and call it here to track events like this?

```elixir
def disable_user(user, reason = "oidc refresh failure") do
      telemetry_module().capture(
      "disable_user",
      common_fields() ++
        [
           user_email_hash: hash(user.email),
           reason: reason
        ]
    )
end
```

File: apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+  def render(assigns) do
+    ~H"""
+    <input type="checkbox" phx-target={@myself} disabled={@user.role == :admin}
+        phx-click="toggle_allowed_to_connect" checked={@user.allowed_to_connect} />
+    """
+  end
+
+  @impl Phoenix.LiveComponent
+  def handle_event("toggle_allowed_to_connect", params, socket) do
+    user =
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex]: Could you call the new telemetry function here too?

File: apps/fz_http/lib/fz_http_web/templates/shared/user_details.html.heex [hunk 7]
```diff
@@ -10,6 +10,14 @@
       <td><%= @user.role %></td>
     </tr>
 
+    <tr>
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/templates/shared/user_details.html.heex]: Hmmm, maybe we should make this non-editable? I wonder if Admins will need to do this en-masse, we might not want to make it this easy for admins to accidentally enable/disable VPN connections.

File: apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex [hunk 8]
```diff
@@ -33,6 +34,9 @@
             <%= live_patch(user.email, to: Routes.user_show_path(@socket, :show, user)) %>
           </td>
           <td id={"user-#{user.id}-device-count"}><%= user.device_count %></td>
+          <td>
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex:37]: What do you think about moving this down to the `Danger Zone` section below? It feels like enabling / disabling a user's VPN should come with a bit more thought.

File: apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex [hunk 9]
```diff
@@ -20,6 +20,7 @@
         <tr>
           <th>Email</th>
           <th>Devices</th>
+          <th>Can Connect</th>
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex]: See comment Re: moving this down to the section below.

File: apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex [hunk 10]
```diff
@@ -0,0 +1,28 @@
...
+  """
+  use FzHttpWeb, :live_component
+
+  import Ecto.Changeset
+  alias FzHttp.Repo
+
+  @impl Phoenix.LiveComponent
+  def render(assigns) do
+    ~H"""
+    <input type="checkbox" phx-target={@myself} disabled={@user.role == :admin}
```
Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex]: Thoughts on adding `data-confirm="Are you sure? This may affect this user's internet connectivity."`

Comment (jamilbk) [inline apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex:13]: Thoughts on adding `data-confirm="Are you sure? This may this user's internet connectivity."`

**Review by jamilbk — CHANGES_REQUESTED** [review]
Looks good, just a few suggestions. Also, a couple design improvements I think we should consider:

* What do you think of refactoring `allowed_to_connect:boolean` to `disabled_at:datetime` field?
* Should probably re-allow VPN sessions after a user successfully authenticates in `Authentication.sign_in/2`
* Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab

**Comment by princemaple** [comment]
Can use a final review if this one goes green.

**Comment by princemaple** [comment]
> Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab

Note: Disconnected user can still reconnect, as they are not signed out. Do we have a way to sign out a user? (i.e. is the user session persisted on server and can be cleared)

**Comment by jamilbk** [comment]
> > Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab
> 
> Note: Disconnected user can still reconnect, as they are not signed out. Do we have a way to sign out a user? (i.e. is the user session persisted on server and can be cleared)

No, the user session is persisted only via cookies and signed out via `Authentication.sign_out/1`. If something there fails server-side, the browser would still have a valid cookie and the user would still be able to authenticate.

~~Hmm good catch on this. I think what we probably want to do is prevent disabled users from being loaded from the cookie on each page request. Currently, users are loaded [using `Guardian.Plug.LoadResource` here](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/authentication/pipeline.ex#L14). I'm thinking we can add our own custom plug that after the `VerifySession` plug but before the `LoadResource` plug that checks to see if the user being loaded has `disabled_at` set?~~

EDIT:

@princemaple 

Actually, if the user is still able to authenticate, that's fine -- it's the VPN session we're disabling. I think what you had earlier is probably better: the only way a user's VPN session can be re-enabled is when admin explicitly does so.

**Comment by princemaple** [comment]
There is code that makes admin VPN sessions never expire. Should it change now or stay the same?

Given that the auto logout is really only against admins. Unprivileged users don't have the ability to grant permission for themselves, even if they can still logon.

**Comment by jamilbk** [comment]
> There is code that makes admin VPN sessions never expire. Should it change now or stay the same?

Let's change it to make admins subject to expiration too.

**Comment by jamilbk** [comment]
> Given that the auto logout is really only against admins. Unprivileged users don't have the ability to grant permission for themselves, even if they can still logon.

I think with 4 hour cookie sessions, we can accept this edge case for now -- maybe we can add a config option for this in the future: `disable user login to the web portal if removed from OIDC`.

**Comment by princemaple** [comment]
Updated PR description

File: apps/fz_http/test/support/test_helpers.ex [hunk 11]
```diff
@@ -146,7 +146,9 @@ defmodule FzHttp.TestHelpers do
     {:ok, user: user}
   end
 
-  def create_users(%{count: count}) do
+  def create_users(opts) do
```
Comment (jamilbk) [inline apps/fz_http/test/support/test_helpers.ex:149]: Thanks :-)

**Review by jamilbk — APPROVED** [review]
LGTM! This is awesome. Nice work!

**Comment by jamilbk** [comment]
cc @gongjason

Two in this PR for you to be aware of:

- new telemetry event: `disable_user`, which contains `user_email_hash` and `reason` fields. Disabled users can no longer connect to VPN.
- Changes to how OIDC works -- if a token refresh fails for whatever reason, the user can't connect to VPN (this is useful for disabling a user's VPN when removed from OIDC provider)

**Comment by princemaple** [comment]
@gongjason and this:
> Store OIDC connection (mainly the refresh token) when user login via an OIDC provider. This can only be done when they sign in via their chosen provider the very first time. Existing users will have to revoke their access on the provider and re-login.

**Comment by luong-komorebi** [comment]
For everyone who just upgrade to 0.3.16 for this feature, please read the the documents for 0.4 [in this commit](https://github.com/firezone/firezone/blob/dac6b5aac4b471826439fe2b236a4e1ec38e8842/docs/docs/authenticate/google.md)

For this feature to work, you will need to
1. Update the callback URL. It should end with `/auth/oidc/<provider_key>/callback/` 
2. Update the scope of the oauth app/client to include scopes that allow OIDC and refresh tokens

**Comment by alikhil** [comment]
Hi!

Does this feature work with keycloak?
