### PR TITLE
test(gui-client): fix zip file export in smoke tests

### LINKED ISSUE #5464: bug(gui-client): the smoke test isn't exporting logs correctly
#### Describe the bug

It's probably because the IPC service isn't running or something. The export function says it can't read a directory. The zip file is only 22 bytes which is probably the ZIP header.

#### To Reproduce

CI is reproducing it

#### Expected behavior

1. Expect the smoke tests to fail if the logs are exported wrong
2. Expect the logs to be exported properly

#### Screenshots / Logs

https://github.com/firezone/firezone/actions/runs/9592350419/job/26450751509#step:10:76

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ ea64155, recent commit on main, probably goes back a few weeks to the IPC split
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Both Linux and Windows
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ CI

#### Additional context

Next steps:
1. Read back the zip file or something and flunk the smoke test if there aren't enough files in the right place (also see about unblocking #5452)
2. Run the IPC service in CI so that the IPC logs will be created

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #5464

These were silently broken, it was exporting an empty zip and passing the test anyway. So this PR will cause the test to fail if the zip wasn't fully exported, and then it will fix the export.

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -324,8 +323,8 @@ async fn smoke_test(ctlr_tx: CtlrTx) -> Result<()> {
         .await
         .context("Failed to get zip file metadata")?
         .len();
-    if zip_len == 0 {
-        bail!("Exported log zip has 0 bytes");
+    if zip_len <= 22 {
+        bail!("Exported log zip just has the file header");
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/gui.rs:327]: This would catch the bug where we leave an empty zip and the test gives a false positive

File: rust/gui-client/src-tauri/src/client/logging.rs [hunk 2]
```diff
@@ -82,7 +82,7 @@ pub(crate) async fn clear_logs() -> StdResult<(), String> {
 
 #[tauri::command]
 pub(crate) async fn export_logs(managed: tauri::State<'_, Managed>) -> StdResult<(), String> {
-    export_logs_inner(managed.ctlr_tx.clone()).map_err(|e| e.to_string())
+    show_export_dialog(managed.ctlr_tx.clone()).map_err(|e| e.to_string())
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/logging.rs:85]: This just needed a clearer name

File: scripts/tests/smoke-test-gui-windows.sh [hunk 3]
```diff
@@ -34,25 +37,11 @@ function smoke_test() {
...
-
-    # Run the test again and make sure the device ID is not changed
-    cargo run --bin "$PACKAGE" -- smoke-test
-    DEVICE_ID_2=$(cat "$DEVICE_ID_PATH")
-
-    if [ "$DEVICE_ID_1" != "$DEVICE_ID_2" ]
-    then
-        echo "The device ID should not change if the file is intact between runs"
-        exit 1
-    fi
```
Comment (ReactorScram) [inline scripts/tests/smoke-test-gui-windows.sh:48]: A lot of this stuff doesn't work now that the IPC service has been split out, and properly running it in CI without just installing it is a little tricky.

In a future PR I should probably install it, but that means fighting the CI more

Comment (ReactorScram) [reply scripts/tests/smoke-test-gui-windows.sh:48]: When we get to #5453, that would be a good time to properly smoke-test the IPC service and put all these checks back in.

**Review by thomaseizinger — APPROVED** [review]
