### PR TITLE
fix(apple): stringify errors from `WrappedSession::connect`

### LINKED ISSUE #5965: `connlib` crashes with no backtrace / log if DNS upstream can't be reached during `Session.connect`
I only have the `demo-postgres` DNS Resource added in a fresh `demo` account on staging.

I've noticed that forwarded queries sometimes hang and time out with hickory. This is happening sporadically and intermittently.

Latest Test Flight client on macOS. Will try to capture better logs.

### PR DESCRIPTION
**Pull request by jamilbk**
Errors returned from `WrappedSession.connect` are always a `RustString` but those are only pointers to the actual data. See https://chinedufn.github.io/swift-bridge/built-in/string/index.html#ruststring for details. To see the actual string on the Swift side (and in the logs), we need to call `.toString()` on it.

Fixes: #5965.

### CODE REVIEW

**Comment by jamilbk** [comment]
adding @ReactorScram for visibility

**Comment by thomaseizinger** [comment]
@jamilbk I ended up pushing another small change on top of this that simplifies how we generate those error strings. I don't think it needs any retesting but I'll leave it up to you to merge.

**Review by thomaseizinger — APPROVED** [review]

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 1]
```diff
@@ -141,7 +141,8 @@ class Adapter {
       // Update state in case everything succeeded
       self.state = .tunnelStarted(session: session)
     } catch let error {
-      throw AdapterError.connlibConnectError(error)
+      let msg = error as! RustString
+      throw AdapterError.connlibConnectError(msg.toString())
```
Comment (ReactorScram) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:146]:
```suggestion
      // `toString` needed to deep copy the string and avoid a possible dangling pointer
      throw AdapterError.connlibConnectError(msg.toString())
```

If I understood it correctly, a comment to prevent accidental removal would be nice

**Review by ReactorScram — APPROVED** [review]
