### PR TITLE
fix(portal): sidebar active item state

### LINKED ISSUE #2065: Sidebar fixes
- [x] Show/collapse for collapsable menubar items
- [x] Add active menu item class and set it on every content page via `temporary_assigns` (eg. `temporary_assigns: [section: :gateways]`).
- [x] Ensure menu item icons are not broken
- [x] Ensure spacing is consistent in the menu

### PR DESCRIPTION
**Pull request by jamilbk**
Adds `active_path` to determine whether or not to highlight a sidebar item.

~~Leaving as draft for now to allow @devsnaked to contribute. Edit: Will use this PR as the base for @devsnaked's upcoming changes~~

Edit: fixes #2065

### CODE REVIEW

File: elixir/apps/web/lib/web/components/navigation_components.ex [hunk 1]
```diff
@@ -170,7 +173,8 @@ defmodule Web.NavigationComponents do
 
   attr :id, :string, required: true, doc: "ID of the nav group container"
   attr :icon, :string, required: true
-  # attr :navigate, :string, required: true
+  attr :active_path, :string, required: true
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/components/navigation_components.ex]: Maybe we should call it `current_path`?

File: elixir/apps/web/lib/web/components/navigation_components.ex [hunk 2]
```diff
@@ -154,6 +156,7 @@ defmodule Web.NavigationComponents do
       flex items-center p-2
       text-base font-medium text-gray-900
       rounded-lg
+      #{if String.starts_with?(@active_path, @navigate), do: @active_class, else: ""}
       hover:bg-gray-100
       dark:text-white dark:hover:bg-gray-700 group]}>
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/components/navigation_components.ex:161]: I think for state changes we should move them out of `~H` and do something like:
```
activity_class = 
  if String.starts_with?(assigns.current_path, assigns.navigate) do
    assigns.active_class
  end

assigns = assign(assigns, activity_class: activity_class)
```

And then to make classes more readable we can leverage list of strings instead of sigil (I noticed Elixir formatted makes some weird moves with it so was trying to avoid it in new code):
```
~H"""
... class={[
  "flex items-center p-2",
  "text-base font-medium text-gray-900",
  "rounded-lg",
  @activity_class
]}
"""
```

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex:161]: 👍 Will get this feedback applied

Comment (AndrewDryga) [reply elixir/apps/web/lib/web/components/navigation_components.ex:161]: Or we can do like Phoenix team does:
```
class={[
  "flex items-center p-2",
  "text-base font-medium text-gray-900",
  "rounded-lg",
  String.starts_with?(@current_path, @navigate) && @active_class,
]}
```

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex:161]: I think the second one might end up being cleaner because we need the particular `navigate` attribute for each item inside the comprehension

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex:161]: Updated

File: elixir/apps/web/lib/web/components/navigation_components.ex (hunk 1 above)
Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex]: Updated

File: elixir/apps/web/lib/web/components/navigation_components.ex [hunk 3]
```diff
@@ -85,11 +85,12 @@ defmodule Web.NavigationComponents do
     """
   end
 
-  slot :bottom, required: false
+  slot(:bottom, required: false)
```
Comment (AndrewDryga) [inline elixir/apps/web/lib/web/components/navigation_components.ex]: Your formatter is broken, not because of changes you added to `elixir/.formatter.exs`, but because Elixir LS is broken in many cases. See https://github.com/elixir-lsp/vscode-elixir-ls/issues/345#issuecomment-1676742647. When that starts to happen you should just restart the editor.

And this particular formatted change should be rolled back manually now :(.

Comment (jamilbk) [reply elixir/apps/web/lib/web/components/navigation_components.ex]: Sigh, yeah these snuck back in. I'm using Vim so the issue is slightly different (related to not running `mix format` from root so that the existing style is picked up)

**Comment by jamilbk** [comment]
@AndrewDryga fixed.

**Review by AndrewDryga — APPROVED** [review]
