### PR TITLE
Fix saml certfile path for omnibus

### LINKED ISSUE #1327: saml error - issue / 502 cannot login
Morning, 

Non docker user; fedora 37 using fedora35 rpms.. 

At somepoint the webui was getting 502's and found that I had some saml errors in the logs.. 

I tried to remove saml or odic from my firezone.rb and regenerate, but it didn't seem to help. 

More/other information is posted in slack.. 

```
2023-01-17_17:13:57.93988 12:13:57.939 [error] [Samly] Failed load SP certfile ["/var/opt/firezone/ssl/saml_certfile.pem"]: %{certfile: "/var/opt/firezone/ssl/saml_certfile.pem", entity_id: "urn:firezone.dev:firezone-app", id: "firezone", keyfile: "/var/opt/firezone/ssl/saml_keyfile.pem"}
```

```
[I] root@fedora-d510f2 /v/o/f/ssl# pwd
/var/opt/firezone/ssl
[I] root@fedora-d510f2 /v/o/f/ssl# ls -al saml*
-rw-r--r--. 1 root root 1505 Oct 25 11:00 saml.crt
-rw-r--r--. 1 root root 1679 Oct 25 11:00 saml.key
```

```
[I] root@fedora-d510f2 /v/o/f/ssl# mv saml.crt saml.crt-backup
[I] root@fedora-d510f2 /v/o/f/ssl# mv saml.key saml.key-backup
[I] root@fedora-d510f2 /v/o/f/ssl# firezone-ctl reconfigure | grep saml
  * openssl_x509_certificate[/var/opt/firezone/ssl/saml.crt] action create
    * file[/var/opt/firezone/ssl/saml.crt] action create_if_missing
      - create new file /var/opt/firezone/ssl/saml.crt
      - update content in file /var/opt/firezone/ssl/saml.crt from none to 55167a
      --- /var/opt/firezone/ssl/saml.crt        2023-01-17 12:48:55.097137072 -0500
      +++ /var/opt/firezone/ssl/.chef-saml20230117-41913-rhhc32.crt     2023-01-17 12:48:55.097137072 -0500
    * file[/var/opt/firezone/ssl/saml.key] action create_if_missing
      - create new file /var/opt/firezone/ssl/saml.key
      - update content in file /var/opt/firezone/ssl/saml.key from none to 1f9783
```

```
[I] root@fedora-d510f2 /e/firezone (master)# grep saml *
firezone-running.json:      "saml": {
firezone-running.json:        "key": "/var/opt/firezone/ssl/saml.key",
firezone-running.json:        "cert": "/var/opt/firezone/ssl/saml.crt"
firezone.rb:default['firezone']['authentication']['saml']['key'] = '/var/opt/firezone/ssl/saml.key'
firezone.rb:default['firezone']['authentication']['saml']['cert'] = '/var/opt/firezone/ssl/saml.crt'
[I] root@fedora-d510f2 /e/firezone (master)# firezone-ctl tail | grep saml
2023-01-17_17:59:03.66752 12:59:03.667 [error] [Samly] Failed load SP certfile ["/var/opt/firezone/ssl/saml_certfile.pem"]: %{certfile: "/var/opt/firezone/ssl/saml_certfile.pem", entity_id: "urn:firezone.dev:firezone-app", id: "firezone", keyfile: "/var/opt/firezone/ssl/saml_keyfile.pem"}
2023-01-17_17:59:03.66757 12:59:03.667 [error] [Samly] Failed load SP keyfile ["/var/opt/firezone/ssl/saml_keyfile.pem"]: %{certfile: "/var/opt/firezone/ssl/saml_certfile.pem", entity_id: "urn:firezone.dev:firezone-app", id: "firezone", keyfile: "/var/opt/firezone/ssl/saml_keyfile.pem"}
```

```
==> SAML_CERTFILE_PATH <==
/var/opt/firezone/ssl/saml_certfile.pem
==> SAML_KEYFILE_PATH <==
/var/opt/firezone/ssl/saml_keyfile.pem
```

```
[I] root@fedora-d510f2 /v/o/f/ssl# ls -al saml*
lrwxrwxrwx. 1 root root    8 Jan 17 13:36 saml_certfile.pem -> saml.crt
-rw-r--r--. 1 root root 1505 Jan 17 13:16 saml.crt
-rw-r--r--. 1 root root 1505 Oct 25 11:00 saml.crt-backup
-rw-r--r--. 1 root root 1679 Jan 17 13:16 saml.key
-rw-r--r--. 1 root root 1679 Oct 25 11:00 saml.key-backup
lrwxrwxrwx. 1 root root    8 Jan 17 13:36 saml_keyfile.pem -> saml.key
```

I can't seem to figure out why this is happening.. or how to overcome it.. 

Can someone help? 

Thanks in advance.

### PR DESCRIPTION
**Pull request by jamilbk**
Updated to match what's set in https://github.com/firezone/firezone/blob/master/omnibus/cookbooks/firezone/recipes/ssl.rb

Fixes #1327

### CODE REVIEW

**Review by AndrewDryga — APPROVED** [review]

File: omnibus/cookbooks/firezone/libraries/config.rb [hunk 1]
```diff
@@ -264,8 +264,8 @@ def self.app_env(node, reject = [])
         # the <= 0.4.4 to >= 0.4.5 version boundary.
         'WIREGUARD_PRIVATE_KEY_PATH' => "#{node['firezone']['var_directory']}/cache/wg_private_key",
 
-        'SAML_KEYFILE_PATH' => "#{node['firezone']['ssl']['directory']}/saml_keyfile.pem",
-        'SAML_CERTFILE_PATH' => "#{node['firezone']['ssl']['directory']}/saml_certfile.pem",
+        'SAML_KEYFILE_PATH' => "#{node['firezone']['ssl']['directory']}/saml.key",
```
Comment (jamilbk) [inline omnibus/cookbooks/firezone/libraries/config.rb:267]: Matches 
https://github.com/firezone/firezone/blob/master/omnibus/cookbooks/firezone/recipes/ssl.rb#L92
