### PR TITLE
fix(windows-client): remove spurious "Connected to Firezone" notifications

### LINKED ISSUE #4385: bug(windows Client): the Windows Client sometimes shows spurious "Firezone is connected" notifications
Next step: Decide when it should be shown.

#### Describe the bug

I have my Windows laptop open, idle, and it sometimes shows the "Firezone is connected" pop-up.

Switching networks also causes several notifications. (See #4530)

#### To Reproduce

Leave the Client running and signed in, and wait. Or switch networks.

#### Expected behavior

Expect "Firezone is connected" to only happen when I sign in. Really, it doesn't even need to happen when changing networks, since there's no corresponding "Firezone is disconnected" message on Windows yet.

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C067DSY7TFX/p1711665353784999

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ a3680e0
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI from draft release

#### Additional context

None

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #4385

```[tasklist]
### Manual test cases (f2c8f47b3 passed)
- [x] Given there is no token on disk, when you start the app, then there is no notification
- [x] Given there is a token on disk, when you start the app and it signs in, then there is 1 notification
- [x] Given the app is signed out, when you sign in, then there is 1 notification (test this in a sign-out-sign-in cycle)
- [x] Given the app is signed in, when you sign out, then there is no notification
- [x] Given the app is signed in, when you change Wi-Fi networks, then there is no notification
```

This will work on Linux once the Linux GUI comes up

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -638,13 +638,16 @@ impl Controller {
...
             Req::TunnelReady => {
+                let was_already_ready = self.tunnel_ready;
                 self.tunnel_ready = true;
                 self.refresh_system_tray_menu()?;
 
-                os::show_notification(
-                    "Firezone connected",
-                    "You are now signed in and able to access resources.",
-                )?;
+                if !was_already_ready {
```
Comment (conectado) [inline rust/gui-client/src-tauri/src/client/gui.rs]: Maybe we can move this check before mutating `tunnel_ready` so we don't need the intermediate variable?

I don't feel to strongly about this

**Review by conectado — APPROVED** [review]
LGTM

File: rust/gui-client/src-tauri/src/client/gui.rs (hunk 1 above)
Comment (ReactorScram) [reply rust/gui-client/src-tauri/src/client/gui.rs]: Yeah, not sure why I had that variable there. Fixed it
