### PR TITLE
fix(linux-client): don't show the token in `--help`

### LINKED ISSUE #4653: `--help` should not print the `FIREZONE_TOKEN` env

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #4653

### CODE REVIEW

File: rust/headless-client/src/lib.rs [hunk 1]
```diff
@@ -50,7 +50,7 @@ struct Cli {
     // TODO: It isn't good for security to pass the token as a CLI arg.
     // If we pass it as an env var, we should remove it immediately so that
     // other processes don't see it. Reading it from a file is probably safest.
```
Comment (jamilbk) [inline rust/headless-client/src/lib.rs]: Other procs wouldn't see our env vars right?

File: rust/headless-client/src/lib.rs [hunk 2]
```diff
@@ -50,7 +50,7 @@ struct Cli {
...
-    #[arg(env = "FIREZONE_TOKEN")]
+    #[arg(env = "FIREZONE_TOKEN", hide = true)]
```
Comment (jamilbk) [inline rust/headless-client/src/lib.rs:53]: Wondering if there's any usability downside to this. I think env vars are standard even for sensitive things like [api keys](https://tailscale.com/kb/1210/terraform-provider).

Comment (ReactorScram) [reply rust/headless-client/src/lib.rs:53]: Hm. Yeah last I saw they're not easily snooped like CLI args...

So I'd like to drop the support for tokens in the CLI, but we can keep env vars if writing a file isn't practical. There is a trick to unset the env var after you read it, it's on my todo list, that adds a little bit of safety so that child processes can't inherit it or something.

Comment (ReactorScram) [reply rust/headless-client/src/lib.rs:53]: I fixed the comment. I think you're right that normally a non-root user shouldn't be able to see env vars of a root process.

And this PR doesn't disable the CLI arg or env var, it just prevents clap from printing it when you run `--help`

I get why they do that, but it feels like the wrong default for secrets.

image

**Review by jamilbk — APPROVED** [review]
