### PR TITLE
fix(gateway): don't route outbound ICMP errors

### LINKED ISSUE #10983: `Tunnel error: Failed to translate outbound packet: Unsupported ICMPv4 type: DestinationUnreachable(Port)` during normal Gateway operation
While setting up for a customer demo of flow logs, this message spammed the log on a default Ubuntu 24.04 install (ipv4-only VM) and only one resource - `ifconfig.net`.

This is a quite common / minimal configuration and now that we will have admins ingesting these logs, it's a bit more important to be careful about what we log on WARN probably.

```
{"timestamp":"2025-11-26T15:46:33.670825Z","level":"WARN","message":"Tunnel error: Failed to translate outbound packet: Unsupported ICMPv4 type: DestinationUnreachable(Port)","target":"firezone_gateway::eventloop"}
```

### PR DESCRIPTION
**Pull request by thomaseizinger**
ICMP errors like "Destination unreachable" can be sent by both ends of a network connection. For DNS resources, handling these packets requires special care as we also need to translate the failed packet embedded within these ICMP messages such that the recipient can correctly relate them to the network socket that has sent the original packet.

We do this for inbound ICMP errors already to alert the Client of e.g. unreachable paths such as unreachable IPv6 networks. Outbound ICMP errors, that is, ICMP errors generated by the Client for a packet sent by a resource are currently not handled and result in warnings such as:

> Failed to translate outbound packet: Unsupported ICMPv4 type: DestinationUnreachable(Port)

Whilst it is possible to correctly handle and translate these packets, doing so requires a fair amount of work and changes to a very critical part of the Gateway. As such, we simply drop these packets for now as "unroutable packets" which downgrades their log level to DEBUG.

Resolves: #10983

### CODE REVIEW

File: rust/libs/connlib/tunnel/src/gateway/client_on_gateway.rs [hunk 1]
```diff
@@ -1210,6 +1215,34 @@ mod tests {
...
+        )
+        .unwrap();
+
+        let error = peer.translate_outbound(icmp_unreachable, now).unwrap_err();
+        let error = error.any_downcast_ref::<UnroutablePacket>().unwrap();
+
+        assert_eq!(error.to_string(), "Unroutable packet: OutboundIcmpError");
+        assert_eq!(error.source().to_string(), "unknown");
+        assert_eq!(error.destination().to_string(), "unknown");
+        assert_eq!(error.proto().to_string(), "unknown");
```
Comment (thomaseizinger) [inline rust/libs/connlib/tunnel/src/gateway/client_on_gateway.rs:1243]: This will improve with #10987.

**Review by jamilbk — APPROVED** [review]
LGTM
