### PR TITLE
fix(portal): Update portal font to source sans 3

### LINKED ISSUE #2893: Add more font weights to product
We're missing some of the light and bold weights that we enjoy for the website.

Perhaps it's worth using Google fonts to link to `Source Sans 3` like we do for the website.

https://github.com/firezone/firezone/blob/main/website/src/components/RootLayout/index.tsx#L12

### PR DESCRIPTION
**Pull request by bmanifold**
Why:

* The previous font being used in the portal (Source Sans Pro) did not
      have multiple weights available, which meant that the `font-*` classes
      on all html tags were not being used.  Switching to Source Sans 3
      allows all but 1 (`font-thin` or `100` is not present) of the Tailwind
      font sizes to be used.

Closes #2893

### CODE REVIEW

File: elixir/apps/web/assets/js/app.js [hunk 1]
```diff
@@ -1,4 +1,20 @@
-import "@fontsource/source-sans-pro"
+import '@fontsource/source-sans-3/200.css';
```
Comment (AndrewDryga) [inline elixir/apps/web/assets/js/app.js:1]: Should we use fewer front-weights than importing all of them? I think 2-3 should be enough (regular, bold, and, optionally, light)

Comment (jamilbk) [reply elixir/apps/web/assets/js/app.js:1]: Hmm, yeah, the bundle might end up being smaller, but this should be pretty cache-friendly right? We include them all on the website and use, I think about half of them.

If we include them all it will prevent the possibility that we try to use a weight in the future that isn't available and we don't know why (or didn't notice why) it doesn't work.

But I don't feel super strongly either way.

Comment (bmanifold) [reply elixir/apps/web/assets/js/app.js:1]: @AndrewDryga Good question.  I didn't know what the norm was for most sites and since tailwind allows for all the weights by default I went ahead and imported all of them.  One recommendation I have would be to have at least one more than what you suggested, only because bold was very bold and I have a feeling we probably won't need/want that bold of a font very often (if ever).  Other than that I don't have a strong preference.

Just out of curiosity, is the concern of loading all of them just the amount of time to pull them down to the browser?

**Review by jamilbk — COMMENTED** [review]
LGTM, will defer to @AndrewDryga to approve.

File: elixir/apps/web/assets/js/app.js (hunk 1 above)
Comment (AndrewDryga) [reply elixir/apps/web/assets/js/app.js:1]: @bmanifold there are two reasons:
1. Pulling fonts makes UI a bit slower during the first load, which is minor;
2. I don't want us even to have the option of using too many weights as that would be bad for our product consistency. 

But all this is minor, so it's up to you if you want to clear things out for now.

P.S. That "very bold" can be just the weight we define as "our bold", I thin having two bold styles can be a source of mess by itself.

**Review by AndrewDryga — APPROVED** [review]
