### PR TITLE
fix(connlib): re-resolve portal host on WS hiccup

### LINKED ISSUE #10238: Portal connection does not roam stacks
When switching from IPv4-only to IPv6-only and vice-versa, the portal connection fails to re-establish:

### After switching to IPv4-only network:

```
21:32:06.542256-0700	client_shared::eventloop: Hiccup in portal connection: Reconnecting to portal on transient error: failed to connect socket: [[2600:1901:0:8cb3::]:443: No route to host (os error 65)] backoff=4.311377621s max_elapsed_time=Some(86400s)
21:32:10.855798-0700	client_shared::eventloop: Hiccup in portal connection: Reconnecting to portal on transient error: failed to connect socket: [[2600:1901:0:8cb3::]:443: No route to host (os error 65)] backoff=18.654290473s max_elapsed_time=Some(86400s)
```

### After switching to IPv6-only network:

```
21:35:15.749562-0700	phoenix_channel: Connecting to portal host=api.firez.one addresses=[34.160.64.79:443] user_agent=Mac OS/15.6.0 connlib/1.5.8 (arm64; 24.6.0)
21:35:15.749912-0700	client_shared::eventloop: Hiccup in portal connection: Reconnecting to portal on transient error: failed to connect socket: [34.160.64.79:443: Network is unreachable (os error 51)] backoff=0ns max_elapsed_time=Some(86400s)
21:35:15.752043-0700	connlib: disabled_resources=["dca3fcc6-b5e0-470a-bc7b-6446cdd03bb3"]
21:35:15.753055-0700	phoenix_channel: Connecting to portal host=api.firez.one addresses=[34.160.64.79:443] user_agent=Mac OS/15.6.0 connlib/1.5.8 (arm64; 24.6.0)
21:35:15.754889-0700	client_shared::eventloop: Hiccup in portal connection: Reconnecting to portal on transient error: failed to connect socket: [34.160.64.79:443: Network is unreachable (os error 51)] backoff=308.109401ms max_elapsed_time=Some(86400s)

```

This happens on `main` consistently in both the IPv4-IPv6 and IPv6-IPv4 direction.

### PR DESCRIPTION
**Pull request by thomaseizinger**
Currently, the DNS records for the portal's hostname are only resolved during startup. When the WebSocket connection fails, we try to reconnect but only with the IPs that we have previously resolved. If the local IP stack changed since then or the hostname now points to different IPs, we will run into the reconnect-timeout configured in `phoenix-channel`.

To fix this, we re-resolve the portal's hostname every time the WebSocket connection fails. For the Gateway, this is easy as we can simply reuse the already existing `TokioResolver` provided by hickory. For the Client, we need to write our own DNS client on top of our socket factory abstraction to ensure we don't create a routing loop with the resulting DNS queries. To simplify things, we only send DNS queries over UDP. Those are not guaranteed to succeed but given that we do this on every "hiccup", we already have a retry mechanism. We use the currently configured upstream DNS servers for this.

Resolves: #10238

### CODE REVIEW

File: rust/client-shared/src/eventloop.rs [hunk 1]
```diff
@@ -569,3 +602,130 @@ fn is_unreachable(e: &io::Error) -> bool {
...
+                a.response_code() == dns_types::ResponseCode::NOERROR
+                    && b.response_code() == dns_types::ResponseCode::NOERROR
+            })
+            .next()
+            .await
+            .with_context(|| {
+                format!("All DNS servers ({servers:?}) failed to resolve portal host '{host}'")
+            })?;
+
+        let ips = iter::empty()
```
Comment (klochowicz) [inline rust/client-shared/src/eventloop.rs:657]: do we need more than one IP resolved here? 

if we care about the first one, perhaps something like https://docs.rs/futures/0.3.31/futures/future/fn.select_ok.html could do ? instead of waiting for all of them to resolve?

**Review by klochowicz — APPROVED** [review]
LGTM!

File: rust/client-shared/src/eventloop.rs (hunk 1 above)
Comment (thomaseizinger) [reply rust/client-shared/src/eventloop.rs:657]: Yeah we definitely want to use all IPs that we resolve. `select_ok` across all DNS servers could be an interesting choice though. We'd have to see how we can incorporate the checking of the response code to avoid having those used.
