### PR TITLE
fix: cap log size on all platforms

### LINKED ISSUE #2343: log file size limit
It might be a good idea to implement a log size rollover strategy in addition to the time-based one.

### PR DESCRIPTION
**Pull request by klochowicz**
Enforce log size cap with background cleanup on all desktop platforms (including Linux headless client) and Android client.
All platforms reuse the same constants, ie. cleanup interval and max log size.

On desktop clients, we spawn a background thread, and on Android we use a coroutine.

Fixes #2343

### CODE REVIEW

File: rust/libs/logging/src/cleanup.rs [hunk 1]
```diff
@@ -1,14 +1,86 @@
...
+/// Default maximum total log size in MB across all log directories.
+pub const DEFAULT_MAX_SIZE_MB: u32 = 100;
+
+/// Default interval between log cleanup runs
+pub const DEFAULT_CLEANUP_INTERVAL: Duration = Duration::from_hours(1);
+
+/// Minimum age for files to be eligible for deletion.
 /// Files modified more recently than this are protected.
-const MIN_AGE_SECS: Duration = Duration::from_secs(300);
+const MIN_AGE: Duration = Duration::from_mins(5);
```
[the remark this answers is not in the document]
Comment (klochowicz) [reply rust/libs/logging/src/cleanup.rs:21]: not the case anymore from Rust 1.91

File: rust/headless-client/src/main.rs [hunk 2]
```diff
@@ -65,6 +65,14 @@ struct Cli {
     #[arg(short, long, env = "LOG_DIR")]
     log_dir: Option<PathBuf>,
 
+    /// Maximum total log size in MB before old files are cleaned up.
+    #[arg(long, env = "LOG_MAX_SIZE_MB", default_value_t = logging::DEFAULT_MAX_SIZE_MB)]
+    log_max_size_mb: u32,
+
+    /// Interval in seconds between log cleanup runs.
+    #[arg(long, env = "LOG_CLEANUP_INTERVAL_SECS", default_value_t = logging::DEFAULT_CLEANUP_INTERVAL.as_secs())]
+    log_cleanup_interval_secs: u64,
```
Comment (thomaseizinger) [inline rust/headless-client/src/main.rs]: I'd be okay to not expose this tbh. Don't want to maintain an API that neither we nor anyone else is asking for.

File: rust/libs/logging/src/cleanup.rs [hunk 3]
```diff
@@ -1,14 +1,86 @@
...
+
+const MIN_CLEANUP_INTERVAL: Duration = Duration::from_secs(30);
+
+/// Handle to stop the cleanup background thread.
+///
+/// When dropped, disconnects the channel which wakes the thread's `recv_timeout`
+/// with [`RecvTimeoutError::Disconnected`], causing it to exit.
+#[must_use = "Dropping this handle immediately stops the cleanup thread -- store it in a variable to keep cleanup running"]
```
Comment (thomaseizinger) [inline rust/libs/logging/src/cleanup.rs:29]: 👍

File: rust/libs/logging/src/cleanup.rs [hunk 4]
```diff
@@ -1,14 +1,86 @@
...
+    log_dirs: Vec<PathBuf>,
+    max_size_mb: u32,
+    interval: Duration,
+) -> Option<CleanupHandle> {
+    // Prevent excessively frequent cleanup that could cause performance issues
+    let interval = if interval < MIN_CLEANUP_INTERVAL {
+        tracing::warn!(
+            ?interval,
+            "Requested log cleanup interval is very short, increasing to 30 seconds to prevent performance issues"
+        );
```
Comment (thomaseizinger) [inline rust/libs/logging/src/cleanup.rs]:
```suggestion
        tracing::debug!(
            ?interval,
            "Requested log cleanup interval is very short, increasing to 30 seconds to prevent performance issues"
        );
```

File: rust/headless-client/src/main.rs (hunk 2 above)
Comment (klochowicz) [reply rust/headless-client/src/main.rs]: yeah, happy to remove it - that's why I kept it as a separate commit, it was just handy for testing. :)

File: rust/libs/logging/src/cleanup.rs [hunk 5]
```diff
@@ -1,14 +1,86 @@
...
+                    Err(RecvTimeoutError::Disconnected) => break,
+                    Err(RecvTimeoutError::Timeout) => continue,
+                }
+            }
+        });
+
+    match result {
+        Ok(_) => Some(CleanupHandle { _stop_tx: stop_tx }),
+        Err(e) => {
+            tracing::warn!(error = %e, "Failed to spawn log cleanup thread");
```
Comment (thomaseizinger) [inline rust/libs/logging/src/cleanup.rs]: Maybe return a `Result` and let the caller decide how to handle it?

File: rust/headless-client/src/main.rs (hunk 2 above)
Comment (klochowicz) [reply rust/headless-client/src/main.rs]: can remove a bit more of defensive assertions then and simplify the code a bit as a result.

**Review by thomaseizinger — APPROVED** [review]
Concept ACK

Some minor comments.

File: rust/libs/logging/src/cleanup.rs (hunk 4 above)
Comment (klochowicz) [reply rust/libs/logging/src/cleanup.rs]: hm... is this purely because we currently upload warnings to sentry?
I'm a bit torn, because as a user I would *expect* such a situation to result in a warning, which I could see in the logs.

Perhaps it would be better if we didn't send warnings to sentry if we're worried about sending too much there?

(asking for future occurrences)

Comment (thomaseizinger) [reply rust/libs/logging/src/cleanup.rs]: IMO a warning is justified if something is about to go seriously wrong. "Why is my log cleanup not running as often as I specified?" is a question you'd ask during debugging. I am okay with accepting INFO although I think it is not important enough for that.

WARN is definitely too high of a level.

Comment (thomaseizinger) [reply rust/libs/logging/src/cleanup.rs]: My rule of thumb for WARN is:

> If you log on WARN, consider whether or not it is important enough to wake an ops person at 3am.

File: rust/libs/logging/src/cleanup.rs (hunk 5 above)
Comment (klochowicz) [reply rust/libs/logging/src/cleanup.rs]: great idea, this simplifies Handle, as I don't need to have an option there.

File: rust/libs/logging/src/cleanup.rs (hunk 4 above)
Comment (jamilbk) [reply rust/libs/logging/src/cleanup.rs]: Is it possible there will be log messages that are warnings to the user, but that we don't care about receiving Sentry alerts for?

In the portal we have `Logger.warn(skip_sentry: true)`
