### PR TITLE
chore(gui-client/linux): fix DNS

### LINKED ISSUE #3812: feat(linux): make systemd-resolved the default DNS control method
Next step: Waiting until GA is done. For now customers that need `systemd-resolved` will have to use the env var explicitly.

Per this thread https://github.com/firezone/firezone/pull/3810/files#r1507843669
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by ReactorScram**
Make the GUI use systemd-resolved to retrieve the system's resolvers. This allows the IPC service to set up sentinels for those resolvers and control the system's DNS.

Closes #3812

### CODE REVIEW

File: rust/gui-client/src-tauri/src/client/resolvers.rs [hunk 1]
```diff
@@ -7,12 +7,8 @@ mod imp {
     use anyhow::Result;
     use std::net::IpAddr;
 
-    // TODO: The code here will depend on the chosen DNS control method.
-    // So that will need to be threaded in here somehow.
-    #[allow(clippy::unnecessary_wraps)]
     pub fn get() -> Result<Vec<IpAddr>> {
-        tracing::error!("Resolvers module not yet implemented for Linux, returning empty Vec");
-        Ok(Vec::default())
+        firezone_headless_client::imp::get_system_default_resolvers_systemd_resolved()
```
Comment (ReactorScram) [inline rust/gui-client/src-tauri/src/client/resolvers.rs:11]: I think all desktop systems we support will have systemd and probably systemd-resolved, so I made this the only option here for when the GUI retrieves the system resolvers

Comment (jamilbk) [reply rust/gui-client/src-tauri/src/client/resolvers.rs:11]: Yep! Makes sense. "Install systemd-resolved" is a valid requirement I think.

**Review by jamilbk — APPROVED** [review]
