### PR TITLE
fix(apple): don't apply unchanged network settings

### LINKED ISSUE #11120: Network settings re-applied on each `flow_creation_failed` message
Receiving the `flow_creation_failed` message causes a DNS set loop on macOS.

Build: 21ee0a52 (latest release client)

```
dev.firezone.firezone.network-extension	08:23:31.576873-0800	wire::api::recv: {"event":"flow_creation_failed","ref":null,"topic":"client","payload":{"reason":"offline","resource_id":"61e91f80-2eaa-403f-a375-84d3128fa13a"}}
dev.firezone.firezone.network-extension	08:23:31.580559-0800	tunnel::client: Dropping packet with bad source IP packet=Packet { src: fe80::223:a4ff:fe07:1760, dst: ff02::16, protocol: "IPv6-ICMP", icmp_type: Unknown { type_u8: 143, code_u8: 0, bytes5to8: [0, 0, 0, 1] } }
dev.firezone.firezone.network-extension	08:23:31.677656-0800	tunnel::client::dns_config: Received system-defined DNS servers servers=[192.168.1.254, 2600:1700:3ecb:2410::1] sanitized=[192.168.1.254, 2600:1700:3ecb:2410::1]
dev.firezone.firezone.network-extension	08:23:31.677712-0800	tunnel::client::dns_config: Effective DNS servers are unchanged servers=[Do53 { server: 1.1.1.1:53 }]
dev.firezone.firezone.network-extension	08:23:31.677741-0800	tunnel::io: Re-configuring UDP DNS client with new upstreams servers=[192.168.1.254, 2600:1700:3ecb:2410::1]
dev.firezone.firezone.network-extension	08:23:31.943690-0800	tunnel::client: Dropping packet with bad source IP packet=Packet { src: fe80::223:a4ff:fe07:1760, dst: ff02::16, protocol: "IPv6-ICMP", icmp_type: Unknown { type_u8: 143, code_u8: 0, bytes5to8: [0, 0, 0, 1] } }
dev.firezone.firezone.network-extension	08:23:32.153625-0800	tunnel::client::dns_config: Received system-defined DNS servers servers=[192.168.1.254, 2600:1700:3ecb:2410::1] sanitized=[192.168.1.254, 2600:1700:3ecb:2410::1]
dev.firezone.firezone.network-extension	08:23:32.153678-0800	tunnel::client::dns_config: Effective DNS servers are unchanged servers=[Do53 { server: 1.1.1.1:53 }]
dev.firezone.firezone.network-extension	08:23:32.153704-0800	tunnel::io: Re-configuring UDP DNS client with new upstreams servers=[192.168.1.254, 2600:1700:3ecb:2410::1]
dev.firezone.firezone.network-extension	08:23:32.501986-0800	tunnel::unique_packet_buffer: Buffering packet tag=pending-flow-resources is_full=false packet=Packet { src: 100.82.80.16, dst: 8.8.8.8, protocol: "ICMP", icmp_type: EchoRequest(IcmpEchoHeader { id: 37947, seq: 1180 }) } rid=61e91f80-2eaa-403f-a375-84d3128fa13a
dev.firezone.firezone.network-extension	08:23:32.502060-0800	tunnel::client: Sending connection intent trigger=packet-for-resource rid=61e91f80-2eaa-403f-a375-84d3128fa13a
dev.firezone.firezone.network-extension	08:23:32.502197-0800	wire::api::send: msg={"topic":"client","event":"create_flow","payload":{"resource_id":"61e91f80-2eaa-403f-a375-84d3128fa13a","connected_gateway_ids":["08ad313b-ca35-4f21-8b45-1ea25e54ef20"]},"ref":32}
dev.firezone.firezone.network-extension	08:23:32.580889-0800	wire::api::recv: {"event":"flow_creation_failed","ref":null,"topic":"client","payload":{"reason":"offline","resource_id":"61e91f80-2eaa-403f-a375-84d3128fa13a"}}
dev.firezone.firezone.network-extension	08:23:32.586296-0800	tunnel::client: Dropping packet with bad source IP packet=Packet { src: fe80::223:a4ff:fe07:1760, dst: ff02::16, protocol: "IPv6-ICMP", icmp_type: Unknown { type_u8: 143, code_u8: 0, bytes5to8: [0, 0, 0, 1] } }
dev.firezone.firezone.network-extension	08:23:32.764098-0800	tunnel::client::dns_config: Received system-defined DNS servers servers=[192.168.1.254, 2600:1700:3ecb:2410::1] sanitized=[192.168.1.254, 2600:1700:3ecb:2410::1]
dev.firezone.firezone.network-extension	08:23:32.764344-0800	tunnel::client::dns_config: Effective DNS servers are unchanged servers=[Do53 { server: 1.1.1.1:53 }]
```

This effectively breaks internet connectivity system-wide:

Image

### PR DESCRIPTION
**Pull request by jamilbk**
Connlib sends various updates via the `onResourcesUpdated` event to the app in order to both update network settings (for route changes) and the UI (for site online / offline status).

We were blindly applying these updates without first determining if they had any network-related changes. Combined with a bug in connlib that emitted this event even when nothing changed, it had the potential to cause very noticeable network disruptions during something like a `flow_creation_failed` event. This is because updates like those are emitted at the rate we retry resource connections, every 2s.

When network settings are applied, apps like Google Chrome detect this and immediately cut all in-flight browser requests with an `ERR_NETWORK_CHANGED` error.

With this change in place, these should happen much less frequently in day to day operation.

Fixes #11120

### CODE REVIEW

File: swift/apple/FirezoneNetworkExtension/NetworkSettings.swift [hunk 1]
```diff
@@ -28,6 +28,24 @@ class NetworkSettings {
   private var matchDomains: [String] = [""]
   private var searchDomains: [String] = [""]
 
+  // Track the last applied settings to avoid redundant applies
+  private var lastAppliedSettings: AppliedSettings?
```
Comment (thomaseizinger) [inline swift/apple/FirezoneNetworkExtension/NetworkSettings.swift]: Can we not duplicate this information again?

We already have a custom class `NetworkSettings` here. That only exists because connlib used to emit all this information in different events. It is now all in one event so we should be able to actually get rid of `NetworkSettings` and construct the `NEPacketTunnelNetworkSettings` directly and save us the indirection. Or if that is not `Equatable`, can we at least refactor this by comparing `NetworkSettings` instead of creating yet another struct?

**Review by thomaseizinger — APPROVED** [review]
Concept ACK but I'd like to see this refactored to remove some of the indirection.

File: swift/apple/FirezoneNetworkExtension/NetworkSettings.swift (hunk 1 above)
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/NetworkSettings.swift]: So unfortunately, after testing, it appears that `NEPacketTunnelNetworkSettings` that are instantiated with the same values are not equal. So we will need to track these separately.

Are you suggesting we instantiate a new instance of `NetworkSettings` on each callback and check for equality from Adapter? I can try that.

Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/NetworkSettings.swift]: > Are you suggesting we instantiate a new instance of `NetworkSettings` on each callback and check for equality from Adapter? I can try that.

Yeah, basically have `NetworkSettings` perform the role of what you are trying to do with `AppliedSettings` in here. Maybe the `apply` function needs to move out of the class such that `NetworkSettings` becomes a side-effect free data structure that makes sense to keep around and compare against itself.

It is kind of weird that we are passing the packet tunnel provider _into_ the `NetworkSettings` and then delegate `apply` to it. I think it would be cleaner if the side-effect was outside of `NetworkSettings`. For example, what you could do is create an `update` function on `NetworkSettings` where you pass in all new values and only if they differ, you get back a `NEPacketTunnelNetworkSettings` that you can then pass to the packet tunnel provider.

That would also allow you to unit test that we are only creating the settings if there is an actual change.

**Review by jamilbk — COMMENTED** [review]
Tested:

- [x] macOS 15.7.2
- [x] iOS 26.1
- [x] Tested enabling / disabling a resource -> settings applied
- [x] Tested updating a resource name -> settings not applied
- [x] Tested pinging a resource that's connected to an offline Site -> settings not applied

This fixes a long-standing issue I've faced where opening a Resource in Chrome after initially connecting would always fail with `ERR_NETWORK_CHANGED`.

File: swift/apple/FirezoneNetworkExtension/NetworkSettings.swift [hunk 2]
```diff
@@ -32,6 +32,24 @@ class NetworkSettings {
...
+      && lhs.routes4.count == rhs.routes4.count
+      && lhs.routes6.count == rhs.routes6.count
+      && zip(lhs.routes4, rhs.routes4).allSatisfy {
+        $0.destinationAddress == $1.destinationAddress
+          && $0.destinationSubnetMask == $1.destinationSubnetMask
+      }
+      && zip(lhs.routes6, rhs.routes6).allSatisfy {
+        $0.destinationAddress == $1.destinationAddress
+          && $0.destinationNetworkPrefixLength == $1.destinationNetworkPrefixLength
+      }
```
[the remark this answers is not in the document]
Comment (thomaseizinger) [reply swift/apple/FirezoneNetworkExtension/NetworkSettings.swift:74]: I think this is a valid point. Connlib does sort them I believe but defense-in-depth would be good.

**Review by thomaseizinger — APPROVED** [review]
Nice, that is a much cleaner diff. We can do the refactoring of `NetworkSettings` another time.

File: swift/apple/FirezoneNetworkExtension/NetworkSettings.swift (hunk 2 above)
[the remark this answers is not in the document]
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/NetworkSettings.swift:74]: Ok I've implemented this, and also had to do more refactoring since this wasn't actually comparing equality properly.

The issue was that class types are reference types in Swift, so setting `lastAppliedNetworkSettings` was a bug.

I've now made this a `struct` type and updated the relevant bits to make this work, including removing the packetTunnelProvider property in it.

This is going to all completely change with making Adapter an actor so I'm not sure further refactoring is warranted for now.

[the remark this answers is not in the document]
Comment (jamilbk) [reply swift/apple/FirezoneNetworkExtension/NetworkSettings.swift:74]: I also added a `dnsAddresses` property on NetworkSettings to track these across updates to fix a bug where we need to apply the networkSettings to flush the DNS cache when _only_ a resource's DNS address has changed and not any of the routes hitting the routing table.

File: swift/apple/FirezoneNetworkExtension/Adapter.swift [hunk 3]
```diff
@@ -597,7 +618,8 @@ class Adapter: @unchecked Sendable {
     // If matchDomains is an empty string, /etc/resolv.conf will contain connlib's
     // sentinel, which isn't helpful to us.
     private func resetToSystemDNSGettingBindResolvers() -> [String] {
```
Comment (jamilbk) [inline swift/apple/FirezoneNetworkExtension/Adapter.swift:620]: I cannot wait for this hackjob to be removed in #10979

**Comment by jamilbk** [comment]
I've retested this on both macOS and iOS and correctly receive both UI updates and networkSettings apply updates properly.
