### PR TITLE
fix(portal): dump smtp tls_options correctly

### LINKED ISSUE #3208: SMTP Adapter: handling of TLS options
**Describe the bug**

Firstly, I know that you `don't support self-hosting the control plane at this time` but I found this bug while trying to do so, I hope you will consider it.

I was trying to use the email adapter `Swoosh.Adapters.SMTP` and the `tls_options` appears not to be handled correctly. This option is not in Swoosh documentation but is forwarded to the `gen-smtp` lib used by Swoosh:
https://github.com/gen-smtp/gen_smtp/blob/master/README.md?plain=1#L86

**To Reproduce**
Use a SMTP server that for example supports only STARTTLS and its certificate cannot be verified.

Here is a config that works after modifying the default dumper in your code:
```
OUTBOUND_EMAIL_ADAPTER_OPTS: |
    {
        "relay": "smtp.domain.tld",
        "username": "{{ .username | toString }}",
        "password": "{{ .password | toString }}",
        "ssl": false,
        "tls": "always",
        "auth": "always",
        "port": 587,
        "retries": 5,
        "no_mx_lookups": true,
        "tls_options": {
            "verify": "verify_none"
        }
      }
```

Bad config:
```
[adapter: Swoosh.Adapters.SMTP, from_email: \"firezone@domain.tld\", auth: \"always\", no_mx_lookups: true, password: \"password\", port: 587, relay: \"smtp.domain.tld\", retries: 5, ssl: false, tls: \"always\", tls_options: %{\"verify\" => \"verify_none\"}, username: \"username\"]
```

Good config:
```
[adapter: Swoosh.Adapters.SMTP, from_email: \"firezone@domain.tld\", auth: \"always\", no_mx_lookups: true, password: \"password\", port: 587, relay: \"smtp.domain.tld\", retries: 5, ssl: false, tls: \"always\", tls_options: [verify: :verify_none], username: \"username\"]
```

As `tls_options` is used by Erlang ssl lib, I think you could reuse the dump_ssl_opts dumper.
I can do the PR and modify the existing dumper of create a dedicated one for `erlang_cluster_adapter_config`. What do you think?

**Expected behavior**
It should connect to the SMTP server and send mails.

**Platform (please complete the following information):**
 - Firezone Version 1.0.0-c73dd141709bc2b7c3f66bf6952065691f968286
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 5.15.0
 - Deployment method: Kubernetes

**Additional context**

### PR DESCRIPTION
**Pull request by Intuinewin**
Resolves #3208

### CODE REVIEW

File: elixir/apps/domain/lib/domain/config/definitions.ex [hunk 1]
```diff
@@ -590,7 +590,20 @@ defmodule Domain.Config.Definitions do
     # TODO: validate opts are present if adapter is not NOOP one
     default: %{},
     sensitive: true,
-    dump: &Dumper.keyword/1
+    dump: fn map ->
+      keyword = Dumper.keyword(map)
+
+      cond do
+        compile_config!(:outbound_email_adapter) == Swoosh.Adapters.SMTP ->
```
Comment (AndrewDryga) [inline elixir/apps/domain/lib/domain/config/definitions.ex]: @Intuinewin I think we don't need to check for the adapter and can assume that TLS options should always be mapped.

Comment (Intuinewin) [reply elixir/apps/domain/lib/domain/config/definitions.ex]: Is it better?

Comment (AndrewDryga) [reply elixir/apps/domain/lib/domain/config/definitions.ex]: Yes, thank you
