### PR TITLE
fix(portal): handle cases where policy group_id null

### LINKED ISSUE #12204: ArgumentError: cannot dump given UUID to binary: nil
Sentry Issue: [PORTAL-Z4](https://firezone-inc.sentry.io/issues/7271361348/?referrer=github_integration)

```
ArgumentError: cannot dump given UUID to binary: nil
  File "lib/ecto/uuid.ex", line 157, in Ecto.UUID.dump!/1
  File "lib/portal/cache/cacheable.ex", line 44, in Portal.Cache.Cacheable.Portal.Policy.to_cache/1
  File "lib/portal/cache/client.ex", line 374, in Portal.Cache.Client.delete_policy/5
  File "lib/portal_api/client/channel.ex", line 973, in PortalAPI.Client.Channel.handle_change/2
  File "lib/portal_api/client/channel.ex", line 97, in PortalAPI.Client.Channel.handle_info/2
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes policy group sync metadata handling and a nil-UUID crash in cache conversion.

- Fixed crash when caching policies with group_id = nil by making policy cache UUID dumping nil-safe.
- Ensured group_idp_id is synchronized whenever group_id changes in both REST API (POST/PUT /policies) and LiveView policy forms (new and edit).
- Sync behavior is now:
    1. If selected group_id is a synced group, set group_idp_id to that group’s idp_id.
    2. If selected group_id is not synced, set group_idp_id to nil.
- Updated policy API schema to allow nullable group_id in responses.
- Added/updated tests for nil group_id cache conversion, REST create/update sync behavior, LiveView new/edit sync behavior, and orphaned policy response with group_id = nil.

---

Fixes #12204

### CODE REVIEW

File: elixir/lib/portal_api/controllers/policy_controller.ex [hunk 1]
```diff
@@ -207,13 +208,13 @@ defmodule PortalAPI.PolicyController do
     end
 
     defp populate_group_idp_id(changeset, subject) do
-      case get_field(changeset, :group_id) do
+      case get_change(changeset, :group_id) do
```
Comment (jamilbk) [inline elixir/lib/portal_api/controllers/policy_controller.ex:211]: I realize that we only need to fetch the associated group when the group_id is changing - will avoid a needless query when this doesn't change.

**Review by bmanifold — APPROVED** [review]
