### PR TITLE
fix(apple): sync tunnel configuration after saving

### LINKED ISSUE #4321: bug(apple client): can't sign in
#### Describe the bug

I can't sign in on my Macbook

#### To Reproduce

I try to sign in. The webview opens, I click "Firezone" and "Google Workspace" as usual. It says, "You may close this window" and auto-closes as usual.

Then the icon animates for a while, and it says "Signed in, resources unavailable, connecting..." and eventually goes back to signed-out state.

#### Expected behavior

Sign-in should succeed

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C04JR58F7ND/p1711414860003079?thread_ts=1711413805.387969&cid=C04JR58F7ND

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (1711413647)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS Sonoma
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

Was this the bug that was mentioned about the NetworkExtension needing to be cycled during updates? That should only be for local builds, not CI/CD builds, even in TestFlight, right?

### LINKED ISSUE #4339: bug(macos Client): At startup the Welcome window flashes for a couple frames before closing
#### Describe the bug

The window flashes for a few frames.

#### To Reproduce

Close the macOS Client and re-open it. The Welcome window flashes because it's opened and immediately closed

#### Expected behavior

Expect the window to not open at all if it's not the first boot.

#### Screenshots / Logs

https://github.com/firezone/firezone/assets/13400041/6a5cdef7-f9bb-4afd-a97b-5df0ca8ad8c6

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (1711524489)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS Sonoma
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ TestFlight

#### Additional context

In the Tauri Client I do it the opposite way, the window is hidden by default and I only show it when needed. Is that possible on macOS?

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #4321 
Fixes #4339

### CODE REVIEW

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift [hunk 1]
```diff
@@ -123,10 +123,7 @@ public final class TunnelStore: ObservableObject {
   func createManager() async throws {
     let protocolConfiguration = NETunnelProviderProtocol()
     let manager = NETunnelProviderManager()
-    let providerConfiguration =
-      protocolConfiguration.providerConfiguration
-      as? [String: String]
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:128]: This was ~~the~~ a bug.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift [hunk 2]
```diff
@@ -26,12 +26,12 @@ public final class SettingsViewModel: ObservableObject {
   public init(tunnelStore: TunnelStore, logger: AppLogger) {
     self.tunnelStore = tunnelStore
     self.logger = logger
-    settings = Settings.defaultValue
+    self.settings = tunnelStore.settings
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift:29]: Fixes another exposed race condition that we hit more often now because we connect faster and don't switch between states unless we need to.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift [hunk 3]
```diff
@@ -26,12 +26,12 @@ public final class SettingsViewModel: ObservableObject {
...
 
-    loadSettings()
+    setupObservers()
   }
 
-  func loadSettings() {
+  func setupObservers() {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift:34]: Renamed to match the convention elsewhere

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift [hunk 4]
```diff
@@ -557,8 +557,8 @@ public struct SettingsView: View {
     dismiss()
   }
 
-  func loadSettings() {
-    model.loadSettings()
+  func reloadSettings() {
+    model.settings = model.tunnelStore.settings
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift:561]: Not sure why this was rebinding settings each time... maybe a memory leak

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/DeviceMetadata.swift [hunk 5]
```diff
@@ -5,14 +5,23 @@
...
 import Foundation
 
 #if os(iOS)
   import UIKit.UIDevice
 #endif
 
 public class DeviceMetadata {
+  // If firezone-id hasn't ever been written, the app is considered
+  // to be launched for the first time.
+  public static func firstTime() -> Bool {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/DeviceMetadata.swift:17]: Moved to DeviceMetadata since it doesn't really belong in TunnelStore

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Keychain/Keychain.swift [hunk 6]
```diff
@@ -20,7 +20,7 @@ public enum KeychainError: Error {
 public actor Keychain {
   private let label = "Firezone token"
   private let description = "Firezone access token used to authenticate the client."
-  private let service = "dev.firezone.firezone"
+  private let service = Bundle.main.bundleIdentifier!
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Keychain/Keychain.swift:23]: This is updated just so that debug testing and release testing don't clobber each other's Keychain items.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift [hunk 7]
```diff
@@ -27,12 +27,13 @@ struct Settings: Equatable {
...
-  static func fromProviderConfiguration(providerConfiguration: [String: String]?) -> Settings {
-    if let providerConfiguration = providerConfiguration {
+  static func fromProviderConfiguration(providerConfiguration: [String: Any]?) -> Settings {
+    if let providerConfiguration = providerConfiguration as? [String: String] {
       return Settings(
         authBaseURL: providerConfiguration[TunnelStoreKeys.authBaseURL]
           ?? Settings.defaultValue.authBaseURL,
-        apiURL: providerConfiguration[TunnelStoreKeys.apiURL] ?? Settings.defaultValue.apiURL,
+        apiURL: providerConfiguration[TunnelStoreKeys.apiURL]
+          ?? Settings.defaultValue.apiURL,
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift:36]: Cleanup

**Review by jamilbk — COMMENTED** [review]
This TunnelStore class is full of code smells still, but at least it's commented. Baby steps.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift [hunk 8]
```diff
@@ -27,12 +27,13 @@ struct Settings: Equatable {
   }
 
   // Convert provider configuration (which may have empty fields if it was tampered with) to Settings
-  static func fromProviderConfiguration(providerConfiguration: [String: String]?) -> Settings {
-    if let providerConfiguration = providerConfiguration {
+  static func fromProviderConfiguration(providerConfiguration: [String: Any]?) -> Settings {
```
Comment (ReactorScram) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift:30]: Why did this change to Any?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift [hunk 9]
```diff
@@ -79,16 +78,17 @@ public final class TunnelStore: ObservableObject {
     setupTunnelObservers()
 
     Task {
-      // loadAllFromPreferences() returns list of tunnel configurations we created. Since our bundle ID
-      // can change (by us), find the one that's current and ignore the others.
+      // loadAllFromPreferences() returns list of tunnel configurations created by our bundle ID.
+      // Since our bundle ID can change (by us), find the one that's current and ignore the others.
```
Comment (ReactorScram) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:82]: It can't change at runtime, right? This is talking about the ID changing after an update is installed?

The App Store doesn't use the bundle as a package ID? Is such a thing possible?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift (hunk 1 above)
Comment (ReactorScram) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:128]: Was it trying to read something that wasn't there?

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift [hunk 10]
```diff
@@ -235,6 +223,8 @@ public final class TunnelStore: ObservableObject {
     try await stop(clearToken: true)
   }
 
+  // Network Extensions don't have a 2-way binding up to the GUI process,
+  // so we need to periodically ask the tunnel process for them.
```
Comment (ReactorScram) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:227]: Right, you mentioned that, now I remember.

**Review by ReactorScram — APPROVED** [review]
I don't understand most of it and I just skimmed through it

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift (hunk 8 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Models/Settings.swift:30]: We take on the responsibility of casting in here instead of making the caller do it

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift (hunk 9 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:82]: Nah, this can't change at runtime. It's inexorably linked to other things in the App Store listing, so it wouldn't be easy to change.

One scenario we may want to change it though is if we build a different Network Extension for some reason (different transport, DNS proxy, content filter, etc) and want to include both or update this one's name.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift (hunk 1 above)
Comment (jamilbk) [reply swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift:128]: I think by default it's an empty dict `[]` which can be cast to `[String: String]`, causing the conditional to evaluate `true`.
