### PR TITLE
fix(ios/android): Pass device name and os version as overrides over connect

### LINKED ISSUE #3035: ios: Device name and user agent aren't shown correctly
These will need to be passed over the FFI or retrieved in a callback.

These can be pulled from [UIDevice](https://developer.apple.com/documentation/uikit/uidevice)

s

### LINKED ISSUE #3037: Android: Device name and OS version not shown correctly
Screenshot 2023-12-28 at 6 12 30 PM

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #3035 
Fixes #3037 

# Before

Screenshot 2023-12-28 at 8 05 31 AM

Screenshot 2023-12-28 at 6 12 30 PM

# After

Screenshot 2023-12-28 at 10 48 31 AM
Screenshot 2023-12-28 at 6 29 37 PM

### CODE REVIEW

File: rust/connlib/clients/apple/src/lib.rs [hunk 1]
```diff
@@ -174,10 +176,14 @@ fn init_logging(log_dir: PathBuf, log_filter: String) -> file_logger::Handle {
 }
 
 impl WrappedSession {
+    // TODO: Some of these arguments could be combined into a ConnectInfo struct or something
+    #[allow(clippy::too_many_arguments)]
```
Comment (jamilbk) [inline rust/connlib/clients/apple/src/lib.rs:181]: Probably needs some refactoring soon

**Comment by jamilbk** [comment]
The other option I considered in this PR is using a callback to get the info, but then we'd have to pass the callbacks instance into PhoenixChannel.

File: rust/connlib/clients/apple/src/lib.rs (hunk 1 above)
Comment (thomaseizinger) [reply rust/connlib/clients/apple/src/lib.rs:181]: I wouldn't worry about it too much for now. The real problem here is that we are passing too much information "down" into the tunnel only to pass it back "up" as part of making an HTTP call to the portal.

Similarly to the gateway, I think the solution here is to separate the components better. Decouple communication with the portal from the tunnel and session. This will result in some code "duplication" between the clients but I think that is better than passing several optional parameters into the session. The fact that we want to customize individual clients deep down in the stack IMO is a sign that we are trying too hard to deduplicate things here.

Comment (jamilbk) [reply rust/connlib/clients/apple/src/lib.rs:181]: > Decouple communication with the portal from the tunnel and session

I think I see where you're coming from, but I'm not sure I'm quite following what you mean by this. I was thinking the Session is the tunnel + portal coms. We could make these parameters a callback instead, and the relevant platforms could call them to get the info they need as opposed to passing them through the Session connect.

That might be the better approach here. Thoughts @conectado ?

File: rust/connlib/clients/apple/src/lib.rs [hunk 2]
```diff
@@ -174,10 +176,14 @@ fn init_logging(log_dir: PathBuf, log_filter: String) -> file_logger::Handle {
...
     fn connect(
         api_url: String,
         token: String,
         device_id: String,
+        device_name_override: Option<String>,
+        os_version_override: Option<String>,
```
Comment (conectado) [inline rust/connlib/clients/apple/src/lib.rs:187]: I think we always override both at the same time so we could perhaps merge these parameters.

File: rust/connlib/clients/apple/src/lib.rs (hunk 1 above)
Comment (conectado) [reply rust/connlib/clients/apple/src/lib.rs:181]: I think what thomas is suggesting is: similarly to the gateway, we pass to the `Session` a `PhoenixChannel` that we already created(+ the init parameters) which I'd be up for, we can do it as part of refactoring the `control` module out of `client-shared`. This makes sense so that `connect` would only need to take that channel and the `CallbackHandler` (we can also just setup the logging before calling `connect` as well)

But we can do that later, for now I think it'd be simpler in a next PR if we could just pass the `user_agent` as part of `connect` so that we don't need to juggle so many parameters.

File: rust/connlib/clients/apple/src/lib.rs (hunk 2 above)
Comment (conectado) [reply rust/connlib/clients/apple/src/lib.rs:187]: Maybe with this change we can re-enable clippy's lint

File: rust/connlib/clients/apple/src/lib.rs (hunk 1 above)
Comment (jamilbk) [reply rust/connlib/clients/apple/src/lib.rs:181]: @conectado Yeah passing `user_agent` in connect is a good call, that'd allow us to use the app version number instead of connlib's.

File: rust/connlib/clients/apple/src/lib.rs (hunk 2 above)
Comment (jamilbk) [reply rust/connlib/clients/apple/src/lib.rs:187]: Possibly, will do some refactoring and see.

**Review by roop — APPROVED** [review]
Swift part looks good

File: rust/connlib/clients/apple/src/lib.rs (hunk 2 above)
Comment (jamilbk) [reply rust/connlib/clients/apple/src/lib.rs:187]: Unfortunately these are passed in different parts of the connection request to the portal; user agent is a header, while the device ID is sha256'd and device_name are added as parameters.

File: rust/connlib/clients/apple/src/lib.rs (hunk 1 above)
Comment (jamilbk) [reply rust/connlib/clients/apple/src/lib.rs:181]: On second thought, these parameters are used / modified independently within connlib so I'm not sure it makes sense to join them and pass them as a String.

I also started refactoring this to make these callbacks instead (e.g. `get_device_id()`, `get_device_name()`, etc) but then we're passing around the callbacks and its error handling to the individual components which felt dirty.

~~I'll see if I can pass a struct down instead.~~

Edit: it might be easier to just refactor this when we standardize the PhoenixChannel out of the control module like @conectado suggested.

This is a user-facing bug, so can we get this in for now?
