### PR TITLE
fix(windows): don't crash if the saved log filter is invalid

### LINKED ISSUE #3452: bug(windows): Don't crash on invalid log filters
I want to be sure it doesn't crash or soft-lock or something if the user makes a typo in the filter field
```[tasklist]
### Tasks
- [ ] Add warning dialog at startup
- [ ] Use default filter if custom filter is invalid
```

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #3452

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
LGTM. This will probably come up in other clients too.

File: rust/windows-client/src-tauri/src/client/gui.rs [hunk 1]
```diff
@@ -63,6 +63,28 @@ pub(crate) fn run(params: client::GuiParams) -> Result<()> {
 
     let advanced_settings = settings::load_advanced_settings().unwrap_or_default();
 
+    // If the log filter is unparsable, show an error and use the default
+    // Fixes <https://github.com/firezone/firezone/issues/3452>
+    let advanced_settings =
+        match tracing_subscriber::EnvFilter::from_str(&advanced_settings.log_filter) {
+            Ok(_) => advanced_settings,
+            Err(_) => {
```
Comment (thomaseizinger) [inline rust/windows-client/src-tauri/src/client/gui.rs:71]: We could also write a `warn` to the log that contains the error so that an advanced user could fix it.

File: rust/windows-client/src-tauri/Cargo.toml [hunk 2]
```diff
@@ -46,6 +46,7 @@ rand = "0.8.5"
 windows-implement = "0.52.0"
 sadness-generator = "0.5.0"
 bincode = "1.3.3"
+native-dialog = "0.7.0"
```
Comment (thomaseizinger) [inline rust/windows-client/src-tauri/Cargo.toml:49]: Do we necessarily need to use a cross-platform library here? It appears that it comes with a few limitations: https://github.com/native-dialog-rs/native-dialog-rs?tab=readme-ov-file#misc

Does Tauri not have a way of showing a dialog?

**Review by thomaseizinger — APPROVED** [review]
Two non-blocking comments!

File: rust/windows-client/src-tauri/Cargo.toml (hunk 2 above)
Comment (ReactorScram) [reply rust/windows-client/src-tauri/Cargo.toml:49]: Tauri does, but I got this stuck in my head cause I was working on #3464 at the same time and I was going to use `native-dialog` for that one anyway. (And in that one, Tauri isn't available)

I agree it's overkill, we could call Win32's `MessageBox` API directly if we need to later
