### PR TITLE
fix(portal): more robust replication pid discovery

### LINKED ISSUE #9911: Minimize replication downtime during deploys
It seems that even with https://github.com/firezone/infra/pull/67, the old replication connection pids are staying alive in Postgres well after the VMs themselves are spun down. We need to figure out why that's the case and prevent this lag during deploys.

### PR DESCRIPTION
**Pull request by jamilbk**
When debugging why we're receiving "Failed to start replication connection" errors on deploy, it was discovered that there's a bug in the Process discovery mechanism that new nodes use to attempt to link to the existing replication connection. When restarting an existing `domain` container that's not doing replication, we see this:

```
{"message":"Elixir.Domain.Events.ReplicationConnection: Publication tables are up to date","time":"2025-07-22T07:18:45.948Z","domain":["elixir"],"application":"domain","severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.Events.ReplicationConnection.handle_publication_tables_diff/2","line":2,"file":"lib/domain/events/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.764.0>"}}
{"message":"notifier only receiving messages from its own node, functionality may be degraded","time":"2025-07-22T07:18:45.942Z","domain":["elixir"],"application":"oban","source":"oban","severity":"DEBUG","event":"notifier:switch","connectivity_status":"solitary","logging.googleapis.com/sourceLocation":{"function":"Elixir.Oban.Telemetry.log/2","line":624,"file":"lib/oban/telemetry.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.756.0>"}}
{"message":"Elixir.Domain.ChangeLogs.ReplicationConnection: Publication tables are up to date","time":"2025-07-22T07:18:45.952Z","domain":["elixir"],"application":"domain","severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.ChangeLogs.ReplicationConnection.handle_publication_tables_diff/2","line":2,"file":"lib/domain/change_logs/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.763.0>"}}
{"message":"Elixir.Domain.ChangeLogs.ReplicationConnection: Starting replication slot change_logs_slot","time":"2025-07-22T07:18:45.966Z","state":"[REDACTED]","domain":["elixir"],"application":"domain","severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.ChangeLogs.ReplicationConnection.handle_result/2","line":2,"file":"lib/domain/change_logs/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.763.0>"}}
{"message":"Elixir.Domain.Events.ReplicationConnection: Starting replication slot events_slot","time":"2025-07-22T07:18:45.966Z","state":"[REDACTED]","domain":["elixir"],"application":"domain","severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.Events.ReplicationConnection.handle_result/2","line":2,"file":"lib/domain/events/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.764.0>"}}
{"message":"Elixir.Domain.ChangeLogs.ReplicationConnection: Replication connection disconnected","time":"2025-07-22T07:18:45.977Z","domain":["elixir"],"application":"domain","counter":0,"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.ChangeLogs.ReplicationConnection.handle_disconnect/1","line":2,"file":"lib/domain/change_logs/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.763.0>"}}
{"message":"Elixir.Domain.Events.ReplicationConnection: Replication connection disconnected","time":"2025-07-22T07:18:45.977Z","domain":["elixir"],"application":"domain","counter":0,"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.Events.ReplicationConnection.handle_disconnect/1","line":2,"file":"lib/domain/events/replication_connection.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.764.0>"}}
{"message":"Failed to start replication connection Elixir.Domain.Events.ReplicationConnection","reason":"%Postgrex.Error{message: nil, postgres: %{code: :object_in_use, line: \"607\", message: \"replication slot \\\"events_slot\\\" is active for PID 135123\", file: \"slot.c\", unknown: \"ERROR\", severity: \"ERROR\", pg_code: \"55006\", routine: \"ReplicationSlotAcquire\"}, connection_id: 136400, query: nil}","time":"2025-07-22T07:18:45.978Z","domain":["elixir"],"application":"domain","max_retries":10,"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.Replication.Manager.handle_info/2","line":41,"file":"lib/domain/replication/manager.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.761.0>"},"retries":0}
{"message":"Failed to start replication connection Elixir.Domain.ChangeLogs.ReplicationConnection","reason":"%Postgrex.Error{message: nil, postgres: %{code: :object_in_use, line: \"607\", message: \"replication slot \\\"change_logs_slot\\\" is active for PID 135124\", file: \"slot.c\", unknown: \"ERROR\", severity: \"ERROR\", pg_code: \"55006\", routine: \"ReplicationSlotAcquire\"}, connection_id: 136401, query: nil}","time":"2025-07-22T07:18:45.978Z","domain":["elixir"],"application":"domain","max_retries":10,"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"Elixir.Domain.Replication.Manager.handle_info/2","line":41,"file":"lib/domain/replication/manager.ex"},"logging.googleapis.com/operation":{"producer":"#PID<0.760.0>"},"retries":0}
```

Before, we relied on `start_link` telling us that there was an existing pid running in the cluster. However, from the output above, it appears that may not always be reliable.

Instead, we first check explicitly where the running process is and, if alive, we try linking to it. If not, we try starting the connection ourselves.

Once linked to the process, we react to it being torn down as well, causing a first-one-wins scenario where all nodes will attempt to start replication, minimizing downtime during deploys.

Now that https://github.com/firezone/infra/pull/94 is in place, I did verify we are properly handling SIGTERM in the BEAM, so the deployment would now go like this:

1. GCP brings up the new nodes, they all find the existing pid and link to it
2. GCP sends SIGTERM to the old nodes
3. The _actual_ pid receives SIGTERM and exits
4. This exit propagates to all other nodes due to the link
5. Some node will "win", and the others will end up linking to it

Fixes #9911

### CODE REVIEW

File: elixir/apps/domain/lib/domain/replication/manager.ex [hunk 1]
```diff
@@ -26,32 +26,42 @@ defmodule Domain.Replication.Manager do
...
+              {:ok, new_pid} ->
+                {:noreply, %{state | retries: 0, connection_pid: new_pid}}
+
+              {:error, {:already_started, new_pid}} ->
+                Process.link(new_pid)
+                {:noreply, %{state | retries: 0, connection_pid: new_pid}}
+
+              {:error, reason} ->
+                handle_start_error(reason, retries, state, connection_module)
+            end
```
Comment (bmanifold) [inline elixir/apps/domain/lib/domain/replication/manager.ex]: It looks like this case statement is repeated up above as well.  Would it make sense to pull this out in to a private function?

Comment (jamilbk) [reply elixir/apps/domain/lib/domain/replication/manager.ex]: Yeah, let me refactor it a bit and also handle the race that Copilot caught.

Comment (jamilbk) [reply elixir/apps/domain/lib/domain/replication/manager.ex]: Made the following changes:

- simplified function definitions to just take a `state`
- handled edge case where `Process.link` could return an `ArgumentError`
- cancels the retry timer when a pid is successfully linked (before it would no-op every 30s)
- increased retry timer to 5s + 12 times

**Review by bmanifold — APPROVED** [review]
