### PR TITLE
fix(portal): allocate tun addresses in O(1) time

### LINKED ISSUE #10151: Refactor address claiming algorithm
- Drop `network_addresses`
- Add index to `clients` and `gateways`
- Refactor query to be O(n)
- Ensure taking a lock / transaction won't be an issue

### LINKED ISSUE #11153: Portal database seed error
Just run into this when trying to merge a PR: https://github.com/firezone/firezone/actions/runs/20203201301/job/57998190887

### PR DESCRIPTION
**Pull request by jamilbk**
When inserting new Clients and Gateways, we need a unique IPv4 and IPv6 address within our designated ranges to reserve to use for the tunnel interface IPs.

This is unfortunately not a trivial problem to solve. It requires the use of a shared `network_addresses` table which is used to ensure unique addresses across both entity types with a foreign key from `(account_id, address)` on network_addresses to `(account_id, ipv4)` on clients/gateways.

To find a free address, we used an algorithm that involved:

1. Opening a transaction
2. Run a query to scan for available addresses in the `network_addresses` table by picking a random offset into the range and then scanning forwards *and* backwards for the first unused IP
3. Grab it 
4. Perform the insert for both network_address and client/gateway

This meant that as occupancy grows, the amount of time we hold open the transaction (and risk for contention) grows as well.

To reduce the average-case runtime of this allocation from O(n) to O(1) we implement the following algorithm:

- Upon insert, find the max used address, increment and save counter then attempt to insert address
- If success, return address
- If collision, increment and try again
- If num_iterations > num_addresses_in_cidr, we've exhausted the pool - raise an exception

The tradeoff here is that addresses are handed out with a sequential pattern instead of the prior random pattern, but random address allocation was never a requirement for this particular function and sequential allocation should be fine.

Fixes #11153 
Fixes #10151

### CODE REVIEW

File: elixir/apps/domain/test/domain/network_test.exs [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+        # IPv6 addresses should be sequential
+        assert %Postgrex.INET{address: {64_768, 8_225, 4_369, 0, 0, 0, 0, 2}, netmask: nil} =
+                 addr1
+
+        assert %Postgrex.INET{address: {64_768, 8_225, 4_369, 0, 0, 0, 0, 3}, netmask: nil} =
+                 addr2
+      end)
+    end
+
+    test "different accounts get independent address spaces", %{account: account1} do
```
Comment (thomaseizinger) [inline elixir/apps/domain/test/domain/network_test.exs]: Interesting, has this always been the case?

Comment (jamilbk) [reply elixir/apps/domain/test/domain/network_test.exs]: Yes

File: elixir/apps/domain/priv/repo/seeds.exs [hunk 2]
```diff
@@ -88,10 +88,22 @@ defmodule Domain.Repo.Seeds do
...
-  # Uses UUID hash for deterministic, unique IPs
+  # Allocate tunnel IPs for clients/gateways
+  # When STATIC_SEEDS is set, uses deterministic UUID-based IPs for local development
+  # Otherwise uses the sequential network address allocation system
   defp create_tunnel_ips(account_id, uuid) do
+    if System.get_env("STATIC_SEEDS") == "true" do
+      create_static_tunnel_ips(account_id, uuid)
+    else
+      ipv4 = Domain.Network.fetch_next_available_address!(account_id, :ipv4)
+      ipv6 = Domain.Network.fetch_next_available_address!(account_id, :ipv6)
```
[the remark this answers is not in the document]
Comment (jamilbk) [reply elixir/apps/domain/priv/repo/seeds.exs]: We control the seeds environment, so these shouldn't fail.

File: elixir/apps/domain/priv/repo/migrations/20251214053535_split_network_addresses.exs [hunk 3]
```diff
@@ -0,0 +1,185 @@
+defmodule Domain.Repo.Migrations.SplitNetworkAddresses do
+  use Ecto.Migration
+
+  def up do
+    # Create ipv4_addresses table
+    create table(:ipv4_addresses, primary_key: false) do
```
Comment (thomaseizinger) [inline elixir/apps/domain/priv/repo/migrations/20251214053535_split_network_addresses.exs:6]: Should the table maybe be called `tunnel_ipv4_addresses`?

File: elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+        IF v_attempts > v_total_addresses THEN
+          RAISE EXCEPTION 'Address pool exhausted for account %', p_account_id
+            USING ERRCODE = 'P0002';
+        END IF;
+
+        BEGIN
+          IF p_type = 'ipv4' THEN
+            INSERT INTO ipv4_addresses (account_id, address, inserted_at)
+            VALUES (p_account_id, v_next_address, NOW());
+          ELSE
```
Comment (bmanifold) [inline elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs]: Same as above about ELSEIF

File: elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+      v_max_address := host(broadcast(p_cidr))::inet - 1;
+      v_max_offset := (v_max_address - v_base_address)::bigint;
+      v_total_addresses := v_max_offset;
+
+      -- Find the current max address for this account
+      IF p_type = 'ipv4' THEN
+        SELECT MAX(address) INTO v_current_max
+        FROM ipv4_addresses
+        WHERE account_id = p_account_id;
+      ELSE
```
Comment (bmanifold) [inline elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs:46]: Should we make this an ELSEIF p_type = 'ipv6' and then have an ELSE block that throws an error?

Mainly asking/recommending since we're in SQL and it might not be as easy to troubleshoot if things were to ever go wrong.

File: elixir/apps/domain/priv/repo/migrations/20251214053535_split_network_addresses.exs (hunk 3 above)
Comment (jamilbk) [reply elixir/apps/domain/priv/repo/migrations/20251214053535_split_network_addresses.exs:6]: Hmmm this table is not exposed anywhere to the end user so I'd prefer to keep naming simpler since there are no other types of ipv4_address tables/schemas.

File: elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs (hunk 5 above)
Comment (jamilbk) [reply elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs:46]: Yeah, probably not a bad idea.

File: elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs (hunk 4 above)
Comment (jamilbk) [reply elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs]: fixed

File: elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs (hunk 5 above)
Comment (jamilbk) [reply elixir/apps/domain/priv/repo/migrations/20251214053536_refactor_network_address_allocation.exs:46]: fixed

**Review by bmanifold — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@jamilbk Looks like the DB seeding isn't quite deterministic yet and can still fail?

**Comment by jamilbk** [comment]
> @jamilbk Looks like the DB seeding isn't quite deterministic yet and can still fail?

Taking a look.

**Comment by jamilbk** [comment]
> > @jamilbk Looks like the DB seeding isn't quite deterministic yet and can still fail?
> 
> Taking a look.

Yep, I've simply removed STATIC_SEEDS from affecting tun IPs. In both cases (whether STATIC_SEEDS is set / unset) we will generate deterministic TUN IPs based on the monotonic counter.
