### PR TITLE
fix(portal): Improve OIDC usability and fix unexpected Mint.TransportError causing crash

### LINKED ISSUE #3044: Add OIDC docs for Fusion
Got some feedback on the use of our OIDC connector:

* Document Fusion auth
* crash when typing out the document URI
* minor UI / typos

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #3044

### CODE REVIEW

File: elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex [hunk 1]
```diff
@@ -6,14 +6,21 @@ defmodule Web.Settings.IdentityProviders.OpenIDConnect.Components do
     <div class="max-w-2xl px-4 py-8 mx-auto lg:py-12">
       <.form for={@form} phx-change={:change} phx-submit={:submit}>
         <.step>
-          <:title>Step 1. Create OAuth app in your identity provider</:title>
+          <:title>Step 1. Create OAuth client in your identity provider</:title>
```
Comment (bmanifold) [inline elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex]: Just curious on the change here.  I've always seen IDPs use the 'app' terminology, such as: [Okta Docs](https://help.okta.com/en-us/content/topics/apps/apps_app_integration_wizard_oidc.htm)

Just wondering if you had seen different.

File: website/src/app/kb/authenticate/oidc/fusion/readme.mdx [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+     alt="image of oauth tab"
+     src="/images/kb/authenticate/oidc/fusion/setup-jwt.png"
+     width="800"
+     height="800"
+     className="shadow mx-auto"
+   />
+1. Save your application. Then go back into your application in edit mode. Copy
+   the client id / secret to enter into Firezone in the next step.
+
+## Step 2: Create identity provider in Firezone
```
Comment (bmanifold) [inline website/src/app/kb/authenticate/oidc/fusion/readme.mdx:79]: Was wondering if you considered putting this as a pre-req step and then calling this step 'Configure Firezone'?

File: website/src/app/kb/authenticate/oidc/fusion/readme.mdx [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+
+1. In your Firezone admin dashboard, go to
+   `Settings -> Identity Providers -> Add -> OIDC`.
+1. Enter the client id and secret saved from the previous step.
```
Comment (bmanifold) [inline website/src/app/kb/authenticate/oidc/fusion/readme.mdx]:
```suggestion
1. Enter the `client id` and `client secret` saved from the previous step.
```
Was just thinking that it could be nice to emphasize OAuth/OIDC terminology where possible.

**Review by bmanifold — COMMENTED** [review]
Just a couple of small questions/thoughts

File: elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex (hunk 1 above)
Comment (jamilbk) [reply elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex]: Yeah, we could use `app`, I think I've seen a similar naming pattern. Was just trying to be consistent. I'll update these.

File: website/src/app/kb/authenticate/oidc/fusion/readme.mdx (hunk 2 above)
Comment (jamilbk) [reply website/src/app/kb/authenticate/oidc/fusion/readme.mdx:79]: Hm, yeah that might be a good idea. `Configure Firezone` matches what we say in the product as well, so then our docs are just an in-depth version of the same steps we lay out in the creation form.

Comment (jamilbk) [reply website/src/app/kb/authenticate/oidc/fusion/readme.mdx:79]: Updated

File: elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex (hunk 1 above)
Comment (jamilbk) [reply elixir/apps/web/lib/web/live/settings/identity_providers/openid_connect/components.ex]: Fixed

File: elixir/apps/domain/lib/domain/auth/adapters/openid_connect/settings/changeset.ex [hunk 4]
```diff
@@ -25,6 +25,10 @@ defmodule Domain.Auth.Adapters.OpenIDConnect.Settings.Changeset do
         {:ok, _uri} ->
           [{:discovery_document_uri, "is not a valid URL"}]
 
+        {:error, %Mint.TransportError{reason: reason}} ->
```
Comment (jamilbk) [inline elixir/apps/domain/lib/domain/auth/adapters/openid_connect/settings/changeset.ex:28]: Not having this was causing a crash when typing out the discovery document URI, once you made it to `https://`

**Review by bmanifold — APPROVED** [review]
