### PR TITLE
fix(apple): use throwing Swift API for writing files

### LINKED ISSUE #11983: SIGABRT: NSException > terminating due to uncaught exception of type NSException
Sentry Issue: [APPLE-CLIENT-CS](https://firezone-inc.sentry.io/issues/7233993442/?referrer=github_integration)

```
SIGABRT: NSException > terminating due to uncaught exception of type NSException
  File "Log.swift", line 246, in closure in LogWriter.write
    handle.write(jsonData)
  File "<compiler-generated>", in thunk for closure
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by thomaseizinger**
The `FileHandle::write` API is deprecated and throws `NSException`s which are not catch-able in Swift. To avoid race-conditions when the file gets deleted after we have obtained the handle, we switch to the non-deprecated API and silence the error with `try?`.

Resolves: #11983

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Going to try to add an automated test for this.

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift [hunk 1]
```diff
@@ -128,7 +128,7 @@ public final class Log {
 
 /// Thread-safe: All mutable state access is serialised through workQueue.
 /// Log writes are queued asynchronously to avoid blocking the caller.
-private final class LogWriter: @unchecked Sendable {
+internal final class LogWriter: @unchecked Sendable {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift]: `internal` is the default level.
```suggestion
final class LogWriter: @unchecked Sendable {
```

File: swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift [hunk 2]
```diff
@@ -192,7 +192,7 @@ private final class LogWriter: @unchecked Sendable {
   }
 
   // Returns a valid file handle, recreating file if necessary
-  private func ensureFileExists() -> FileHandle? {
+  internal func ensureFileExists() -> FileHandle? {
```
Comment (jamilbk) [inline swift/apple/FirezoneKit/Sources/FirezoneKit/Helpers/Log.swift]:
```suggestion
  func ensureFileExists() -> FileHandle? {
```

**Review by jamilbk — APPROVED** [review]
Good catch. Minor suggestion to remove explicit `internal`.

**Review by klochowicz — APPROVED** [review]
